### ISSUE TITLE
[HOLD for payment 2022-11-16] [$500] Dev - Activating metrics on crashes the app on Android - reported by @parasharrajat

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#10622]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1.Set the env with following.
ONYX_METRICS=true
CAPTURE_METRICS=true
2. Build the app for android.

## Expected Result:
App should build 

## Actual Result:
App crashes 

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web
- Android

**Version Number:** 
**Reproducible in staging?:** need repro
**Reproducible in production?:** need repro 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

![image - 2022-08-28T224657 651](https://user-images.githubusercontent.com/43995119/187113169-8a4165bb-4c2e-49b4-a90e-3a0901a76943.png)
![image - 2022-08-28T224655 216](https://user-images.githubusercontent.com/43995119/187113170-a4d3945f-a0a9-4234-a804-39ca6e8bf5dd.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @parasharrajat
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1660151993852989

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by puneetlath** [comment]
External Upwork post: https://www.upwork.com/jobs/~01b6342fd8e2b2240a
Internal Upwork job: https://www.upwork.com/ab/applicants/1564180886378299392/job-details

**Comment by wildan-m** [comment]
Is it OK to have `originalPromise` value `undefined`?

In `node_modules/react-native-onyx/lib/metrics/index.native.js`

the `originalPromise` is `undefined` when the `args` value is:

```
["isLoadingReportData", true]
```

If `originalPromise` might be `undefined`, then my proposal is to add undefined check

```diff
+        if(originalPromise)
            originalPromise
                .then((result) => {
                    measureMarkToNow(mark, {result});
                })
                .catch((error) => {
                    measureMarkToNow(mark, {error});
                });

```

**Comment by christianwen** [comment]
# **Proposal**

## **Problem**
For the issue in Android, it's due to the code in `react-native-onyx` -> `lib/metrics/index.native.js` -> `function decorateWithMetrics` is expecting that the `func` passed in is a function that returns a promise, which it's not always the case, for example the `lib/Onyx.js` -> `function update(data) {` does not return anything. So the attempt to use the `decorateWithMetrics` with that `update` function will result in that error because in `decorateWithMetrics` we're using `.then` with an `undefined` variable.

## **Solution**
In `function decorateWithMetrics`, we should check that the returned value of the function is a promise first before attempting to resolve that promise. The code can be changed to below
```diff
+function isPromise(value){
+    return typeof value?.then === 'function';
+}

/**
 * Wraps a function with metrics capturing logic
 * @param {function} func
 * @param {String} [alias]
 * @returns {function} The wrapped function
 */
function decorateWithMetrics(func, alias = func.name) {
    if (decoratedAliases.has(alias)) {
        throw new Error(`"${alias}" is already decorated`);
    }

    decoratedAliases.add(alias);

    function decorated(...args) {
        const mark = addMark(alias, args);

+       const returnedValue = func.apply(this, args);

+       if (isPromise(returnedValue)) {
            /*
            * Then handlers added here are not affecting the original promise
            * They create a separate chain that's not exposed (returned) to the original caller
            * */
+           returnedValue
                .then((result) => {
                    measureMarkToNow(mark, {result});
                })
                .catch((error) => {
                    measureMarkToNow(mark, {error});
                });
+       }

+       return returnedValue;
    }

    return decorated;
}
```

The way I check if a value is a promise is also how `graphql-js` does it, you can refer here https://github.com/graphql/graphql-js/blob/main/src/jsutils/isPromise.ts

**Android after the fix, no more crashes**
<img width="317" alt="Screen Shot 2022-09-01 at 21 39 30" src="https://user-images.githubusercontent.com/21312517/187941915-429ae970-eeb9-4eb9-a9f6-c70fdcf036ec.png">

## About the crash in web
I'm not sure if the web crash is in the scope of this issue, but for the issue in web, it's due to the `decorateWithMetrics` noop in `react-native-onyx` -> `lib/metrics/index.web.js` is not returning anything, thus when we're using `getAllKeys = decorate.decorateWithMetrics(getAllKeys, 'Onyx:getAllKeys');`, the `getAllKeys` becomes undefined. So to fix that we need to modify the noop so that it returns the original function that is passed in
```diff
-function decorateWithMetrics() {}
+function decorateWithMetrics(func) { return func }
```

**No more crash in web after the fix**
<img width="1440" alt="Screen Shot 2022-09-01 at 21 47 13" src="https://user-images.githubusercontent.com/21312517/187943908-38115e45-f896-480c-bd71-9d7c786c8bed.png">

Please let me know if you have any concerns regarding the above proposal
Thanks!

**Comment by Santhosh-Sellavel** [comment]
Will review this today/tomorrow.

**Comment by Santhosh-Sellavel** [comment]
@puneetlath 
Actually, @wildan-m suggestion solves the crash that occurs on android devices.
I do prefer their solution to address the same.

From @christianwen proposal,
> I'm not sure if the web crash is in the scope of this issue, but for the issue in web, it's due to the decorateWithMetrics noop in react-native-onyx -> lib/metrics/index.web.js is not returning anything, thus when we're using getAllKeys = decorate.decorateWithMetrics(getAllKeys, 'Onyx:getAllKeys');, the getAllKeys becomes undefined. So to fix that we need to modify the noop so that it returns the original function that is passed in

There is a different issue that occurs on the web, I can confirm that. We need a proposal to address that issue, but their solution doesn't address the issue.

### TLD
So we are looking proposal to address the crash that occurs on the web also.

**Comment by christianwen** [comment]
Hi, @Santhosh-Sellavel in my proposal I've also put the solution to address the crash on the web by fixing the `decorateWithMetrics` noop. By `their solution doesn't address the issue`, do you mean the crash still happens for you after trying the solution?

<img width="854" alt="Screen Shot 2022-09-08 at 07 39 39" src="https://user-images.githubusercontent.com/21312517/189008596-c344bd9a-921e-44d7-bf56-7c36ee879f1f.png">

**Comment by Santhosh-Sellavel** [comment]
Yes crash occurred for me

**Comment by christianwen** [comment]
@Santhosh-Sellavel can you attach the log of the crash after you apply the suggestion
is it the same log as in the original description?
<img width="812" alt="Screen Shot 2022-09-08 at 09 34 03" src="https://user-images.githubusercontent.com/21312517/189020693-3e77111e-454a-4aa0-b46d-9cad9404a060.png">
thanks

**Comment by Santhosh-Sellavel** [comment]
Yeah getAllKeys was the issue, I checked it on the Latest main earlier.

**Comment by christianwen** [comment]
@Santhosh-Sellavel confirming with you, you are modifying it in the `node_modules/react-native-onyx/lib/metrics/index.web.js` of this repo `https://github.com/Expensify/App` to try right?

if that's the case then it's not working because in `node_modules`, it is using the built code of `react-native-onyx` in `node_modules/react-native-onyx/dist/web.development.js` instead. You can try modifying the built code to test as follow (line 1786)

<img width="679" alt="Screen Shot 2022-09-08 at 10 50 23" src="https://user-images.githubusercontent.com/21312517/189030188-a17193d4-86c7-4c4d-b2e7-5f98dee8564f.png">

**Comment by wildan-m** [comment]
@Santhosh-Sellavel Forgot to investigate the web version
My updated proposal
For android:
```diff
+         originalPromise && originalPromise
                .then((result) => {
                    measureMarkToNow(mark, {result});
                })
                .catch((error) => {
                    measureMarkToNow(mark, {error});
                });

```

For web:
```diff
function applyDecorators() {
    // We're requiring the script dynamically here so that it's only evaluated when decorators are used
    const decorate = require('./metrics');

    // Re-assign with decorated functions
    /* eslint-disable no-func-assign */
+    get = decorate.decorateWithMetrics(get, 'Onyx:get') || get;
+   set = decorate.decorateWithMetrics(set, 'Onyx:set') || set;
+    multiSet = decorate.decorateWithMetrics(multiSet, 'Onyx:multiSet') || multiSet;
+   clear = decorate.decorateWithMetrics(clear, 'Onyx:clear') || clear;
+   merge = decorate.decorateWithMetrics(merge, 'Onyx:merge') || merge;
+   mergeCollection = decorate.decorateWithMetrics(mergeCollection, 'Onyx:mergeCollection') || mergeCollection;
+   getAllKeys = decorate.decorateWithMetrics(getAllKeys, 'Onyx:getAllKeys') || getAllKeys;
+   initializeWithDefaultKeyStates = decorate.decorateWithMetrics(initializeWithDefaultKeyStates, 'Onyx:defaults') || initializeWithDefaultKeyStates;
+    update = decorate.decorateWithMetrics(update, 'Onyx:update') || update;
    /* eslint-enable */

```

The @christianwen  wen solution for web version might be cleaner and not repeated

**Comment by Santhosh-Sellavel** [comment]
> @Santhosh-Sellavel confirming with you, you are modifying it in the `node_modules/react-native-onyx/lib/metrics/index.web.js` after cloning repo `https://github.com/Expensify/App` locally to try right?

Ya right!

> if that's the case then it's not working because in `node_modules`, it is using the built code (not the source code) of `react-native-onyx` in `node_modules/react-native-onyx/dist/web.development.js` instead. You can try modifying the built code to test as follow (line 1786)
> 
> <img alt="Screen Shot 2022-09-08 at 10 50 23" width="679" src="https://user-images.githubusercontent.com/21312517/189030188-a17193d4-86c7-4c4d-b2e7-5f98dee8564f.png">
> 

This solution solves the crash on the web, need to ensure all platforms are working well before moving forward!

**Comment by Santhosh-Sellavel** [comment]
Not overdue. 

Need to check on other platforms too!

**Comment by Santhosh-Sellavel** [comment]
@christianwen have you checked other platforms, does a crash occur there?

**Comment by christianwen** [comment]
@Santhosh-Sellavel yeah I've checked, no more crash on any platform, screenshots attached below

**iOS**
![simulator_screenshot_C9FE8B23-06B8-4EAB-B613-188E3EA78691](https://user-images.githubusercontent.com/21312517/189782704-f66e8554-5678-45d0-b9e0-1c546699853f.png)

mWeb
<img width="501" alt="Screen Shot 2022-09-13 at 07 49 59" src="https://user-images.githubusercontent.com/21312517/189783627-f4928130-3592-4b54-bfb3-06530b625ec8.png">

Mac Desktop app
<img width="1196" alt="Screen Shot 2022-09-13 at 07 50 40" src="https://user-images.githubusercontent.com/21312517/189783723-3bfe1dfd-f569-4a8b-be6f-e37f47797d67.png">

For Android and web I've already attached screenshots in https://github.com/Expensify/App/issues/10622#issuecomment-1234389410

Thanks!

**Comment by puneetlath** [comment]
Updated to $500. @Santhosh-Sellavel mind providing an update?

**Comment by Santhosh-Sellavel** [comment]
Sorry for the delay here!
@puneetlath 
Actually, @christianwen proposal solves the issue, but I am not sure this is the right way and am afraid of missing something else in the context here. So can we have a look from internal who is familiar & involved in implementing this moving forward?

**Comment by luacmartins** [comment]
Commented on the other thread!

**Comment by puneetlath** [comment]
@parasharrajat @luacmartins just to make sure I understand, you are both saying that [this Onyx PR](https://github.com/Expensify/react-native-onyx/pull/133/files#r975658158) should solve this issue. And no further action should be needed, is that correct?

**Comment by luacmartins** [comment]
Well that PR was merged a while ago, so we will need to put up a fix.

**Comment by puneetlath** [comment]
Ah whoops, understood. 

@christianwen feel free to update your proposal accordingly if you're still interested!

**Comment by christianwen** [comment]
# **Updated Proposal**

Here's my updated proposal for the Android crash following the recommendation by @parasharrajat here https://github.com/Expensify/App/issues/10622#issuecomment-1252708044

In `function update(data) {`:
```diff
-_.each(data, ({onyxMethod, key, value}) => {
+const promises = _.map(data, ({onyxMethod, key, value}) => {
    switch (onyxMethod) {
        case 'set':        
+            return set(key, value);
-             set(key, value);
-             break;
        case 'merge':
+            return merge(key, value);
-             merge(key, value);
-             break;
        case 'mergecollection':
+            return mergeCollection(key, value);
-             mergeCollection(key, value);
-             break;
        case 'clear':
+            return clear();
-             clear();
-             break;
        default:
            break;
    }
});

+return Promise.all(promises);
```

For the web crash, the proposed solution is still the same as in https://github.com/Expensify/App/issues/10622#issuecomment-1234389410

For unit tests, I'll add later in the PR once the above proposal is confirmed
cc @puneetlath @luacmartins

**Comment by puneetlath** [comment]
@Santhosh-Sellavel what do you think?

**Comment by Santhosh-Sellavel** [comment]
Looks good to me for android, about unsure about the web proposal. 

> ### About the crash in web
> I'm not sure if the web crash is in the scope of this issue, but for the issue in web, it's due to the decorateWithMetrics noop in react-native-onyx -> lib/metrics/index.web.js is not returning anything, thus when we're using getAllKeys = decorate.decorateWithMetrics(getAllKeys, 'Onyx:getAllKeys');, the getAllKeys becomes undefined. So to fix that we need to modify the noop so that it returns the original function that is passed in
> 
> -function decorateWithMetrics() {}
> +function decorateWithMetrics(func) { return func }


if `decorateWithMetrics` is expecting a return `func`, I'm not sure how we could've missed this earlier.

**Comment by Santhosh-Sellavel** [comment]
@luacmartins any thoughts?

**Comment by luacmartins** [comment]
Native implementation looks fine. I _think_ the web changes also make sense, but just like @Santhosh-Sellavel, I'm also confused by how we've had those methods be noops for a while now. @tgolen would you mind taking a look at [this comment](https://github.com/Expensify/App/issues/10622#issuecomment-1234389410) since you created [this file](https://github.com/Expensify/react-native-onyx/blob/3f936d9a81350ee3763fcf70971ec70dafe6b72c/lib/metrics/index.web.js)?

**Comment by Santhosh-Sellavel** [comment]
@tgolen Bump!

**Comment by tgolen** [comment]
Well, the reason it's been fine up until now is that this is the first time someone's tried using the metric code in forever. This stuff has always been super low-value in my opinion. It's hard for me to follow the different proposals here. Can't we just change the no-op methods to return an instantly resolved promise? `return Promise.resolve();`

**Comment by Santhosh-Sellavel** [comment]
@christianwen any thoughts on the above?

**Comment by christianwen** [comment]
@Santhosh-Sellavel If we do as below
```function decorateWithMetrics() { return Promise.resolve(); }``` 
in the noop then the `getAllKeys` will not work correctly anymore

Here's the usage of `decorateWithMetrics`:
```getAllKeys = decorate.decorateWithMetrics(getAllKeys, 'Onyx:getAllKeys');```

The `decorateWithMetrics` should only add side effects to `getAllKeys` if `CAPTURE_METRICS=true`, not modifying the behavior of it. If we `return Promise.resolve();` in the noop then the getAllKeys will lose it's behavior and become a dummy function. I believe the noop in this case should not add any side effects and also should not change how the function works, so my suggested change below satisfies both conditions.
`function decorateWithMetrics(func) { return func }`

FYI @tgolen we're discussing the below part of the [proposal](https://github.com/Expensify/App/issues/10622#issuecomment-1234389410)
<img width="855" alt="Screen Shot 2022-10-11 at 00 22 20" src="https://user-images.githubusercontent.com/21312517/194921296-6727c9eb-35a7-42d2-b387-3fa5ed864095.png">

**Comment by tgolen** [comment]
OK, got it. I think `function decorateWithMetrics(func) { return func }` sounds like a good solution then.

**Comment by Santhosh-Sellavel** [comment]
Thanks, everyone!
@puneetlath We are good to go with @christianwen here!

**Comment by christianwen** [comment]
Thanks @puneetlath, I applied for the job, here's my Upwork profile https://www.upwork.com/freelancers/~01991fd5e5c11ef3ba
The PR will be ready by Oct 13

**Comment by puneetlath** [comment]
Sorry for the delay, just added a comment on the PR.

**Comment by Santhosh-Sellavel** [comment]
PR in review

**Comment by puneetlath** [comment]
I believe we now also need a PR to update the app to use the new onyx version, is that right?

**Comment by Santhosh-Sellavel** [comment]
Yes right, @christianwen can you make submit again the E/APP, thanks!

**Comment by christianwen** [comment]
@Santhosh-Sellavel PR for it here https://github.com/Expensify/App/pull/12465
Thanks

**Comment by puneetlath** [comment]
@Santhosh-Sellavel could you help out with determining which PR introduced this bug?

**Comment by Santhosh-Sellavel** [comment]
@puneetlath 
I suspect this is the PR https://github.com/Expensify/react-native-onyx/pull/132

**Comment by puneetlath** [comment]
Checklist completed. Everyone paid. 

Thanks for your contributions everyone!
