### ISSUE TITLE
Web - Chat - Offline messages above the header of the group/room created offline

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#13533]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go to https://staging.new.expensify.com/
and login
2. Go offline
3. Create a new group chat or room
4. Sent some messages in this created group chat or room
5. Go back online

## Expected Result:
Messages should stay below group chat / room header

## Actual Result:
Messages are displayed above the chat header

## Workaround:
Unknown

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.2.38.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**Email or phone of affected tester (no customers):** 

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/207158726-c3ea2bd1-117c-49ae-8c69-87869f8db53a.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:** 

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by luacmartins** [comment]
AFAIK this should be fixed when we deprecate sequence numbers

**Comment by strepanier03** [comment]
### Bug0 Triage Checklist
_Note: see [this SO](https://stackoverflow.com/c/expensify/questions/14418) for more information._
- [ ] The "bug" is actually a bug 
- [ ] The bug is not a duplicate report of an existing GH.
  - If it is, close the GH and add any novel details to the original GH instead 
- [ ] The bug is reproducible, following the reproduction steps.
  - [ ] If the GH doesn’t have steps to reliably reproduce the bug and you figure it out, then please add them.
  - [ ] If you’re unable to reproduce the bug, add the `Needs reproduction` label. 
  - [ ] Comment on the issue outlining the steps you took to try to reproduce the bug, your results and tag the issue reporter and the Applause QA member who created the issue. Ask them to clarify reproduction steps and/or to check the reproduction steps again. Close issue. 
- [ ] The GH template is filled out as fully as possible
  - The GH body and title are clear (ie. could an external contributor understand it and work on it?) 
- [ ] The GH was created by an Expensify employee or a QA tester 
- [ ] If the bug is an OldDot issue, you should decide whether it is widespread enough to justify fixing or it is better to wait for reunification. If it’s better to wait, close the GH & provide this justification 
- [ ] If there's a link to Slack, check the discussion to see if we decided not to fix it 
- [ ] Decide if the GH should be resolved by an External contributor or Internal engineer, add the appropriate label

**Comment by strepanier03** [comment]
Working through this checklist but I have a shortened day due to a sick child and I'm about to be offline. I'll have testing done and a plan of action completed tomorrow.

**Comment by strepanier03** [comment]
My behavior is not the same as the behavior in the video above. 

In my testing, the comments only temporarily appeared above the header but then it seems like they loaded and moved under the header. Still not the best experience but not as bad as staying above the header.

Video:
https://user-images.githubusercontent.com/10925636/207994183-225174ca-cfa6-4d06-a97f-fe7f9bf5112e.mp4

@kbecciv - Could you test again? Is the behavior I recorded the expected behavior or should the messages all populate under the header immediately without them going above and then below?

**Comment by JmillsExpensify** [comment]
Putting this on hold for Sequence Numbers and taking it over as the BZ member assigned to those.

**Comment by JmillsExpensify** [comment]
Still on hold, Melvin.

**Comment by JmillsExpensify** [comment]
Updated the labels for consistency with issues related to sequence numbers.

**Comment by JmillsExpensify** [comment]
Need to re-test this one. Circling back on it tomorrow though.

**Comment by JmillsExpensify** [comment]
So I tested this and these temporarily go above the header. That said, we're handling this in another issue that I've created, so I'm closing this one.
