### ISSUE TITLE
[HOLD for payment 2023-01-25] [$1000] Long text strings disappear from single-line text fields when text is too long

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#13802]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action performed:

1. Login with any account
2. Choose any single line TextInput, ie: First name, Last name, Workspace name.
3. Enter the long text with multiple words, for example: `Visaocuoitroi193's Workspacethisverylongtext` and save entry

## Expect result:
If the full text is too long to fit in the text field, the text should be cut off and we should add a `...` to show that the string continues.

## Actual result: 
Any words that go past the end of the text field disappear from view. (I think it's because they are moved to a newline)

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] iOS / native

**Version Number:** 1.2.43-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/209234493-cab6cc31-fa2b-411c-9eb2-9f4f4805169a.MP4

https://user-images.githubusercontent.com/43996225/209234529-dd914157-702f-4a10-8bf2-d1c8fc7e8078.MP4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @hungvu193 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1671552728713329

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01174c064be0dcafb8</li>
        <li>Upwork Job ID: 1611117990550892544</li>
        <li>Last Price Increase: 2023-01-05</li>
    </ul>
</details>

**Comment by sakluger** [comment]
This doesn't have anything to do with the `'` actually. What's happening is that if you add a long string of characters after a space, the word moves down to the next line (basically text wrapping).

I posted in the original Slack thread to see if we'd like to fix and what the expected behavior should be in this case.

**Comment by sakluger** [comment]
Changing this to weekly and we will revisit in the new year when more people are back online.

**Comment by sakluger** [comment]
We discussed in Slack and decided that we should fix this and that it should be external. Adding the label now.

**Comment by hungvu193** [comment]
<b>Proposal</b>
I believe the root cause of this issue is about the `textAlign` inside our `RNTextInput`.
<img width="1136" alt="Screen Shot 2023-01-06 at 09 59 52" src="https://user-images.githubusercontent.com/16502320/210921076-65b0b63e-aac1-4cc9-acd3-c23c4c479248.png">

We can fix this by setting the textAlign to auto with single line TextInput since this issue only happened with single line.

Here's the result:

https://user-images.githubusercontent.com/16502320/210921156-bace5779-cc6f-4073-a75a-34c96461624e.mov

**Comment by mollfpr** [comment]
Thanks for the proposals!

@allroundexperts Is changing the `lineHeight` will have an effect? What I get when testing your proposal, the line height seems not doing anything to fix the issue.

Also, changing the `textAlign` will cause a problem with RTL localization like Arabic.
<img width="453" alt="Screen Shot 2023-01-06 at 10 41 54" src="https://user-images.githubusercontent.com/25520267/210926280-73494939-f5de-4f76-8bdf-861b74b5624e.png">
<img width="459" alt="Screen Shot 2023-01-06 at 10 41 20" src="https://user-images.githubusercontent.com/25520267/210926295-ee62f522-a453-4665-83d3-aa43a2f29949.png">

I'll ask to the Slack channel for opinions about the above issue, where do we want to override the text-align or let it as it is.

cc @yuwenmemon

**Comment by bernhardoj** [comment]
### **Proposal**

This is a known [issue](https://github.com/facebook/react-native/issues/29068) on react-native repo and not fixed yet. For some reason, when we set the `lineHeight` prop, the line break will be set to wrap.

One of the [comments](https://github.com/facebook/react-native/issues/29068#issuecomment-985682364) has a temporary patch that I think we can apply to our fork.

Here is the code
```diff
- (void)setDefaultTextAttributes:(NSDictionary<NSAttributedStringKey, id> *)defaultTextAttributes
{    
  if ([_defaultTextAttributes isEqualToDictionary:defaultTextAttributes]) {
    return;
  }

+ // limit single-line fields to 1-line (no wrapping)
+ if ([self.textInputDelegate isKindOfClass: [RCTSinglelineTextInputView class]]) {
+     NSParagraphStyle* ps = defaultTextAttributes[NSParagraphStyleAttributeName];
+     NSMutableParagraphStyle* mps = [ps mutableCopy];
+     mps.lineBreakMode = NSLineBreakByTruncatingTail;
+     NSMutableDictionary<NSAttributedStringKey, id>* mutableDefaultTextAttributes = [defaultTextAttributes mutableCopy];
+     mutableDefaultTextAttributes[NSParagraphStyleAttributeName] = [mps copy];
+     defaultTextAttributes = [mutableDefaultTextAttributes copy];
+ }
    
  _defaultTextAttributes = defaultTextAttributes;
  [super setDefaultTextAttributes:defaultTextAttributes];
  [self _updatePlaceholder];
}
```

What the code does is basically check if the text input is single line, if true, we set the line break mode to `NSLineBreakByTruncatingTail`.

**Comment by allroundexperts** [comment]
@mollfpr When line height is set, the text gets wrapped on to the next line. That's why we need to remove it. For the `textAlign` as you can see in my proposal, we're removing it ONLY if RTL is INACTIVE. When you type in Arabic, RTL gets activated, and `textAlign` gets applied.

**Comment by yuwenmemon** [comment]
@mollfpr Personally, I don't think I'm too concerned if changing the `textAlign` messes with Arabic, since we [call out](https://github.com/Expensify/App/blob/3b54638d85bfe9e82b4fa02d749eaf64325050d8/src/components/RNTextInput.js#L26) that we don't support RTL in-app.

**Comment by mollfpr** [comment]
@allroundexperts @hungvu193 @bernhardoj you can put your thoughts in [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1673017988188739), thanks!

**Comment by mollfpr** [comment]
@allroundexperts Can you confirm that removing the input line height is not causing regression?

I'm only able to track https://github.com/Expensify/App/issues/5462 and https://github.com/Expensify/App/issues/13336 where it's related to the line-height style.

**Comment by allroundexperts** [comment]
> @allroundexperts Can you confirm that removing the input line height is not causing regression?
> 
> I'm only able to track #5462 and #13336 where it's related to the line-height style.

@mollfpr I can confirm that it does not cause any regression if we do it on iOS only.

**Comment by allroundexperts** [comment]
> > @allroundexperts Can you confirm that removing the input line height is not causing regression?
> > I'm only able to track #5462 and #13336 where it's related to the line-height style.
> 
> @mollfpr I can confirm that it does not cause any regression if we do it on iOS only.

@mollfpr Since we have disabled `fontScaling` on text input, removing line height in text input won't cause any issue.

**Comment by mollfpr** [comment]
@yuwenmemon this @allroundexperts  [proposal](https://github.com/Expensify/App/issues/13802#issuecomment-1372914209)'s is working for me but I'm a bit worried about changing the input style. Any thoughts?

**Comment by hungvu193** [comment]
> Since we have disabled `fontScaling` on text input, removing line height in text input won't cause any issue.

@mollfpr   I forgot to remove lineHeight inside baseTextInput in my diff, so please ignore my comment, if we go with changing lineHeight, then we can consider only apply it with singleLine TextInput, since this issue only happen singleLine TextInput.

**Comment by mollfpr** [comment]
>This will affect multiline input style. i.e. on CloseAccountPage or WorkspaceInvitePage

@0xmiroslav Thanks for the proposal! Can you elaborate on what the side effects are?

**Comment by allroundexperts** [comment]
@mollfpr On iOS we shouldn't be using line heights for text inputs even if its a multiline input. The caret size grows out of proportion with the value which makes it sort of useless.

![image](https://user-images.githubusercontent.com/30054992/211231707-39ff19c3-72b2-4a5b-b88a-4a633a8b4fb7.png)

The caret size wasn't an issue because our default lineHeight turns out to be `16` which very close to our default used font size `15`. 

Here's the difference on the multiline input with and without line height (Only if you can spot it somehow).

<img width="400" alt="Screenshot 2023-01-09 at 7 12 51 AM" src="https://user-images.githubusercontent.com/30054992/211231861-1b90af1b-f84c-4466-b3c6-49f7d305bd14.png">

<img width="416" alt="Screenshot 2023-01-09 at 7 13 18 AM" src="https://user-images.githubusercontent.com/30054992/211231866-ed2a0553-0be3-4790-8392-a0f7bc9f92bf.png">

**Comment by mollfpr** [comment]
>@mollfpr here's the difference

@0xmiroslav Is the difference on without line-height the space between the line a bit cramped?

**Comment by allroundexperts** [comment]
@mollfpr it seems to be actually opposite for iOS (more cramped up when line height is set):

With line height:
<img width="399" alt="Screenshot 2023-01-09 at 8 09 16 AM" src="https://user-images.githubusercontent.com/30054992/211235636-9f2dfa33-f792-4795-959c-257766251607.png">

Without line height:
<img width="425" alt="Screenshot 2023-01-09 at 8 09 46 AM" src="https://user-images.githubusercontent.com/30054992/211235650-8cf9ff2f-93ba-4035-8039-0ca834ff2e98.png">

**Comment by hungvu193** [comment]
> > @mollfpr here's the difference
> 
> @0xmiroslav Is the difference on without line-height the space between the line a bit cramped?

Right, that's why, we only fix this issue for single line input.

**Comment by mollfpr** [comment]
Okay, so most of the proposal is suggesting removing/changing the `textAlign` from the `RNTextInput` by removing the line height for the text input style.

I think we only want the fix not to affect the multiline text input, so @0xmiroslav [proposal](https://github.com/Expensify/App/issues/13802#issuecomment-1375016021) looks like is the candidate for that.

---

But I have a concern with removing the line height.

Currently, on a smaller iPhone device aspect ratio (in the video I'm using an iPhone 6s iOS 15.0 simulator), the emoji are cut off when we focus on the text input.

https://user-images.githubusercontent.com/25520267/211242518-df6e978d-bec7-48bf-a390-8f88ed1a7a59.mov

If we remove the line height the emoji doesn't cut off whether it's on focus or not. But, there's an effect like the text input height is changing on focus/blur.

https://user-images.githubusercontent.com/25520267/211242845-58c18956-688b-4e6f-b694-94d0bd84e692.mov

What do you think @yuwenmemon?

**Comment by s77rt** [comment]
I think we need to fix this on RN.

> If the reason you can't write cross-platform code is because there is a bug in ReactNative that is preventing it from working, the correct action is to fix RN and submit a PR upstream -- not to hack around RN bugs with platform-specific code paths.

**Comment by yuwenmemon** [comment]
@mollfpr that effect in your second video is barely noticeable - I think it's acceptable.

@s77rt correct, that is something we state in our [App philosophy](https://github.com/Expensify/App#philosophy) - but are we writing any platform-specific code paths here?

**Comment by s77rt** [comment]
@yuwenmemon Sorry I think I misunderstood the proposals, I thought we are going to only remove the line height for iOS.

**Comment by mollfpr** [comment]
I will test again regarding the line height removed.

**Comment by mollfpr** [comment]
Asking here https://expensify.slack.com/archives/C01GTK53T8Q/p1673542227049079 for clarity about `line-height`.

**Comment by yuwenmemon** [comment]
Looking at this [latest comment](https://github.com/Expensify/App/pull/12447#issuecomment-1380877752) it seems like they won't be addressing the line-height issue in that PR. But agreed it may change things if the "look" of the inputs are going to drastically change, which it looks like they will.

**Comment by puneetlath** [comment]
@yuwenmemon @sakluger @mollfpr this issue is now 3 weeks old. There is one more week left before this issue <a href='https://stackoverflowteams.com/c/expensify/questions/15233/15234#15234'>breaks WAQ</a> and will need to go internal. What needs to happen to get a PR in review this week? Please create a thread in #expensify-open-source to discuss. Thanks!

**Comment by mollfpr** [comment]
I just try this [proposal](https://github.com/Expensify/App/issues/13802#issuecomment-1375016021) against the refactoring input [PR](https://github.com/Expensify/App/pull/12447). Here's the result:

| iPhone 6s | iPhone 13 | Android |
|-----------|-----------|---------|
| <video src="https://user-images.githubusercontent.com/25520267/212228150-d8fd2013-6670-445e-bd34-0eba207495da.mov"></video> | <video src="https://user-images.githubusercontent.com/25520267/212228253-cccae7de-08f6-4b39-bd75-29851bb60c53.mov"></video> | <video src="https://user-images.githubusercontent.com/25520267/212228356-215e42a7-d685-4898-8d46-53c1aef19083.mov"></video> |

I didn't find any noticeable issue with @0xmiroslav [proposal](https://github.com/Expensify/App/issues/13802#issuecomment-1375016021). What do you think? @yuwenmemon @puneetlath

**Comment by yuwenmemon** [comment]
Cool, let's go with that then :+1:

@0xmiroslav can you make a PR?

**Comment by sakluger** [comment]
I've sent offers to @hungvu193 (issue reporter), @mollfpr (contributor+), and @0xmiroslav (contributor) on the Upwork job, please accept the offer when you have a chance! Since the PR was merged quickly, it is eligible for the efficiency bonus as long as there are no regressions.

I'm discussing adding regression test steps [here in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1674511712268599). It's a little tricky because the behavior is different depending on the platform (iphone vs android vs web). I'll update once we've made a decision there.

**Comment by mollfpr** [comment]
@sakluger Thanks, accepted!

**Comment by sakluger** [comment]
Hey everyone, sorry I did not notice this sooner, but as mentioned in my last comment, I noticed that the behavior is different for different platforms:

- On the iPhone app, we add a `...` to the end of single line text fields if the text is too long

<img width="413" alt="image" src="https://user-images.githubusercontent.com/5997400/214378247-0f16bec4-81a6-4de7-95ec-79483f14309f.jpeg">


- On the Desktop App and web, there is no `...`, it just cuts off the text at the end of the field and I can scroll left and right

Desktop App:
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5997400/214377694-82163952-2d11-4fc2-9cc8-3a3ebcfeff77.png">

Web:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/5997400/214377297-6eff4d48-237b-4e19-84d3-ea1f66f7637f.png">

- I'm not sure what it looks like on Android


The expected result listed in the original description was that we should add `...` at the end of the text field. In general, we aim to have behavior and design stay as consistent as possible across all platforms. Did we intentionally make it so that it worked differently on different platforms, or is that a bug?

**Comment by sakluger** [comment]
That makes sense!

I've paid out everyone, and included the 50% efficiency bonus for the Contributor and C+ payments.

I'm not closing out the issue quite yet, since I need to make sure we update our regression tests correctly.

**Comment by sakluger** [comment]
Created a [GH issue](https://github.com/Expensify/Expensify/issues/258035) to update TestRail steps.

@mollfpr @yuwenmemon, before I close out the issue, do you know if any previous PR caused this bug, or was this always the behavior and we just caught it for the first time?

**Comment by mollfpr** [comment]
@sakluger Sorry, I forgot to fill out the checklist. Probably from this https://github.com/Expensify/App/pull/7594.

> we just caught it for the first time?
I believe so.

**Comment by sakluger** [comment]
Thanks! The second item in the checklist is `The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.` Could you please comment on that PR to explain why you think it caused this bug?

**Comment by mollfpr** [comment]
@sakluger Done https://github.com/Expensify/App/pull/7594#issuecomment-1406610314

**Comment by mollfpr** [comment]
I haven't opened a discussion about the expected result but it's a regression from adding the `textAlign`. I think the expected result is confirmed https://github.com/Expensify/App/issues/13802#issuecomment-1372813559 cc @sakluger.

I addressed my concern about removing `textAlign` in https://github.com/Expensify/App/issues/13802#issuecomment-1373109270, and I opened a discussion about that [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1673017988188739).

**Comment by sakluger** [comment]
All done here, thanks everyone!
