### ISSUE TITLE
[$1000] IOU - Currency input has several `.` entering big amount and clearing all the digits

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#14418]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Open web
2. Click the global + icon
3. Split Bill (or Send Monday, or Request Money - happens in all flows)
4. Change currency to currency that has three letters (i.e AED)
5. Enter large amount and clear (eg 8 digits)

## Expected Result:
dots` .` should not appear
## Actual Result:
There are several dots `……`

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?

- [ ] MacOS / Safari

**Version Number:** 1.2.56-0
**Reproducible in staging?:** y 
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/213556964-05f6092d-90b0-4c81-99fe-96f6ed68dcc8.mov

https://user-images.githubusercontent.com/43996225/213557211-c8e148d6-3c4c-4dbe-b955-802ec5f355e8.mp4

**Expensify/Expensify Issue URL:**
**Issue reported by:** @getusha 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1674153979209299

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a45e6916504d6da4</li>
        <li>Upwork Job ID: 1617978130995597312</li>
        <li>Last Price Increase: 2023-01-24</li>
    </ul>
</details>

**Comment by JmillsExpensify** [comment]
Wow sorry for the delay. I totally missed this last week. Checking the report now.

**Comment by JmillsExpensify** [comment]
Huh that's super weird. It actually looks like it only happens for currency abbreviations that are all letters. Doesn't occur for MX$. 

https://user-images.githubusercontent.com/1127863/214397623-03499f2b-5fd7-4ca3-a021-2399f25788e6.mov

Also this isn't limited to the Split Bill. Flow I can also reproduce in Send/Request Money as well.

**Comment by JmillsExpensify** [comment]
Opening up to `external`

**Comment by allroundexperts** [comment]
### Proposal

The issue ONLY happens for the currencies starting with letter A. This is because the downward stroke of the letter A is out of the symbol boundary. That causes this rendering issue on Safari.

We have 3 options to fix this.

1. Change the font to one without overflowing letters or fix this one so that letters don't overlap (specifically letter 'A').
2. Add padding to the `Text` as suggested by @Ollyws.
3. Cut the letter A's leg by adding `overflow: hidden` to the `Text` Element of the `CurrencySymbolButton` component.

Options 2 and 3 are sort of workarounds. I think we should fix this font and make sure that the letters stay within there bound. cc @shawnborton

**Comment by luacmartins** [comment]
I'll take a look at these proposals tomorrow!

**Comment by shawnborton** [comment]
Hmm, I don't think @allroundexperts is right here. This is a very strange bug, even after you delete the input you still see the remaining three dots:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/2319350/214523153-0a94e944-8a1e-41a8-a66e-8d22eecc28fc.png">

And then as soon as you resize your window, the dots go away. 

Also, this only happens in Safari too which is strange...

**Comment by getusha** [comment]
### Proposal
### RCA

This issue occurs when the text is rendered in a lower frame rate than the text's animation rate, causing the previous text frames to linger on the screen. This can create an effect where the text appears to be leaving a trail behind it.

>For performance reasons, WebKit only repaints those part of a page that it thinks might have changed.

Reference: 
* https://stackoverflow.com/a/17822836/18007080

```diff --git a/src/styles/styles.js b/src/styles/styles.js
index e30b5f77b5..92c5dcdceb 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -2181,6 +2181,9 @@ const styles = {
         fontSize: variables.iouAmountTextSize,
         color: themeColors.heading,
         lineHeight: variables.inputHeight,
+        outlineWidth: 1,
+        outlineStyle: 'solid',
+        outlineColor: 'transparent'
     },

     iouAmountTextInput: addOutlineWidth({
```

**Comment by luacmartins** [comment]
I agree with @allroundexperts here. This does seem to stem from the fact that some letters overflow their boundary and webkit leaves the artifacts when animating them. It seems to happen for the letters A, V, W and Y.

@shawnborton is it possible to fix the font itself so it doesn't overflow? If not, I think we should go with [option 3](https://github.com/Expensify/App/issues/14418#issuecomment-1402751398) and hide the overflow.

**Comment by shawnborton** [comment]
Oh wow, that's super interesting. I don't think modifying the font is a good option here, so hopefully we can fix this another way. That being said, if we "hide the overflow" - will the font appear to be cut off?

**Comment by shawnborton** [comment]
Also, why not try one of the solutions provided by @getusha [here](https://github.com/Expensify/App/issues/14418#issuecomment-1403788521)? Take a look at the StackOverflow that was linked.

**Comment by allroundexperts** [comment]
@shawnborton The font appears fine but I've noticed that it lags for a moment. [option 2](https://github.com/Expensify/App/issues/14418#issuecomment-1402751398) seems to work the best without any noticeable lag.

**Comment by luacmartins** [comment]
Thanks for confirming @shawnborton! I'd imagine we want to avoid the extra padding and shifting the layout by 1px. In that case the best option would be to add an outline as described [here](https://github.com/Expensify/App/issues/14418#issuecomment-1403788521).

**Comment by shawnborton** [comment]
Fair points, I would be fine with doing nothing for now.

**Comment by getusha** [comment]
I believe that this issue should be addressed, as it appears to be affecting all currency inputs.

**Comment by getusha** [comment]
@shawnborton every currency name that starts with "A" is affected

**Comment by shawnborton** [comment]
That makes sense, I'm just curious how many real users are sending money requests in currencies that start with A right now.

**Comment by getusha** [comment]
Also currency that starts with "Y", "W" and "V"  affected

**Comment by allroundexperts** [comment]
@rushatgabhane IMO, this link https://stackoverflow.com/questions/17575624/how-can-i-avoid-animation-artifacts-on-my-touch-draggable-border-radius-element/17723401#17723401 is not relevant to our error. It does not explain why this happens for a particular font only.

**Comment by getusha** [comment]
<img width="773" alt="Screenshot 2023-01-26 at 10 32 17 AM" src="https://user-images.githubusercontent.com/75031127/214920192-83539ae5-5ad6-4359-a434-f671ed40311b.png">

@rushatgabhane The WebKit rendering engine utilizes an optimization technique to improve performance by only redrawing parts of the webpage that have been modified. since the font is out of the box it doesn't move the rendered clipped text with the main text

**Comment by getusha** [comment]
<img width="773" alt="Screenshot 2023-01-26 at 10 35 56 AM" src="https://user-images.githubusercontent.com/75031127/214920906-6cd202d8-6a4f-4f5a-8896-9bc9db08b36a.png">

**Comment by getusha** [comment]
### Proposal 2

```diff --git a/src/styles/styles.js b/src/styles/styles.js
index e30b5f77b5..d19656b3c0 100644
--- a/src/styles/styles.js
+++ b/src/styles/styles.js
@@ -2181,6 +2181,7 @@ const styles = {
         fontSize: variables.iouAmountTextSize,
         color: themeColors.heading,
         lineHeight: variables.inputHeight,
+        willChange: "transform",
     },

     iouAmountTextInput: addOutlineWidth({
```

### Result

https://user-images.githubusercontent.com/75031127/214922240-a179f374-be4a-4736-8ea9-c7214dc5a593.mov

**Comment by s77rt** [comment]
It's worth noting that `will-change` is mostly used to deal with performance issues and not visual effects issues, there is a bunch of warnings that this property must be used with caution.
https://developer.mozilla.org/en-US/docs/Web/CSS/will-change

**Comment by JmillsExpensify** [comment]
Despite having tested and triaged this, it's hard to find a major currency in this list aside from AUD and maybe AED. Here's the full list of affected.

A: AED, AFN, ALL, AMD, ANG, AOA, ARS, AWG, AZN, AUD
V: VEB, VEF, VES, VUV
Y: YER
W: None

If we're not going to change the font, then I favor the doing nothing.

**Comment by luacmartins** [comment]
Sounds like we are ok with doing nothing here. I'll close the issue. Thanks for the input everyone!
