### ISSUE TITLE
[$2000] Web - Chat - Group chat - Emojis from quick menu appear with delay or after page refresh

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#18492]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Go https://staging.new.expensify.com/
2. Create a group chat + split bill
3. Confirm there is a split bill message
4. React to the split bill message with all 4 quick emojis

## Expected Result:
All 4 emojis should be displayed

## Actual Result:
1 or 2 emojis are displayed, rest 3 or 3 appear after page refresh.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] Windows / Chrome 
- [ ] MacOS / Desktop

**Version Number:** 1.3.9.14

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://user-images.githubusercontent.com/93399543/236540986-19571570-f1ad-43fd-a90b-c98ab54b16e4.mp4

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01d5a6606456b547ba</li>
        <li>Upwork Job ID: 1655565360362438656</li>
        <li>Last Price Increase: 2023-05-25</li>
    </ul>
</details>

**Comment by garrettmknight** [comment]
Reproduced, opening it up!

**Comment by garrettmknight** [comment]
Should be fixed by https://github.com/Expensify/App/issues/12775 - holding till that is fixed. Also reassigning since I'm going OOO.

**Comment by VitaliiP-0205** [comment]
![image](https://github.com/Expensify/App/assets/132633339/72ad803b-073c-4d48-996f-b85c2153dde1)
Hello all contributors.
When I run expensify app for web chrome, page like above page is displaying.
I cannot go to main page.
How can I do?

**Comment by VitaliiP-0205** [comment]
Contributor details
Your Expensify account email: vtlptpnk@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01e2d2dee073709f46

**Comment by Nikhil-Vats** [comment]
@jasperhuangg I think so, I looked into this issue and was able to find out the root cause. The emojis appear correctly first but then disappear because of the pusher events received. Although what I didn't understand was why the pusher events are always out of order, the pusher event from the first API call is always returned last due to which the emojis on the UI are wrong (only 1 emoji is added since the first AddEmojiReaction pusher event was received at the end and it has only 1 reaction). So, I think this will be fixed by the replay effect PR.

Also, this happens on all platforms and also happens when we remove multiple emojis quickly. The state becomes correct when an `OpenReport` request is triggered due to any kind of navigation.

**Comment by jasperhuangg** [comment]
https://github.com/Expensify/App/assets/31285285/fab6a543-52aa-4eb0-bc2a-1ed063a99365

Can still reproduce this one sadly. It looks like the Onyx data sent back from the server is correct for each response, so this is a front-end issue.

**Comment by jasperhuangg** [comment]
@MelvinBot it was on HOLD, so we haven't had a chance to accept proposals yet.

@0xmiroslav I'm pretty confident it's a front-end issue, since the Onyx updates we're receiving from Pusher seem to be correct.

**Comment by adelekennedy** [comment]
@kadiealexander I'm ooo for the next week but will pick up when I am back - we're just waiting for proposals!

**Comment by kadiealexander** [comment]
Going to bump the price since it's been quiet in here!

**Comment by koko57** [comment]
Hi I'm Agata from Callstack - expert contributor group - maybe I can do some investigation here? 🙂

**Comment by neil-marcellini** [comment]
Sorry @koko57, but I think this issue a duplicate of https://github.com/Expensify/App/issues/16506.

**Comment by koko57** [comment]
@neil-marcellini thanks for the info! 🙂 I was working on another issue today, was about to start the investigating this one now. If you'd need a hand with the original issue, let me know, maybe I could help. 🙂
