### ISSUE TITLE
[$1000] After creating a group with a new user, user is automatically removed from the group (or we navigate away)

### ISSUE THREAD

**Issue by Beamanator** [Expensify/App#20812]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. click on "+" icon
2. then go to create group section
3. select user from list
4. add new user from search
5. select the random email and select that email
6. Click on create group
7. Observe the group

## Expected Result:
The optimistic report should remain, and you should be able to type in the chat

## Actual Result:
The new user is removed for the group, or maybe we navigate to a different report

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** `main`
**Reproducible in staging?:** N
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation
**Expensify/Expensify Issue URL:**
**Issue reported by:** @niravkakadiya25
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686831616374889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e256c96a0de2398f</li>
        <li>Upwork Job ID: 1670720417402716160</li>
        <li>Last Price Increase: 2023-06-19</li>
    </ul>
</details>

**Comment by BeeMargarida** [comment]
I can't reproduce this with web but in iOS I can 🤔

**Comment by dylanexpensify** [comment]
@Beamanator I'm not able to reproduce on my side with iOS - can you elaborate a bit more what we should see?

**Comment by dylanexpensify** [comment]
Bumping this @Beamanator!

**Comment by Beamanator** [comment]
Yes sorry for the delay! 🙏 

@dylanexpensify you're also not able to reproduce on iOS? 😅 Basically the user was seeing that, if they create a group with 2 users - 1 existing and 1 brand new one that doesn't exist yet (a.k.a. creating the group will create their account), they saw that:
1. At first, the group was created successfully
2. After a few seconds, the brand new user was removed from the group 😅 

If you're not seeing that on staging iOS, maaaaaaaybe we can close this out? Or ask for better reproduction steps?

**Comment by dylanexpensify** [comment]
Ahh I'll try again for good measure, but may need to see about repro steps bein better!! Thanks man!

**Comment by dylanexpensify** [comment]
Ahh was able to repro! Thanks for the check @Beamanator!!

**Comment by waterim** [comment]
Hi! 
I'm Artem from Callstack - expert contributor group
Maybe I could help with this one?

**Comment by AbeerAhmad** [comment]
Contributor details
Your Expensify account email: abeerahmad204@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/abeerahmad204

**Comment by nitin-kukreti** [comment]
Contributor details
Your Expensify account email: nitinkukreti12@gmail.com
Upwork Profile Link: https://www.upwork.com/freelancers/~01cab64261c95a66c5

**Comment by mountiny** [comment]
Thanks @waterim feel free to work on this one! Post a proposal first please

**Comment by waterim** [comment]
Investigating why wrong data is coming.
I can see that for the first render after creating everything is fine, report was generated correctly, but after rerender new wrong report is coming.
For now two possible issues in my mind: 1. wrong data is coming from the backend. 2. Data is merging with some issues in onyx. 
Continuing with that.

**Comment by waterim** [comment]
Hello everyone!
I have a question related to the bug.
After I create a report(chat)  participantAccountIDs: [ 14892739, 5821110062872095 ] looks like this. First one is right, but the second one looks different. After a rerender of the page second one just is not coming from the backend side, but when I refresh the full application ids are comming correctly in this form: participantAccountIDs: [ 14892739, 14899579 ]

And the question is: How these ids are working? Why its different for a newly added user and how backend is handling that? 
I think that some issues can come from the backend side related to those different formatted ids.

The main issue here, from web side It has the same issue with getting just one user, without newly created, but after it takes the newest data with correct ids automatically. 
But from the mobile side it doesn't take the newest data withou hard refresh.

I hope I can do more on this issue with that kind of information.

Thank you in advance

**Comment by mountiny** [comment]
> How these ids are working? Why its different for a newly added user and how backend is handling that?
I think that some issues can come from the backend side related to those different formatted ids.

This is a new change and there are possibly some bugs related to it.

Essentially the new id is optimistic so we create the account with the details without waiting fro the backend. then ideally the API call should overwrite this data with the correct information. Seems like its not doing it automatically.

Could you bring this to #expensify-open-source channel as I am not super familiar with how this should work

**Comment by waterim** [comment]
Thank you, added this question to that channel :)

**Comment by s77rt** [comment]
@waterim Any updates here?

**Comment by waterim** [comment]
@s77rt no answers for my question yet on the channel. Should I ask it again?

**Comment by waterim** [comment]
@s77rt 
For online mode it takes old account as a small id, but new as a big one.
For offline it creates two big ids. Despite the fact that the first account was created previously, not during this "group creation". And after coming online it takes these 2 big ids.
<img width="476" alt="image" src="https://github.com/Expensify/App/assets/39777589/587f70e6-69fd-47e9-9f4e-d1ad530898c2">

**Comment by s77rt** [comment]
@waterim Can you please follow the proposal template? I don't think you provided a clear RCA yet.

It may be helpful for you to investigate whether the data is created correctly in offline mode or not, if it's not then we probably have to fix something in the FE. Your above comment is confusing (kept cycling between offline/online results)

> when you are coming the offline mode during using the app - old account will have small id, but new email a big one

> In offline mode group is creating correctly without issues

This seems like a contradiction

**Comment by waterim** [comment]
@s77rt based on our [conversation](https://expensify.slack.com/archives/C01GTK53T8Q/p1687289908644099) on slack 
I left this [comment](https://github.com/Expensify/App/issues/20812#issuecomment-1603363967) about weird ids after creating group in offline mode.
This [comment](https://github.com/Expensify/App/issues/20812#issuecomment-1603363967) is not a proposal yet.
 
As I understand after investigation these long ids are coming from the Onyx.
But in Offline mode I can create a group without this particular bug, email is not deleting. 
______
This bug exists just for an online usage. 
1. Locally optimistic report is being generated correctly.
2. The application sends the correct report, including the correct parameter: `emailList`.
3. The first response is not correct - it doesn't have new user data in the `participantsAccountIDs` nor `participants`.
4. The second response(after refreshing the app) is correct - report includes new user.

Looks like it is a backend issue.

**Comment by s77rt** [comment]
@waterim Thanks for the quick follow up.

> Locally optimistic report is being generated correctly

The `participantsAccountIDs` does not seem to be correct, the new one (for the new user) is a big number that will be overwritten. I think this may be okay, AFAIK we cannot predict the id of a user given their email.

> The first response is not correct - it doesn't have new user data in the participantsAccountIDs nor participants.

It looks correct, maybe this was fixed already? Is the bug still reproducible from your end?

**Comment by nitin-kukreti** [comment]
Is there any video reference for this issue?

**Comment by s77rt** [comment]
@nitin-kukreti There is from Slack post https://expensify.slack.com/archives/C049HHMV9SM/p1686831616374889


https://github.com/Expensify/App/assets/16493223/0f02ae9b-e4de-497c-96b9-b48500742dd6


@Beamanator Can you please include it in the issue description?

**Comment by nitin-kukreti** [comment]
wfewfke@wer.com user is not exist

**Comment by s77rt** [comment]
@nitin-kukreti Yes, that's what the bug is about, create a group chat with two users one that exists (chatted with before) and the other new

**Comment by s77rt** [comment]
@nitin-kukreti Yes, that appears to be the bug here although I'm not able to reproduce it. Are you still able to reproduce the bug?

**Comment by nitin-kukreti** [comment]
@s77rt  yes I am able to reproduce it this is because  we are getting empty reportAccountId after some reenders in mobile I am working on It I will give its solution asap

**Comment by waterim** [comment]
@s77rt My colleague is not able to repro this as well as you, but Im able

**Comment by nitin-kukreti** [comment]
@waterim do you know any method by which we can do breakpoints debugging in react native

**Comment by waterim** [comment]
@nitin-kukreti RN debugging inside of the chrome can be useful for that

**Comment by waterim** [comment]
@s77rt Okay, trying it

**Comment by waterim** [comment]
@s77rt With staging server everything looks correct

**Comment by s77rt** [comment]
@waterim Cool so the issue seems to be fixed already. @nitin-kukreti Can you confirm the same?

**Comment by nitin-kukreti** [comment]
@s77rt  I think I issue is in front-end side

**Comment by nitin-kukreti** [comment]
@waterim  no we can create group with one person (also with person which not exist)

**Comment by waterim** [comment]
<img width="310" alt="image" src="https://github.com/Expensify/App/assets/39777589/0dea33d2-bad6-4ac6-bb89-de08e3ec86e6">
participantAccountIDs array is empty in this case

**Comment by Beamanator** [comment]
I'd recommend looking in `personalDetailsList`, not `personalDetails` (keyed by accountID, not email) - I think we fixed the `-1` accountID problem in `personalDetailsList`, hopefully :D

**Comment by waterim** [comment]
@Beamanator Here I dont have even my newly created user :D
<img width="382" alt="image" src="https://github.com/Expensify/App/assets/39777589/e34f3cb4-bcbc-4b2e-a408-7274a9f0d5f9">

**Comment by nitin-kukreti** [comment]
@Beamanator when we are requesting from mobile devices for gerrating new Report with a user which not exit  giving accounId=-1 in api response but when we are performaing same operation from desktop web we are getting accurate response in which accountId is not -1.
does we are using different API end points for mobile and web ?

**Comment by Beamanator** [comment]
@waterim aahhhh this is the response to an API command, sorry i thought you were looking in Onyx directly :D

@nitin-kukreti that's quite strange, it's very unlikely that the data "should" be sent / returned different depending on the platform (mobile vs web) - we strive to make it all the same so we don't have weird edge cases for 1 platform

**Comment by s77rt** [comment]
@Beamanator Is the issue still reproducible from your end? (test against staging server). Currently it appears that only @nitin-kukreti is able to reproduce which is odd

**Comment by nitin-kukreti** [comment]
@Beamanator  and @s77rt  
It is a serverside error
I attaching some response portion of both mWeb and Web
`here accountId=-1`
this response from mWeb when first time we create Group with new user which not exit yet but after reloading response is ok.
## MWeb
### Before Reloading

![image](https://github.com/Expensify/App/assets/59364817/74f8bbc2-0f67-4efc-8c7d-8c1c56d35626)

### After Reloading
 Response Is totally different (Before it was array of 7 but after reloading on new request its only array of 5  as In previous response two entry were duplicate ) but accoudId exist for newly created user its not -1

![image](https://github.com/Expensify/App/assets/59364817/78845571-0494-4105-98d8-155c6a6dd05e)

## Web
 response in web is similar to response of mWeb but here account Id is not -1 but their also have two duplicate entry
 
![image](https://github.com/Expensify/App/assets/59364817/3497e0fc-76fc-455b-94b8-4bb37181b8dc)

**Comment by s77rt** [comment]
@nitin-kukreti I really doubt we get different responses based on the device. I'm still unable to reproduce the bug. Also the `personalDetails` is deprecated. You should just check `personalDetailsList`. As for the duplicated entries I have reported this [here](https://github.com/Expensify/App/issues/21600#issuecomment-1609266104) as well.

**Comment by Beamanator** [comment]
> I really doubt we get different responses based on the device.

Agreed response shouldn't be different based on device - check you're on the same env (staging / production) on both 🙏 

> Also the `personalDetails` is deprecated. You should just check `personalDetailsList`. 

Agreed 👍 We'll be removing all `personalDetails` data very soon b/c we don't use it in the App anymore - we will use `personalDetailsList` from now on

> As for the duplicated entries I have reported this https://github.com/Expensify/App/issues/21600#issuecomment-1609266104 as well.

👍

**Comment by nitin-kukreti** [comment]
@Beamanator  
I am rechecking that asap

**Comment by nitin-kukreti** [comment]
@Beamanator  @s77rt 

## MWeb 
not getting detail of newly created user
```
{
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "14923263": {
                    "accountID": 14923263,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_21.png",
                    "displayName": "nitinkukreti19@gmail.com"
                }
            }
        }
```
### after refreshing page 
  same report open but this time response is correct
  ```
 {
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "14943429": {
                    "accountID": 14943429,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_6.png",
                    "displayName": "rugsghfttfry@gugtyu.gtfyy"
                }
            }
        },
```
## Web
  Every thing is ok
```
 {
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "14943466": {
                    "accountID": 14943466,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_16.png",
                    "displayName": "dfaweraf@dfsgegse.gseegse"
                },
                "14893351": {
                    "accountID": 14893351,
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/00e8d12809980f19e9830837925eba7f04c7b31c_128.jpeg",
                    "displayName": "Nitin Kukreti"
                }
            }
        },
```
### after Reload
```

{
            "onyxMethod": "merge",
            "key": "personalDetailsList",
            "value": {
                "14943466": {
                    "accountID": 14943466,
                    "avatar": "https:\/\/d2k5nsl2zxldvw.cloudfront.net\/images\/avatars\/default-avatar_16.png",
                    "displayName": "dfaweraf@dfsgegse.gseegse"
                }
            }
        },
```

## Apart form this problem I notice a inconsistent API response after reloading page we are getting different response for same report  in key=personalDetailsList

**Comment by s77rt** [comment]
@nitin-kukreti That's weird :sweat_smile: Just double check that all those request are being sent to the correct server and that is the staging server. I don't know why you are the only one who can reproduce this. From my end both web and mweb return same data

**Comment by s77rt** [comment]
Melvin

> Are we close to approving a proposal?

We are not even close to reproducing the bug :sweat_smile:  That's a good thing I hope

**Comment by dylanexpensify** [comment]
reviewing today and posting next steps!

**Comment by dylanexpensify** [comment]
@s77rt can you repro? Or should we close this out? cc @Beamanator

**Comment by Beamanator** [comment]
Hoping we can close this out 🙏

**Comment by s77rt** [comment]
@dylanexpensify I can't repro. Let's close this

**Comment by s77rt** [comment]
Melvin we will probably close this one

**Comment by dylanexpensify** [comment]
Closing!
