### ISSUE TITLE
Web -Tooltip for user in group is offcenter and displayed over report

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21105]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Scroll to group report which has partial name or email in end
3. Hover on 3 dots

## Expected Result:
App should display tooltip over 3 dots in LHN for group users

## Actual Result:
 App displays tooltip over report for group users in end

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.29-3

**Reproducible in staging?:** y

**Reproducible in production?:** y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/fc3cd91e-2e18-4924-8bea-f19750165117

https://github.com/Expensify/App/assets/93399543/0c3d3b2e-5e57-4beb-9593-c00972bb4222

**Expensify/Expensify Issue URL:**

**Issue reported by:** @dhanashree-sawant

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1686647368251889

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by alitoshmatov** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web -Tooltip for user in group is offcenter and displayed over report
### What is the root cause of that problem?
We are not passing `shiftHorizontal` prop down to tooltip in `UserDetailsTooltip` 
### What changes do you think we should make in order to solve the problem?
We should pass `props.shiftHorizontal` down to `Tooltip` component here:
https://github.com/Expensify/App/blob/e6c2704eb43d4d31a55eff5d5d1b3e89c5292bc3/src/components/UserDetailsTooltip/index.js#L42

### What alternative solutions did you explore? (Optional)

**Comment by jeet-dhandha** [comment]
@alitoshmatov Your proposal should fix this issue too. 

ISSUE: https://github.com/Expensify/App/issues/21100

**Comment by alitoshmatov** [comment]
@jeet-dhandha You are right it should fix that issue

**Comment by tjferriss** [comment]
I tried to recreate the issue. My tooltips hover over the name as intended. Does this only happen with extra long names/emails? If so, @kbecciv can you update the OP?

<img width="494" alt="Screenshot 2023-06-23 at 09 51 27" src="https://github.com/Expensify/App/assets/8292562/5b145aef-4318-48f8-9023-d99cf871a62e">

**Comment by alitoshmatov** [comment]
![Uploading Screenshot 2023-06-26 at 11.18.05 PM.png…]()

I think it is still reproducable
