### ISSUE TITLE
[Pending Checklist] [$1000] Description - Cursor half visible when hitting Enter and going to next line of Task Description

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#21271]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/20775
## Action Performed:
1. Login to NewDot
2. Go to any chat
3. Click + and Assign Task
4. Enter first line in Description field
5. Press Enter on the keyboard

## Expected Result:
Cursor should be well visible on the second line

## Actual Result:
Cursor partially visible until any other character is type after Enter

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.30.0

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/29a66825-ee1c-45d3-9177-f2be6777a755

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014922e794dd66dc4a</li>
        <li>Upwork Job ID: 1677228108574597120</li>
        <li>Last Price Increase: 2023-07-14</li>
    </ul>
</details>

**Comment by greg-schroeder** [comment]
There are a couple issues pointing to this:

https://github.com/Expensify/App/issues/21280
https://github.com/Expensify/App/issues/21205

I think it will just be fixed by https://github.com/Expensify/App/issues/21205.

**Comment by s-alves10** [comment]
Please check this proposal. This will solve the all kind of issues related to auto-grow `TextInput`

https://github.com/Expensify/App/issues/21905#issuecomment-1613869581

**Comment by fabriziobertoglio1987** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- TextInput has the wrong height after hitting enter on Safari/Macos/Chrome
- The cursor is cut

### What is the root cause of that problem?

The root cause of the issue is the difference in behaviour of the Text Component on different platforms (web, iOS and Android).
The height of the TextInput is calculated with Text [onLayout](https://github.com/Expensify/App/blob/c0ece67e0edcb725d8f72cf57cd40d98854c552c/src/components/TextInput/BaseTextInput.js#L392), which has a different behaviour when adding new line between react-native-web and react-native.

#### React Native Web uses white-space: pre-wrap to render new lines and spaces

`react-native-web` uses [white-space: pre-wrap](https://github.com/necolas/react-native-web/blob/b10c66351eae55a8ea798a1217254d7a2658c5b1/packages/react-native-web/src/exports/Text/index.js#L198) which adds a new line only when the `\n` is followed by a character (for ex. `Line1\n` has one line, `Line1\nLine2` has two lines).

https://snack.expo.dev/@fabrizio.bertoglio/grounded-croissant

<img width="1648" alt="Screenshot 2023-07-02 at 5 39 55 PM" src="https://user-images.githubusercontent.com/24992535/250347746-0ad18c52-f966-4012-b1bf-5a4fc9af1601.png">


<img width="1648" alt="Screenshot 2023-07-02 at 5 40 18 PM" src="https://user-images.githubusercontent.com/24992535/250347763-afc5a577-6ddb-4338-83ee-b64d8223861a.png">

<img width="2032" alt="Screenshot 2023-07-02 at 5 41 12 PM" src="https://user-images.githubusercontent.com/24992535/250347815-71a98d19-cd46-44ec-9634-b1106fe95469.png">

<img width="2032" alt="Screenshot 2023-07-02 at 5 41 43 PM" src="https://user-images.githubusercontent.com/24992535/250347853-cb03ba24-4dbe-421f-ad4e-cfd0f9ebee10.png">

#### React Native uses native Layout APIs to calculate the View height and sets the height of the View onMeasure

`react-native` uses native APIs to calculated the layout from the ShadowNode (on Android using the Layout API). The `\n` adds a new line (for ex. `Line1\n` has two lines) on iOS and Android.

snack https://snack.expo.dev/@fabrizio.bertoglio/grounded-croissant

When the Text has some text in the new line:

- Android height 36
- Safari height 34

<img width="1648" alt="Screenshot 2023-07-02 at 1 44 16 PM" src="https://user-images.githubusercontent.com/24992535/250337114-4b1a7c5b-d559-4afb-b404-7c630044f08a.png">

When the Text has an empty line:

- Android height 36
- Safari height 17

<img width="1648" alt="Screenshot 2023-07-02 at 1 44 25 PM" src="https://user-images.githubusercontent.com/24992535/250337129-4ddb0c5c-bf9f-4c6b-923e-ee11ecda675f.png">

iOS


<img width="1648" alt="Screenshot 2023-07-02 at 9 54 34 PM" src="https://user-images.githubusercontent.com/24992535/250361219-d2b3dc41-367f-47d7-a936-39d92df538a8.png">

### What changes do you think we should make in order to solve the problem?

https://reactnative.dev/docs/tutorial#whats-going-on-here
>JSX lets you write your markup language inside code. It looks like HTML on the web, except instead of web things like div or span, you use React components. 

https://github.com/react-native-community/discussions-and-proposals/pull/496
>React Native currently includes many APIs that are modelled on Web APIs but do not conform to the standards of those Web APIs.

React Native is based on Web Standards. For this reason, iOS and Android should uniform to Web. 
The native implementation needs to be updated to behave like Web, on Android requires changes to ReactTextShadowNode measure, FontMetricsUtil, ReactTextView onLayout, TextLayoutManager and TextLayoutManagerMapBuffer measureText to avoid adding a new line when `\n` is not followed by a character.
Similar changes are required on iOS. 

### What alternative solutions did you explore? (Optional)

Fixing the issue in react-native-web and adding a new line when using `\n` to uniform the API with iOS and Android.

**Comment by sophiepintoraetz** [comment]
I can reproduce this, @greg-schroeder  (albeit in a different place in the product but there are proposals in here that will address both) - https://github.com/Expensify/App/issues/21205 did not fix this issue.

![2023-07-04_15-45-09 (1)](https://github.com/Expensify/App/assets/42940078/b7403f49-8e67-41fc-9ff1-8045fca3ed5f)

**Comment by Nathan-Mulugeta** [comment]
Hey I am coming from #21905 aren't these two issues found on different places of the product? Doesn't that make me eligible for reporting @sophiepintoraetz , thanks.

**Comment by sophiepintoraetz** [comment]
@Nathan-Mulugeta - they are different areas but the same issue - https://github.com/Expensify/App/issues/21905 has been closed out as a dupe. I see you are prolific you are in reporting issues, so I think you'll make this one up quickly!.

**Comment by Nathan-Mulugeta** [comment]
Thanks for your reply and for the compliment @sophiepintoraetz 🙂

**Comment by s-alves10** [comment]
I think we have to fix the root cause of the problem. Please check my [proposal](https://github.com/Expensify/App/issues/21905#issuecomment-1613869581)

**Comment by sakluger** [comment]
Hey folks, I just closed another duplicate issue (https://github.com/Expensify/App/issues/21449) on yet another page of the product. I think that whatever solution we go with, it should be a global solution that fixes this across all pages.

**Comment by greg-schroeder** [comment]
All right - if it wasn't fixed by #21205 we can fix it here, while keeping https://github.com/Expensify/App/issues/21271#issuecomment-1622262257 in mind

**Comment by sobitneupane** [comment]
Thanks for the proposal @fabriziobertoglio1987 

> Fixing the issue in react-native-web and adding a new line when using \n to uniform the API with iOS and Android.

Is there any open issue in react-native-web for this?

**Comment by sobitneupane** [comment]
> https://github.com/Expensify/App/issues/21271#issuecomment-1619490591

@s-alves10 Can you please add your proposal in this issue?

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Cursor gets half hidden on enter in Welcome message page

### What is the root cause of that problem?

We get the required height of the `TextInput` here
https://github.com/Expensify/App/blob/3b721c4cbf1714720d529a9ef5b81f14e1cb699c/src/components/TextInput/BaseTextInput.js#L384-L394

We use `Text` component and its height doesn't increase when the text is ended with line break.

This is the root cause

### What changes do you think we should make in order to solve the problem?

We can add space character to the end of the text if text is ended with `line-break`.

```
    {props.value ? props.value + (props.value.endsWith('\n') ? ' ' : '') : props.placeholder}
```

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/c77e59fc-a660-460d-a86d-2f3ee82eb40b


</details>

### What alternative solutions did you explore? (Optional)
Instead of above code, we can use add '\n' character to the text.

```
    {props.value ? props.value + '\n' : props.placeholder}
```

**Comment by sobitneupane** [comment]
Thanks @s-alves10. Please try to add more explanation in the root cause analysis. Your solution is kind of workaround. We will look for solution that solves the issue at root. Your proposal is under consideration.

**Comment by sobitneupane** [comment]
Thanks @Ollyws. Your proposal is very similar to @s-alves10's [proposal](https://github.com/Expensify/App/issues/21271#issuecomment-1628784442).

**Comment by s-alves10** [comment]
In order to get the required height for `TextInput` component, we use `Text` component with the same content.
If we encounter '\n' at the last of the content, `TextInput` needs to place the cursor at the next line and increase the height so that cursor is fully visible. But for Text component, no need to increase its height since there is no cursor. That's why the size of `Text` and `TextInput` is different when there is '\n' character at the end of the content

**Comment by sobitneupane** [comment]
@s-alves10 

> If you want to make an entirely new proposal or update an existing proposal, please go back and edit your original proposal, then post a new comment to the issue in this format to alert everyone that it has been updated:
> ## Proposal
> [Updated](link to proposal)

When certain change is requested on your proposal, please follow the above mentioned rule in Contributing guideline. It will be easier for the final reviewer to go through your proposal at once.

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21271#issuecomment-1628784442)

**Comment by greg-schroeder** [comment]
@sobitneupane does your thumbs above mean approved or still reviewing?

**Comment by sobitneupane** [comment]
Still expecting proposals. We already have proposals that solves the issue but we would prefer the issue to be solved upstream if possible.

**Comment by s-alves10** [comment]
I think this is the bug of the `BaseTextInput` component and we need to fix the root cause. I'd like to know what you mean by upstream.

**Comment by greg-schroeder** [comment]
Still awaiting proposals - do we need to double this potentially?

**Comment by s-alves10** [comment]
@sobitneupane 
Will you tell me what drawbacks [my solution](https://github.com/Expensify/App/issues/21271#issuecomment-1628784442) has?

**Comment by sobitneupane** [comment]
@s-alves10 We are using [`Text`](https://github.com/Expensify/App/blob/3b721c4cbf1714720d529a9ef5b81f14e1cb699c/src/components/TextInput/BaseTextInput.js#L384-L394) as workaround. So, I was expecting some proposal to remove the work-around and solve the task. But for now we can go with your solution as it solves the issue.

**Comment by sobitneupane** [comment]
[Proposal](https://github.com/Expensify/App/issues/21271#issuecomment-1628784442) from @s-alves10 looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by s-alves10** [comment]
@dangrous 
I think so too

**Comment by dangrous** [comment]
Lies melvin

**Comment by sobitneupane** [comment]
@dangrous Yeah. We can go with the alternative soltuion.

**Comment by dangrous** [comment]
Sweet. Let's move forward then. Assigning @s-alves10 now!

**Comment by greg-schroeder** [comment]
PR on staging, awaiting deploy to prod

**Comment by greg-schroeder** [comment]
Assigned July 20 -> Merged July 24th (2 business days)

Payment summary:

Reporter: Applause (no payment) 
C: @s-alves10 - $1,500
C+: @sobitneupane - $1,500

**Comment by greg-schroeder** [comment]
Processing

**Comment by greg-schroeder** [comment]
@sobitneupane you're up on the [checklist](https://github.com/Expensify/App/issues/21271#issuecomment-1652066737)!

**Comment by greg-schroeder** [comment]
bump @sobitneupane

**Comment by sobitneupane** [comment]
> **BugZero Checklist:** The PR fixing this issue has been merged! The following checklist ([instructions](https://stackoverflow.com/c/expensify/questions/14574)) will need to be completed before the issue can be closed:
> 
> * [ ]  [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:

https://github.com/Expensify/App/pull/19377
> * [ ]  [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

It was a known issue in the PR. https://github.com/Expensify/App/pull/19377#issuecomment-1557290282
> * [ ]  [@sobitneupane] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

It was a known issue. Discussion : https://github.com/Expensify/App/pull/19377#issuecomment-1557290282

> * [ ]  [@sobitneupane] Determine if we should create a regression test for this bug.

yes
> * [ ]  [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.

**Comment by sobitneupane** [comment]
**Regression Test Proposal**

1. Open ND and log in with any account
2. Click FAB and Assign Task
3. Enter first line in description field
4. Press Enter key
5. Verify that the cursor is fully visible

Do we agree 👍 or 👎

**Comment by dangrous** [comment]
Test looks good to me

**Comment by JmillsExpensify** [comment]
Reviewed the details for @sobitneupane. $1,500 approved for payment in NewDot.

**Comment by greg-schroeder** [comment]
Filed regression test issue, closing
