### ISSUE TITLE
[Awaiting bug report payment][$1000] Workspace - No loader for workspace members page

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#21567]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app in a new incognito window. Don't open in an existing incognito window.
2. Create a workspace if you don't already have one.
3. Go to Settings > Workspaces > Members.
4. Notice that there is no loader for the members and the message "Member not found. To invite a new member to the workspace, please use the Invite button above." is shown before members are loaded.

## Expected Result:
A loader should be shown before members are loaded.

## Actual Result:
There is no loader before members are loaded and the message "Member not found. To invite a new member to the workspace, please use the Invite button above."  is shown which might be confusing for users if they have slow connection.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [x] Android / Chrome
- [x] iOS / native
- [x] iOS / Safari
- [x] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** 1.3.29-11
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/99cf1043-4c68-4184-b750-7473e7b92a62

https://github.com/Expensify/App/assets/93399543/62a84e50-07b9-4c8a-b708-1cc97f4ed030

**Expensify/Expensify Issue URL:**
**Issue reported by:** @Nikhil-Vats
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687423087741759

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010e98a1022376a0f5</li>
        <li>Upwork Job ID: 1673721545937694720</li>
        <li>Last Price Increase: 2023-07-04</li>
    </ul>
</details>

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Loader is not shown on workspace members page before members are loaded. Instead an error message is shown.

### What is the root cause of that problem?
We are not using ActivityIndicator in the page and are showing error if length is 0 for members.

### What changes do you think we should make in order to solve the problem?
Use `ActivityIndicator` in `WorkspaceMembersPage` if length of data is 0 and isLoading is `true` and show error only if members are loaded (`isLoading` is false) and data length is 0.

### What alternative solutions did you explore? (Optional)

NA

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Loader is not shown on workspace members page before members are loaded. Instead an error message is shown - "Member not found. To invite a new member to the workspace, please use the Invite button above."

### What is the root cause of that problem?
We are not using ActivityIndicator in the page and are showing error if length is 0 for members. We are not using the function `shouldShowPolicy()` which checks if the policy data is loaded in onyx.

https://github.com/Expensify/App/blob/1e308ca7eb8771acc468d8dde45a770c435c1b66/src/libs/PolicyUtils.js#L66-L84

### What changes do you think we should make in order to solve the problem?
Use `ActivityIndicator` in `WorkspaceMembersPage` if `PolicyUtils.shouldShowPolicy(props.policy.id)` is false.

### What alternative solutions did you explore? (Optional)
We can also show the loader on the whole view rather than only the members list. For that, we just need to change the position of `ActivityIndicator` in the returning JSX. 

Result -

https://github.com/Expensify/App/assets/31413407/2dd560ac-96ba-44eb-8e12-40ea139e8b3a

**Comment by Nikhil-Vats** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Loader is not shown on workspace members page before members are loaded. Instead an error message is shown - "Member not found. To invite a new member to the workspace, please use the Invite button above."

### What is the root cause of that problem?
We are not checking if policy members have loaded and are showing error if length is 0 for members. There is no use of `ActivityIndicator` in page to show any loader if members have not loaded. See line 471.

https://github.com/Expensify/App/blob/1e308ca7eb8771acc468d8dde45a770c435c1b66/src/pages/workspace/WorkspaceMembersPage.js#L448-L472

### What changes do you think we should make in order to solve the problem?
Check if `props.policyMembers` is empty using `_.isEmpty(props.policyMembers)` and show `ActivityIndicator` if it is indeed empty.

We can show the loader in the center rather than on top using the `flex-grow: 1` and `justify-content: center` property on the container of loader so that it grows to remaining space. 

```javascript
{_.isEmpty(props.policyMembers) ? (
    <View style={[styles.flexGrow1, styles.justifyContentCenter]}>
        <ActivityIndicator
            color={themeColors.spinner}
            size="large"
        />
    </View>
) : (
  // existing code to render members, buttons, etc. when all data is loaded
)}
```
If we don't want to show it in center, we can simply remove the `View` wrapper.

We can also make a function for this in the `WorkspaceMembersPage` or in `PolicyUtils` (which has other utilities related to workspace) -
```javascript
function shouldShowPolicyMembers(policyMembers) {
  return !_.isEmpty(policyMembers);
}
```
Then, we can use this function in `WorkspaceMembersPage`. If this function returns `true` then we can render members, buttons, etc. otherwise we render `ActivityIndicator`. 

### What alternative solutions did you explore? (Optional)
NA

Result -


https://github.com/Expensify/App/assets/31413407/4d8a4713-722f-4410-9724-47bdd458c061

**Comment by trjExpensify** [comment]
I think this is a dupe of [this issue](https://github.com/Expensify/App/issues/19236) and should be fixed by [this PR](https://github.com/Expensify/App/pull/21387) when we implement the skeleton UI on this page when it's loading. Going to close it out!

**Comment by Nikhil-Vats** [comment]
@trjExpensify this is not a dupe of https://github.com/Expensify/App/issues/19236, that issue is trying to fix the 'Hmm.. it's not here page' that appears when we open the members or invite page using deeplink in desktop app.

Screenshot of that issue -
<img width="1147" alt="image" src="https://github.com/Expensify/App/assets/31413407/f997ae9e-648d-41b5-8fce-25cffaee45df">

Video of that issue -

https://user-images.githubusercontent.com/96077027/236749763-f88e9a37-e5e4-4ddb-bc9b-be83af3d38d9.mov

This issue appears on all platforms and is not related to deeplink at all. This issue is simply the lack of loader on Workspace Members page which shows this message until members are not loaded -
"Member not found. To invite a new member to the workspace, please use the Invite button above." 

You can see the issue description for more details.

**Comment by trjExpensify** [comment]
Hm, but isn't the root cause the same? We don't currently have the skeleton UI implemented on the workspace members page? By adding it, this won't be a problem. 

Happy to reopen and get a second opinion however! CC: @kowczarz @aimane-chnaif

**Comment by Nikhil-Vats** [comment]
@trjExpensify I tested that PR and it doesn't fix this issue because the state of `policyMembers` (whether they are loaded or not) is not being checked anywhere in existing code and that PR. That PR is showing the skeleton view when the workspace details have not loaded which includes details like name, owner, currency, etc. but doesn't include `policyMembers` since there is a separate API call for that.
<img width="294" alt="image" src="https://github.com/Expensify/App/assets/31413407/6025d065-c006-4510-91a2-03f5f07e10df">

Screen recording using the PR's code locally checked out -

https://github.com/Expensify/App/assets/31413407/aade138a-5401-448b-b3d0-9d80e2b7b28f

**Comment by trjExpensify** [comment]
Hehe, that's the same PR I referenced [here](https://github.com/Expensify/App/issues/21567#issuecomment-1607990200)

**Comment by Nikhil-Vats** [comment]
@allroundexperts that code can be removed since there is always at least 1 member in the workspace - the workspace owner which cannot be removed by anyone.
<img width="375" alt="image" src="https://github.com/Expensify/App/assets/31413407/1f3add03-2133-4a82-a03e-d08d0dd60ea7">

I updated my [proposal](https://github.com/Expensify/App/issues/21567#issuecomment-1607748470) to reflect it.

**Comment by trjExpensify** [comment]
How are we looking here now @allroundexperts?

**Comment by Nikhil-Vats** [comment]
Thanks @allroundexperts . I unnecessarily updated my proposal and like you said, it won't work correctly if we search for members. I have reverted the changes back as the initial proposal works fine. Please see the video below. It is also attached in my [updated proposal](https://github.com/Expensify/App/issues/21567#issuecomment-1607748470).


https://github.com/Expensify/App/assets/31413407/a9ee798f-8524-4dc4-9e2f-baf48ecac93a

As for a workspace without an admin, can you tell me how were you able to produce an instance with no members so that I can better understand the edge case and propose an updated solution? As no one can remove the admin, not even the admin themselves.

**Comment by trjExpensify** [comment]
@allroundexperts are you cool with the updated proposal?

**Comment by roryabraham** [comment]
Sorry, I don't agree that we should display an activity indicator. Let's use a skeleton UI instead.

**Comment by Nikhil-Vats** [comment]
Sure @roryabraham . I will update the proposal to use Skeleton UI.

**Comment by Nikhil-Vats** [comment]
Sure @roryabraham . I will update the proposal to use skeleton UI.

**Comment by roryabraham** [comment]
> Skeleton will be added in https://github.com/Expensify/App/pull/21387

Looks like a loading spinner, not a skeleton UI?

> @roryabraham Lets put this on hold then since https://github.com/Expensify/App/pull/21387 is doing something similar?

Agreed, seems like this is a dupe of https://github.com/Expensify/App/issues/19236, so let's put this on HOLD to see if @amyevans agrees. If so, we should just close this. @amyevans what do you think?

**Comment by amyevans** [comment]
> Agreed, seems like this is a dupe of https://github.com/Expensify/App/issues/19236, so let's put this on HOLD to see if @amyevans agrees. If so, we should just close this. @amyevans what do you think?

I don't think it's _strictly_ a dupe, because different data missing is resulting in different views during the load phase. That said, per @aimane-chnaif's [comment in the PR](https://github.com/Expensify/App/pull/21387#issuecomment-1627432736), we'll ensure both cases are covered in the PR and a skeleton UI is displayed. So I think a `HOLD` makes sense for this GH, with a reporter bonus payout once https://github.com/Expensify/App/pull/21387 is live?

**Comment by roryabraham** [comment]
Thanks @amyevans!!!

**Comment by trjExpensify** [comment]
Nice, makes sense to me. Added the issue title in the header for the hold!

**Comment by trjExpensify** [comment]
Linked PR is in review!

**Comment by roryabraham** [comment]
on HOLD

**Comment by trjExpensify** [comment]
Linked PR is still in review.

**Comment by trjExpensify** [comment]
Deployed to staging 15 hours ago! Retested and the skeleton UI circumvents the problem:

https://github.com/Expensify/App/assets/16232057/0c84391e-812e-4ffa-8a8f-957706db2c5f

With that, I've sent @Nikhil-Vats an offer for $250 for the bug report. Once settled, we can close this out! :)

**Comment by trjExpensify** [comment]
Settled!
