### ISSUE TITLE
[WAITING ON MIROSLAV TO COMPLETE CHECKLIST] [HOLD for payment 2023-10-02] [$1000] content of input jumps from top to bottom in multi-line inputs

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#21654]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. create a task
2. open the task
3. write a long multi-line description and save it
4. now open the description and observe the input field and scrollbar in RHP
## Expected Result: 
content should be at bottom at the time of rendering
## Actual Result: 
content of input jumps from top to bottom

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.32-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/9ab22950-78ee-4962-b443-f64f3a3369a2

https://github.com/Expensify/App/assets/43996225/128bb525-01d3-4409-b6fa-0b3e324d69cf

**Expensify/Expensify Issue URL:**
**Issue reported by:** @chiragxarora 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1687610858267479

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014ef411cb69302ae1</li>
        <li>Upwork Job ID: 1673690266454241281</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>0xmiroslav | Reviewer | 26723385</li>
<li>chiragxarora | Contributor | 26723386</li>
<li>chiragxarora | Reporter | 26723387</li>
</ul></li>
    </ul>
</details>

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Content of Input jumps from top to bottom in multi-line input

### What is the root cause of that problem?

We set focus on the input after transition ends as you can see below

https://github.com/Expensify/App/blob/96e534a5b28cecb7cb221986a2dbca57c6d2fc1e/src/pages/tasks/TaskDescriptionPage.js#L65

So focus is set after the transition ends and the modal is shown fully. This is the root cause

### What changes do you think we should make in order to solve the problem?

We can add `autoFocus` props to the `TextInput` and remove the `onEntryTransitionEnd` props from `ScreenWrapper`

This works as expected.

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/b457c5e4-4a6e-410f-9481-8af6ff0801dd


</details>

### What alternative solutions did you explore? (Optional)

**Comment by abekkala** [comment]
@0xmiroslav have you had a chance to review the proposals that have come in so far?

**Comment by abekkala** [comment]
@0xmiroslav can you review the proposals above?

**Comment by abekkala** [comment]
@jliexpensify Reassigning for sabbatical
____
### CURRENT STATUS:

Waiting on a proposal to be chosen

- Issue reported by: @chiragxarora
- Assigned for Fix: TBD
- C+: @0xmiroslav

**Comment by s-alves10** [comment]
@0xmiroslav 
What do you think of my solution?

**Comment by JSExpert1121** [comment]
I think using shouldDelayFocus isn't a solution. How much delay should we use? To fix the root cause of the issue, we need to fix the autoFocus function of the TextInput component.
If autoFocus is set, TextInput should work as expected without any other actions

**Comment by jliexpensify** [comment]
@0xmiroslav - it looks like you've been bumped a few times to address comments! Can you take a look please?

**Comment by jliexpensify** [comment]
@chiragxarora hello, did you manage to update your proposal? Cheers!

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21654#issuecomment-1608776831)

@0xmiroslav 
Yes you're right. We should manage focus in `BaseTextInput` itself. I tested the updated solution on all platforms and works perfect.

**Comment by jliexpensify** [comment]
Bump @0xmiroslav to review the above solution

**Comment by s-alves10** [comment]
@0xmiroslav 

Yes. If `autoFocus` isn't set, we don't set focus
https://github.com/Expensify/App/blob/8dcad168d11a71424b6ffd7fa30fd1770c0165d5/src/components/TextInput/BaseTextInput.js#L60-L81

And if not multiline, `focusAndUpdateMultilineInputRange` function only set focus at the end of the input. This is an expected behavior, I think.  https://github.com/Expensify/App/blob/8dcad168d11a71424b6ffd7fa30fd1770c0165d5/src/libs/focusAndUpdateMultilineInputRange.js#L12-L24

Do we need any other props for `BaseTextInput`?

**Comment by jliexpensify** [comment]
Bump @0xmiroslav to check out proposals!

**Comment by s-alves10** [comment]
@0xmiroslav 

Will you check https://github.com/Expensify/App/issues/21654#issuecomment-1645162780 and let me know your thought?

**Comment by jliexpensify** [comment]
Bump @0xmiroslav for reviews!

**Comment by jliexpensify** [comment]
Bump @0xmiroslav for reviews please!

**Comment by s-alves10** [comment]
@0xmiroslav 

[My solution](https://github.com/Expensify/App/issues/21654#issuecomment-1608776831) use neither `setTimeout` nor `onEntryTransitionEnd`.
Will you tell me what is the drawback of my solution?

**Comment by jliexpensify** [comment]
Bump @0xmiroslav to address questions

**Comment by jliexpensify** [comment]
Bump @0xmiroslav to address questions. Otherwise I will reassign this one to another C+, thanks!

**Comment by s-alves10** [comment]
> There has been discussion that we are trying to consolidate autofocus approach into `onEntryTransitionEnd` callback because `shouldDelayFocus` is still using `setTimeout` and not perfect solution.

Can you send me the discussion link?

**Comment by jliexpensify** [comment]
Not overdue!

**Comment by jliexpensify** [comment]
@0xmiroslav - we're not getting any further proposals. What do you want me to do here? Double it or do you want to choose @s-alves10's one?

**Comment by jliexpensify** [comment]
Bump @0xmiroslav - can I get some thoughts here? If you are unable to work on this, I will reassign another C+.

**Comment by jliexpensify** [comment]
@0xmiroslav making this on External again, it looks like Melvin automatically made this Internal. 

I just tested again and am seeing this behaviour.

**Comment by s-alves10** [comment]
@0xmiroslav 

There was a similar discussion https://github.com/Expensify/App/issues/20836#issuecomment-1600491194

And yes, I was wrong. On iOS, we can't solve the issue with `autoFocus`

**Comment by jliexpensify** [comment]
Still no suitable solutions

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/21654#issuecomment-1697022393)

**Comment by jliexpensify** [comment]
Bumo @0xmiroslav to review the above proposal.

**Comment by ShogunFire** [comment]
@0xmiroslav I think we should fix this by using selection props, it was actually like this before but there is an issue in react native with selection: https://github.com/facebook/react-native/issues/30298 Do you think this is worth trying to solve the react native issue or you have something else in mind ?

**Comment by jliexpensify** [comment]
Not overdue, waiting for proposals!

**Comment by jliexpensify** [comment]
Hey @kavimuru @chiragxarora @0xmiroslav - SInce this is such an old issue. I've tested this one again, and I'm seeing that the LHN is a lot more stable: nothing seems to be jumping. Can you test and verify this?

**Comment by s-alves10** [comment]
@jliexpensify 

This is an issue related to the TextInput focusing when opening a task description edit page
If a task description is multiline text, the focus jumps to bottom. It is still reproducible.
Please test with 10+ lines of description

**Comment by jliexpensify** [comment]
Sorry, my mistake - I had 3 issues open and must have looked/posted in the wrong one! Thanks for confirming.

**Comment by jliexpensify** [comment]
We're still no closer to coming up with a suitable proposal?

**Comment by jliexpensify** [comment]
[Was there a regression here](https://github.com/Expensify/App/issues/21654#issuecomment-1724019984)? 

Payment Summary:

- Reporter / Contributor: @chiragxarora $250 + $1000
- C+: @0xmiroslav : $1000 

[Upwork job](https://www.upwork.com/jobs/~014ef411cb69302ae1)

Miroslav, please complete the checklist.

**Comment by jliexpensify** [comment]
Ok, that's fair - I can trace it to this [comment](https://github.com/Expensify/App/pull/27702#issuecomment-1727388685). I'll adjust!

**Comment by jliexpensify** [comment]
Thanks, are you ready to take payments @0xmiroslav ?

**Comment by jliexpensify** [comment]
@chiragxarora no worries, I will fix this up when I pay - there's the ability to add bonuses.

**Comment by jliexpensify** [comment]
Oh weird, the job is now closed - @chiragxarora you haven't been paid right? I guess it was an old listing.

**Comment by jliexpensify** [comment]
Hmm everything is showing as inactive for me:

![image](https://github.com/Expensify/App/assets/30815269/af417b8b-992f-4974-b447-f6220d26029e)

Can you share the job/contract link with me? Cheers

**Comment by jliexpensify** [comment]
@chiragxarora I can pay these ones - can you send me a link to the reporter one as well?

**Comment by jliexpensify** [comment]
Thanks, have paid you @chiragxarora . @0xmiroslav closing this out, [but here is the payment summary.](https://github.com/Expensify/App/issues/21654#issuecomment-1744158553)
