### ISSUE TITLE
[$1000] "Last reply ..." Notifier overflows in spanish for threads with more than two replies

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#22039]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1.  Sign in to staging new dot
2.  Go to a chat with more than two replies to one of the messages
3.  Notice how the last replied time is shown in full in the parent message
4.  Go to preferences and change the language to spanish
5.  Notice how the last reply message is overflown hiding the date and time of the message

## Expected Result: 
Notifier should not over flow
## Actual Result: 
Notifier overflows hiding the main part(date and time) of the notification

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [x] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.35-5
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/18bb1819-758b-4789-8b38-21f8a4350c99

https://github.com/Expensify/App/assets/43996225/dff2f105-e8f4-4833-90ed-e01b5521f4d1

**Expensify/Expensify Issue URL:**
**Issue reported by:** @sofoniasN
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1688122181578499

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01f5d13d183f194814</li>
        <li>Upwork Job ID: 1675927092667117568</li>
        <li>Last Price Increase: 2023-07-03</li>
    </ul>
</details>

**Comment by sobitneupane** [comment]
@shawnborton Can you please confirm that your suggestion is to remove "Last Reply" part and only show `timestamp` as suggested by @dhairyasenjaliya in [his proposal](https://github.com/Expensify/App/issues/22039#issuecomment-1616413282).
Before:
<img width="327" alt="Screenshot 2023-07-05 at 15 50 50" src="https://github.com/Expensify/App/assets/25876548/24eca214-1c9c-433d-821c-369d924e1ba4">
After:
<img width="327" alt="Screenshot 2023-07-05 at 15 51 24" src="https://github.com/Expensify/App/assets/25876548/25f721ba-eb0d-46f5-b8bc-13e63c4b4bad">

**Comment by shawnborton** [comment]
Hmm I actually do like removing the "Last reply" part as it feels extraneous. And then if the row still runs too long, we just truncate the text via ellipsis.

**Comment by sobitneupane** [comment]
Proposal from @dhairyasenjaliya looks good to me.

🎀 👀 🎀 C+ reviewed

**Comment by johnmlee101** [comment]
I like it too, going with @dhairyasenjaliya's proposal

**Comment by johnmlee101** [comment]
@thienlnam this was resolved though, even though you marked as dupe, right?

**Comment by thienlnam** [comment]
We still need to send the contributors offers - I was testing again and have a fix for it on the way for future issues like this

**Comment by MitchExpensify** [comment]
Just to be sure, @sofoniasn is due reporting payment. @sobitneupane is due C+ payment. Is @dhairyasenjaliya also due payment here seeing as it was @thienlnam 's fix? Thanks

**Comment by thienlnam** [comment]
Oh I didn't fix anything related to this issue - I was referencing the automatic hiring

**Comment by MitchExpensify** [comment]
Ah thanks for confirming @thienlnam ! 

Everyone has been invited to this Upwork job posting https://www.upwork.com/jobs/~01f5d13d183f194814

**Comment by MitchExpensify** [comment]
Cool, adding a reminder to my calendar to pay on the 17th!

**Comment by MitchExpensify** [comment]
- Reporting bonus paid to @SofoniasN
- Contributor payment issued to @dhairyasenjaliya 
- C+ @sobitneupane can you accept the [Upwork offer please](https://www.upwork.com/nx/wm/offer/25462416)? Thanks! 

Do we need to add a new testing step here @sobitneupane ?

**Comment by MitchExpensify** [comment]
Thanks @dhairyasenjaliya - Corrected with a bonus payment. 

@sobitneupane waiting on you to accept the offer before we can close this out - Thanks!

**Comment by MitchExpensify** [comment]
Done!

**Comment by sobitneupane** [comment]
@MitchExpensify I will request payment via newDot.

**Comment by MitchExpensify** [comment]
Got it! Thanks @sobitneupane -Will close this once confirmation of payment comes through

**Comment by sobitneupane** [comment]
Payment Requested on newDot.

**Comment by JmillsExpensify** [comment]
@MitchExpensify Can you please summarize the appropriate individual payments for all parties involved in this issue? This is holding up @sobitneupane's NewDot payments. More information on this compliance process [in Slack](https://expensify.slack.com/archives/C01SKUP7QR0/p1690321157273869).

**Comment by MitchExpensify** [comment]
Of course @JmillsExpensify !  Here it is 

Issue reporter: @SofoniasN $250 (Paid) 
Contributor: @dhairyasenjaliya $1500 (Paid)
Contributor+: @sobitneupane $1500 (To be issued via NewDot)

**Comment by JmillsExpensify** [comment]
Reviewed details for @sobitneupane. These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

**Comment by MitchExpensify** [comment]
> These details are accurate based on summary from Business Reviewer and are now approved for payment in NewDot.

Just to be sure @JmillsExpensify, does this mean the payment has been issued in NewDot?

**Comment by JmillsExpensify** [comment]
Yeah you're good.

**Comment by MitchExpensify** [comment]
Awesome, thanks!

**Comment by MitchExpensify** [comment]
I see no automated final BZ steps. @sobitneupane adding these manually if you could take a look when you get a chance then we'll close this out:

- [ ] [@sobitneupane] The PR that introduced the bug has been identified. Link to the PR:
- [ ] [@sobitneupane] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
- [ ] [@abdulrahuman5196] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:
- [ ] [@sobitneupane] Determine if we should create a regression test for this bug.
- [ ] [@sobitneupane] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again.
- [ ] [@MitchExpensify] Link the GH issue for creating/updating the regression test once above steps have been agreed upon:

**Comment by sobitneupane** [comment]
@MitchExpensify Rather than a bug, it's an improvement on the app. So, checklist is not applicable here. I don't think even regression test is necessary.

**Comment by MitchExpensify** [comment]
Great! Thanks for confirming
