### ISSUE TITLE
[HOLD for payment 2023-09-20] [$500] MacOS: Context Menu does not translate to Spanish

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#25704]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Launch Expensify MacOS app
2. Set Profile > Preferences > Language > Spanish > Close
3. In Report Composer, right click

## Expected Result:
ContextMenu options are translated to Spanish like MenuItems in ToolBar

## Actual Result:
ContextMenu options are not translated to Spanish

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [x] MacOS / Desktop

**Version Number:** v1.3.55-7 

**Reproducible in staging?:** Y

**Reproducible in production?:** Y

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/8ae9ee5d-a043-4334-8fb5-5dd83438ca9d

https://github.com/Expensify/App/assets/115492554/a052bad7-c875-44ac-ba7a-b68e8f91b838

**Expensify/Expensify Issue URL:**

**Issue reported by:** @ygshbht

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1691379420264869

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01780b67747fbfff83</li>
        <li>Upwork Job ID: 1696262248411463680</li>
        <li>Last Price Increase: 2023-09-05</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Proposal from @ygshbht
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
The issue is that on the Expensify MacOS app, the `ContextMenu` options are not being translated to Spanish, even when the user has set the language preference to Spanish.
### What is the root cause of that problem?
The current setup for the `ContextMenu` in the application does not handle translations. Specifically, the labels for various options in the `ContextMenu` (like cut, paste, and copy) aren't being translated based on the user's language preference.
https://github.com/Expensify/App/blob/21146e534492fc21811b5bac0718e0f1e8ffbfd4/desktop/main.js#L42-L57
### What changes do you think we should make in order to solve the problem?
To address this issue, the `ContextMenu` function can be enhanced to support translations. Specifically, the labels for the default menu options can be provided directly using the labels option, like so:
```
labels: {
    cut: Localize.translate(preferredLocale, 'desktopApplicationMenu.cut'),
    paste: Localize.translate(preferredLocale, 'desktopApplicationMenu.paste'),
    copy: Localize.translate(preferredLocale, 'desktopApplicationMenu.copy'),
    /** Rest of the desired translations */
}
```
Additionally, for custom menu items that we're manually appending, the label can be set directly within the `MenuItem`:
```
append: (defaultActions, parameters, browserWindow) => [
        new MenuItem({
            // Only enable the menu item for Editable context which supports paste
            visible: parameters.isEditable && parameters.editFlags.canPaste,
            role: 'pasteAndMatchStyle',
            accelerator: DESKTOP_SHORTCUT_ACCELERATOR.PASTE_AND_MATCH_STYLE,
            label: Localize.translate(preferredLocale, 'desktopApplicationMenu.pasteAndMatchStyle'),
        }),
        new MenuItem({
            label: Localize.translate(preferredLocale, 'desktopApplicationMenu.pasteAsPlainText'),
            visible: parameters.isEditable && parameters.editFlags.canPaste && clipboard.readText().length > 0,
            accelerator: DESKTOP_SHORTCUT_ACCELERATOR.PASTE_AS_PLAIN_TEXT,
            click: () => pasteAsPlainText(browserWindow),
        }),
    ],
```
<sub> Please note this is the bulk of solution, minor modifications such as listening to language change events and recreating the menu also need to be done to ensure the app functions like in the video below </sub>

**Comment by ygshbht** [comment]
Thanks!

Solution video: 

https://github.com/Expensify/App/assets/65986357/990eba5f-370d-488e-b874-4b511879fa18

**Comment by michaelhaxhiu** [comment]
I had to brew on this one. I think it's a valid issue to fix, but it's small and non-urgent. For that reason I want to propose we dock the payments to be as follows for this one-off:

**Bug reporting bonus: $50
Contributor fix: $250
C+ proposal/PR review: $250**

I'm stating these now before I assign the `External` label so that folks know the prices before they invest too much time.

**Comment by ygshbht** [comment]
@michaelhaxhiu At the very least, I think the bug reporting price is fixed

**Comment by michaelhaxhiu** [comment]
@situchan when you are ready we have a proposal from @ygshbht ready for your review [above](https://github.com/Expensify/App/issues/25704#issuecomment-1688635139) 👀 .

**Comment by michaelhaxhiu** [comment]
bump @situchan

**Comment by michaelhaxhiu** [comment]
@ygshbht keep in mind there's no urgency bonus due to the merge freeze, but you can still get your PR ready to go

more context [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1693407966629239?thread_ts=1693347701.566439&cid=C01GTK53T8Q)

**Comment by Julesssss** [comment]
@michaelhaxhiu I'd say it should apply if the PR was ready to go and held by us

**Comment by michaelhaxhiu** [comment]
@Julesssss what do you mean? Are you saying the urgency bonus would still apply to this job/PR presently?

**Comment by neil-marcellini** [comment]
@michaelhaxhiu it's explained [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1693932008747439?thread_ts=1693347701.566439&cid=C01GTK53T8Q) that we do still have the urgency bonus during the freeze. I hope that helps 🙂

**Comment by neil-marcellini** [comment]
> @ygshbht thanks for demo video. [Proposal](https://github.com/Expensify/App/issues/25704#issuecomment-1688633271) looks good.
> 🎀 👀 🎀 C+ reviewed

I agree that the proposal looks good. Thanks! Although we have a merge freeze you can create the PR and we'll get it reviewed. We can merge it once the freeze is over.

**Comment by neil-marcellini** [comment]
@michaelhaxhiu why did you assign him already? Isn't that my job? Anyways all good. @ygshbht please put up a review soon!

**Comment by ygshbht** [comment]
@neil-marcellini Sure!

**Comment by michaelhaxhiu** [comment]
@neil-marcellini mybad, DM'ed you and the assigned job is on the `Engineer` (you in this case).

**Comment by ygshbht** [comment]
@situchan The [PR](https://github.com/Expensify/App/pull/26841) is ready for review! If you want to add more translations to the other lables that `electron-context-menu` provides (please see options argument and start reading from `showLearnSpelling` https://www.npmjs.com/package/electron-context-menu) please let me know

**Comment by situchan** [comment]
> @situchan The [PR](https://github.com/Expensify/App/pull/26841) is ready for review! If you want to add more translations to the other lables that `electron-context-menu` provides (please see options argument and start reading from `showLearnSpelling` https://www.npmjs.com/package/electron-context-menu) please let me know

I think they're out of scope. These are all app uses:

<img width="417" alt="Screenshot 2023-09-07 at 11 06 04 PM" src="https://github.com/Expensify/App/assets/108292595/717fbc0e-6c26-4180-bfaa-c2e0bb549109">

**Comment by ygshbht** [comment]
Ok

**Comment by neil-marcellini** [comment]
Bump for payment @michaelhaxhiu

**Comment by michaelhaxhiu** [comment]
Payment summary:

- Bug reporter: $250 @ygshbht
- Contributor: $500 @ygshbht 
- C+: @situchan $500 @situchan 

@situchan do you get paid via NewDot or Upwork?

**Comment by ygshbht** [comment]
Does this not get 50% bonus?

**Comment by michaelhaxhiu** [comment]
I am basing my price point on Vit's slack comment here:

https://expensify.slack.com/archives/C01GTK53T8Q/p1693407966629239?thread_ts=1693347701.566439&cid=C01GTK53T8Q
>Good question, i think to make this fair consider that if the PR is non-urgent ie non related to the above topics, you dont have to rush as it would most likely not be merged in the time for the urgency bonus. I believe if it’s urgent pr we make external the engineer/ bugzero person will clealy clarify that

This was assigned Sept 5, and merged sept 11 (delay likely due to feature freeze). But I get that there was some mixed guidance on this GH issue about bonuses and so this is totally fair to ask @ygshbht.

If you & situ or @neil-marcellini feel strongly, I am obviously open to offering the bonus. I just was trying to _fairly_ apply the rule in slack across the board. As you can imagine this gets hairy for a BZ to discern when we start making one-off exceptions from the rule of thumb.

**Comment by situchan** [comment]
@situchan do you get paid via NewDot or Upwork?

upwork

Example of bonus applied: https://github.com/Expensify/App/issues/25889#issuecomment-1728889333

**Comment by neil-marcellini** [comment]
I approved the proposal on September 6th, the PR was raised the same day, C+ approved on the 8th, I approved and merged on the 12th. So it was good to merge within 3 days, but I was slow to review. I think we should give the bonuses @michaelhaxhiu.

**Comment by michaelhaxhiu** [comment]
Bug reporter: $250 @ygshbht
Contributor: $750 @ygshbht (50% bonus)
C+: @situchan $750 @situchan (50% bonus)

**Comment by michaelhaxhiu** [comment]
All are paid. @situchan can you please complete the BZ checklist so that we can close this?

**Comment by situchan** [comment]
No regression. This is for desktop only, Spanish only, context menu only which is super rare care for the user. I think this is enough reason why we don't wanna add regression test step.

**Comment by michaelhaxhiu** [comment]
Cool, I agree that this was just a candid oversight. Closing!
