### ISSUE TITLE
[HOLD for payment 2023-10-09] [$500] Chat - Loader is shown on top of image even after image is loaded in attachment carousel

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#26046]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open a report
2. Send 3-4 images/pdf's
3. Scroll through carousel multiple times

## Expected Result:
The loader should not appear on top of the image if the image is already loaded

## Actual Result:
The loader appears on top of the image even if the image is already loaded

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.57-5

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/78819774/24da66b5-0f34-44ce-9dec-aa65cd031136

https://github.com/Expensify/App/assets/78819774/06168b45-fd23-4a75-8274-738311208f41

**Expensify/Expensify Issue URL:**

**Issue reported by:** @krishna2323

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692443921240289

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e48d51a0940adaac</li>
        <li>Upwork Job ID: 1699172582322225152</li>
        <li>Last Price Increase: 2023-09-12</li>
<li>Automatic offers: </li>
<ul>
<li>Krishna2323 | Contributor | 26743909</li>
<li>krishna2323 | Reporter | 26743910</li>
</ul></li>
    </ul>
</details>

**Comment by pradeepmdk** [comment]
### Proposal
### Please re-state the problem that we are trying to solve in this issue.
Chat - Loader is shown on top of image even after image is loaded in attachment carousel

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d09a1b66fd957f68a985cc25ebd372ac35e47de0/src/components/Attachments/AttachmentCarousel/Pager/AttachmentCarouselPage.js#L115C27-L115C27

forgot to add 
`onLoadEnd={() => setIsImageLoading(false)}
`
### What changes do you think we should make in order to solve the problem?

we need add this 
`onLoadEnd={() => setIsImageLoading(false)}`

**Comment by sakluger** [comment]
We're discussing moving the shortcuts modal to the RHN, so I'm going to close this issue.

**Comment by sakluger** [comment]
I'm sorry, I closed the wrong issue.

**Comment by sakluger** [comment]
I'm sure we've fixed this before. Here's one issue where we fixed an issue of the carousel loading every image multiple times: https://github.com/Expensify/App/issues/15922. @kidroca @thesahindia you worked on that issue so I'm hoping you're familiar - is this a regression of that one?

**Comment by sakluger** [comment]
Posted in the original Slack thread again.

**Comment by sakluger** [comment]
@thesahindia confirmed that we fixed this and it's a regression. Adding external label, I'd like to first see if we can track down the regression, because the person who caused it should ideally fix it.

**Comment by sakluger** [comment]
Reassigning the external label. @eVoloshchak could you please take a look at the proposals we've received so far? Thanks!

**Comment by sakluger** [comment]
@eVoloshchak could you please review these proposals? I can choose another C+ again if you're not available to review by tomorrow.

**Comment by eVoloshchak** [comment]
@pradeepmdk, I can still reproduce this using your [proposal](https://github.com/Expensify/App/issues/26046#issuecomment-1694928149)
The bug doesn't occur when you use arrow buttons for navigation, only when you're swiping between images manually

https://github.com/Expensify/App/assets/9059945/228c5970-e877-49d8-bd96-53619080393d

**Comment by eVoloshchak** [comment]
@Krishna2323, thank you for the [proposal](https://github.com/Expensify/App/issues/26046#issuecomment-1694961826)!

I wonder if there is a better way to resolve this, adding a delay (i.e. setTimeout) should be the last resort.

Actually, [this](https://github.com/Expensify/App/issues/23268#issuecomment-1653977404) this comment summed up this perfectly:
> Given that this is a special case where there is no standard way to detect the cache, thus delaying the loader is fine. The main purpose of the settimeout is to schedule a task for the future and this issue seems like a perfect match where we want to delay the loader for a short time which validates the use of settimeout

The same logic you're proposing has already been implemented for [ImageWithSizeCalculation](https://github.com/Expensify/App/pull/23781), is that correct? If so, could we add it to the `Image` component itself? I think having the same logic implemented in two places isn't ideal

**Comment by pradeepmdk** [comment]
@eVoloshchak Proposal updated https://github.com/Expensify/App/issues/26046#issuecomment-1694928149

**Comment by eVoloshchak** [comment]
@Krishna2323's [updated proposal](https://github.com/Expensify/App/issues/26046#issuecomment-1720917666) looks good to me
This isn't ideal, but there is no standard way to detect if the image is cached, so it's the next best thing. We'll also be shifting this logic from `ImageWithSizeCalculation` to a generic `Image`, so while not perfect, I think that's the approach we should take

🎀👀🎀 C+ reviewed!

**Comment by eVoloshchak** [comment]
- The PR that introduced the bug has been identified. Link to the PR: I'm unable to pinpoint the exact PR that caused this, the root cause for this was present in the initial implementation
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: N/A
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: I don't think an additional discussion is needed, the bug is specific to this particular component, there is no universal approach/checklist item we could implement

**Comment by eVoloshchak** [comment]
**Regression Test Proposal**

1. Open any chat
2. Send 3-4 images
3. Scroll through the carousel multiple times
4. Verify that the loader doesn't briefly appear on top of the image if the image is already loaded

**Do we agree 👍 or 👎**

**Comment by sakluger** [comment]
@Krishna2323 thanks for the reminder on the issue creation date. I updated the offers accordingly.

@eVoloshchak does not require payment (Eligible for Manual Requests)
@Krishna2323 requires payment [offer](https://www.upwork.com/nx/wm/offer/26743909) (Contributor)
@Krishna2323 requires payment [offer](https://www.upwork.com/nx/wm/offer/26743909) (Contributor)


**Summarizing payouts for this issue:**

Reporter: @Krishna2323 $250 (paid via Upwork)
Contributor: @Krishna2323 $1000 (paid via Upwork)
Contributor+: @eVoloshchak $1000 (payable via Manual Request)

Above payments include efficiency bonus 🎉 
Upwork job: https://www.upwork.com/jobs/~01e48d51a0940adaac

**Comment by sakluger** [comment]
@eVoloshchak let me know once you've sent the manual request, I'll close the issue at that point. Thanks!

**Comment by eVoloshchak** [comment]
@sakluger, request has been sent, thank you!

**Comment by JmillsExpensify** [comment]
$1,000 payment approved for @eVoloshchak based on BZ summary.
