### ISSUE TITLE
[HOLD for payment 2023-10-23] [$1000]  FAB menu not opening on new Registration

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#26076]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Platform A: Logout if logged in
2. Platform B: Register with new Email
3. Platform A: Open magic code link -> Click 'just sign in here'
## Expected Result: 
It should show FAB menu when Logging in for very first time
## Actual Result: 
Does not show FAB menu when logged in with magic code link on another device

## Workaround:
Can the user still use Expensify without this being fixed? Have you informed them of the workaround?

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:**
**Reproducible in staging?:** needs reproduction (applause team could not reproduce)
**Reproducible in production?:** needs reproduction
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/43996225/5278149d-c129-4338-81c4-f99fe88fb136

**Expensify/Expensify Issue URL:**
**Issue reported by:** @DinalJivani
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692186526922569

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019d7177db6deed95f</li>
        <li>Upwork Job ID: 1696513451401539584</li>
        <li>Last Price Increase: 2023-10-05</li>
    </ul>
</details>

**Comment by DinalJivani** [comment]
@garrettmknight 
Still able to reproduce! Checked on Desktop/Chrome, make sure you don't have any login on that device.
1. I tried to registering from Mobile app
2. Received mail on desktop -> All instance were logged out from desktop
3. I clicked on the link magic SignIn link from magic code email
4. It showed me Magic code and option **_'just sign in here'_** -> Click on **_'just sign in here'_**

Attaching full video again:

https://github.com/Expensify/App/assets/58871336/eae19662-bc1d-47d5-a5fa-446cf49880b5

**Comment by garrettmknight** [comment]
Still having trouble reproducing:
1. Signed out of both staging and prod in Chrome + signed out of the desktop app and closed it.
2. Signed up for a new account on the mobile app.
3. Clicked "Click here to sign into your Expensify account, like magic! 🪄" from the email on my desktop.
4. That opened a magic code page without the ",or just sign in here" option:

<img width="443" alt="Screenshot 2023-08-29 at 2 05 13 PM" src="https://github.com/Expensify/App/assets/1529980/5543e16d-0f93-4d53-95b2-9d59d0a680b4">

I had to clear my onyx local storage to reproduce, but I was able to.

**Comment by jjcoffee** [comment]
Should be fixed in [this PR](https://github.com/Expensify/App/pull/26293). cc @garrettmknight

**Comment by DinalJivani** [comment]
@garrettmknight @jjcoffee 
I just checked that, My Issue log time is earlier than [this](https://github.com/Expensify/App/issues/26288).

**Comment by garrettmknight** [comment]
Good call @jjcoffee, I'm going to close this as a dupe issue and suggest that @DinalJivani get the reporting payment.

**Comment by DinalJivani** [comment]
@garrettmknight 
Can you please reopen this bug, The linked bug and PR is merged but this issue is Still reproducible.
Check comments [from here](https://github.com/Expensify/App/issues/26288#issuecomment-1718659707)

**Comment by DinalJivani** [comment]
@garrettmknight  bump ^^

**Comment by garrettmknight** [comment]
Reopening to test tomorrow.

**Comment by garrettmknight** [comment]
Thanks for the bump @DinalJivani - i was able to repro this time. Opening up.

**Comment by ArekChr** [comment]
Is it possible to reproduce it in development? The "Click here to sign in to your Expensify account, like magic!" link always opens production but  after changing the URL from prod to localhost and opening it, instead of the magic code, I got this screen 

<img width="482" alt="image" src="https://github.com/Expensify/App/assets/24796318/38c6384a-ca5e-4274-ab87-f003087e1f40">

**Comment by garrettmknight** [comment]
Changing to external, we waited to open this report up for outside proposals until another potential root bug was fixed.

**Comment by garrettmknight** [comment]
<img width="439" alt="Screenshot 2023-09-25 at 6 31 24 PM" src="https://github.com/Expensify/App/assets/1529980/f749f6f1-121f-47ac-8ec7-465aa895352e">
I just tested this one again and I'm getting the above screen when I signup using a different browser/platform. @DinalJivani can you test and see if you're getting the same?

**Comment by DinalJivani** [comment]
@garrettmknight 
Still reproducible! Able to reproduce with same steps, Check full video below.

https://github.com/Expensify/App/assets/58871336/a0f806ed-e362-4bfa-906d-b1825a3bb1e8

Steps:
1. Logout of all instances, Staging and New
2. Register with new Email
3. Open magic code email -> Click _'Click here to sign into your Expensify account, like magic! 🪄'_  Link
4. On magic code page -> Click on _'just sign in here'_  Link

**Comment by garrettmknight** [comment]
Thanks for reproducing - @ArekChr following those steps, are you having any luck on prod?

**Comment by garrettmknight** [comment]
@ArekChr can you review this when you get a chance?

**Comment by ArekChr** [comment]
The proposal from @dukenv0307 looks good and seems quite straightforward. Could you share the outcomes resulting from this change? There are different behaviours between staging and dev, which I didn't have a chance to get to.

**Comment by ArekChr** [comment]
@tsa321 The proposal is about adding ValidateLogin to the white list screen, not to remove this check

**Comment by ArekChr** [comment]
@tsa321 You're right. The fab menu will show on the abracadabra page. Let's prevent making the same regression again. thanks for the details. Your [proposal](https://github.com/Expensify/App/issues/26076#issuecomment-1739495776) looks good to me.

:ribbon: :eyes: :ribbon: C+ reviewed

**Comment by garrettmknight** [comment]
**Summary of payments:**
- Urgency Bonus: Yes
- Reporter: @DinalJivani $250 awaiting payment: https://www.upwork.com/en-gb/nx/wm/offer/27336930
- Contributor: @tsa321 $1500 awaiting payment: https://www.upwork.com/en-gb/nx/wm/offer/27336930
- Reviewer: N/A

**Comment by DinalJivani** [comment]
@garrettmknight 
Offer accepted! Thanks

**Comment by garrettmknight** [comment]
All paid up
