### ISSUE TITLE
[$500] [HOLD for payment 2023-09-07] [HOLD for payment 2023-09-07] 'FAB' popover menu is not opened when user Sign-up

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#26288]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Navigate to sign-up page
2. Enter email & click on continue
3. Enter magic code

## Expected Result:
'FAB' popover menu should be opened on sign-up

## Actual Result:
'FAB' popover menu is not opened on sign-up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** v1.3.59-0

**Reproducible in staging?:** Y

**Reproducible in production?:** N

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/115492554/224660e6-bb48-4952-bab3-b93761c8220a

https://github.com/Expensify/App/assets/115492554/352b5645-ddfd-415f-a784-6b89bc97e3ff

**Expensify/Expensify Issue URL:**

**Issue reported by:** @Natnael-guchima

**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1693369621472089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015934b071bb2db892</li>
        <li>Upwork Job ID: 1702307379358162944</li>
        <li>Last Price Increase: 2023-09-14</li>
    </ul>
</details>

**Comment by kbecciv** [comment]
This is similar KI https://github.com/Expensify/App/issues/26076

**Comment by amyevans** [comment]
Thanks @grgia!

**Comment by luacmartins** [comment]
Seems like we merged and CPed a fix. Removing the blocker label.

**Comment by DinalJivani** [comment]
@grgia @amyevans @laurenreidexpensify 
Dupe of [this issue](https://github.com/Expensify/App/issues/26076)

**Comment by Natnael-Guchima** [comment]
This one was only reproducible on staging and the issue you linked was reproducible on prod and was reported on Aug 16 that is before the offending PR was merged to main.

**Comment by DinalJivani** [comment]
I have reported this bug earlier like 15 days ago. So I think I'll be eligible for reporting bonus.
CC: @laurenreidexpensify @garrettmknight

**Comment by jjcoffee** [comment]
Just flagging for eventual compensation that I reviewed [the PR](https://github.com/Expensify/App/pull/26293) for this. cc @laurenreidexpensify

**Comment by situchan** [comment]
> Just flagging for eventual compensation that I reviewed [the PR](https://github.com/Expensify/App/pull/26293) for this. cc @laurenreidexpensify

I see that your reviewed [PR](https://github.com/Expensify/App/pull/26293) which fixes the regression came from original [PR](https://github.com/Expensify/App/pull/26182) you reviewed.
In that case, double compensation is eligible?

**Comment by jjcoffee** [comment]
@situchan The regression comes from [code added](https://github.com/Expensify/App/pull/26182/commits/c0e1409a7c65e2ec8319ad636078de6e44c1cca4) _after_ I [approved](https://github.com/Expensify/App/pull/26182#pullrequestreview-1600793519) that PR, so I thought it would be treated more like a standard deploy blocker PR review. I did jump in and take over the PR review from the initial C+ who was assigned (and seemed unavailable), prioritising the review over other work, so I'd think at least some compensation would be due. 

That being said, I'm a new C+ and this sort of stuff doesn't really seem to be documented anywhere so honestly unsure how it works in this case! :smile:

**Comment by situchan** [comment]
@jjcoffee can you please continue discussion on [this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1680778526596219) for reference in the future so that other C+s know how much to get paid in such cases?

**Comment by garrettmknight** [comment]
Looks like this bug report is actually a dupe of https://github.com/Expensify/App/issues/26076. I'll close the other one, but I think @DinalJivani should get the reporter payment.

**Comment by jjcoffee** [comment]
@laurenreidexpensify Gentle bump for payment on this one!

**Comment by laurenreidexpensify** [comment]
@grgia @amyevans I'm not familiar with the back and forth here on the regressions etc - can you help me unpick this so we can get it closed? Thanks

**Comment by DinalJivani** [comment]
@laurenreidexpensify 
Gentle bump for payment 
& 
_"Issue reported by:"_   should be updated by my name. Thanks
cc: @garrettmknight

**Comment by amyevans** [comment]
@laurenreidexpensify It was a regression from https://github.com/Expensify/App/pull/26182

https://github.com/Expensify/App/issues/26076 was reported in Slack August 16. https://github.com/Expensify/App/pull/26182 wasn't merged until August 29 so I don't really see how #26076 would have reported the bug before it was introduced 😄 That bug report looks specific to a cross-platform flow.

So to me it looks like:
* @Natnael-Guchima is due $250 for reporting
* @jjcoffee is due $1000 for PR review

But I'd like @grgia to weigh in first because she has more context than I do

**Comment by grgia** [comment]
@laurenreidexpensify I fixed the regression in this PR https://github.com/Expensify/App/pull/26293 after being alerted on slack by @jjcoffee. I agree it's just whichever bug report came first in this case

**Comment by Natnael-Guchima** [comment]
They are different bug reports. https://github.com/Expensify/App/issues/26076 is a cross-platform test with different test steps. By the time https://github.com/Expensify/App/issues/26076 was reported the regression fixed here wasn't introduced as @amyevans  mentioned [here](https://github.com/Expensify/App/issues/26288#issuecomment-1717857237).

**Comment by Natnael-Guchima** [comment]
@DinalJivani can you please retest your report again with the exact test steps, and share a video so that we might see if the issue you reported is still reproducible or not?

**Comment by DinalJivani** [comment]
@grgia @amyevans @garrettmknight 
Sorry to tag y'all 😅

Steps are simple:
1. Logout of all instances, Staging and New 
2. Register with new Email
3. Open magic code link from email -> Click on _**'just sign in here'**_ link

@Natnael-Guchima The bug reports or steps might be same but the resolution to it might be the same for both issue.

https://github.com/Expensify/App/assets/58871336/7e2a5ee8-9cd1-4aa1-825b-bc26d0206201

**Comment by Natnael-Guchima** [comment]
@DinalJivani correct me if I am wrong. From the video, it seems that the issue you have reported still exists, right?

**Comment by DinalJivani** [comment]
@Natnael-Guchima Yes I am still able to reproduce this issue. 
May be, That's why I could find that bug even before it occurred from regression

**Comment by Natnael-Guchima** [comment]
Hmmm, if it is still reproducible I think the fix doesn't address the issue you have reported. IMO, both issues seems to be different because one of the bug is fixed and the other is not by the fixing PR.

**Comment by DinalJivani** [comment]
Yes my issue was closed based on [comment](https://github.com/Expensify/App/issues/26076#issuecomment-1699274164) by @jjcoffee that it will be fixed in [this PR](https://github.com/Expensify/App/pull/26293)
@Natnael-Guchima  let's wait for them to decide on this now!

**Comment by jjcoffee** [comment]
@laurenreidexpensify Thanks, offer accepted!

**Comment by Natnael-Guchima** [comment]
Accepted the offer. Thanks @laurenreidexpensify

**Comment by situchan** [comment]
> @jjcoffee can you please continue discussion on [this thread](https://expensify.slack.com/archives/C02NK2DQWUX/p1680778526596219) for reference in the future so that other C+s know how much to get paid in such cases?

@jjcoffee bump ^

**Comment by laurenreidexpensify** [comment]
Payments issued, closing
