### ISSUE TITLE
[$500] Web - Workspace request money message displays wrong currency before conversion

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#26309]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
1. Open the app
2. Open settings and click on new workspace
3. In new workspace, if current currency is not 'USD' the change  to USD and if 'USD', change to any other currency.
4. In LHN, workspace chat will be created, open it
5. Click on plus and click Request money
6. In request money, select currency different then workspace currency eg: In video, INR is selected in request money and workspace currency is USD
7. Complete the request with any amount
8. Observe the IOU message displays the workspace currency even before conversion to it eg: In video, it displays $900 instead of ₹900 and few moments later, it converts to $10.9

## Expected Result:
Before conversion to workspace currency, app should display request money selected currency symbol in request money message

## Actual Result:
Before conversion to workspace currency, app still displays workspace selected currency symbol in request money message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.59.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/8ce7b6da-f681-450d-81fb-e615fbc9b982

https://github.com/Expensify/App/assets/93399543/2ff52168-af31-402f-acc3-ddf2a5384427

**Expensify/Expensify Issue URL:**
**Issue reported by:** @dhanashree-sawant
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1692866442917089

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010daaf0b73a652083</li>
        <li>Upwork Job ID: 1702053307519152128</li>
        <li>Last Price Increase: 2023-09-13</li>
<li>Automatic offers: </li>
<ul>
<li>DylanDylann | Contributor | 26746667</li>
<li>dhanashree-sawant | Reporter | 26746668</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @dylanexpensify</details>

**Comment by dylanexpensify** [comment]
Reviewing today!

**Comment by dylanexpensify** [comment]
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr

**Comment by dylanexpensify** [comment]
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr

**Comment by dylanexpensify** [comment]
Reviewing today while in the air! Currently taxi'd, will get to once I can hop on wifi! Sorry I didn't get to this last week, had head down on wave4 saastr

**Comment by dylanexpensify** [comment]
Coming back from conference last week - updating today!

**Comment by dylanexpensify** [comment]
confirmed

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Workspace request money message displays wrong currency before conversion

### What is the root cause of that problem?
https://github.com/Expensify/App/blob/d68263ad664d8a8a81ca859147696df8abfcd480/src/pages/iou/steps/NewRequestAmountPage.js#L70
If there is no currency in the param we will use currency from iou
### What changes do you think we should make in order to solve the problem?
I suggest that we can get policyID from params and get currency of that policy. We only use iou.currency if the currency from policy is falsy
```
const currency = currentCurrency || policy.currency || iou.currency; 
``` 


### What alternative solutions did you explore? (Optional)

**Comment by robertKozik** [comment]
Hi @DylanDylann!
Your solution looks well designed and addresses the issue entirely, as it's the only one here let's see it in action 🚀 

🎀 👀 🎀 C+ reviewed

**Comment by dylanexpensify** [comment]
Nice! Let's get that PR raised and merged for that sweet bonus!

**Comment by DylanDylann** [comment]
@robertKozik I see the problem still happens if we change currency when requesting money. Let's see this case, 
- Normal case: In the first request money, I request 23000Đ, in the second time I request 23000Đ and then the IOU message will display 46000Đ. 
- exception case: Turn offline. In the first request money, I request 23000Đ, in the second time I request 1$. what should we do display in the IOU message ? Note that we can't convert currency from FE and we are offline

**Comment by danieldoglas** [comment]
@dylanexpensify can you confirm the expected use case on @DylanDylann 's question above from the product perspective?

**Comment by DylanDylann** [comment]
@dylanexpensify Could you help to check above comment?

**Comment by DylanDylann** [comment]
I posted this question to [Slack](https://expensify.slack.com/archives/C01GTK53T8Q/p1695788106305139) to get more eyes. 
cc @dylanexpensify

**Comment by robertKozik** [comment]
@DylanDylann @dylanexpensify I'm not sure how this should look from the product perspective, but maybe we could stick with the current behaviour (even when requests are in different currencies, values are added together as it would be one currency)? Attaching video from the staging env

https://github.com/Expensify/App/assets/61146594/1d48b26e-3706-4a60-81a4-c62d12b5940c

**Comment by DylanDylann** [comment]
Yeah, it is currently behavior. But it maybe make some confusions when we display incorrect amount

**Comment by dylanexpensify** [comment]
I'd agree we stick with current behavior - but I'm just checking internally to confirm that flow!

**Comment by DylanDylann** [comment]
@dylanexpensify Gentle bump, Any update here?

**Comment by DylanDylann** [comment]
@dylanexpensify @robertKozik Any update here?
If we agree with the current behavior, we don't need to do anything in this issue

**Comment by robertKozik** [comment]
I think we agree to keep the current behaviour for the offline requests ([your exception case](https://github.com/Expensify/App/issues/26309#issuecomment-1726817878) described before). How is it interfere with the main problem of this issue?

**Comment by DylanDylann** [comment]
@robertKozik @danieldoglas 
Let's see the current logic:  
- Case 1: I request $2 in workspace chat, In optimistic data we will convert currency to the default currency of workspace (in this case is đ) then we display đ2. Then the Server returns the correct amount with this currency is đ48609 and the App displays it correctly. The optimistic data are causing flickers 
- Case 2:  In workspace chat, the first request money I request 23000Đ, in the second time I request 1$. In optimistic data we use currency to the default currency of workspace (in this case is đ) and then we display total amount đ23001 (23000 + 1). Then the Server returns the correct amount with this currency is đ48609 and the App displays it correctly. The optimistic data are causing flickers 

Should we consider removing the amount of optimistic data to avoid flicker

**Comment by robertKozik** [comment]
I thought that this issue was about the currency symbol flickering and this should be resolved. I think we cannot interfere into the amount, as changing the currency is done on backend.

Don't removing the amount from the optimistic data cause strange UX (request with no amount) when it will be first money request? (being offline scenario)

**Comment by dylanexpensify** [comment]
Sorry, we agreed we always show the report in the output currency of the workspace. @danieldoglas thoughts on keeping this open?

**Comment by danieldoglas** [comment]
@dylanexpensify I think we still need to fix the flick that is happening right? 

based on the original report:

```
Observe the IOU message displays the workspace currency even before conversion to it eg: In video, it displays $900 instead of ₹900 and few moments later, it converts to $10.9
```

So even if we're converting on the backend, we should show `₹900` and not `$900` when we just create it.

**Comment by DylanDylann** [comment]
@danieldoglas I agree with you in [this comment](https://github.com/Expensify/App/issues/26309#issuecomment-1745925400). But we have another flicker:
In workspace chat, the first request money I request 23000Đ, in the second time I request 1$. In optimistic data we use currency to the default currency of workspace (in this case is đ) and then we display total amount đ23001 (23000 + 1). Then the Server returns the correct amount with this currency is đ48609 and the App displays it correctly. The optimistic data are causing flickers

https://github.com/Expensify/App/assets/141406735/ec76eef9-bc47-4a12-a4dd-64a280c2083e


What is expected for this case? (Note that we can't convert amount currency from FE)

**Comment by DylanDylann** [comment]
Summary, we have 2 cases that make flickers as mentioned [here](https://github.com/Expensify/App/issues/26309#issuecomment-1742647241). We can fix the flicker in case 1 as @danieldoglas mentioned [here](https://github.com/Expensify/App/issues/26309#issuecomment-1745925400) but flicker in case 2 still happen. As I undestand, We have 2 options:
1. Do nothing
2. Remove optimistic data and only update amount of request from BE (don't update amount if user request money offline)

**Comment by robertKozik** [comment]
I believe we shouldn't remove the optimistic data in this scenario since the request won't update any visuals while the user is offline. 

We should focus on fixing the currency symbol flicker, and leave the amount flicker as it is, since there's no way to predict it for the optimistic data. Alternatively we can close this issue, as flicker on this is unavoidable as exchanging the currency needs the BE

**Comment by danieldoglas** [comment]
I agree with doing nothing on the second case.

**Comment by DylanDylann** [comment]
@danieldoglas You mean that we should fix case 1, right? Just a note, case 1 is only an edge case of case 2. If we agree with the behavior of case 2, we should do nothing here (also accept case 1). Only fixing case 1 will make the code complicated and I don't see that It helps to improve UX because users still see a flicker if request money for the second time.
cc @robertKozik

**Comment by danieldoglas** [comment]
I see, thanks for that @DylanDylann . @dylanexpensify So I think you agree we should do nothing in this case too, right?

I'll be OOO next week, but if you (@dylanexpensify) agree, let's :do-nothing: here.

**Comment by DylanDylann** [comment]
@dylanexpensify Are we eligible for compensation for our effort? Contributors are already assigned and started on the PR. It's just due to the expectation changes and the solution becomes outdated.

**Comment by dylanexpensify** [comment]
@danieldoglas mind confirming here? ^ If we agree, happy to do so!

**Comment by danieldoglas** [comment]
@dylanexpensify Yeah, I think compensation is due in this case.

**Comment by dylanexpensify** [comment]
Do we feel fine with $250 @danieldoglas @DylanDylann

**Comment by danieldoglas** [comment]
That works for me.

**Comment by DylanDylann** [comment]
I think the payment should be 100% like some other similar cases below:
https://github.com/Expensify/App/issues/26470#issuecomment-1750485083
https://github.com/Expensify/App/issues/26309#issuecomment-1759950890
https://github.com/Expensify/App/issues/21419#issuecomment-1629018328
https://github.com/Expensify/App/issues/22806#issuecomment-1767395619

Anyway, Happy with your decision.

**Comment by DylanDylann** [comment]
bump @danieldoglas @dylanexpensify

**Comment by danieldoglas** [comment]
Reopening the issue so we don't lose track of it

**Comment by DylanDylann** [comment]
@danieldoglas @dylanexpensify Could you help to check [this comment](https://github.com/Expensify/App/issues/26309#issuecomment-1782646822)

**Comment by danieldoglas** [comment]
bump @dylanexpensify

**Comment by dylanexpensify** [comment]
Apologies! Looking now

**Comment by dylanexpensify** [comment]
ah, confirming we paid $250, and the request is for an amount of $500? Is that right @DylanDylann ?

**Comment by DylanDylann** [comment]
@dylanexpensify yeah. But happy with your final decision

**Comment by dylanexpensify** [comment]
Sounds good - thanks for understanding!

**Comment by DylanDylann** [comment]
@dylanexpensify I haven't received any payment for this issue 😄 Could you help to check again? This is [my opinion](https://github.com/Expensify/App/issues/26309#issuecomment-1782646822)
cc @danieldoglas

**Comment by dylanexpensify** [comment]
Oh apologies! Jeez - blonde time. Payment of $250 sent, as discussed above!
