### ISSUE TITLE
[DISTANCE] [$1000] LOW: mWeb / Safari- i icon and mapbox logo not displayed

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#27800]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/27491
## Action Performed:
1. Launch the app on mWeb safari
2. Open the global create menu and select Request money
3. Select the Distance tab if it is not already active

## Expected Result:
Toggle attribution (i) icon at the bottom-right of the map and Mapbox logo at the bottom-left of the map displayed to select

## Actual Result:
Icon and mapbox icon not displayed. (No issue in chrome mWeb)

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [x] iOS / Safari
- [ ] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.71-7

**Reproducible in staging?:** Yes

**Reproducible in production?:** Yes

**If this was caught during regression testing, add the test name, ID and link from TestRail:**

**Email or phone of affected tester (no customers):**

**Logs:** https://stackoverflow.com/c/expensify/questions/4856

**Notes/Photos/Videos:** Any additional supporting documentation

![Bug6206495_IMG_7377](https://github.com/Expensify/App/assets/78819774/cbe6d42b-f3a2-4b4e-b208-dce43682e9e1)

**Expensify/Expensify Issue URL:**

**Issue reported by:** Applause - Internal Team

**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015fbbf81efc9a06b4</li>
        <li>Upwork Job ID: 1706697994798551040</li>
        <li>Last Price Increase: 2023-10-19</li>
<li>Automatic offers: </li>
<ul>
<li>abdulrahuman5196 | Reviewer | 27464745</li>
<li>aswin-s | Contributor | 27464746</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by johncschuster** [comment]
@lanitochka17 for those of us less familiar with this new feature, can you please provide a video example of the incorrect behavior, as well as a video example of the correct behavior? I'd like to see the difference between what you spotted on Safari vs Chrome.

Thanks!

**Comment by m-natarajan** [comment]
@johncschuster  I am attaching the video for reference.


https://github.com/Expensify/App/assets/38435837/507fc7c7-e9e8-4ede-a5e7-1cbc0b42ad53

**Comment by akinwale** [comment]
This seems to be caused by the Smart App banner pushing down the elements, which can only be seen on the staging or production URLs. Still trying to figure out why.

There's an open [PR](https://github.com/Expensify/App/pull/27574) that fixes a bug that occurs when the map container resizes. I am not sure if that would fix this, but it may be worth a shot to check it out.

**Comment by akinwale** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
On mWeb Safari, the mapbox logo and the toggle attribution (i) icon are not visible after the Smart App Banner is displayed.

### What is the root cause of that problem?
After the Distance Request screen loads, the Smart App Banner being automatically displayed triggers a re-render of the map canvas, which causes the map to be rendered over the Mapbox logo and toggle attribution icon, resulting in the controls being hidden. Since it is mandatory to display the Mapbox logo and text attribution when using Mapbox maps, this needs to be fixed.

### What changes do you think we should make in order to solve the problem?
Add the following style to [web/index.html](https://github.com/Expensify/App/blob/main/web/index.html) to ensure that the canvas is always rendered below the Mapbox logo and the attribution icon.
```
.mapboxgl-canvas {
    z-index: -1;
}
```

### What alternative solutions did you explore? (Optional)
None.

**Comment by akinwale** [comment]
After doing some more digging, it turns out that when the Smart App Banner is displayed, this somehow messes up the z-indexes of the map and its controls, since it triggers a re-render of the map canvas, and the map ends up being rendered over the Mapbox logo and the toggle attribution icon, resulting in the controls being hidden.

Setting a `z-index` of `-1` for the `.mapboxgl-canvas` CSS class seems to solve the rendering problem. However, this prevents the map from being interacted with (panning / zooming operations stop working).

**Comment by johncschuster** [comment]
Thanks for posting that video, @m-natarajan! That was very helpful!

**Comment by johncschuster** [comment]
@abdulrahuman5196 just a heads up, @akinwale has already shared what they believe is the cause in [this comment](https://github.com/Expensify/App/issues/27800#issuecomment-1727588133).

**Comment by kameshwarnayak** [comment]
Unable to reproduce in the current main.


![simulator_screenshot_1F037C7D-9F48-4D75-A0B9-DFCDA22098B1](https://github.com/Expensify/App/assets/2232432/02537455-a6f8-4d17-a265-531907f9826a)

**Comment by johncschuster** [comment]
@lanitochka17 are you able to reproduce this on main?

**Comment by lanitochka17** [comment]
Issue is reproducible on Build 1.3.75-3

![IMG_7523](https://github.com/Expensify/App/assets/78819774/1cb9c300-2014-4248-97e2-eada9b672ac2)

**Comment by abdulrahuman5196** [comment]
@johncschuster Not sure of the issue status here. Do let me know when this issue comes into proposal review phase. Would be happy to help review on proposals.

**Comment by kameshwarnayak** [comment]
@lanitochka17 Can you check on main. Cant reproduce. It might have been already fixed.

**Comment by johncschuster** [comment]
@lanitochka17 bump! Can you check on main to see if this is still reproducible?

**Comment by lanitochka17** [comment]
@johncschuster 
Hello, issue is reproducible on Build 1.3.77-5


https://github.com/Expensify/App/assets/78819774/5751aad1-a4f8-412e-a988-8525d0f21f83

**Comment by abdulrahuman5196** [comment]
I think this issue is still waiting on @johncschuster Traige.
Do let me know if anything is required from my end  - https://github.com/Expensify/App/issues/27800#issuecomment-1742024216

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by neil-marcellini** [comment]
That's not what I see. The issue is still reproducible. We should see the mapbox logo and info icon on the map here.
<img src=https://github.com/Expensify/App/assets/26260477/0398c0a0-d461-4fe7-a0cd-780ff83a894e  width=300px>

**Comment by neil-marcellini** [comment]
@mvtglobally please check your test steps.

**Comment by b4s36t4** [comment]
Is this only happening on physical devices? I tried on simulator not able to repro.

**Comment by neil-marcellini** [comment]
Interesting, I guess so.

**Comment by johncschuster** [comment]
@abdulrahuman5196 

> I think this issue is still waiting on @johncschuster Traige.
> Do let me know if anything is required from my end - https://github.com/Expensify/App/issues/27800#issuecomment-1742024216

Thanks for checking! This issue has already been triaged. We're just waiting on proposals.

**Comment by abdulrahuman5196** [comment]
@johncschuster There hasn't been any proposals yet. Can we re-test the issue and raise the bounty?

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by johncschuster** [comment]
@neil-marcellini has already reproduced it, [here](https://github.com/Expensify/App/issues/27800#issuecomment-1760143330)

**Comment by abdulrahuman5196** [comment]
Yup. I was also able to reproduce this issue. I don't think this is fixed. We are still waiting on proposals.

**Comment by aswin-s-kumar** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
MapBox attribution controls are not visible on iOS Safari

### What is the root cause of that problem?

The problem arises due to the SmartApp banner in PROD, which pushes content down and reduces the screen height. This forces the scroll view to render distance request components within a scrollable container, leading to the Canvas element (responsible for rendering the map view) being painted above the attribution controls, thereby hiding them. This issue is caused by a Webkit bug that affects the stacking order of the canvas element when it's rendered inside a scrolling parent container.

This issue occurs only in PROD and on small-screen devices like the iPhone SE. However, it can be replicated on DEV and simulators by adding an additional view of 50px in height above the screen contents. It's important to note that this problem is specific to Mac/iOS Safari, which uses the Webkit rendering engine. Chrome on desktop and Android uses the Blynk rendering engine and does not experience this issue.

https://github.com/Expensify/App/assets/145648771/07d98f63-1004-4d36-a706-d68dcda3f6f1


Let me explain this behaviour further.

Here's how the components are organised in the React component tree. Less important components have been omitted.

```tsx
MoneyRequestSelectorPage
├── HeaderWithBackButton
└── OnyxTabNavigator
    └── NewDistanceRequestPage
        └── DistanceRequest
            └── DraggableList (ScrollView)
                ├── DistanceRequestRenderItem
                └── DistanceRequestFooter
                    └── DistanceMapView
                        └── MapView (Uses MapBoxGL component)

```

The entire Distance Request controls are rendered within a ScrollView component to ensure accessibility on small-screen devices. The map is rendered using the mapbox-gl library, and this is how it gets rendered in the DOM:

```tsx
scroll-view (Parent scrollable div element with overflow-y auto)       
└── mapbox-map
    ├── mapboxgl-canvas-container
    │   └── mapboxgl-canvas (canvas element, relatively positioned)
    └── mapboxgl-control-container (attribution controls)
        ├── mapboxgl-ctrl-top-left
        ├── mapboxgl-ctrl-top-right
        ├── mapboxgl-ctrl-bottom-left (logo, absolutely positioned)
        └── mapboxgl-ctrl-bottom-right (info icon, absolutely positioned)
```

Based on the DOM structure above, the absolutely positioned attribution controls should be rendered above the canvas element. However, when the screen height is insufficient, the parent container with overflow-y:auto becomes a scrollable container. This triggers a rendering bug in Webkit browsers that causes the relatively positioned canvas element to be painted over the absolutely positioned controls. This can be verified in PROD by reducing the min-height of mapViewContainer from 300px to 250px. This reverts the scroll container back to normal, and the controls become visible again.


https://github.com/Expensify/App/assets/145648771/e224a1e3-99eb-4fae-b6cd-c54c6909e373



### What changes do you think we should make in order to solve the problem?

As the issue is related to nodes directly under the MapBox container, we cannot apply styles to the component nodes or change the stacking order. There are no props for the Map component that allow us to inject custom CSS. To target the nodes, we need to explicitly reference them by their class name and apply a CSS fix to the Web platform.

To address the stacking order bug related to absolutely positioned elements within a scrolling parent, we can resolve it by compelling the browser to paint the layer separately using a CSS transform. The transform style prompts the browser to repaint the controls above the canvas element.

1. Add a css file with the transform style applied to attribution controls

```css
/* attribution-fix.css */
.mapboxgl-ctrl-bottom-left {
  -webkit-transform: translate3d(0, 0, 1px);
  transform: translate3d(0, 0, 1px);
}

.mapboxgl-ctrl-bottom-right {
  -webkit-transform: translate3d(0, 0, 1px);
  transform: translate3d(0, 0, 1px);
}
```
2. Import the css in MapView.web.tsx

https://github.com/Expensify/App/blob/3656ae16d2105920659c9105cb865ebe9d52a04d/src/components/MapView/MapView.web.tsx#L20

```tsx
import Direction from './Direction';
import {MapViewHandle, MapViewProps} from './MapViewTypes';

import 'mapbox-gl/dist/mapbox-gl.css';

// Add this line
import './attribution-fix.css';

```

Here is how it looks after the fix


https://github.com/Expensify/App/assets/145648771/ca77510a-33fc-4e55-bccb-521d6cdee20a



### What alternative solutions did you explore? (Optional)
None

**Comment by aswin-s-kumar** [comment]
Contributor details
Your Expensify account email: aswin@videntia.in
Upwork Profile Link: https://www.upwork.com/agencies/1709816849611558912

**Comment by aswin-s-kumar** [comment]
Contributor details
Your Expensify account email: aswin@videntia.in
Upwork Profile Link: https://www.upwork.com/freelancers/~010b194c3e145d5456

**Comment by aswin-s** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
MapBox attribution controls are not visible on iOS Safari

### What is the root cause of that problem?

The problem arises due to the SmartApp banner in PROD, which pushes content down and reduces the screen height. This forces the scroll view to render distance request components within a scrollable container, leading to the Canvas element (responsible for rendering the map view) being painted above the attribution controls, thereby hiding them. This issue is caused by a Webkit bug that affects the stacking order of the canvas element when it's rendered inside a scrolling parent container.

This issue occurs only in PROD and on small-screen devices like the iPhone SE. However, it can be replicated on DEV and simulators by adding an additional view of 50px in height above the screen contents. It's important to note that this problem is specific to Mac/iOS Safari, which uses the Webkit rendering engine. Chrome on desktop and Android uses the Blynk rendering engine and does not experience this issue.

https://github.com/Expensify/App/assets/145648771/07d98f63-1004-4d36-a706-d68dcda3f6f1


Let me explain this behaviour further.

Here's how the components are organised in the React component tree. Less important components have been omitted.

```tsx
MoneyRequestSelectorPage
├── HeaderWithBackButton
└── OnyxTabNavigator
    └── NewDistanceRequestPage
        └── DistanceRequest
            └── DraggableList (ScrollView)
                ├── DistanceRequestRenderItem
                └── DistanceRequestFooter
                    └── DistanceMapView
                        └── MapView (Uses MapBoxGL component)

```

The entire Distance Request controls are rendered within a ScrollView component to ensure accessibility on small-screen devices. The map is rendered using the mapbox-gl library, and this is how it gets rendered in the DOM:

```tsx
scroll-view (Parent scrollable div element with overflow-y auto)       
└── mapbox-map
    ├── mapboxgl-canvas-container
    │   └── mapboxgl-canvas (canvas element, relatively positioned)
    └── mapboxgl-control-container (attribution controls)
        ├── mapboxgl-ctrl-top-left
        ├── mapboxgl-ctrl-top-right
        ├── mapboxgl-ctrl-bottom-left (logo, absolutely positioned)
        └── mapboxgl-ctrl-bottom-right (info icon, absolutely positioned)
```

Based on the DOM structure above, the absolutely positioned attribution controls should be rendered above the canvas element. However, when the screen height is insufficient, the parent container with overflow-y:auto becomes a scrollable container. This triggers a rendering bug in Webkit browsers that causes the relatively positioned canvas element to be painted over the absolutely positioned controls. This can be verified in PROD by reducing the min-height of mapViewContainer from 300px to 250px. This reverts the scroll container back to normal, and the controls become visible again.


https://github.com/Expensify/App/assets/145648771/e224a1e3-99eb-4fae-b6cd-c54c6909e373



### What changes do you think we should make in order to solve the problem?

As the issue is related to nodes directly under the MapBox container, we cannot apply styles to the component nodes or change the stacking order. There are no props for the Map component that allow us to inject custom CSS. To target the nodes, we need to explicitly reference them by their class name and apply a CSS fix to the Web platform.

To address the stacking order bug related to absolutely positioned elements within a scrolling parent, we can resolve it by compelling the browser to paint the layer separately using a CSS transform. The transform style prompts the browser to repaint the controls above the canvas element.

1. Add a css file with the transform style applied to attribution controls

```css
/* attribution-fix.css */
.mapboxgl-ctrl-bottom-left {
  -webkit-transform: translate3d(0, 0, 1px);
  transform: translate3d(0, 0, 1px);
}

.mapboxgl-ctrl-bottom-right {
  -webkit-transform: translate3d(0, 0, 1px);
  transform: translate3d(0, 0, 1px);
}
```
2. Import the css in MapView.web.tsx

https://github.com/Expensify/App/blob/3656ae16d2105920659c9105cb865ebe9d52a04d/src/components/MapView/MapView.web.tsx#L20

```tsx
import Direction from './Direction';
import {MapViewHandle, MapViewProps} from './MapViewTypes';

import 'mapbox-gl/dist/mapbox-gl.css';

// Add this line
import './attribution-fix.css';

```

Here is how it looks after the fix


https://github.com/Expensify/App/assets/145648771/ca77510a-33fc-4e55-bccb-521d6cdee20a



### What alternative solutions did you explore? (Optional)
None

**Comment by aswin-s-kumar** [comment]
Sorry guys with the mixup above with my contributor account. I was trying to use an agency upwork profile link. Was not sure how it works. Sorry for the spam emails 👼

**Comment by abdulrahuman5196** [comment]
We got a proposal to review in the weekend. Need to investigate the proposal much further.

Before that,

>This issue occurs only in PROD and on small-screen devices like the iPhone SE.

@aswin-s-kumar  / @aswin-s  (not sure which is correct GH). I was able to repro this issue in iphone 14 simulator on adhoc builds generated.

**Comment by johncschuster** [comment]
@abdulrahuman5196 did you see the above comment?

**Comment by abdulrahuman5196** [comment]
@aswin-s Sorry missed the reply. I meant a different question.

>This issue occurs only in PROD and on small-screen devices like the iPhone SE

I was pointing out that this is wrong actually. I am able to reproduce in iphone 14 size of screens as well.

**Comment by aswin-s** [comment]
@abdulrahuman5196  Ok. I'll remove above line to avoid confusion. Did you get a chance to look at evaluating the root cause and proposal?

**Comment by abdulrahuman5196** [comment]
Reviewing the same now.

**Comment by abdulrahuman5196** [comment]
I think the proposal seems convincing on reviewing since I was just testing it out. But will take some time to test it further and update if it pans out.

**Comment by abdulrahuman5196** [comment]
> I think the proposal seems convincing on reviewing since I was just testing it out. But will take some time to test it further and update if it pans out.

Still on same boat. Will provide update today.

**Comment by abdulrahuman5196** [comment]
Re-reviewing now

**Comment by abdulrahuman5196** [comment]
@aswin-s 's proposal here https://github.com/Expensify/App/issues/27800#issuecomment-1773979494 looks good and works well. Tested in different platforms and is working well. It could seem like a workaround to transform and fix but seems like the best and effective fix at the moment IMO.

🎀 👀 🎀
C+ Reviewed

**Comment by aldo-expensify** [comment]
@aswin-s which account should I invite? @aswin-s or @aswin-s-kumar ?

**Comment by aswin-s** [comment]
@aldo-expensify You may use @aswin-s

**Comment by abdulrahuman5196** [comment]
>The PR that introduced the bug has been identified. Link to the PR:
The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Not a regression. Issue present as part of the mapbox implementation.

>Determine if we should create a regression test for this bug.

Yes.

>If we decide to create a regression test for the bug, please propose the regression test steps to ensure the same bug will not reach production again.


1) Open NewExpensify on Safari mWeb
2) Open Request Money page from global navigation
3) Open 'Distance' tab
4) Wait for the map to load
5) Verify that the MapBox logo and the information icon is shown at the bottom edge of the map


@johncschuster 
Seems melvin bot didn't update here automatically. Seems the issue is in payment due for today - https://github.com/Expensify/App/pull/30673#issuecomment-1804800565

**Comment by abdulrahuman5196** [comment]
@johncschuster Gentle ping on payment as mentioned above.

**Comment by aswin-s** [comment]
@johncschuster @dylanexpensify Gentle reminder on the payment.

**Comment by johncschuster** [comment]
Thanks for the bump! I'll get payment issued shortly!

**Comment by aswin-s** [comment]
Bump @johncschuster

**Comment by johncschuster** [comment]
Sorry team! I let this slip. Payment has now been issued!

**Comment by johncschuster** [comment]
I'll leave this open for me so I can get the regression steps
