### ISSUE TITLE
[$500] Web - Login - Console error shows up after logging in

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#28042]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___
**Issue found when executing PR** https://github.com/Expensify/App/pull/23390

## Action Performed:
1. Go to staging.new.expensify.com
2. Log in to any account.

## Expected Result:
There is no console error after successfully logging in.

## Actual Result:
Console error shows up after logging in.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / native
- [ ] Android / Chrome
- [ ] iOS / native
- [ ] iOS / Safari
- [x] MacOS / Chrome / Safari
- [ ] MacOS / Desktop

**Version Number:** 1.3.73.0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation

https://github.com/Expensify/App/assets/93399543/207c197c-59e6-4335-84ae-c5197ba5483b

**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team 
**Slack conversation:**

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~011309d5c068a9ccee</li>
        <li>Upwork Job ID: 1706215107655745536</li>
        <li>Last Price Increase: 2023-10-02</li>
    </ul>
</details>

**Comment by mountiny** [comment]
I cannot repro, demoting

**Comment by mountiny** [comment]
Maybe its not repro and we can close it

**Comment by jjcoffee** [comment]
I'm 99% sure this only happens for `AuthenticatePusher` calls where the channel name is `private-report-reportID-null`, which only happens if you have `report_null` in your Onyx data (which would have come from [this issue](https://github.com/Expensify/App/issues/26205) which is now fixed). So no bad side-effects really and I think we can close.

**Comment by JawadSadiq01** [comment]
### Proposal

**Please re-state the problem that we are trying to solve in this issue.**
Login - Console error shows up after logging in

**What is the root cause of that problem?**
At **src/libs/action/Report.js#179**, **"reportId"** has a string value which is **"null"**. The if condition at line#179 fails, because if(!reportId) return false and the code does not return. And due to this, it's returning **private-report-reportID-_null_** string. In this, the **null** is due to **reportId === "null"**. The **Pusher api(http://localhost:8082/api?command=AuthenticatePusher)** runs with **channel_name: private-report-reportID-null** and prints error of 404 on the console.

**What changes do you think we should make in order to solve the problem?**
You just have to change the **if block** condition with the below code on **src/libs/action/Report.js#179**.
```
if (!reportID || reportID === null) {
        return;
}
```
or
```
if (!JSON.parse(reportID)) {
        return;
}
```
Now the **AuthenticatePusher** will be execute with a valid **reportId**, and no error would be log in the console. It will not through **404 error** in the **Network tab**

**What alternative solutions did you explore? (Optional)**
NA

**See Attachment**
<img width="1432" alt="image" src="https://github.com/Expensify/App/assets/135354140/2dcf57e6-6eb5-4b4c-af71-56e892ef6c0f">
<img width="1432" alt="image" src="https://github.com/Expensify/App/assets/135354140/19e645ef-0d71-4305-93f7-6586eb968cb3">

**Comment by mallenexpensify** [comment]
@jjcoffee please review @JawadSadiq01 's proposal above
https://github.com/Expensify/App/issues/28042#issuecomment-1733874876

**Comment by jjcoffee** [comment]
@mallenexpensify I'm not sure if this is worth fixing, see my earlier [comment](https://github.com/Expensify/App/issues/28042#issuecomment-1733668764). I don't think we really want to be handling having a report with a null ID.

**Comment by JawadSadiq01** [comment]
@jjcoffee, @mallenexpensify Yes, this bug currently doesn't cause any problems for the app because the page redirects, but it's still showing up in the console. If the same code is used elsewhere in the app, it could crash the entire page(**bcz of 404 error**) if reportId is equal to null. It's a quick fix, only taking about 2 minutes.

**Comment by jjcoffee** [comment]
So just to sum up in @JawadSadiq01's [proposal](https://github.com/Expensify/App/issues/28042#issuecomment-1733874876) we would be actively adding a check for a null `reportID`. This would handle cases where (as I understand it) we've optimistically added a report with a `null` ID (so you end up with `report_null` in Onyx) due to a [typo](https://github.com/Expensify/App/issues/26205) that has since been fixed. 

Personally I don't think this is worth handling, and I don't agree that it would [cause](https://github.com/Expensify/App/issues/28042#issuecomment-1743145366) a crash (pretty sure we would have seen reports of this too!). If we do want to fix, we can go with @JawadSadiq01's [proposal](https://github.com/Expensify/App/issues/28042#issuecomment-1733874876). I'll leave it up to the engineer to make the final decision.

:ribbon::eyes::ribbon: C+ reviewed
