### ISSUE TITLE
[HOLD for payment 2023-11-13]  Expense - Copy to clipboard option for system message for paid expense crashes the app

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#30796]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.3.95-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/30478
## Action Performed:
1. Launch New Expensify app
2. Go to workspace chat that has paid expense
3. Tap on the workspace expense
4. Long press on the system message for paid expense
5. Tap Copy to clipboard

## Expected Result:
App does not crash

## Actual Result:
App crashes
Crash is reproducible on Android and iOS.
On web, mweb and desktop app, Copy to clipboard button is not responsive and console error shows up

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/38065adc-8cc5-4b69-b07d-bceda02b9327

[logs.txt](https://github.com/Expensify/App/files/13244105/logs.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by marcaaron** [comment]
Seems most likely related to the changes [here](https://github.com/Expensify/App/pull/30085)

**Comment by marcaaron** [comment]
![2023-11-02_10-50-12](https://github.com/Expensify/App/assets/32969087/f7b7237e-be5b-4e7c-8591-afbd9e33292c)

**Comment by marcaaron** [comment]
Maybe this one then -> https://github.com/Expensify/App/pull/30640 ?

**Comment by AmjedNazzal** [comment]
@marcaaron why is it related to that? our change was execlusive to safari only, nothing else, so if it was related why would this issue happen on all platform when our code change doesn't even get executed by anything other than Safari?

**Comment by marcaaron** [comment]
@AmjedNazzal yes, see my next comment. I was taking an educated guess based on the title of the PR.

**Comment by marcaaron** [comment]
Reverting https://github.com/Expensify/App/pull/30640 fixes the issue.

**Comment by cubuspl42** [comment]
I approved the PR, but let's keep this issue open until we figure out why we have this `{amount, currency}` inconsistency and figure out a proper long-term fix.

**Comment by Beamanator** [comment]
Fix should be working in staging, NAB

**Comment by cubuspl42** [comment]
I added [follow-up questions in the PR](https://github.com/Expensify/App/pull/30818/files#r1383116060).

**Comment by marcaaron** [comment]
I am kind of lost on what was decided here and didn't merge the linked PR. Did we come up with some explanation for the root cause? It's hard to answer the above questions. 

I think the correct thing to do here is assign @saranshbalyan-1234 and @cubuspl42 to this issue since they worked on the linked PR.

Also tagging in @Beamanator if you can help with any of the above items. I mainly just called out which PR had the problem on this one. 😄

**Comment by Beamanator** [comment]
@marcaaron I agree it would make sense to assign @saranshbalyan-1234 to this issue as well

@cubuspl42 do you mind helping fill out the BugZero checklist above?

I can help with anything / take over assignment if you want @marcaaron - all I did was helped review the fix PR & got it CP'd to unblock deploy last week :D

**Comment by cubuspl42** [comment]
> Did we come up with some explanation for the root cause?

Not really. This might be backend-related, but it's not confirmed yet. There's a [thread on the PR](https://github.com/Expensify/App/pull/30818/files#r1381263794).

The truth is that in Expensify, seemingly trivial problems like this one are pretty complex to investigate because:
- Most of the domain model is still not typed
- We perform domain logic on backend-received data directly
- Contributors don't have access to the backend source code

What's sure is that sometimes the (`currency`, `amount`) properties reside directly in the message and sometimes are nested in a `IOUDetails` aggregate object (only in case of  `type = pay`?).

I found a comment stating that...

> // In send money flow, we store amount, comment, currency in IOUDetails when type = pay

I'm not sure why in a specific case these properties might _not_ be present there.

**Comment by marcaaron** [comment]
>What's sure is that sometimes the (currency, amount) properties reside directly in the message and sometimes are nested in a IOUDetails aggregate object (only in case of type = pay?).

Thanks @cubuspl42. 

Maybe the Manual Requests crew can help us make sense of this one... 

@mountiny @luacmartins we're trying to figure out the root cause of this issue and there's some conversation in [this thread](https://github.com/Expensify/App/pull/30818/files#r1381263794).

From what I can tell - sometimes the `amount` and `currency` fields are showing up on the `reportAction.originalMessage.IOUAction` and other times they show up on the `reportAction.originalMessage` itself. That doesn't make a whole lot of sense to me.

@cubuspl42 @saranshbalyan-1234 both seem to imply there is some backend issue. But it's not clear from the comment thread what that issue is. So, I'm not sure where the best place to look next would be... 😄

**Comment by cubuspl42** [comment]
> So, I'm not sure where the best place to look next would be...

I would say: the backend code that constructs these structures. The meta-issue is that we're not entirely sure what the structure _should_ be, as it's neither documented, typed, or validated on the frontend. It's likely that it should _not_ be the way it is now.

I think that what we could do on the frontend would be to provide more devtools debugging data and try finding the pattern (_when_ is `IOUAction` entry present and when it's absent?). 

It would be great if you could do that, @saranshbalyan-1234 😃

**Comment by mountiny** [comment]
I assume you meant `IOUDetails`. If so that is expected for case of sending money so iou action type `pay`, this structe is in place because type `pay` is for both paying existing request and sending money. So to distinguish them, we check if the originalMessage has the IOUDetails property and if it does, we know this is Send money action.

Why did we decide to not have IOU `send` action and not relay on the `IOUDetails`? Great question and I dont know, this was before me :D

**Comment by mountiny** [comment]
Do you have a link to that specific code pleasE?

**Comment by cubuspl42** [comment]
@mountiny I'm talking about [the line](https://github.com/Expensify/App/pull/30818/files#diff-65c096044d5f69b35bcdec14c99c4fda4580759df9b1a7c36650d58eea276f1dR4090) you're probably aware of. I can see that you added a comment in the discussion.

**Comment by mountiny** [comment]
Ah yeah I think that is reasonable its just the structure of the data we have so adding a comment will help for engineers to get better context

**Comment by greg-schroeder** [comment]
Should @saranshbalyan-1234 be assigned here? Do I need to pay them or not?

**Comment by greg-schroeder** [comment]
@mountiny @marcaaron can you weigh in here as well? thanks!

**Comment by cubuspl42** [comment]
@ishpaul777 

> as far as i have noticed if PR author choose to go with Proposed solution, 25% of base price is paid to contributor who propose the solution.

This issue wasn't even ever labeled "External". Thank you for your input, but I would ask you to unsubscribe from notifications here and move on to working on other issues (preferably marked as "External" and "Help wanted"), as we **do** have guidelines about the lack of any guarantees about posting proposals to internal issues, unnecessary pinging, and other.

**Comment by cubuspl42** [comment]
@saranshbalyan-1234 

> As the previous issue was only paying 125$ which I don't think is suitable for this issue Instead of previous issue, we should keep this one for payment

You misspelled $62.50 🤪

[contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md)

> a 50% penalty will be applied to the Contributor and [Contributor+](https://github.com/Expensify/App/blob/main/contributingGuides/HOW_TO_BECOME_A_CONTRIBUTOR_PLUS.md) for each regression on an issue

We could try arguing, instead, that the schema of the discussed structure is unclear, and we'd like to ask for considering not applying the regression penalty in this case.

**Comment by mountiny** [comment]
it was a regression from @saranshbalyan-1234 PR right? And they raised a fix? then no payment here but also no penalty for regression on the original issue

**Comment by mountiny** [comment]
@ishpaul777 unfortunately the DB are still kind of a grey area in this case and we havent standardized a good approach. Problem is simply that the DBs are regressions from someone elses PR and if we should pay another person $500 + $500 for  a C+ review and then we also pay the engineers who cause the deploy blocker, although with a penalty, thats seems like throwing money out of window, doesnt it? At the same time we want to get them fixed asap. So no guidelines as of now, but I think we will try to work on ways to make the treatment of deploy blcookers more transparent and easier to manage.

@saranshbalyan-1234 I understand this took more time to debug, but I believe this should have been caught in the original PR and tested properly all the cases on report actions and copy to clipboard. This caused a crash of the app which is a major regression.

**Comment by mountiny** [comment]
Thank you, we value your contributions, its just not easy to manage the program with so many individual contributors.

**Comment by greg-schroeder** [comment]
Thanks all for the discussion. Agreed with @mountiny that we need a bit clearer guidelines on DBs... I'll start a convo with the team about this.
