### ISSUE TITLE
[$500] Web - Chat - The "Add reaction" popup position is indicating that the message above it is selected

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#31577]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.4
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Open any 1:1 chat with a few messages
3. Right click on a message
4. Click on the "Add reaction" button

## Expected Result:
The popup should be near the original text

## Actual Result:
The "Add reaction" popup position is indicating that the message above it is selected

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/5d18a2fb-b7d5-48e2-9ced-54c62750a386

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015472f79c881ba152</li>
        <li>Upwork Job ID: 1726686898383130624</li>
        <li>Last Price Increase: 2024-01-11</li>
    </ul>
</details>

**Comment by StefanNemeth** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When opening the emoji picker via the context menu it looks like it belongs to another message instead of the one that the context menu was opened for.
### What is the root cause of that problem?

The emoji picker opens at the top right position of the context menu and has a smaller height, so that it will be placed above the message that the context menu was previously opened on.

In `src/components/Reactions/QuickEmojiReactions/index.js` the anchor origin is set to TOP, RIGHT
```
    const onPressOpenPicker = (openPicker) => {
        openPicker(contextMenuRef.current.contentRef.current, {
            horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.RIGHT,
            vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.TOP,
        });
    };
```

### What changes do you think we should make in order to solve the problem?


1. Updating `src/components/Reactions/QuickEmojiReactions/index.js` with the anchor origin set to BOTTOM, LEFT
```
    const onPressOpenPicker = (openPicker) => {
        openPicker(contextMenuRef.current.contentRef.current, {
            horizontal: CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT,
            vertical: CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.BOTTOM,
        });
    };
```
2. Implementing the corresponding logic so that the proper anchor position is calculated (currently LEFT, BOTTOM does not have an implementation) in `src/libs/calculateAnchorPosition.ts`:
```
export default function calculateAnchorPosition(anchorComponent: View, anchorOrigin?: AnchorOrigin) ...
    // ...
        anchorComponent.measureInWindow((x, y, width, height) => {
            // ...

            if (anchorOrigin?.vertical === CONST.MODAL.ANCHOR_ORIGIN_VERTICAL.BOTTOM && anchorOrigin?.horizontal === CONST.MODAL.ANCHOR_ORIGIN_HORIZONTAL.LEFT) {
                return resolve({horizontal: x, vertical: y + height + (anchorOrigin?.shiftVertical ?? 0)});
            }

   // ...
```

https://github.com/Expensify/App/assets/5003405/dc2f748f-e73c-4cfa-b18e-5f69f9c41852

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by erquhart** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

When selecting a reaction from the emoji picker, it isn't clear which message the reaction will apply to.

### What is the root cause of that problem?

I don't believe the positioning of the picker should be relied on as an indicator of which message is being reacted to - the message should be highlighted instead. Popover position is complicated to do well, and in some cases, such as screen size limitations, it isn't possible to use positioning this way. And even if we could, it still would not be absolutely clear which message was being reacted to, the popover is too large for that.

The root cause is that we don't highlight the relevant message when the emoji picker is open. This doesn't seem to be regression, we just don't do it. We do it for the context menu, but not the emoji picker (note `isContextMenuActive`): https://github.com/Expensify/App/blob/eef8347c59b5a3bb7fc508484f4c32ff092a05da/src/pages/home/report/ReportActionItem.js#L671


### What changes do you think we should make in order to solve the problem?

We should highlight the relevant message when the emoji picker is open, just like we do when the context menu is active.

**Comment by s-alves10** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The `EmojiPicker` by `Add reaction` button in context menu is positioned as if the message above the selected one is selected

### What is the root cause of that problem?

The anchor position of the `EmojiPicker` is calculated by anchor and origin here
https://github.com/Expensify/App/blob/72e73ae6d922b915198e0a5bcff9d71de5a1001b/src/components/EmojiPicker/EmojiPicker.js#L59

In the above code, anchor is the `Add reaction` button and the origin is `DEFAULT_ANCHOR_ORIGIN` defined here
https://github.com/Expensify/App/blob/72e73ae6d922b915198e0a5bcff9d71de5a1001b/src/components/EmojiPicker/EmojiPicker.js#L14-L17

That is, the anchor position is based on the `Add reaction` button, not on the selected message. 

This is the root cause

### What changes do you think we should make in order to solve the problem?

The position of the `Add reaction` button is changed by the message type and so the position of the `EmojiPicker` will also be changed. I think the ideal solution would be to set the anchor position based on the selected message. It'd be better if we can set the anchor position of the `EmojiPicker` same as the anchor position of context menu

We calculated the anchor position of the context menu here
https://github.com/Expensify/App/blob/72e73ae6d922b915198e0a5bcff9d71de5a1001b/src/pages/home/report/ContextMenu/PopoverReportActionContextMenu.js#L169-L172

Pass this value to the `EmojiPicker` to use instead of anchor and origin

This works as expected

The complete solution can be found here https://github.com/s-alves10/App/tree/fix/issue-31577

<details>
    <summary>Result</summary>


https://github.com/Expensify/App/assets/126839717/1029fc23-a33a-497f-ae0c-0749c40b3617


</details>

### What alternative solutions did you explore? (Optional)

**Comment by kaushiktd** [comment]
### Please re-state the problem that we are trying to solve in this issue.
The "Add reaction" popup position is indicating that the message above it is selected

### What is the root cause of that problem?
Function named `calculateAnchorPosition` that yields both the horizontal and vertical values, where the vertical value is responsible for the misalignment of the popup.

### What changes do you think we should make in order to solve the problem?
File path:- https://github.com/Expensify/App/blob/6c29cabf1cce381bc927af52f819223ba6b541bc/src/libs/calculateAnchorPosition.ts#L29

The adjustment in the vertical position by adding 50 units ensures proper placement above the anchor element.

 `return resolve({horizontal: x + width, vertical: y + 50});`

### Video:- 
https://drive.google.com/file/d/1esXNtk-pIefZEVWb4Lx2epmj76rp6R7t/view?usp=sharing

**Comment by sobitneupane** [comment]
Thanks for the proposal everyone.

I agree with @erquhart rather than position of picker we should rely on the indicator.

> We should highlight the relevant message when the emoji picker is open, just like we do when the context menu is active.

@erquhart Would you mind updating your proposal to add more details on how you will implement the solution?

**Comment by s-alves10** [comment]
@sobitneupane 

I think we need to set clear expectation here. Can you please confirm internally?

**Comment by NicMendonca** [comment]
^ Anyone can confirm anything internally via Slack as an FYI!

**Comment by erquhart** [comment]
@sobitneupane it's going to take a bit more investment than I thought to pull this off, due to our use of refs instead of context for global state management of certain bits. I'm not going to take this one on, but someone else is welcome to implement.

I do stand by the assertion that fulfilling the _requirements_ of this issue - slightly modifying the position of the popup - will not at all address the _objective_ of the issue, which is to clearly indicate the selected message.

**Comment by s-alves10** [comment]
@sobitneupane 

I think it would look weird if the popup isn't positioned at the message though the message is highlighted.
Will you confirm the expected behavior with the internal team members?

Thank you

**Comment by erquhart** [comment]
@s-alves10 there's nothing wrong with bumping the positioning per yours and the other proposals, positioning just doesn't serve as an effective indicator for which message is selected, and indicating the selected message is the premise of this issue. I'm not taking on the work so feel free to add to your proposal for highlighting the message. It doesn't look very difficult to do, just more involved than I want to get into right now.

**Comment by s-alves10** [comment]
@erquhart 

We're not highlighting the message when opening `EmojiPicker` now. Please check the below video

https://github.com/Expensify/App/assets/126839717/7a7103f1-f941-403a-97c9-de85cb001315

As you can see, highlight is removed when moving mouse while the EmojiPicker is opened by EmojiBubble button. If we keep highlighting the message while EmojiPicker is opened from context menu, this can be an inconsitency. That's why I wanted to set clear expectation before going forward.

cc @sobitneupane

**Comment by erquhart** [comment]
@s-alves10 do what you just did in that video, but with the context menu instead of the emoji picker. See how the message stays highlighted while you hover outside of the context menu? There's no reason the emoji picker shouldn't also be doing that - this is a current inconsistency, and I'm fairly certain that it's unintentional. Bumping the emoji picker a few pixels is super easy to do, but it won't address the root problem at all.

I believe @NicMendonca's point was that you can confirm this yourself in Slack instead of waiting to hear back from the reviewer.

**Comment by s-alves10** [comment]
@erquhart 

> Bumping the emoji picker a few pixels is super easy to do, but it won't address the root problem at all

We're not moving the emoji picker a few pixels. Trying to place it at the right position. Not sure what you're trying to say. Each issue should have its clear expectation and should be confirmed internally if it needs to be changed. I understand your thoughts, but it's nothing but your idea. It's not the target of this issue unless it's confirmed.

**Comment by sobitneupane** [comment]
@s-alves10 I believe re-positioning the emoji picker along with highlighting the message item will be great. I agree with @erquhart that position alone won't be helpful for indicating the right message. Due to screen-size limitation, we cannot always place the picker just above the message.

https://github.com/Expensify/App/assets/25876548/1ab2c46d-4c81-430e-a40e-7cd11d085057

**Comment by sobitneupane** [comment]
@s-alves10 Do you want to update your proposal to meet [this](https://github.com/Expensify/App/issues/31577#issuecomment-1840178141) expectation?

**Comment by s-alves10** [comment]
Yes, I'll @sobitneupane

**Comment by NicMendonca** [comment]
^ done

**Comment by NicMendonca** [comment]
still holding

**Comment by NicMendonca** [comment]
setting to weekly while we wait for https://github.com/Expensify/App/issues/28029

**Comment by NicMendonca** [comment]
https://github.com/Expensify/App/issues/28029 is fixed!

@lanitochka17 since this issue is quite old, can you confirm if you're still able to reproduce?

**Comment by lanitochka17** [comment]
@NicMendonca Hello
Issue is reproducible on the latest build 1.4.23-1

https://github.com/Expensify/App/assets/78819774/bc2ca692-8674-4d95-b044-5fbe48aaf6c3

**Comment by s-alves10** [comment]
## Proposal
[Updated](https://github.com/Expensify/App/issues/31577#issuecomment-1820317427)

**Comment by NicMendonca** [comment]
I actually can't repro this. The Add reaction popup come up on the correct message: 

<img width="572" alt="image" src="https://github.com/Expensify/App/assets/24947345/82d190e4-018e-4cc8-ab2b-411c4eed5b36">

**Comment by s-alves10** [comment]
@NicMendonca 
This issue is still reproducible. The issue is for the position of emoji picker from the context menu

**Comment by s-alves10** [comment]
I can still see this issue


https://github.com/Expensify/App/assets/126839717/c356631b-ada1-40c6-917e-e26b6349f958

**Comment by sobitneupane** [comment]
@NicMendonca Issue is still reproducible.

https://github.com/Expensify/App/assets/25876548/c260db83-476b-4323-9f1b-d86f473603b6
