### ISSUE TITLE
[$500] [HOLD for payment 2023-11-30] Web - Referral - 'Got it' button does not take you back to the Previous page after a reload

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#31628]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.1.5
**Reproducible in staging?:** y
**Reproducible in production?:** new feature
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Click on FAB > Request Money > switch to Manual
2. Enter the amount and click on Next
3. Click on 'Request money, get $250' to go to the referral page
4. Reload the page
5. Click on the 'Got it' Button

## Expected Result:
Click on the 'Got it' Button takes you back to the Manual page

## Actual Result:
Click on the 'Got it' Button takes you back to the main chat.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/e9241618-b661-44da-8fab-ea3c274badc2

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0114db822bdf934768</li>
        <li>Upwork Job ID: 1730235291142729728</li>
        <li>Last Price Increase: 2023-11-30</li>
    </ul>
</details>

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Web - Referral - 'Got it' button does not take you back to the Previous page after a reload 

### What is the root cause of that problem?
Currently, when clicking Got it button, we will call `Navigation.goBack()`. So if we reload page navigation history will be lost, It cause this bug 
### What changes do you think we should make in order to solve the problem?
We should use `referralContentType` in route to detect which is previous page and navigate to this page directly

### What alternative solutions did you explore? (Optional)

**Comment by luacmartins** [comment]
@DylanDylann are you able to work on a PR within the next hour?

**Comment by Tony-MK** [comment]
@luacmartins I am available, only if dylan is away. Should I post a prospal?

**Comment by luacmartins** [comment]
sure, go ahead

**Comment by Tony-MK** [comment]
@luacmartins It seems that I can't come up with a better proposal than Dylan's. If I do post a proposal, most likely it will be the same as Dylans.

**Comment by luacmartins** [comment]
We got a fix merged and CPed

**Comment by DylanDylann** [comment]
> @DylanDylann are you able to work on a PR within the next hour?

@luacmartins It was 2:42 AM in my time, so I wasn't available to raise a quick PR. Thanks so much for your PR. Could you assign me to this issue for compensation?

**Comment by luacmartins** [comment]
Closing issue as per comment above. Thanks everyone!

**Comment by conorpendergrast** [comment]
Damn, you stole the satisfying bit. 

And thanks! I am still not used to 90% of bugs coming directly from regression testing

**Comment by luacmartins** [comment]
Sorry haha I'll let you close it next time :)
