### ISSUE TITLE
[HOLD for payment 2024-01-22] [$500] iOS - Attachment - The image shakes when you zoom in and back to the original size

### ISSUE THREAD

**Issue by kbecciv** [Expensify/App#32110]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.4.0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Log in
3. Take and upload a photo to any conversations
4. Open the preview of the photo
5. Zoom in a little bit
6. Zoom out a little bit

## Expected Result:
The image should zoom smoothly without shaking.

## Actual Result:
The image shakes when you zoom in a little and when you zoom back to the original size.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/93399543/fbeb28e8-e4e9-4193-9f57-9566a89288de

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01a3b2c6d67f8d66f1</li>
        <li>Upwork Job ID: 1729484843894013952</li>
        <li>Last Price Increase: 2023-12-05</li>
    </ul>
</details>

**Comment by sakluger** [comment]
I agree that this is an annoying bug that we should solve. Let's see if any contributors can figure out what's going on and how to fix it.

**Comment by ikevin127** [comment]
Debugging observations:
- in order to debug this one needs to be able to run the iOS app on a real device
- the issue's RC comes from the `ImageTransformer.js` implementation of pan / pinch gestures which are both active simultaneously and the conflict between the 2 is not handled
- it seems like while pinch zooming, when 1 of the 2 pointers (fingers) is lifted up, the image jumps and centers to the anchor of the 1 remaining pointer - when this happens fast like in the issue's video, we get that image shake

Considering all these findings, I was still not able to find a fix yet.

Maybe @chrispader can chime in with some pointers as to a possible fix for this issue since he's the author of `ImageTransformer`'s implementation and I am sure he's more familiar with gestures and the way they work together.

**Comment by chrispader** [comment]
I'm going to look into this tmrw! I'm currently working on improving the `ImageView`/`Lightbox` component, so i can fix this in the other PR:

https://github.com/Expensify/App/pull/31308

**Comment by sakluger** [comment]
Thanks @chrispader! Please let us know once you confirm whether you'll be able to fix this issue in that PR.

**Comment by sakluger** [comment]
@chrispader any updates?

**Comment by chrispader** [comment]
@kbecciv i'm not sure if this has coincidentally been fixed in this PR or if i'm just unable to reproduce anymore. I know for sure that i've also experienced this bug before, but just can't reproduce with the current changes.

Could you test this and let me know please? :)

https://github.com/Expensify/App/pull/31308

**Comment by sakluger** [comment]
That would be great if this was resolved in another update already! @kbecciv please give it a try and let us know if you can still reproduce, thanks!

**Comment by sakluger** [comment]
Reached out to @kbecciv on Slack.

**Comment by sakluger** [comment]
@kbecciv posted this video in Slack showing that the issue is still reproduceable on build 1.4.13.0, device: iPhone 12 Pro / iOS 17.1.1.

https://github.com/Expensify/App/assets/5997400/45397f6f-a756-4b43-8afc-81d182a1e3fd

**Comment by sakluger** [comment]
@chrispader could you please take another look? We've confirmed that this si still reproduceable, see my comment above.

**Comment by sakluger** [comment]
I asked @chrispader [in Slack](https://github.com/Expensify/App/pull/31308) if he added a fix for this issue in his related PR: https://github.com/Expensify/App/pull/31308.

**Comment by chrispader** [comment]
Looking into this again now! :)

**Comment by chrispader** [comment]
> @kbecciv posted this video in Slack showing that the issue is still reproduceable on build 1.4.13.0, device: iPhone 12 Pro / iOS 17.1.1.
> 
>  Ulct6113.mp4

i can now reproduce this!

**Comment by chrispader** [comment]
This problem was fixed here: https://github.com/Expensify/App/pull/33755

I also created another PR which improves the `MultiGestureCanvas` code by a lot. https://github.com/Expensify/App/pull/33756

**Comment by mollfpr** [comment]
@sakluger Let's assign this issue to @chr

**Comment by mountiny** [comment]
@mollfpr @chrispader what are the next steps on this one?

**Comment by chrispader** [comment]
> @mollfpr @chrispader what are the next steps on this one? 

@mountiny the PR is ready for review and merge! :) #33755

**Comment by mountiny** [comment]
Thanks!

**Comment by sakluger** [comment]
@mollfpr can you please complete the BZ checklist? Thanks!

**Comment by sakluger** [comment]
@mollfpr friendly bump on the BZ checklist so I can post the payment summary and close out the issue. Thanks!

**Comment by mollfpr** [comment]
> [@mollfpr] The PR that introduced the bug has been identified. Link to the PR:
 [@mollfpr] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:

I couldn't find the offending PR.

> [@mollfpr] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

The regression step should be good.

>[@mollfpr] Determine if we should create a regression test for this bug.
 [@mollfpr] If we decide to create a [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) for the bug, please propose the regression test steps to ensure the same bug will not reach production again.

1. Go to a report with image attachments
2. Open an image
3. Pinch to zoom in and slightly move both fingers in some direction (top/right/bottom/left)
4. Release pinch gesture
5. Verify the image is not flickers/shakes
6. 👍 or 👎

**Comment by sakluger** [comment]
Thanks! Updated the payment summary here: https://github.com/Expensify/App/issues/32110#issuecomment-1904433566. @mollfpr feel free to submit the manual request for payment.

**Comment by JmillsExpensify** [comment]
$500 payment for @mollfpr based on payment summary.
