### ISSUE TITLE
[$500]  IOU - On workspace chat, category of previously created expense is auto-assigned

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32234]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.5-3
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-requisite: user must be a member of a workspace as an employee
1. Go to workspace chat
2. Create a money request and select a category
3. Create another money request, but do not select any category

## Expected Result:
The most recent expense should not have any category assigned

## Actual Result:
The category of the most recent expense is auto-assigned to the one selected on the previous money request

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/d7eef6ce-711d-497d-9f89-8b49fe9317d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fc799cb6c6c36b1</li>
        <li>Upwork Job ID: 1729989330099601408</li>
        <li>Last Price Increase: 2023-12-06</li>
    </ul>
</details>

**Comment by unicorndev-727** [comment]
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/actions/IOU.js#L183-L186
Here we are setting transaction data like category, merchant and so on
but if a transaction data contains an empty category value in `RequestMoney` API, the backend is likely set to the previously selected category in `RequestMoney` API call.

https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/libs/actions/IOU.js#L874-L898

**Comment by DylanDylann** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- IOU - On workspace chat, category of previously created expense is auto-assigned
### What is the root cause of that problem?
- Currently, when creating money request, if user does not select the category, BE will auto create a money request with the category of the previous request.
### What changes do you think we should make in order to solve the problem?
- We can create the default category for each policy. Do it by:
1. First, create an onyx collection, for example ```INITIAL_POLICY_CATEGORY``` to store the initial category for each policy.
2. Create a set method for this collection
```
function setInitialCategory(policyID, category) {
    Onyx.set(`${ONYXKEYS.COLLECTION.INITIAL_POLICY_CATEGORY}${policyID}`, category)
}
```

3. Subscribe the ONYXKEYS.COLLECTION.INITIAL_POLICY_CATEGORY in [MoneyRequestConfirmPage](https://github.com/Expensify/App/blob/main/src/pages/iou/steps/MoneyRequestConfirmPage.js) 
4. Update:
https://github.com/Expensify/App/blob/ef3d8cd3f9f069a2d917ac7c1ee0a5baf7baaffa/src/pages/iou/steps/MoneyRequestConfirmPage.js#L363
to:
```
                        iouCategory={props.iou.category || props.initialCategory}
```

### What alternative solutions did you explore? (Optional)

- NA

**Comment by JmillsExpensify** [comment]
@eVoloshchak Mind commenting on the proposals so far?

**Comment by eVoloshchak** [comment]
> Currently, when creating money request, if user does not select the category, BE will auto create a money request with the category of the previous request.

@DylanDylann, while we could resolve this on the front end with your fix, I think we should resolve it on the back end itself. Are there advantages you'd think of of fixing this on FE?

**Comment by DylanDylann** [comment]
@eVoloshchak 
- If the user creates a lot of request money sequentially, they do not need to re-select the category (This is a feature request rather than a bug). We need to confirmation from internal team. cc @JmillsExpensify 
- But we also need to fix from the BE side that if the payload does not contain category data, do not auto-assign the previous category.

**Comment by JmillsExpensify** [comment]
I don't think we want that feature at the moment, so let's make sure this gets fixed in the backend.

**Comment by eVoloshchak** [comment]
@JmillsExpensify, could you assign an internal engineer to this please?
The only thing we need is the BE fix (https://github.com/Expensify/App/issues/32234#issuecomment-1832935991)
> fix from the BE side that if the payload does not contain category data, do not auto-assign the previous category.

**Comment by JmillsExpensify** [comment]
Still waiting to be picked up internal.

**Comment by MonilBhavsar** [comment]
I am not able to reproduce, I sus that the policy has category expense rules set and it is auto categorising the expense?
@eVoloshchak are you able to reproduce?

**Comment by MonilBhavsar** [comment]
@lanitochka17 is is still reproducible?
> I sus that the policy has category expense rules set and it is auto categorising the expense?

To confirm this suspicion, could you please check if policy has any category expense rules set, or try requesting money on a new workspace chat, thanks!

**Comment by MonilBhavsar** [comment]
Not sure if this is bug https://github.com/Expensify/App/issues/32234#issuecomment-1871931337

**Comment by MonilBhavsar** [comment]
@lanitochka17 @eVoloshchak @JmillsExpensify are you able to reproduce?
If not, we can close this bug

**Comment by eVoloshchak** [comment]
@MonilBhavsar, unable to reproduce this one

**Comment by lanitochka17** [comment]
I am not able to reproduce with latest build 1.4.21-3


https://github.com/Expensify/App/assets/78819774/fa28f517-91a9-4ef2-898a-a6beba8522ad

**Comment by MonilBhavsar** [comment]
Thanks for checking. Closing this issue then. Feel free to reopen if issues is reproducible
