### ISSUE TITLE
[$500] Chat - After selecting "here" from suggestion list, the suggestion box is opened

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#32280]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.6-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Pre-condition : Must have user with 'here' in the display name.
1. Go to https://staging.new.expensify.com/
2. Tap on a report
3. Enter @ in compose box
4.Select "here" from suggestion list

## Expected Result:
After selecting "here" from suggestion list, the suggestion box must be closed

## Actual Result:
After selecting "here" from suggestion list, the suggestion box is opened showing contact with "here" display name

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a3cee8d0-4409-405c-b4ba-fb07223c4ab7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010fc871e1309cdbb5</li>
        <li>Upwork Job ID: 1740328328014270464</li>
        <li>Last Price Increase: 2024-02-14</li>
    </ul>
</details>

**Comment by paultsimura** [comment]
If this is not an expected behavior – it looks like a regression from https://github.com/Expensify/App/issues/30217

**Comment by sakluger** [comment]
@graylewis @allroundexperts, the above proposal says that your PR for https://github.com/Expensify/App/issues/30217 may have caused this regression, do you think that's right?

@situchan this also seems related (or at least very similar) to the issue you just fixed for https://github.com/Expensify/App/issues/32214, and your PR there didn't fix this one. Are they related, or just similar?

**Comment by situchan** [comment]
Seems like this is another edge case where user display name includes "here"

**Comment by allroundexperts** [comment]
Hm... But the root cause is the same as previous bug, right?

**Comment by situchan** [comment]
yes, both issues are regression from https://github.com/Expensify/App/issues/30217

**Comment by situchan** [comment]
Ideally, https://github.com/Expensify/App/pull/31435 should have been reverted at the time of [deploy blocker](https://github.com/Expensify/App/issues/32214).
But we applied patch (more like UX improvement) instead of revert in https://github.com/Expensify/App/pull/32227. This actually didn't fix the root cause of regression caused by https://github.com/Expensify/App/pull/31435.
So I'd say bug demoted to NAB by fixing non-display name cases. Still remaining in this edge case of "here" being contained in display name.

**Comment by allroundexperts** [comment]
It's a weird situation tbh. @situchan Can you maybe raise a PR for this since you applied the previous patch as well?

**Comment by situchan** [comment]
yes will do if @graylewis doesn't want to.

**Comment by sakluger** [comment]
Just to confirm, should this have been fixed in any of the past PRs? Or is this a separate edge case?

**Comment by graylewis** [comment]
@sakluger @allroundexperts Unfortunately things came up the past couple days. Going to try to get a PR in this week. Sorry for the delay

**Comment by sakluger** [comment]
@graylewis it's important that we prioritize fixing regressions, can you please prioritize this one today?

**Comment by graylewis** [comment]
Trying to build a fix for this issue now but I'm unable to reproduce. Was a patch for this already pushed? Also tested this on Android chrome with the same results

https://github.com/Expensify/App/assets/10010793/c11a622e-3dc3-4105-99c7-5f7ead432334

**Comment by sakluger** [comment]
I'm still able to reproduce on Android. To reproduce, you just type the `@` then click on `@here` in the suggestion list. If you type out the full `@here` the issue doesn't happen.

https://github.com/Expensify/App/assets/5997400/a621cdf9-254b-4a2b-a85f-ab4cb260ba1a

**Comment by graylewis** [comment]
I'm still unable to reproduce. I'm assuming it's because there's someone in your room with the substring "here" in their name.

**Comment by sakluger** [comment]
@situchan are you able to reproduce this one?

**Comment by sakluger** [comment]
@situchan bump.

**Comment by sobitneupane** [comment]
@situchan Looks like you are already working on the issue.

**Comment by sakluger** [comment]
I bumped @situchan in Slack: https://expensify.slack.com/archives/C01GTK53T8Q/p1704230193540999

**Comment by graylewis** [comment]
Pulled from main and I'm still unable to replicate. Are the replication instructions missing anything?

**Comment by sakluger** [comment]
I'm not sure @graylewis, I was able to reproduce following the original steps, I added a few details on the steps I took here: https://github.com/Expensify/App/issues/32280#issuecomment-1856402880

**Comment by sakluger** [comment]
@situchan are you able to make a PR for this follow up issue? We can't complete the payment for https://github.com/Expensify/App/issues/32214 until this issue has been fixed.

**Comment by sakluger** [comment]
Bumped @situchan in Slack.

**Comment by situchan** [comment]
@graylewis please try this:
1. Update your display name to `Hi There` (Hi: first name, There: last name)
2. Focus on composer
3. Type `@` and press Enter

**Comment by graylewis** [comment]
Ah okay now I can replicate. So your last name has to contain the entire name of another person's first name for this to be an issue.

**Comment by graylewis** [comment]
I'm not sure if this is something we can prevent with the current approach. The only solution I can think of is to just force the dialog closed after selecting a suggestion but that would require a refactor on the suggestion logic

**Comment by situchan** [comment]
I think we should revert very original [PR](https://github.com/Expensify/App/pull/31435) and find new solution to cover this case as I stated [here](https://github.com/Expensify/App/issues/32280#issuecomment-1836660145)

**Comment by sakluger** [comment]
Reopened and posted in https://github.com/Expensify/App/issues/30217 asking them if we can revert that PR.

**Comment by sobitneupane** [comment]
@sakluger In that case should we hold this issue?

**Comment by sakluger** [comment]
Yes, adding a HOLD while we sort things out.

**Comment by sakluger** [comment]
Sorry, I forgot to update this one after we last discussed it.

We decided that we wouldn't revert https://github.com/Expensify/App/issues/30217. Instead, we would fix that issue and this issue with a new, comprehensive solution.

For the sake of getting this all done, I'm going to finish paying out https://github.com/Expensify/App/issues/32214, and we can treat this as a new bug. The original folks who worked on that one are welcome to make a new proposal, but I'm going to add the help wanted label here.

For anyone submitting a proposal, please be sure that the new solution doesn't break what we did here: https://github.com/Expensify/App/issues/30217.

**Comment by sakluger** [comment]
Still waiting for proposals.

**Comment by sakluger** [comment]
Asked for volunteers in Slack: https://expensify.slack.com/archives/C03UK30EA1Z/p1707857949470189

**Comment by koko57** [comment]
Hi 🙂 I'm Agata from Callstack and I can take a look at this issue

**Comment by koko57** [comment]
It's a tricky issue, and it happens either somebody's name includes "here" or an email address used as a login like Puneet mentioned here: https://github.com/Expensify/App/issues/32280#issuecomment-1839003662. Same I guess with phone numbers (I'm going to test it). As I'm looking for some other cases that may cause this issue I'm thinking of a simple yet robust solution to cover all the cases. I'll keep you updated

https://github.com/Expensify/App/assets/28020445/7b8bffbf-02c7-4be5-9f43-ec5532455a9f

**Comment by koko57** [comment]
today I had to take care of my other PR - I will continue on Monday

**Comment by koko57** [comment]
I've tried to find any other edge case for this issue, but it seems that we have only these two cases (with here and email being part of the display name). I'm working on one solution, testing it now

**Comment by koko57** [comment]
My solution: quite simple but solves the problem. It is similar to the already proposed solution, but it checks for the `lastWord` and covers the case with emails. 

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After choosing “@here” (or a user whose display name contains an email) from the mention suggestion box, the box is not closed if there is any user that whose name includes “here” or the email typed in the composer.

### What is the root cause of that problem?

Regression from [#30217](https://github.com/Expensify/App/issues/30217). We’re checking the word before the space so if there’s any name that includes this value, it appears in the suggestion box and the box is displayed.

### What changes do you think we should make in order to solve the problem?

Thanks to this logic https://github.com/Expensify/App/blob/03c81a6f5a65e6da6bd9b4651a7d08dbbb62a5a8/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L206-L209 we get the `lastWord` and the `secondToLastWord`. When we hit the space the `lastWord` is always an empty string and the `secondToLast` word is the last word we typed. 
As calculateMentionSugestion is also triggered when we choose a suggestion, we should check if the `secondToLast` is not empty (can happen when we only type some spaces in the composer), the word includes “@here” or a valid email and if so reset the suggestions and return early from the function.

### What alternative solutions did you explore? (Optional)
-

**Comment by sobitneupane** [comment]
Thanks for the [proposal](https://github.com/Expensify/App/issues/32280#issuecomment-1956098430) @koko57 

One drawback of the solution would be that we won't be showing an user with here in the name if we type @here and space, right? And similar is the case for email address.

**Comment by koko57** [comment]
For @here - yes, you're right. For the email address - if it's typed correctly we don't need the suggestion box anymore. After sending the message the user will be properly mentioned. The chances that someone will have i.e. a different in their display name and different email for logging are IMHO very low. BUT still the suggestion will appear if after the @here or @[email] someone will type a letter that is matching the last name:


https://github.com/Expensify/App/assets/28020445/b357d918-3bcd-486a-ac54-faa685278187


https://github.com/Expensify/App/assets/28020445/0c706bc0-7ae3-42a6-9256-c06150abf224


I was thinking of having a flag if the suggestion was chosen, but it would need to be stored somewhere (ideally in Onyx, I wonder if it should also be sent to the BE - I'll check it) and then toggled when we start to type another mention and I wonder if it would affect the overall performance and is worth implementing. But if you think that's something worth investigating I'll continue my research on that.

**Comment by sobitneupane** [comment]
Thanks for the update @koko57 

The case we are talking about is one-off. So, I am okay to go with the [current proposal](https://github.com/Expensify/App/issues/32280#issuecomment-1956098430). However, I would request the assigned CME to go through https://github.com/Expensify/App/issues/32280#issuecomment-1956362250 and https://github.com/Expensify/App/issues/32280#issuecomment-1956502961 comments.

🎀 👀 🎀 C+ reviewed

**Comment by arosiclair** [comment]
I'm thinking the root problem is that we are still showing suggestions after a suggestion has already been selected. I also think this would be an issue for any matching prefix not just "here". For example this would also reproduce the issue:

1. Type in @prefix
2. Select "Prefix" from suggestions
3. Suggestion still displays for "Prefix Suffix".

So this

> I was thinking of having a flag if the suggestion was chosen, but it would need to be stored somewhere (ideally in Onyx, I wonder if it should also be sent to the BE - I'll check it) and then toggled when we start to type another mention and I wonder if it would affect the overall performance and is worth implementing.

sounds like a better direction to me.
 
What's tricky is when to start showing suggestions again. Maybe whenever the `@text` is changed or when another `@` is input?

**Comment by koko57** [comment]
> I'm thinking the root problem is that we are still showing suggestions after a suggestion has already been selected. I also think this would be an issue for any matching prefix not just "here". For example this would also reproduce the issue:
> 
> 1. Type in `@prefix`
> 2. Select "Prefix" from suggestions
> 3. Suggestion still displays for "Prefix Suffix".

Responding to your concern - no it won't. If you choose `@prefix` from a selection list the composer will be filled with the handle and a space - the lastWord will be an empty string and secondToLast will be '@prefix'. If we check for '@prefix' in the condition the suggestion list re-calculation won't be triggered and the list will be reset. The suggestion will reappear only if you start typing "Suffix". 

When we select a user from the suggestion list the name we typed is replaced with the handle with the user's email login (even for phone numbers) the only exception is the "here" mention - it stays as it is "@here".  If some other handles like this will be added in the future, that should be added to the condition. We could have a util function to check for all the possible default mentions.

**Comment by arosiclair** [comment]
> If we check for '@Prefix' in the condition the suggestion list re-calculation won't be triggered and the list will be reset. The suggestion will reappear only if you start typing "Suffix".

You mean this regarding your proposal, right? I'm referring to just the current (broken) behavior. 

My concern is that with your proposal, we have to hardcode any conflicting `@text`. And once we add proper `@handle` support (similar thing coming in [this issue](https://github.com/Expensify/App/issues/35532)), it won't work anymore. So it seems that this part that you mentioned:

> As calculateMentionSugestion is also triggered when we choose a suggestion

is the real problem and we just need to stop that from happening with a flag or maybe something else.

**Comment by koko57** [comment]
@arosiclair Ah, ok, yes I meant my proposal. You're right -  if we're going to change the handle behavior, it makes sense to investigate the other solution. Thanks for pointing this out!

**Comment by koko57** [comment]
Working on the alternative solution

**Comment by koko57** [comment]
Ok, so another solution that would be ready for the mention handle changes:

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

same as [here](https://github.com/Expensify/App/issues/32280#issuecomment-1956098430)

### What is the root cause of that problem?

same as [here](https://github.com/Expensify/App/issues/32280#issuecomment-1956098430)

### What changes do you think we should make in order to solve the problem?

Just like we save the draft only in Onyx (we don’t sync the draft with other devices, we don’t send it to the BE), we can do the same for the mentions. Let’s save the mention after it was chosen from the suggestion list as reportDraftLastMention for each chat (just like the drafts). After it was saved we check if the lastWord (ot the secondToLast, when last word is an empty string) is the same as reportDraftLastMention - if so, reset the suggestion list and return early from the calculateMentionSuggestion function. When the message is sent, or we the mention removed from the message, reportDraftLastMention would be cleared. 

### What alternative solutions did you explore? (Optional)
-

**Comment by arosiclair** [comment]
Do we need to use Onyx for that or can we just use local state in `SuggestionMention`? I see we already have a [shouldBlockCalc flag there](https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/pages/home/report/ReportActionCompose/SuggestionMention.js#L68). Maybe we can just use that?

**Comment by koko57** [comment]
local state won't work after refreshing the page and leaving the chat and returning back to draft - the suggestion will be shown again

**Comment by koko57** [comment]
Thanks! 🙌🏻 Yeah, I'll try to come up with another name 😃

**Comment by koko57** [comment]
Hi! I opened the PR last week 🙂 I'm ooo this week, so if any changes will be required or there will be any conflicts to resolve, please ping Callstack team - someone will take it over

**Comment by koko57** [comment]
PR: https://github.com/Expensify/App/pull/37262

**Comment by koko57** [comment]
probably fixed by this: https://github.com/Expensify/App/pull/38361

**Comment by arosiclair** [comment]
@sobitneupane can you retest to verify this is no longer an issue with those changes?

**Comment by sobitneupane** [comment]
@arosiclair Yup. The issue is no longer reproducible.

https://github.com/Expensify/App/assets/25876548/e397d7ae-737b-4257-bd82-fe3050251973

**Comment by arosiclair** [comment]
> @arosiclair Yup. The issue is no longer reproducible.

Alright that's good news. I appreciate the efforts from you guys. @sobitneupane still did most of the work so I think they should still get payment. What do you think @sakluger?

**Comment by sakluger** [comment]
Sounds good to me! Thanks, everyone, for sticking with this one.

Summarizing payment on this issue:

Contributor: @koko57 - no payment necessary (from CallStack)
Contributor+: @sobitneupane $500, please request on Newdot

**Comment by JmillsExpensify** [comment]
$500 approved for @sobitneupane based on summary.
