### ISSUE TITLE
[$1000] IOU- Scanned receipt request is shown separately initially, and "TBD" is displayed after merge

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32650]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.9.-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
1. Launch the mobile app
2. Tap on 1:1 report (chat DM) which has few scan request uploaded already
3. Tap plus icon and select Request money
4. Tap scan
5. Choose and upload a image from gallery
6. Tap request
7. Note instead of being added to the group of request, the new scan request created is shown separately 
8. Tap on the scan request created
9. Tap on header
10. Tap on scan request created

## Expected Result:
- Scan request created should be displayed in the group of scan requests, already in the page and not seperately.
- Scan request created should be displayed together with other the group of requests & TBD shouldn't be displayed.

## Actual Result:
Scan request created is first shown seperately and after opening and revisiting page, it is added to group of scan requests.
When scan request created merged with other group of requests, additionally TBD is displayed.

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [ ] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/049b3ee5-14e8-43cd-a94e-8dab6266a4f7

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01043dffad9e1c8c25</li>
        <li>Upwork Job ID: 1732724181820264448</li>
        <li>Last Price Increase: 2023-12-18</li>
    </ul>
</details>

**Comment by getusha** [comment]
waiting for proposals.

**Comment by trjExpensify** [comment]
FWIW @michaelhaxhiu I can repro this on iOS native `v1.4.11-23` if I use the DM create flow specifically, so I don't think it's Android specific.

**Comment by michaelhaxhiu** [comment]
Thanks for testing and letting me know @trjExpensify.

**Comment by michaelhaxhiu** [comment]
The TBD aspect of the bug is reported and showing up in a few different bug reports, so let's make sure that's addressed at the root (probably not in this bug report).

**Comment by getusha** [comment]
Still waiting for proposals, @michaelhaxhiu could we increase the bounty to attract proposals?

**Comment by michaelhaxhiu** [comment]
Increased price by 2x

**Comment by Victor-Nyagudi** [comment]
The newly scanning receipt is shown grouped together with the other requests on Android native for me. 

Can anyone still reproduce this on the platform?

**Comment by trjExpensify** [comment]
Victor, how are you scanning the receipt and from where?

**Comment by Victor-Nyagudi** [comment]
@trjExpensify On Android Native in a 1 on 1 chat. I tap on the composer's "+" button, request money, scan, upload from gallery, and then make the request.

The chat has previous scan requests that were made on Mac Chrome.

**Comment by trjExpensify** [comment]
Cool, same. Here are my repro steps on iOS native that aren't producing the wonky results anymore on `v1.4.14-2`. 

1. Navigate to a chat with someone
2. Create a request if you don't have one, so an outstanding iouReport exists between you both
3. Using the DM create menu: + > request money > scan > upload from gallery > confirm
4. Observe the receipt is added to the existing iouReport preview

I also tried scanning a receipt, adding one that failed, more than one request on an outstanding report etc. Can't repro it unfortunately.

**Comment by michaelhaxhiu** [comment]
Thanks for both of your help reproducing, super helpful! Let's keep an eye on this and see if there's room to reproduce.
