### ISSUE TITLE
[HOLD for payment 2023-12-20] [$500] Desktop - Expired magic code page for a valid code with no prior use + inability to exit the screen

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#32795]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** Version 1.4.10-1 (1.4.10-1)
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause-Internal Team
**Slack conversation:** @

## Action Performed:
Prerequisites: User must be logged into web app as User A.

1. Launch the Desktop app
2. Enter an email for an existing or new account
3. Go to the email inbox and locate the magic code
4. Copy the Magic link and modify it to staging
5. On the web, open a new tab and navigate to the staging magic link
6. Confirm that the user is prompted to open the desktop app
7. Click on the "Open app" option
8. Repeat steps 5,6 and 7
9. When the apps get opened, click on ''just sign in here ''button

## Expected Result:
The user should be able to sign in right after clicking on ''Just sign in here,'' and they should also have the option to exit the page.

## Actual Result:
When the desktop app is launched using the magic code deep link, the user encounters an expired magic code page even though the code is valid and has not been previously used. Additionally, it's impossible to exit that screen.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/115492554/eb0449b9-708f-481c-abc6-0c64f3bf4c90

[Bug6304327_1701946927913!expen-log2.txt](https://github.com/Expensify/App/files/13634149/Bug6304327_1701946927913.expen-log2.txt)

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01acea970084cf49dd</li>
        <li>Upwork Job ID: 1734159440509161472</li>
        <li>Last Price Increase: 2023-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>alitoshmatov | Reviewer | 28043180</li>
<li>dukenv0307 | Contributor | 28043181</li>
</ul></li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
Different behavior on production.

https://github.com/Expensify/App/assets/115492554/7394a644-3065-4779-99ab-704213e5f9c0

**Comment by Julesssss** [comment]
We released `1.4.11` just before this blocker was created, so I think it will now be an issue on production too. Would you mind retesting to verify?

[here's](https://github.com/Expensify/App/issues/32794) the new checklist

**Comment by Julesssss** [comment]
Hi @dukenv0307, thanks for the proposal. 

> We can simply early return [here](https://github.com/Expensify/App/blob/92662c8119647080916e6e3498ad0865c7161163/src/components/DeeplinkWrapper/index.website.js#L78) (not prompt open desktop) if the auth state is currently NOT_STARTED. We need to pass the session to DeeplinkWrapper.

That makes sense, but why do you think this was a recent regression? This didn't occur on versions prior to `1.4.10` so I'd like to double-check the cause before moving forward.

**Comment by Julesssss** [comment]
Sounds good to me. This is a blocker, so would you be able to raise a PR soon? If so let's do it and I'll find someone on the C+ tema available for a review ASAP

**Comment by Julesssss** [comment]
Hey @dukenv0307, I assigned you for this PR. As this is a blocker could you please prioritise this one? Thanks

**Comment by izarutskaya** [comment]
@Julesssss This issue still reproducible (version 1.4.11-13 (1.4.11-13)

https://github.com/Expensify/App/assets/115492554/0b084b0b-5fb6-44c0-8b72-c9dc5652d4f8

**Comment by Julesssss** [comment]
Thanks @izarutskaya, lets retest once the PR is raised

**Comment by shubham1206agra** [comment]
@dukenv0307 Whats the status of the PR here?

**Comment by luacmartins** [comment]
@dukenv0307 any updates on this PR?

**Comment by joekaufmanexpensify** [comment]
@alitoshmatov could you please handle the BZ checklist so we can prep to issue payment this Wednesday? TY!

**Comment by alitoshmatov** [comment]
- The PR that introduced the bug has been identified: https://github.com/Expensify/App/pull/23673
- The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake: https://github.com/Expensify/App/pull/23673#discussion_r1431218580
- A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. N/a
- Determine if we should create a regression test for this bug: No

**Comment by joekaufmanexpensify** [comment]
Awesome. TY!

**Comment by joekaufmanexpensify** [comment]
BZ checklist complete. All set to issue payment tomorrow (assuming no regressions). We need to pay: 

- @dukenv0307 - $500 for PR. Paid via Upwork. 
- @alitoshmatov - $500 for C+. Paid via Upwork.

**Comment by joekaufmanexpensify** [comment]
All set to issue payment.

**Comment by joekaufmanexpensify** [comment]
@alitoshmatov $500 sent and contract ended!
