### ISSUE TITLE
[HOLD on PR 32432] [$500] Task - task title displays and removes error in few seconds on enter

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#33187]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.13-5
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:** @

## Action Performed:
1. Open the app
2. Open any incomplete task report
3. Click on title to edit it
4. Remove the text and add space
5. Click enter and observe that app displays 'Please enter a title' error for sometime and then removes the error

## Expected Result:
App should display 'Please enter a title' error all the time after enter click when only space is present in task title field like it does on save click

## Actual Result:
App displays 'Please enter a title' error for sometime and removes the error on click of enter when only space is present in title

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/ade448da-0434-45bb-89a1-d170f4b5f5fd

https://github.com/Expensify/App/assets/115492554/6dd85dce-e5b7-4dd8-b361-af66cde6bfd1

https://github.com/Expensify/App/assets/115492554/566edad0-b44a-401d-b7ac-53f325375d7c

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~010c362ca46aa96208</li>
        <li>Upwork Job ID: 1735734569855303680</li>
        <li>Last Price Increase: 2023-12-15</li>
    </ul>
</details>

**Comment by samilabud** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Task - task title displays and removes error in few seconds on enter

### What is the root cause of that problem?
When we are using BaseTextInput (https://github.com/Expensify/App/blob/main/src/components/TextInput/BaseTextInput/index.js)  the validation for input is only enabled when input gets blurred.

### What changes do you think we should make in order to solve the problem?
We could activate the validation of the input when the edit task form (https://github.com/Expensify/App/blob/main/src/pages/tasks/TaskTitlePage.js) has been loaded.

**Comment by m2jobe** [comment]
Proposal:

Investigate Task Title component and identified where state change is occurring to display “Please enter a title” error.

Replicate bug and identify why state change to show error doesn’t persist.

Deploy fix to ensure the error message persist and create PR

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task title displays and removes error in few seconds on enter

### What is the root cause of that problem?

The root cause of the problem is that when the form is initially rendered we have some assumptions which are either the field is empty or the user will click on another element (`shouldSetTouchedOnBlurOnly`) to validate it. Hence, we don't call the `setTouchedInput` function in the [`FormProvider`](https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/components/Form/FormProvider.js#L185) component before validation although the user has focus on the input element. 

https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/components/Form/FormProvider.js#L171-L175

However, in this situation, the user can submit after typing the new empty title without causing the `setTouchedInput` to be called.  Therefore, while the user is typing the new title, the form validator has found `validateErrors` but once it is picked by checking `Boolean(touchedInputs.current[inputID])`, the `touchedInputErrors` will become an empty object.

### What changes do you think we should make in order to solve the problem?

Create an optional prop, defaulted to `{}`, in the [`FormProvider.js`](https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/components/Form/FormProvider.js#L185) component as the argument in `useRef` when initializing the `touchedInputs` variable. 

```
// In TaskTitlePage.js
intialTouchedInput={{"title":true}}

// In FormProvider.js
const touchedInputs = useRef(intialTouchedInput)
```

**Comment by Tony-MK** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Task title displays and removes error in few seconds on enter

### What is the root cause of that problem?

The root cause of the problem is that when the form is initially rendered we have some assumptions which are either the field is empty or the user will click on another element (`shouldSetTouchedOnBlurOnly`) to validate it. Hence, we don't call the `setTouchedInput` function in the [`FormProvider`](https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/components/Form/FormProvider.js#L185) component before validation although the user has focus on the input element. 

https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/components/Form/FormProvider.js#L171-L175

However, in this situation, the user can submit after typing the new empty title without causing the `setTouchedInput` to be called.  Therefore, while the user is typing the new title, the form validator has found `validateErrors` but once it is picked by checking `Boolean(touchedInputs.current[inputID])`, the `touchedInputErrors` will become an empty object.

### What changes do you think we should make in order to solve the problem?

Create an optional prop, defaulted to `{}`, in the [`FormProvider.js`](https://github.com/Expensify/App/blob/c53eca94bd1dfbe44a4b389c5d3a1dc4e8c05e70/src/components/Form/FormProvider.js#L185) component as the argument in `useRef` when initializing the `touchedInputs` variable. 

```
// TaskTitlePage.js
intialTouchedInput={{"title":true}}

// FormProvider.js
const touchedInputs = useRef(intialTouchedInput)
```

**Comment by shubham1206agra** [comment]
@garrettmknight This is fixed by https://github.com/Expensify/App/pull/32432

**Comment by rushatgabhane** [comment]
Agree with @shubham1206agra 
@garrettmknight looks like we can close this issue.

**Comment by garrettmknight** [comment]
Love to see it!

**Comment by Tony-MK** [comment]
It seems like https://github.com/Expensify/App/pull/32432 has been deployed to staging and the bug persists. 

Could please you re-test?

**Comment by shubham1206agra** [comment]
Nope. Still not reproducible on staging

**Comment by Tony-MK** [comment]
@shubham1206agra is correct. It's not reproducible on staging.

**Comment by garrettmknight** [comment]
Looks like we're good here. Closing!
