### ISSUE TITLE
[HOLD - EApp #34466] [$500] Workspace - Infinite loading when navigate to workspace link without access

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34039]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.22-0
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
1. Navigate to Workspace link that doesn't have any users (https://staging.new.expensify.com/workspace/77336CD9870F8DB1
)

## Expected Result:
There's should be error indicating "You do not have access to this page. Are you trying to join the workspace? Please reach out to the owner of this workspace so they can add you as a member! Something else? Reach out to Concierge"

## Actual Result:
Infinite loading remains when user navigate to workspace link without access

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/b1b3de4e-4142-4ce5-902f-10a4bc74358e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013aa8ecc43f8d1fee</li>
        <li>Upwork Job ID: 1743327090406260736</li>
        <li>Last Price Increase: 2024-01-17</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
Should be fixed in https://github.com/Expensify/App/pull/34006

**Comment by alexpensify** [comment]
Ok, based on this news, I'm going to close this one.

**Comment by alexpensify** [comment]
Thanks for flagging!

**Comment by lanitochka17** [comment]
Issue is still reproducible on the latest build 1.4.26-1

https://github.com/Expensify/App/assets/78819774/30137c65-ed0f-4f59-bc39-56ec1145ef83

**Comment by bernhardoj** [comment]
This becomes a problem again after the introduction of `finallyData`  which has the same root cause as https://github.com/Expensify/App/issues/34466

**Comment by alexpensify** [comment]
@bernhardoj - should we reopen https://github.com/Expensify/App/pull/34006 or close this issue for https://github.com/Expensify/App/issues/34466? Thanks for your feedback!

**Comment by bernhardoj** [comment]
@alexpensify maybe we can hold for https://github.com/Expensify/App/issues/34466 and retest after it's deployed to staging. What do you think?

**Comment by alexpensify** [comment]
Good plan, I'm updating this to be weekly and we can check in after https://github.com/Expensify/App/issues/34466 is in production.

**Comment by alexpensify** [comment]
Weekly Update: Still on hold

**Comment by alexpensify** [comment]
Let's hold until next week, looks like there might be a regression.

**Comment by alexpensify** [comment]
@c3024 - I think we should take this one off hold. Do you agree? Thanks!

**Comment by c3024** [comment]
Not reproducible on `main` now. Could you check once @lanitochka17 ?


https://github.com/Expensify/App/assets/102477862/e1b882ff-d031-4583-9541-14b8f8d3233e

**Comment by lanitochka17** [comment]
Issue is not reproducible on the latest build 1.4.42-4


https://github.com/Expensify/App/assets/78819774/1597e8d9-6a71-471e-a91f-a8ea8e1bc171

**Comment by c3024** [comment]
@alexpensify please close this. Issue is not reproducible anymore.

**Comment by alexpensify** [comment]
👍🏼
