### ISSUE TITLE
[MEDIUM] [Android] Large images crashing the App - 'Canvas trying to draw too large'

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#34372]
### Problem

The Android app crashes due to a Canvas OOM exception when the image dimensions are extremely large. This has been fixed in the past, but we recently switched to Expo Image so I believe we'll need a new solution.

```
FATAL EXCEPTION: main
    Process: com.expensify.chat, PID: 28882
    java.lang.RuntimeException: Canvas: trying to draw too large(149730560bytes) bitmap.
    	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
    	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
    	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
    	at android.widget.ImageView.onDraw(ImageView.java:1446)
    	at expo.modules.image.ExpoImageView.onDraw(ExpoImageView.kt:204)
    	at android.view.View.draw(View.java:23900)
    	at expo.modules.image.ExpoImageView.draw(ExpoImageView.kt:200)
    	at android.view.View.updateDisplayListIfDirty(View.java:22767)
    	at android.view.View.draw(View.java:23631)
    	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
    	at android.view.View.updateDisplayListIfDirty(View.java:22758)
    	at android.view.View.draw(View.java:23631)
    	at android.view.ViewGroup.drawChild(ViewGroup.java:4559)
    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4320)
```

We have spent time on different image libraries and many related issues, and I am now trying to combine our current issues and resolve the remaining canvas OOM exception. 

- Share a large image similar to [this](https://private-user-images.githubusercontent.com/10736861/295623310-18b6cbca-c899-4e66-a475-052ca413ba75.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjQxOTksIm5iZiI6MTcwNDk2Mzg5OSwicGF0aCI6Ii8xMDczNjg2MS8yOTU2MjMzMTAtMThiNmNiY2EtYzg5OS00ZTY2LWE0NzUtMDUyY2E0MTNiYTc1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwOTA0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjA0ZjQ4NWIyZWJhZjBkNThmNmVhMzcxMDM4NzZjOTA1NjUyMmZiNmY0MDQ5N2VhZGIxMDgyNTIxZWJiOTc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8DcmaRR14XcX_feiqtw8RYjekb0YfbBenqkxkTdJCd8)
- Attempt to view the image as either a receipt upload or a regular image attachment  

### Solution

Collect all past attempts, recent merged PRs, and determine the best path forward for resolving the crash:

- Here's where we merged [Expo-Image](https://github.com/Expensify/App/pull/30905)
- Here was a [prior attempt ](https://github.com/Expensify/react-native-fast-image/pull/6)to fix the image in `react-native-fast-image`
- Another [PR](https://github.com/Expensify/App/pull/18997) which attempted to fix the issue with an upstream react-native-fast-image PR
- We [introduced AttachmentGallary](https://github.com/Expensify/App/pull/31308) as an improvement to image scaling and a replacement to `ImageZoom`

Next question: Do we need a fix in Expo Image?

**Comment by Julesssss** [comment]
No C+ required yet

**Comment by Julesssss** [comment]
I reached out 1:1 to @WojtekBoman who implemented Expo Image, as I'm not 100% sure whether the exception is fixable within Expo Image or not. I can see some people [suggesting](https://github.com/expo/expo/issues/21949#issuecomment-1495761924) that we disable native Android hardware acceleration -- but this worries me as this will likely reduce performance elsewhere...

I'm thinking that we might need to[ enable it just](https://developer.android.com/topic/performance/hardware-accel#controlling) for the React Views that render potentially lage images

**Comment by Julesssss** [comment]
I'm going to generate a couple of test builds to verify the fix and compare performance.

**Comment by Julesssss** [comment]
As expected, disabling hardware acceleration leads to horrendous performance. We can't make this an app-wide change. My plan is to disable hardware acceleration [just for the specific](https://developer.android.com/topic/performance/hardware-accel#controlling) View/Component that displays image attachments -- this should resolve the crash without harming app performance.

**Comment by Julesssss** [comment]
**Before:**

https://github.com/Expensify/App/assets/10736861/8d38b7cd-82ab-441e-a761-a4957440f24c

**After:**

https://github.com/Expensify/App/assets/10736861/ed2b9b1b-1aea-4b4c-8a6c-e510f78f2f08

**Comment by Julesssss** [comment]
> My plan is to disable hardware acceleration [just for the specific](https://developer.android.com/topic/performance/hardware-accel#controlling) View/Window that displays image attachments

To achieve this we could build our own module, or use this existing (but unknown) `HardwareAccelerationViewManager` [library](https://github.com/Spicy-Sparks/react-native-hardware-acceleration-view/tree/main).

I'd much prefer to resolve this upstream within the Expo Image library though, so I'm going to ask SWM for help.

**Comment by Julesssss** [comment]
This is being passed onto the Expo team, we'll hopefully hear back soon.

**Comment by chrispader** [comment]
Can't we just add a similar `ResizeTransformation` class to the `expo-image` library like in https://github.com/DylanVann/react-native-fast-image/pull/1017 ?

`expo-image` also uses `Glide`, so shouldn't we just be able to attach it with `.transform(new ResizeTransformation())` [here](https://github.com/expo/expo/blob/366c225f9507d5e96143aa44888e86c240e86bc7/packages/expo-image/android/src/main/java/expo/modules/image/ExpoImageModule.kt#L50), or somewhere else ?

(i just looked up this spot, might be a different line file/line)

**Comment by chrispader** [comment]
Either upstream or in a patch, since i'm not sure if this would be the ideal fix for all users. But it most likely should fix the problem for E/App

**Comment by Julesssss** [comment]
> Can't we just add a similar ResizeTransformation class to the expo-image library like in https://github.com/DylanVann/react-native-fast-image/pull/1017 ?

That sounds good, but let's first see what Expo team says 👍

**Comment by Julesssss** [comment]
Expo have released expo-image version  `1.10.6`, which should resolve this exception with changes to the native Android canvas. 

[This PR](https://github.com/Expensify/App/pull/35888) bumps the `expo-image` library and resolves the issue, but I'm having unrelated issues trying to build the Android app...

**Comment by Julesssss** [comment]
The fix seemed to have not resolved our issue. We're in contact with the Expo team again

**Comment by Julesssss** [comment]
No update yet

**Comment by Julesssss** [comment]
Hey @chrispader, just wondering if you've heard anything else from Expo, or whether this conversation is taking place on a public GH repo?

**Comment by Julesssss** [comment]
Awaiting response from Expo and @chrispader

**Comment by Julesssss** [comment]
Asked for an update [here](https://expensify.slack.com/archives/C035J5C9FAP/p1710337880031109)

**Comment by Julesssss** [comment]
Fixed by https://github.com/Expensify/App/pull/38671

**Comment by chrispader** [comment]
Nice stuff! Sorry for not replying fast enough 🥲 I think this solution is valid, as long as `expo-image` takes care of the downsampling
