### ISSUE TITLE
[LOW] [Splits] [$500]  IOU - Error appears after login via IOU URL when using public account

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#34528]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.25-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition: User is logged in [https://staging.new.expensify.com/.](https://staging.new.expensify.com/) in public account
1. Create a IOU in a conversation 
2. Navigate to the IOU report (conversation)
3. Copy the URL
4. Log out of the app
5. Navigate to the IOU URL
6. Log in

## Expected Result:
You're redirected to the correct IOU report after login

## Actual Result:
Hmm it's not here page displayed in conversation history when using public account. User need to refresh page

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/c6cefe0b-7249-4f3a-93ef-fcc906f885bb

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~016573ea8e6bf934e1</li>
        <li>Upwork Job ID: 1746977953315536896</li>
        <li>Last Price Increase: 2024-02-05</li>
    </ul>
</details>

**Comment by jliexpensify** [comment]
@lanitochka17 I think there's an issue with GH not playing videos properly

**Comment by jliexpensify** [comment]
@lanitochka17 @hoangzinh I can't repro this on Staging v1.4.25-4. When I use a new Incognito window and use the IOU URL, it takes me to that exact IOU. Can you try repro-ing and share a video? Thanks!

**Comment by legendAhsan** [comment]
@jliexpensify, I'm able to reproduce this error on both staging [url](https://staging.new.expensify.com/) and on my local machine. 
You will able to reproduce when you go further down the requests or to single request url. I'm also trying to fix it on my side as well.

**Comment by jliexpensify** [comment]
@legendAhsan do you mind sharing a video and version number? Thanks in advance!

**Comment by jliexpensify** [comment]
Hi @hoangzinh - can you review the proposal above? Thanks!

**Comment by MonilBhavsar** [comment]
I'll take a look

**Comment by MonilBhavsar** [comment]
@hoangzinh I am catching up the issue. I want to clarify some things - 

Is the understanding correct that root cause of issue is the `OpenReport` command returns `lastUpdateID` when `clientLastReadTime` param is null?

The solution we're thinking is to make OpenReport not return `lastUpdateID`?

**Comment by MonilBhavsar** [comment]
> But why the API OpenReport only returns `lastUpdateID` when call it with `clientLastReadTime` is null

This is a good question. Figuring this out

**Comment by MonilBhavsar** [comment]
I think it's because if user is starting a new chat and `clientLastReadTime` is null, we want to push `lastReadTime` update to all clients and hence `lastUpdateID` is sent in that case.

**Comment by MonilBhavsar** [comment]
>  @MonilBhavsar to decide whether we fix this issue in FE or BE.?

Okay, let me figure this out. Looking...

**Comment by jliexpensify** [comment]
Hi @MonilBhavsar any thoughts yet?

**Comment by jliexpensify** [comment]
Not overdue, @MonilBhavsar - I think we're waiting for your input!

**Comment by MonilBhavsar** [comment]
Yes, it's on me. I'll be back with investigation

**Comment by MonilBhavsar** [comment]
@hoangzinh I have been trying to figure out the issue and fix. And I am not able to reproduce the issue lately. Could please retest and see if this is fixed or may be I am missing something.

**Comment by jliexpensify** [comment]
Bump @MonilBhavsar

**Comment by MonilBhavsar** [comment]
I'll circle back. Got into two fires yesterday

**Comment by MonilBhavsar** [comment]
That was with payer.
Here is the one with new report and from sender
https://drive.google.com/file/d/1mOjzcbcdoLN6Wn7M9omzlG-gNVlvBpAi/view?usp=sharing

**Comment by MonilBhavsar** [comment]
I can use a gmail account and try.

**Comment by MonilBhavsar** [comment]
I am not able to reproduce on public account also. I am voting to close
Recording: https://drive.google.com/file/d/1gLE0CNELvJ4cKEuwzFAmiQHaFh5nY5nx/view?usp=sharing

**Comment by jliexpensify** [comment]
Ok, closing - as we can't reliably reproduce. Job removed as well.

**Comment by garrettmknight** [comment]
Reopening based on @tienifr's linked issues.

**Comment by shahinyan11** [comment]
## Proposal
### Please re-state the problem that we are trying to solve in this issue.
Not found is shown when deeplinking to expense details
### What is the root cause of that problem?
The `OpenReport` endpoint is called before `OpenApp` and so when we receive the response, the `lastUpdateIDAppliedToClient` is missing, causing the updates to be saved in `Onyx` on [this](https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/libs/Middleware/SaveResponseInOnyx.ts#L45C9-L45C60) line instead of being applied. Then it turns out that during applying updates  the `lastUpdateID` and `lastUpdateIDAppliedToClient`  are equal [here](https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/libs/actions/OnyxUpdates.ts#L84C56-L84C107) which prevents  applying updates . Since I think it also can happen in other cases and not only for openReport I think we should fix globally

### What changes do you think we should make in order to solve the problem?
Us `<`  instead `<=` in [this](https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/libs/actions/OnyxUpdates.ts#L84C56-L84C107)  check. Because of this change, It is possible that sometimes we will overwrite the same data that already exists, but this will help us fix the problem
### What alternative solutions did you explore? (Optional) (edited) 
Always apply changes for specific endpoints . In this case for `OpenReport`. To do that we can change [this](https://github.com/Expensify/App/blob/9bfe961622d03de5ac8e18652bbb56dda5ed9f60/src/libs/actions/OnyxUpdates.ts#L84C56-L84C107) check with below code to  
```
(Number(lastUpdateID) <= lastUpdateIDAppliedToClient && request?.command !== "OpenReport")
```

As ay already said that it can be happen in other places we can create new constant  for request commands list during which we will still overwrite the data .  e.g `ALWAYS_APPLAYING_COMMANDS = [ 'OpenReport', ... ]` and use below option instead above one
```
(Number(lastUpdateID) <= lastUpdateIDAppliedToClient && !ALWAYS_APPLAYING_COMMANDS.includes(request?.command))
```

**Comment by s77rt** [comment]
@MonilBhavsar When you get a chance please check this comment as well https://github.com/Expensify/App/issues/37083#issuecomment-1974878308

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Not found page is shown when open transaction thread report after login

### What is the root cause of that problem?
Summary: The onyx data from the OpenReport request isn't applied because the data is considered outdated.

When we open (deeplink) a report after login, there are 2 requests are made, OpenApp and OpenReport. OpenApp is a read request, so both requests are run in parallel. When the OpenReport request finishes first, `OnyxUpdates.doesClientNeedToBeUpdated` will return true 

https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/Middleware/SaveResponseInOnyx.ts#L40-L45

because `lastUpdateIDAppliedToClient` doesn't exist yet, the OpenReport **response** is saved to `ONYX_UPDATES_FROM_SERVER`.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdates.ts#L136-L139

_if OpenApp finishes first, this issue won't happen_

This will trigger a ReconnectApp request.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdateManager.ts#L59-L75

ReconnectApp will return a `lastUpdateID` and the response will be applied immediately (`requestsToIgnoreLastUpdateID` contains ReconnectApp & OpenApp)
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/Middleware/SaveResponseInOnyx.ts#L40-L42

After it's done, the saved OpenReport response is processed.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdateManager.ts#L87-L88

However, the OpenReport `lastUpdateID` is smaller than the `lastUpdateIDAppliedToClient` (that is updated from ReconnectApp `lastUpdateID`)
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/OnyxUpdates.ts#L81-L85

so the response data is ignored.

### What changes do you think we should make in order to solve the problem?

I think ideally we should wait for the OpenApp request to be finished first before doing the OpenReport request because ReconnectApp doesn't return all report that a user has.

To achieve that, first we need to change the OpenApp API from READ to WRITE, just like [we did for ReconnectApp](https://github.com/Expensify/App/pull/12125), so it's processed sequentially.

However, this isn't enough because OpenApp is called after a promise and onyx connection which delays the call.
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L210-L216
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L149-L158 

To solve this, we can follow a similar pattern of the promise here
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L80-L87

```
let resolveIsOpenAppCalledPromise: () => void;
const isOpenAppCalled = new Promise<void>((resolve) => {
    resolveIsOpenAppCalledPromise = resolve;
});

function waitForOpenApp() {
    return isOpenAppCalled;
}
```

Then, we will resolve the promise once the OpenApp/ReconnectApp api is pushed to the queue
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L214-L215
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/App.ts#L242-L243

_why ReconnectApp too? because [ReconnectApp will be called instead of OpenApp if we already logged in previously](https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/Navigation/AppNavigator/AuthScreens.tsx#L194-L198)_

Or we can resolve the promise immediately when the `ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT` exists.

```
Onyx.connect({
    key: ONYXKEYS.ONYX_UPDATES_LAST_UPDATE_ID_APPLIED_TO_CLIENT,
    callback: (val) => {
        if (val) resolveIsOpenAppCalledPromise();
    },
});
```

Then, we will wait for the promise here:
https://github.com/Expensify/App/blob/4a885f596547a16893ae40ebabcff41c82416453/src/libs/actions/Report.ts#L724-L727

```
App.waitForOpenApp(() => // open report request)
```

**Comment by MonilBhavsar** [comment]
@s77rt https://github.com/Expensify/App/issues/37083#issuecomment-1974878308

Because as you mentioned OpenReport handles two functionalities - 
1. For an old report, returns report data
2. If it is a new report, creates a new report and then returns report data

In case of 2, it is a WRITE command

**Comment by s77rt** [comment]
@MonilBhavsar Right, that all make sense but what I'm trying to say is that we are dealing with case 1 (reading an existing report) yet it's treated as case 2 (treated as WRITE command instead of READ command)

**Comment by MonilBhavsar** [comment]
Can you please specify what does this mean and why you think it is treated as WRITE in first case.
> treated as WRITE command instead of READ command

Not being able to reproduce, there are certain theories revolving around that I am trying to connect.

**Comment by MonilBhavsar** [comment]
> to confirm again if it's the correct expected behavior logic on BE.

Yes, it works like this. If it's a new chat or client's `clientLastReadTime` is updated than that of client, we send a lastReadTime update and may be that is setting `lastUpdateID` in those cases.

However, as I mentioned, I am not able to confirm this theory as I cannot reproduce the issue

**Comment by jliexpensify** [comment]
Bump @MonilBhavsar - do you feel like we need to pull anyone else in here?

**Comment by MonilBhavsar** [comment]
I tried reproducing issue again but with no dice 

Recording: https://drive.google.com/file/d/1rXIe9QjPJEhoRhpyGagh8km9QrvtmPRQ/view?usp=sharing

I think we can first get proper reproduction steps and then we can post in bug-zero or echat and ask for help if they anyone can reproduce. 
cc @jliexpensify @hoangzinh @s77rt

**Comment by s77rt** [comment]
Still able to reproduce. Need 2 accounts (userA, userB), sign in only as userA
1. userA: Make money request to userB under **new** IOU (if you have an old iou, complete/delete all the money requests)
2. userA: Copy the money request link
3. userB: Paste the link and login


https://github.com/Expensify/App/assets/16493223/f70dc5b6-fab9-4f8c-86aa-aa47a726ae53

**Comment by jliexpensify** [comment]
Just a heads up @MonilBhavsar @hoangzinh - I am headed OOO from the 21st to 31st, but I'll keep this assigned to myself as we're not close to a solution yet.

**Comment by MonilBhavsar** [comment]
These steps worked, thanks!

The original steps is missing that report has to be opened as payer or user B

**Comment by MonilBhavsar** [comment]
I've got a draft PR to fix this from server side.
In this case, when user B opens the new report directly through URL, `clientLastReadTime` argument is passed as null for OpenReport. OpenReport, sends back the `lastReadTime` as null in an onyx update that I think is unnecessary and can be skipped. I'll do some testing around it and submit it for review.

**Comment by MonilBhavsar** [comment]
Internal PR is deployed to staging. So issue should be fixed on staging when using staging server

**Comment by MonilBhavsar** [comment]
They ran QA when internal PR was deployed. And issue is now fixed on production too. So I think we can close this now?

**Comment by s77rt** [comment]
I'm still able to reproduce


https://github.com/Expensify/App/assets/16493223/0c2c6a5d-8516-4ed1-a8fd-888e63425c77

**Comment by jliexpensify** [comment]
Bump @MonilBhavsar - looks like the issue wasn't fixed :(

**Comment by jliexpensify** [comment]
Waiting on @MonilBhavsar for this one!

**Comment by jliexpensify** [comment]
@MonilBhavsar bumping you here - looks like the issue wasn't fixed.

**Comment by jliexpensify** [comment]
I think we're waiting on @MonilBhavsar?

**Comment by jliexpensify** [comment]
Sure thing, I dropped the retest label.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Third week)

**Comment by jliexpensify** [comment]
@MonilBhavsar @hoangzinh I think we can close this right?

**Comment by MonilBhavsar** [comment]
Yes, we can close this 👍
