### ISSUE TITLE
[HOLD for payment 2024-04-15] [$500] Expense - Item in report list is not highlighted and list cannot be navigated with keyboard

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#35843]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4-36.1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

**Issue found when executing PR** https://github.com/Expensify/App/pull/35770
## Action Performed:
recondition:
- User is an employee of Collect workspace
- The Collect workspace has dropdown field set up in "Report and Invoice Fields" on Old Dot
1. Go to workspace chat
2. Create a request
3. Go to expense report
4. Click on the report field with the selection list set up from Old Dot
5. Select an item
6. Click on the field
7. Use keyboard to navigate through the list

## Expected Result:
In Step 6, the selected item is highlighted
In Step 7, the list can be navigated with keyboard

## Actual Result:
In Step 6, the selected item is not highlighted
In Step 7, the list cannot be navigated with keyboard

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/9870c3fc-fa67-4236-9b48-f83acd0d34ae

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~013f9bedd40db86a4a</li>
        <li>Upwork Job ID: 1757818279097016320</li>
        <li>Last Price Increase: 2024-02-14</li>
<li>Automatic offers: </li>
<ul>
<li>ZhenjaHorbach | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #wave6
CC @greg-schroeder

**Comment by marcaaron** [comment]
cc @s77rt since it's linked to your PR

**Comment by marcaaron** [comment]
Interesting, but doesn't quite explain where the regression has happened. We implemented this feature [here](https://github.com/Expensify/App/pull/34157).

**Comment by s77rt** [comment]
I don't think this is a regression nor a deploy blocker. This bug existed before and should be handled just like any other bug. Using `indexOffset` is the correct solution.

**Comment by adelekennedy** [comment]
@lanitochka17 can you reproduce this still? I think @marcaaron had a question [here](https://github.com/Expensify/App/issues/35843#issuecomment-1927992038) on reproducing in prod

**Comment by lanitochka17** [comment]
Issue is still reproducible in the latest build 1.4.39-8


https://github.com/Expensify/App/assets/78819774/90595a94-cd29-4d31-8469-6f10e7e123be

**Comment by adelekennedy** [comment]
this doesn't seem to fit under any wave or vip projects but seems like something that should be solved - making external for proposals

**Comment by mananjadhav** [comment]
@ZhenjaHorbach's [proposal](https://github.com/Expensify/App/issues/35843#issuecomment-1944294382) looks good.

🎀 👀 🎀 C+ reviewed.

**Comment by cead22** [comment]
@mananjadhav @ZhenjaHorbach would it make sense to find a way to enforce that `indexOffset` is always passed in the `sections` passed to `OptionsSelector`?

**Comment by cead22** [comment]
> We can simply add an indexOffset inside BaseOptionsSelector for each section automatically

If we can do that for every case, this sounds like a better solution.

If there are cases where we need the knowledge of the parent components to set indexOffset, perhaps we can throw an error or log a warning whenever we pass sections without indexOffset

What are the cases that don't need indexOffset?

**Comment by cead22** [comment]
Awesome! @mananjadhav what do you think?

**Comment by mananjadhav** [comment]
Yeah @cead22 and @ZhenjaHorbach, if we're able to add this to `BaseOptionsSelector` then that would work for all the cases. We can test out all places where it's being used.

**Comment by mananjadhav** [comment]
I was unwell past few days, I'll get to this by tomorrow.

**Comment by adelekennedy** [comment]
**Payouts due:**

- [ ] Contributor: $500 @ZhenjaHorbach (UpWork)
- [ ] Contributor+: $500 @mananjadhav (NewDot)

Upwork job is [here](https://www.upwork.com/ab/applicants/1757818279097016320/hired).

**Comment by mananjadhav** [comment]
I couldn't trace the offending PR for this one. But with the refactor of the indexOffset I don't think we need a regression test for this one. The change is generic and the other tests for keyboard will take care of it.

**Comment by JmillsExpensify** [comment]
$500 approved for @mananjadhav
