### ISSUE TITLE
[$500] [MEDIUM] Room - Invited member can see Concierge invite message in room preview in LHN

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#36080]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.38-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause - Internal Team
**Slack conversation:**

## Action Performed:
Precondition:
- Admin and member are in the same workspace
1. [Admin] Create a room
2. [Admin] Go to the room and invite User B via @mention
3. [Admin] Click Invite them on the Concierge whisper
4. [Member] Go to search list and click on the invited room
5. [Member] Note that in room preview in LHN, it shows Concierge whisper message

## Expected Result:
For the room member, Concierge whisper message "Heads up, x isn't a member of this room" will not be visible from the room preview in LHN

## Actual Result:
For the room member, Concierge whisper message "Heads up, x isn't a member of this room" is visible from the room preview in LHN

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/29eb6911-5087-4f5d-875f-8bc577f622a8

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01e1174cfa6f1ec125</li>
        <li>Upwork Job ID: 1755340073303707648</li>
        <li>Last Price Increase: 2024-02-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @cristipaval</details>

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp
CC @quinthar

**Comment by FitseTLT** [comment]
BE issue

**Comment by cristipaval** [comment]
Assigned myself to this one as per [this](https://expensify.slack.com/archives/C049HHMV9SM/p1707429431205069) Slack discussion

**Comment by cristipaval** [comment]
^ Auth PR with the fix is up

**Comment by cristipaval** [comment]
PR still in review.

**Comment by jasperhuangg** [comment]
I believe this issue has been fixed already!

**Comment by jasperhuangg** [comment]
@DylanDylann can you help us retest to see if it's still happening?

**Comment by jasperhuangg** [comment]
I believe this issue is going to be fixed by https://github.com/Expensify/Auth/pull/10111

**Comment by jasperhuangg** [comment]
I'll bump here when that PR is deployed so we can retest–assigning myself to keep it in my K2

**Comment by cristipaval** [comment]
@jasperhuangg your PR is deployed and the issue is still occurring

<img width="1194" alt="Screenshot 2024-03-25 at 21 08 44" src="https://github.com/Expensify/App/assets/18078393/9f0da9fa-52e1-4d4f-9bb7-2f2eb34bafe0">

**Comment by jasperhuangg** [comment]
Oh interesting, did you use the steps in the OP?

I can investigate this today, thanks for the bump

**Comment by cristipaval** [comment]
yes, after clicking on the *Invite* button, the whisper disappeared from the chat page, but it's still present in the LHN

**Comment by jasperhuangg** [comment]
@cristipaval I can't seem to reproduce this myself on production. Can you let me know the steps you used specifically to reproduce this?

I'm going to go ahead and close this for now, if you're able to reproduce and provide steps feel free to reopen!

https://github.com/Expensify/App/assets/31285285/be90a779-fc5d-4f07-8796-ff41f883de90



<img width="1727" alt="Screenshot 2024-03-26 at 4 58 57 PM" src="https://github.com/Expensify/App/assets/31285285/35a69230-bf87-4213-9030-a62ae62bdf0f">
