### ISSUE TITLE
[$500] Domain name is not dropped when sending text with user mention from same domain

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#36347]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.40-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:** 

## Action Performed:
 1.Go to staging.new.expensify.com
2. Go to any chat.
3. Send a message with mention of another user from the same private domain.

## Expected Result:
The domain name is dropped because the user mention is from same domain.

## Actual Result:
It shows domain name at the end of the mention in the message.

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/5300bd70-1ee3-4fc4-84d7-2e6e5d242eae

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0190f9efc7bd55b768</li>
        <li>Upwork Job ID: 1757079921886003200</li>
        <li>Last Price Increase: 2024-02-12</li>
    </ul>
</details>

**Comment by allroundexperts** [comment]
Not sure if this is a deploy blocker. It seems to me that backend changes caused this issue. This should be fixed once https://github.com/Expensify/App/issues/35532 gets resolved.

**Comment by Beamanator** [comment]
Great find @allroundexperts , I'll bring this to slack but 99% sure this should be a blocker

**Comment by NikkiWines** [comment]
https://github.com/Expensify/App/issues/35532 is a separate issue for handling specifically the search and mention auto-fill functionality. If the domain name is not dropped from the mention itself (after sending) then there's been a regression since that functionality was added in [this PR](https://github.com/Expensify/App/pull/34013) - associated issue [here](https://github.com/Expensify/App/pull/34013)

**Comment by isabelastisser** [comment]
@tylerkaraszewski @allroundexperts, was this reverted, and can it be closed?

**Comment by NikkiWines** [comment]
No, mentions are still not shortened. I've asked if we can re-introduce the original logic from [this PR](https://github.com/Expensify/App/pull/34013/) as part of handling [this issue](https://github.com/Expensify/App/issues/35532) since it's also tied to shortened mentions. 

If the contributor working on that issue agrees, then we can close this issue out in favor of that one. If not, then we can handle re-implementing shortened mentions here

**Comment by isabelastisser** [comment]
@allroundexperts, please follow up on Nikki's comment above. Thanks!

**Comment by allroundexperts** [comment]
Hi @isabelastisser!
@tienifr should be able to handle this case in his PR. @tienifr please confirm and then we can close this one.

**Comment by ruben-rebelo** [comment]
I'll take a look at this ASAP.
Sorry for the late reply

**Comment by isabelastisser** [comment]
Thanks @ruben-rebelo. Please provide an update when you have a chance.

**Comment by isabelastisser** [comment]
Great, thanks @ruben-rebelo!

**Comment by puneetlath** [comment]
It looks like the shortened mentions don't get rendered via the live markdown preview. Is that a bug from this PR or something we just haven't implemented yet? 
![IMG_19DE5EBD41FB-1](https://github.com/Expensify/App/assets/1371996/0304e8a7-8a14-4b5f-97ea-324bb00bec83)

**Comment by NikkiWines** [comment]
This should've gone live as of the changes implemented in https://github.com/Expensify/App/pull/36697

**Comment by puneetlath** [comment]
Ah ok, I created an issue for it here: https://github.com/Expensify/App/issues/38025
