### ISSUE TITLE
[$500] Chat - Chat is not scrolled to the new message on a newly created WS chat after whisper message

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#38855]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.56-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Create a new workspace as account A and invite account B
2. As account B open the workspace chat of the newly created WS on step 1
3. Note the whisper message and send a message after the whisper message

## Expected Result:
The chat should scroll down to the new sent message

## Actual Result:
Chat page does not scroll to the bottom to the new message sent after the whisper message

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/6629999b-5024-4d7c-acab-4465ff9a0bf3

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0195afebb1a07596ef</li>
        <li>Upwork Job ID: 1772292798302457856</li>
        <li>Last Price Increase: 2024-04-09</li>
<li>Automatic offers: </li>
<ul>
<li>ikevin127 | Contributor | 0</li>
</ul></li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@robertjchen  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by robertjchen** [comment]
Yep, this can be handled as an External task 👍

**Comment by ikevin127** [comment]
# Proposal

### Please re-state the problem that we are trying to solve in this issue

Chat is not scrolled to the new message on a newly created WS chat after whisper message.

### What is the root cause of that problem?

The root cause of this issue comes from the [`scrollToBottomForCurrentUserAction`](https://github.com/Expensify/App/blob/ee5ab95f2c893738fb48756a9002e9d9dadd9a31/src/pages/home/report/ReportActionsList.tsx#L321-L331) function where in our case `!hasNewestReportAction` is true when we post the first comment on a newly created WS chat **after** the whisper message report action.

The [`hasNewestReportAction`](https://github.com/Expensify/App/blob/ee5ab95f2c893738fb48756a9002e9d9dadd9a31/src/pages/home/report/ReportActionsList.tsx#L199) variable is checking it the first (`sortedReportActions?.[0]`) report action date is equal to `report.lastVisibleActionCreated` date, which in our case is false when we post the first comment since the whisper report action is the first report action -> hence `hasNewestReportAction` will be false and the scrolling is prevented because of [this](https://github.com/Expensify/App/blob/ee5ab95f2c893738fb48756a9002e9d9dadd9a31/src/pages/home/report/ReportActionsList.tsx#L325-L327) if condition returning early.

### What changes do you think we should make in order to solve the problem?

Change the second part of the if condition from `|| !hasNewestReportAction` to:

`|| (!hasNewestReportAction && !ReportActionsUtils.isWhisperAction(sortedReportActions?.[0]))`

Adding the `!ReportActionsUtils.isWhisperAction(sortedReportActions?.[0]))` to make sure that we return early only if `!hasNewestReportAction` and the first report action is **NOT** the whisper comment, otherwise when the user posts their first comment -> we scroll.

### Videos (before / after)

<details>
<summary>Android: mWeb</summary>

| Before | After |
| ------------- | ------------- |
| <video src="https://github.com/Expensify/App/assets/56457735/a80cb9c5-6aa7-4a13-9669-e679a7f27185"> | <video src="https://github.com/Expensify/App/assets/56457735/9c22218e-e4b5-44c2-b685-cd50d718eea7"> |

</details>

**Comment by ikevin127** [comment]
## Updated [proposal](https://github.com/Expensify/App/issues/38855#issuecomment-2033012936)
- extended solution to cover for existing bug related to scrolling on WebKit engine browsers

**Comment by robertjchen** [comment]
Thanks for the proposal! @thesahindia what do you think of the above? 🙏

**Comment by ikevin127** [comment]
👋 Well, there's other ways to perform `deferred execution` by wrapping the `scrollToOffset` call. We can use any of the following as alternatives to `setTimeout`:
- `requestAnimationFrame`
or
- `Promise.resolve().then`

The gist of it is they all act in the same way, so up to you guys which one we want to go with 🙌
They all solve the WebKit based-browsers edge case mentioned in the proposal above!

cc @thesahindia @robertjchen

**Comment by ikevin127** [comment]
@robertjchen Cool, we can safely go with `requestAnimationFrame` then since it defers execution exactly like `setTimeout` therefore fixing the edge case mentioned in https://github.com/Expensify/App/issues/38855#issuecomment-2045900802.

@thesahindia Are you ok with this approach ? Let us know!

**Comment by robertjchen** [comment]
Alrighty, let's do it!

**Comment by ikevin127** [comment]
I'll have a PR ready for review in about 3 hours.

**Comment by ikevin127** [comment]
🎉 PR https://github.com/Expensify/App/pull/40286 ready for review!

**Comment by ikevin127** [comment]
Woah, wasn't even merged and already has a regression :trollface:

**Comment by ikevin127** [comment]
I think that based on the PR being deployed on production 19h ago (ref https://github.com/Expensify/App/pull/40286#issuecomment-2073664648), this shoud be put on Hold for payment [2024-04-30].

**Comment by ikevin127** [comment]
The PR from here caused a regression:
- https://github.com/Expensify/App/issues/40911

Apparently `requestAnimationFrame` is not exactly the same as `setTimeout` with 0 delay when it comes to deferred execution.

**Comment by ikevin127** [comment]
@robertjchen Can you please assign somebody from `Bug` to handle this when due ?

Also, given that the PR caused a regression and it was suggested we revert it, I'm assuming we'll get the -50% penalty here. If so, this will be due on 2024-05-02 ?

**Comment by ikevin127** [comment]
@parasharrajat The cause is clear:
- we had to choose an alternative deferred execution method [here](https://github.com/Expensify/App/issues/38855#issuecomment-2046028474) and we went with `requestAnimationFrame` since 0 delay `setTimeout` was not ideal and obviously we did not test it thoroughly on both PR author and reviewer sides -> resulting in regression issue: https://github.com/Expensify/App/issues/40911

Keep in mind:
- this issue was and is still fixed by the PR
- the fix caused a regression in another part of the app's functionality

> [!note]
> A follow-up PR that would keep this issue fixed and also eliminate the regression issue https://github.com/Expensify/App/issues/40911 would be to replace deferred execution method `requestAnimationFrame` with 0 delay `setTimeout`.
>
> Alternative would be revert this PR which means we would still have this issue, just to not have the regression anymore.

**Comment by ikevin127** [comment]
This is an issue which had a PR that fixed it, PR which caused a regression in another part of the app -> this means that there will be a 50% compensation penalty for both PR author and reviewer, regardless of the follow-up being a PR revert or not. But yeah, let's wait and see!

**Comment by ikevin127** [comment]
> regardless of the follow-up being a PR revert or not

This was my concern, given I did not have a PR reverted before - I wasn't sure whether there's gonna be any compensation in this case.

##

Additionally, the important part of my solution is good and works as expected (checking for whisper message in the scrolling function), the deferred execution part (problematic) was only added to have the scrolling work on iOS: mWeb as well (caught by me during testing).

Otherwise this problematic part is not needed on other platforms in order for the good part of the solution to work as expected.

So as you can see, this is a bit more complicated than simply reverting and looking for other proposals specifically for the part scrolling not being triggered on iOS: mWeb.

**Comment by anmurali** [comment]
Hmmm so this issue is effectively not fixed since the PR that fixed it caused a regression and therefore had to be reverted. Is that right? If yes, I don't think we would pay anyone anything yet.

**Comment by robertjchen** [comment]
Thanks for the efforts here, in that case I think we can consolidate to the issue here: https://github.com/Expensify/App/issues/40724

**Comment by robertjchen** [comment]
Ah, my mistake- I may have misread. Let's keep this open for now.

**Comment by robertjchen** [comment]
Awaiting proposals

**Comment by tsa321** [comment]
## Proposals

Cross posting my [proposal](https://github.com/Expensify/App/issues/40724#issuecomment-2106322218) from other issue, I think this issue has same RCA.

**Comment by robertjchen** [comment]
Pending solution in https://github.com/Expensify/App/issues/40724#issuecomment-2106322218

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by robertjchen** [comment]
Nice, looks like the change was deployed there. Given that it's unreproducible here, I'll close this out in favor of the one there 👍 https://github.com/Expensify/App/issues/40724#issuecomment-2106322218

**Comment by mallenexpensify** [comment]
@luacmartins and @mountiny.  @parasharrajat has requested payment of 50% for this issue because they worked on [the PR. ](https://github.com/Expensify/App/pull/40286)
> @[luacmartins](https://github.com/luacmartins) luacmartins requested review from [parasharrajat](https://github.com/parasharrajat)

I'm going to pay later this week, assuming neither of you disagree.

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat
