### ISSUE TITLE
[$250] Chat - Space Not Added After Emoji Selection in Composer

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#39822]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.61-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Email or phone of affected tester (no customers):** abebemiherat@gmail.com
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
1, Navigate to any chat.
2, Add emojis in the composer.

## Expected Result:
Upon selecting emojis, notice that a space is not added after the emojis.

## Actual Result:
After selecting emojis in the composer, a space should be added after each emoji.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [x] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/e3dd07eb-c84e-476b-8787-3df868206497

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~018b8b77d54dddade1</li>
        <li>Upwork Job ID: 1777400833001480193</li>
        <li>Last Price Increase: 2024-04-08</li>
    </ul>
</details>

**Comment by izarutskaya** [comment]
@garrettmknight I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by tomekzaw** [comment]
This might be related to Live Markdown Preview.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #vip-vsb.

**Comment by Julesssss** [comment]
> This might be related to Live Markdown Preview.

Yeah, or maybe also the emoji picker/keyboard issue. if so I'd much rather raise those as non-blocking issues and not revert these major PRs

**Comment by garrettmknight** [comment]
I don't think this is a deploy blocker.

**Comment by ikevin127** [comment]
> [!note]
> I remember the exact same issue was opened 7 months ago: [Chat - Space is not added after an emoji is selected](https://github.com/Expensify/App/issues/26709)

But in this case:
> This might be related to Live Markdown Preview.

I think @tomekzaw might be right since there were no other major changes to the Composer recently, therefore that would be the first place I'd look at for the root cause.

Anyway the issue mentioned from 7 months ago can definitely help give more context and check some other possible root causes off the list.

**Comment by tomekzaw** [comment]
It seems like this bug has been fixed in the meantime as I cannot reproduce it on current prod:

https://github.com/Expensify/App/assets/20516055/a884dc06-7235-4a94-aa4e-283417708810

There was an issue with text cursor placed incorrectly (one character earlier than it should be) when typing &ndash; perhaps this bug was another symptom?

**Comment by ikevin127** [comment]
From the OP video it looks like it wasn't just the cursor position, since there's clearly no spaces between the 3 emojis:
<img width="233" alt="Screenshot 2024-04-09 at 00 29 51" src="https://github.com/Expensify/App/assets/56457735/61761bae-6889-4bb1-8124-acd5b31cf189">

Just pulled latest main and **I confirm that the issue is still present** (consistently):

<details>
<summary>MacOS: Chrome / Safari</summary>


https://github.com/Expensify/App/assets/56457735/c57575f0-4066-4088-9967-d83e3f9ea88e



</details>

<details>
<summary>iOS: mWeb Safari</summary>


https://github.com/Expensify/App/assets/56457735/0f223563-4b2f-449d-a65f-2be1f24c1186



</details>

I looked at what's actually happening frame-by-frame and I noticed that on the **first** selected emoji there's actually an empty space and also a newline but shortly after selection we can notice how the Live Markdown Preview (most likely, not sure though) is formatting and removing the space and newline, leaving us with the emoji without a space (cursor right after it):

<details>
<summary>MacOS: Chrome / Safari (frame-by-frame)</summary>

https://github.com/Expensify/App/assets/56457735/bc53b64d-0fb5-410a-ad0c-ebb54566a0d9




</details>

And weirdly, it looks like the space of the first emoji is maintained on **iOS: mWeb Safari** (see video above) **as long as the user adds emojis without focusing the Composer**, but not for the subsequent emojis. The space is **not** maintained for the first emoji if the **Composer is focused (cursor visible)** when adding the subsequent emojis.

cc @tomekzaw Any thoughts ?

**Comment by tomekzaw** [comment]
Indeed, the bug is reproducible on current main (8af9eae36c) but not on production 🤔

**Comment by Skalakid** [comment]
I think this issue has been already fixed in https://github.com/Expensify/App/pull/39934. I can't reproduce it on the lates main now.

https://github.com/Expensify/App/assets/39538890/eed35fce-98d9-4eef-b79d-2c318b7004cb

https://github.com/Expensify/App/assets/39538890/fc7ee020-d68d-47c5-8d3d-763e44060fc0

**Comment by garrettmknight** [comment]
Fixed on staging and prod, closing.
