### ISSUE TITLE
[$250] Comments after threaded comment are gone after returning to parent

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#40644]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v1.4.63-13
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @aldo-expensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1713557851562149

## Action Performed:
1. Join public room, for example: https://staging.new.expensify.com/r/6776919265133947
2. Find a threaded comment that is not the last comment in the chat and click it to open the thread
3. Click on the header to come back to the parent chat
4. Notice that the thread comment is highlighted and you can't scroll down anymore

## Expected Result: 
I would have expected to be able to scroll down again in the parent report without having to click "New Messages"

## Actual Result: 
Can't scroll down, the threaded comment is now the last comment in the parent chat, and I have to click in "New Messages" for it to load more comments and scroll down.

## Workaround:
unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

https://github.com/Expensify/App/assets/38435837/a334938a-0837-4a53-9f3f-bd6c7d11e7ae

https://github.com/Expensify/App/assets/38435837/9bae8a8c-540a-4b85-af46-5ca5aa069229

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0155f72908fd93dc77</li>
        <li>Upwork Job ID: 1782728194457100288</li>
        <li>Last Price Increase: 2024-04-23</li>
    </ul>
</details>

**Comment by sonialiap** [comment]
I can replicate, moving to external

**Comment by ahmedGaber93** [comment]
Not overdue, still waiting for proposals.

**Comment by jacobkim9881** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
In public room, going back from thread makes newer chats missed.

### What is the root cause of that problem?
From report actions data whisper chatting's `previousReportActionID` caused the problem. 

https://github.com/Expensify/App/blob/db9e01cc302df7f2b3dd53a99c1082404676aedb/src/libs/ReportActionsUtils.ts#L343-L344

Above condition filters chained report actions in `getContinuousReportActionChain`. If a report action didn't meet the condition, then left chats are filtered out(So you can see the problem doesn't occurred after not using `getContinuousReportActionChain` function). 

In a chat room each message has `previousReportActionID` that makes clear which one is previous message. But in a public room there are whispers that shows only to you. The whispers hasn't meet the condition above, so left chats are filtered out by the condition.

<details>
  <summary>These have report actions that makes problems. These have keys 'whispredTo' and have problematic `reportActionID` for the condition above.</summary>


```js

                "9115208222621878844": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Zach Greenwald (EXFY Product Manager)"
                        }
                    ],
                    "actorAccountID": 2746397,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.<br \/><br \/>If we find anything considered &quot;off-topic&quot;, it will be removed. <br \/><br \/>Thanks!",
                            "text": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.\n\nIf we find anything considered \"off-topic\", it will be removed. \n\nThanks!",
                            "isEdited": false,

	//* all whispers have this key *//
                            "whisperedTo": [
                                9847009
                            ],
	//* all whispers have this key *//

                            "isDeletedParentAction": false,
                            "deleted": "",
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.<br \/><br \/>If we find anything considered &quot;off-topic&quot;, it will be removed. <br \/><br \/>Thanks!",
                        "lastModified": "2024-04-03 16:31:27.991",
                        "type": "automated",
                        "whisperedTo": [
                            9847009
                        ]
                    },
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/59e3197139caf327d7d95527215285cf1f2a325d_128.jpeg",
                    "created": "2024-04-03 16:31:27.991",
                    "timestamp": 1712161887,
                    "reportActionTimestamp": 1712161887991,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,
                    "reportActionID": "9115208222621878844",
                    "previousReportActionID": "1707092031100627785",
                    "lastModified": "2024-04-03 16:31:27.991",
                    "whisperedToAccountIDs": [
                        9847009
                    ]
                },
                "2078382787109828944": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "concierge@expensify.com"
                        }
                    ],
                    "actorAccountID": 8392101,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "We have detected that you have sent an unsubscribe message into the chat. We have automatically muted this chat for you. If you would like to unmute this chat, please go into the chat settings and update your notification preferences.",
                            "text": "We have detected that you have sent an unsubscribe message into the chat. We have automatically muted this chat for you. If you would like to unmute this chat, please go into the chat settings and update your notification preferences.",
                            "isEdited": false,
                            "whisperedTo": [
                                3037571
                            ],
                            "isDeletedParentAction": false,
                            "deleted": "",
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "We have detected that you have sent an unsubscribe message into the chat. We have automatically muted this chat for you. If you would like to unmute this chat, please go into the chat settings and update your notification preferences.",
                        "lastModified": "2024-04-03 16:07:07.726",
                        "whisperedTo": [
                            3037571
                        ]
                    },
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/894b50e60056c966d12216005fbcacec8ce5a2c0.png",
                    "created": "2024-04-03 16:07:07.726",
                    "timestamp": 1712160427,
                    "reportActionTimestamp": 1712160427726,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,

		//* This key cause the problem *//
                    "reportActionID": "2078382787109828944",
		//* This key cause the problem *//

		//* This key points the reportActionID of the thread you entered *//
                    "previousReportActionID": "6314439357740094412",
		//* This key points the reportActionID of the thread you entered *//


                    "lastModified": "2024-04-03 16:07:07.726",
                    "whisperedToAccountIDs": [
                        3037571
                    ]
                },
                "8603160241470088492": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Zach Greenwald (EXFY Product Manager)"
                        }
                    ],
                    "actorAccountID": 2746397,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.<br \/><br \/>If we find anything considered &quot;off-topic&quot;, it will be removed. <br \/><br \/>Thanks!",
                            "text": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.\n\nIf we find anything considered \"off-topic\", it will be removed. \n\nThanks!",
                            "isEdited": false,
                            "whisperedTo": [
                                11310351
                            ],
                            "isDeletedParentAction": false,
                            "deleted": "",
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.<br \/><br \/>If we find anything considered &quot;off-topic&quot;, it will be removed. <br \/><br \/>Thanks!",
                        "lastModified": "2024-04-03 15:28:15.042",
                        "type": "automated",
                        "whisperedTo": [
                            11310351
                        ]
                    },
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/59e3197139caf327d7d95527215285cf1f2a325d_128.jpeg",
                    "created": "2024-04-03 15:28:15.042",
                    "timestamp": 1712158095,
                    "reportActionTimestamp": 1712158095042,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,
                    "reportActionID": "8603160241470088492",
                    "previousReportActionID": "1707092031100627785",
                    "lastModified": "2024-04-03 15:28:15.042",
                    "whisperedToAccountIDs": [
                        11310351
                    ]
                },
                "6314439357740094412": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "concierge@expensify.com"
                        }
                    ],
                    "actorAccountID": 8392101,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as your email address. If you'd like to add a different display name, open the Display Name page <a href=\"https:\/\/staging.new.expensify.com\/settings\/profile\/display-name\" target=\"_self\" rel=\"noreferrer noopener\">here<\/a>.",
                            "text": "Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as your email address. If you'd like to add a different display name, open the Display Name page here.",
                            "isEdited": false,
                            "whisperedTo": [
                                16568325
                            ],
                            "isDeletedParentAction": false,
                            "deleted": "",
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "Hi there! If you just want to lurk in this room, others won't know you're here. However, if you post, others in the room will see your display name as your email address. If you'd like to add a different display name, open the Display Name page <a href=\"https:\/\/staging.new.expensify.com\/settings\/profile\/display-name\" target=\"_self\" rel=\"noreferrer noopener\">here<\/a>.",
                        "lastModified": "2024-04-03 08:47:14.901",
                        "whisperedTo": [
                            16568325
                        ]
                    },
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/894b50e60056c966d12216005fbcacec8ce5a2c0.png",
                    "created": "2024-04-03 08:47:14.901",
                    "timestamp": 1712134034,
                    "reportActionTimestamp": 1712134034901,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,
                    "reportActionID": "6314439357740094412",
                    "previousReportActionID": "1707092031100627785",
                    "lastModified": "2024-04-03 08:47:14.901",
                    "whisperedToAccountIDs": [
                        16568325
                    ]
                },
                "7450946116911601677": {
                    "person": [
                        {
                            "type": "TEXT",
                            "style": "strong",
                            "text": "Zach Greenwald (EXFY Product Manager)"
                        }
                    ],
                    "actorAccountID": 2746397,
                    "message": [
                        {
                            "type": "COMMENT",
                            "html": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.<br \/><br \/>If we find anything considered &quot;off-topic&quot;, it will be removed. <br \/><br \/>Thanks!",
                            "text": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.\n\nIf we find anything considered \"off-topic\", it will be removed. \n\nThanks!",
                            "isEdited": false,
                            "whisperedTo": [
                                16568325
                            ],
                            "isDeletedParentAction": false,
                            "deleted": "",
                            "reactions": []
                        }
                    ],
                    "originalMessage": {
                        "html": "Welcome to #new-expensify-feedback! This public channel is for you to share positive or constructive feedback on your New Expensify experience directly with our product team. We want you to help make this awesome. For all technical support questions, please ask Concierge to assist.<br \/><br \/>If we find anything considered &quot;off-topic&quot;, it will be removed. <br \/><br \/>Thanks!",
                        "lastModified": "2024-04-03 08:47:14.901",
                        "type": "automated",
                        "whisperedTo": [
                            16568325
                        ]
                    },
                    "avatar": "https:\/\/d1wpcgnaa73g0y.cloudfront.net\/59e3197139caf327d7d95527215285cf1f2a325d_128.jpeg",
                    "created": "2024-04-03 08:47:14.901",
                    "timestamp": 1712134034,
                    "reportActionTimestamp": 1712134034901,
                    "automatic": false,
                    "actionName": "ADDCOMMENT",
                    "shouldShow": true,
                    "reportActionID": "7450946116911601677",
                    "previousReportActionID": "1707092031100627785",
                    "lastModified": "2024-04-03 08:47:14.901",
                    "whisperedToAccountIDs": [
                        16568325
                    ]
                },
```

</details>


### What changes do you think we should make in order to solve the problem?
We should add conditions to pass such whispers to show left chats. 

### What alternative solutions did you explore? (Optional)
1. On BE such unnecessary whispers should be filtered out. Whispers to other accounts is not needed for a user. Since any users can check other users whispers by checking network requests on debug console of a browser, these should not be responded to users.

2. We don't use `getContinuousReportActionChain` since 2 weeks ago `previousReportActionID` doesn't returns `0` from BE as a response. `getContinuousReportActionChain` doesn't function one of its functions for now.

3. Let it be since it only happens in public rooms. You can loads newer chats by clicking New messages button on the chat.

**Comment by roryabraham** [comment]
I think we need to fix this in the back-end.

**Comment by jacobkim9881** [comment]
@roryabraham My Pleasure ☺️ It should be fixed from BE first.

**Comment by sonialiap** [comment]
Looking for an internal engineer

**Comment by sonialiap** [comment]
posted in engineering for eyes https://expensify.slack.com/archives/C03SSAQ7P/p1715124561889129

**Comment by sonialiap** [comment]
No longer reproducible 🎉  I can scroll down

<img width="1146" alt="image" src="https://github.com/Expensify/App/assets/17131195/6bb566fd-daf5-4103-8be1-84a0ef67caa3">

**Comment by aldo-expensify** [comment]
hmm I can still reproduce some form of this, I see some messages below the highlighted one, but I can't scroll to the bottom of the conversation


Uploading Screen Recording 2024-05-14 at 3.47.02 PM.mov…

**Comment by sonialiap** [comment]
Ah darn, I can also repo. Seems like if you don't go far enough in history then you can't scroll down past the thread you clicked into

https://github.com/Expensify/App/assets/17131195/f5ef662c-1ae2-48e7-b4c0-f7b5ca4d1502

**Comment by sonialiap** [comment]
[Looking for internal volunteer](https://expensify.slack.com/archives/C066HJM2CAZ/p1716894587323139)

**Comment by sonialiap** [comment]
Bumped internal volunteer search thread

**Comment by roryabraham** [comment]
I'm not sure, but I suspect this may be fixed by https://github.com/Expensify/App/pull/41962

**Comment by sonialiap** [comment]
Putting this on hold for https://github.com/Expensify/App/pull/41962

**Comment by aldo-expensify** [comment]
I tested the PR https://github.com/Expensify/App/pull/41962 using the ad-hoc build https://41962.pr-testing.expensify.com/ and the problem is still there :(

**Comment by sonialiap** [comment]
Thanks for testing, Aldo! 

Since the issue persists after https://github.com/Expensify/App/pull/41962, taking it off hold and looking for proposals!

**Comment by sonialiap** [comment]
I just tested and it's still an issue. Asking in [slack](https://expensify.slack.com/archives/C05LX9D6E07/p1718716195362319?thread_ts=1717528339.776249&cid=C05LX9D6E07) for volunteers

**Comment by ahmedGaber93** [comment]
I am going to unassign me from this issue to focus on other issues, please reassign. Thanks!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by sonialiap** [comment]
I'm OOO Aug 19-30, adding leave buddy. 
Status: this may have been resolved by another issue. Waiting for the weekly re-tests to confirm if issue is resolved

**Comment by jliexpensify** [comment]
Thanks for the summary Sonia, I'll wait another week for the 2nd re-test.

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (Second week)

**Comment by jliexpensify** [comment]
Ok lets close this one!
