### ISSUE TITLE
[$250] [Held requests] Violation overrides hold in the dot separator on expense preview

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#41460]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.69-0
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @JmillsExpensify 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1714578430463419

## Action Performed:

1. Prerequisite: Create a Collect workspace as user B, require categories, invite user A
2. Create several expenses in the account for user B and submit them to the workspace. For one of the expenses don’t set a category
3. As user B, click into the report with user A’s expenses.
4. Tap on the expense that doesn’t have a category
5. Hold the expense
6. Navigate back to the report

## Expected Result:
The dot separator for the expense preview says Cash * Hold
## Actual Result:
The dot separator for the expense preview says Cash * Review required
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence
![CleanShot 2024-05-01 at 09 49 26@2x](https://github.com/Expensify/App/assets/38435837/c7fbe146-28b5-4743-8f4b-5914f3674836)

![CleanShot 2024-05-01 at 09 49 14@2x](https://github.com/Expensify/App/assets/38435837/2081b00a-2ac5-46b1-932a-17b471821d2e)

https://github.com/Expensify/App/assets/38435837/4fb68ab4-e1bf-451a-820b-2f83f2b30827

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~019469a51db3b3fcb0</li>
        <li>Upwork Job ID: 1787982464084987904</li>
        <li>Last Price Increase: 2024-06-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @c3024</details>

**Comment by strepanier03** [comment]
Thanks for the updates and applying project/status.

**Comment by strepanier03** [comment]
Setting external, missed the label last week. 🤦‍♀️

**Comment by c3024** [comment]
@strepanier03 Please hold this issue for #40153 as [this will likely be fixed in that PR](https://github.com/Expensify/App/issues/41460#issuecomment-2099657391).

**Comment by c3024** [comment]
On hold for #40153

**Comment by c3024** [comment]
On hold

**Comment by c3024** [comment]
On hold

**Comment by robertjchen** [comment]
@Krishna2323 Can you please confirm that the issue is still reproducible and if your proposal addresses it? Thanks!

**Comment by c3024** [comment]
@robertjchen This has been fixed and can be closed.

<img width="1433" alt="Screenshot 2024-06-10 at 8 23 49 PM" src="https://github.com/Expensify/App/assets/102477862/d0d3b611-be7f-4025-b09a-e3d014a350bf">

**Comment by robertjchen** [comment]
Thanks for the confirmation!
