### ISSUE TITLE
[$250] Chat - Unending skeleton is displayed on first time sign-up

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#42063]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.73-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to sign-up page
2. Sing-up with a new account
3. Open Self DM

## Expected Result:
Concierge and Self DM report should load

## Actual Result:
Unending skeleton is displayed on Concierge and Self DM report

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/a59a9c38-49d7-468d-93ba-939988ccb97e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01bf03f46c9583a214</li>
        <li>Upwork Job ID: 1790013644495663104</li>
        <li>Last Price Increase: 2024-05-13</li>
    </ul>
</details>

**Comment by lanitochka17** [comment]
@mountiny  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by lanitochka17** [comment]
We think that this bug might be related to #vip-vsp

**Comment by mountiny** [comment]
I could repro in staging

**Comment by mountiny** [comment]
@ishpaul777 Suggested that reverting https://github.com/Expensify/App/pull/41448/files fixes the issue. @ikevin127 are you available to handle the revert so we can CP the fix?

**Comment by ikevin127** [comment]
> reverting https://github.com/Expensify/App/pull/41448, solves the issue so i guess its the offending PR

@mountiny I checked the issue, it seems like the Concierge part is fixed by reverting. Not sure about the Self-DM part since on my side it does seem to work as expected, the only thing being that OpenReport takes a long time to be called.

There are 2 ways we can go about this:
1. Exclude concierge and self-dm reports from the original PR auto-scroll functionality. (see [diff](https://github.com/Expensify/App/compare/main...ikevin127:follow/35011))
2. Revert PR completely.

Both of these fix the issues reported in this deploy blocker.
Let me know which one should we go with and I'll open the PR right away!

**Comment by ikevin127** [comment]
Discussing this on C+ [Slack 🧵](https://expensify.slack.com/archives/C02NK2DQWUX/p1715609260869129).

**Comment by mountiny** [comment]
I cannot reliably reproduce this one really. Seems like its linked to staging servers being slower now and thats why it shows up as loading for a long time 
<img width="1623" alt="image" src="https://github.com/Expensify/App/assets/36083550/86cfbdc5-c0bd-47be-a509-55ecf0e49ee3">

Hence I dont think this must be a deploy blocker given this behaviour.

I will keep this open to see if there are any hints at App related changes

**Comment by mountiny** [comment]
I could still reproduce now and its really weird, I am on limited availability now so I will try to continue investigating when I can but adding the label again

**Comment by mountiny** [comment]
It works fine in production

**Comment by Beamanator** [comment]
I'm also noticing this problem, even after logging out / in in staging (on a very new account), `OpenReport` isn't getting called so I get an infinite skeleton :/ could it be because we're deploying Auth right now??

**Comment by Beamanator** [comment]
ooh everything loaded now

**Comment by Beamanator** [comment]
Hmm

![Screenshot 2024-05-14 at 12 25 37 PM](https://github.com/Expensify/App/assets/3885503/dc23bd26-5106-4c7d-b92b-93cee295eb0f)

**Comment by danieldoglas** [comment]
I think this is the cause: https://github.com/Expensify/App/issues/40044

**Comment by danieldoglas** [comment]
There's a PR to fix it https://github.com/Expensify/App/pull/42095

**Comment by Skakruk** [comment]
I also think it's not related to https://github.com/Expensify/App/issues/40044, since the page is not reloaded and `beforeunload` event can't be called.

**Comment by Beamanator** [comment]
Hmm I'm also not able to reproduce this on main main (dev) but I can reproduce this issue in staging on my main expensify account AND on a brand new account... `OpenReport` seems to never be called once `OpenApp` finishes - BUT other chats are loading in the LHN, and clicking on them does call `OpenReport` 🤷  so maybe this isn't a fire but definitely a blocker

**Comment by danieldoglas** [comment]
Interesting. Testing locally yesterday, I saw several logs with `[info] [Pusher] Received updates, but ignoring it since this is not the active client -`

Since we check for active client before doing requests, I noticed that my client was not executing any requests because of that. Iy could not be the case for you guys.

**Comment by mountiny** [comment]
I have been testing locally using staging branch and staging API and while it took a really long time to load, it did for both concierge and selfDM (might be my wifi though)

<img width="1752" alt="image" src="https://github.com/Expensify/App/assets/36083550/42110344-030f-4ed8-9b23-000713406569">

These seemed to be the logs with API requests that were made since signing in  (and then me switching to the selfDM)

```
[info] Finished API request in 473ms - {"command":"OpenReport","jsonCode":404,"requestID":"883c83568ee963cf-LHR"}
Log.ts:69 [info] Finished API request in 479ms - {"command":"OpenReport","jsonCode":404,"requestID":"883c83594b3f63cf-LHR"}
Log.ts:69 [info] Finished API request in 836ms - {"command":"OpenReport","jsonCode":404,"requestID":"883c835cb8c263cf-LHR"}
Log.ts:69 [info] Finished API request in 754ms - {"command":"BeginSignIn","jsonCode":200,"requestID":"883c9106283163cf-LHR"}
Log.ts:69 [info] Finished API request in 136085ms - {"command":"SigninUser","jsonCode":200,"requestID":"883c926e3ef763cf-LHR"}
Log.ts:69 [info] Finished API request in 30915ms - {"command":"OpenApp","jsonCode":200,"requestID":"883c95c66ed763cf-LHR"}
Log.ts:69 [info] Finished API request in 5725ms - {"command":"OpenApp","jsonCode":200,"requestID":"883c96850ad763cf-LHR"}
Log.ts:69 [info] Finished API request in 24867ms - {"command":"UpdateAutomaticTimezone","jsonCode":200,"requestID":"883c96aa7d2b63cf-LHR"}
Log.ts:69 [info] Finished API request in 18392ms - {"command":"UpdateAutomaticTimezone","jsonCode":200,"requestID":"883c9743fc7863cf-LHR"}
Log.ts:69 [info] Finished API request in 5164ms - {"command":"GetMissingOnyxMessages","jsonCode":200,"requestID":"883c97b72c0063cf-LHR"}
Log.ts:69 [info] Finished API request in 448ms - {"command":"AuthenticatePusher","jsonCode":500,"requestID":"883c97d80b5763cf-LHR"}
Log.ts:69 [info] Finished API request in 477ms - {"command":"AuthenticatePusher","jsonCode":500,"requestID":"883c97d81b6063cf-LHR"}
Log.ts:69 [info] Finished API request in 660ms - {"command":"OpenReport","jsonCode":200,"requestID":"883c97d79abe63cf-LHR"}
Log.ts:69 [info] Finished API request in 873ms - {"command":"OpenReport","jsonCode":200,"requestID":"883c97db8fb863cf-LHR"}
Log.ts:69 [info] Finished API request in 488ms - {"command":"AuthenticatePusher","jsonCode":500,"requestID":"883c9815a83b63cf-LHR"}
Log.ts:69 [info] Finished API request in 42896ms - {"command":"CompleteGuidedSetup","jsonCode":200,"requestID":"883c9812dc6c63cf-LHR"}
Log.ts:69 [info] Finished API request in 16589ms - {"command":"GetMissingOnyxMessages","jsonCode":200,"requestID":"883c991ecd5863cf-LHR"}
Log.ts:69 [info] Finished API request in 428ms - {"command":"OpenReport","jsonCode":200,"requestID":"883c9986788d63cf-LHR"}
Log.ts:69 [info] Finished API request in 1469ms - {"command":"ReadNewestAction","jsonCode":200,"requestID":"883c9988fba863cf-LHR"}
Log.ts:69 [info] Finished API request in 3173ms - {"command":"GetMissingOnyxMessages","jsonCode":200,"requestID":"883c999288b963cf-LHR"}
Log.ts:69 [info] Finished API request in 2874ms - {"command":"GetMissingOnyxMessages","jsonCode":200,"requestID":"883c99a62a3763cf-LHR"}
Log.ts:69 [info] Finished API request in 397ms - {"command":"OpenReport","jsonCode":200,"requestID":"883c99b8eaf463cf-LHR"}
Log.ts:69 [info] Finished API request in 1391ms - {"command":"ReadNewestAction","jsonCode":200,"requestID":"883c99bb3e1863cf-LHR"}
Log.ts:69 [info] Finished API request in 1884ms - {"command":"GetMissingOnyxMessages","jsonCode":200,"requestID":"883c99c41a2f63cf-LHR"}
Log.ts:69 [info] Finished API request in 662ms - {"command":"OpenReport","jsonCode":200,"requestID":"883c9c00cffd63cf-LHR"}
Log.ts:69 [info] Finished API request in 485ms - {"command":"AuthenticatePusher","jsonCode":500,"requestID":"883c9c037bae63cf-LHR"}
Log.ts:69 [info] Finished API request in 469ms - {"command":"OpenReport","jsonCode":200,"requestID":"883c9c052df663cf-LHR"}
Log.ts:69 [info] Finished API request in 421ms - {"command":"AuthenticatePusher","jsonCode":500,"requestID":"883c9c091b9763cf-LHR"}
```

Seems like the requests took very long to finish leading to this experienece

**Comment by jasperhuangg** [comment]
We CP'd https://github.com/Expensify/App/pull/42095 which should fix this issue.

**Comment by jasperhuangg** [comment]
Can't reproduce on web with fresh accounts, and I was previously able to reproduce very consistently using the same method.

**Comment by jasperhuangg** [comment]
I've tested it a couple times with fresh accounts and I think it's pretty safe to say that the issue has been fixed, closing
