### ISSUE TITLE
[$250] App sending burst of GetMapboxAccessToken requests

### ISSUE THREAD

**Issue by aldo-expensify** [Expensify/App#43517]
Coming from: https://github.com/Expensify/Expensify/issues/371083

Sporadically, maybe once a day or sometimes more, we get hundreds of requests to `GetMapboxAccessToken` in a short time window (couple minutes). These burst of requests make us exceed the rate limit from MapBox. Under normal usage, we are far from this limit, except for when this happens.

I have tried to reproduce this problem but I haven't been able to. My guess is that under some combination of network status change and user actions we can get stuck in a retry loop for `GetMapboxAccessToken`. The code fetching `GetMapboxAccessToken` is here:

https://github.com/Expensify/App/blob/60530f643b30f30510914ed28e2a90ed5d37184a/src/libs/actions/MapboxToken.ts#L54-L57

<img width="1265" alt="Screenshot 2024-06-11 at 4 02 37 PM" src="https://github.com/Expensify/App/assets/87341702/45df4410-6e0e-4aaa-b320-602a7933cce0">

These logs show a testing user calling `GetMapboxAccessToken` hundreds of times:

https://www.expensify.com/_devportal/tools/logSearch/#query=blob%3A%20%22Bench%20totals%20for%20command%22%20AND%20email%3A%22berhanesarah.testing%2Btwerd%40gmail.com%22%20AND%20timestamp%3A%5B2024-06-06T13%3A53%20TO%202024-06-06T13%3A54%5D&index=_all

All the requests came from the `web` platform, user agent `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`

If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation:**

## Action Performed:

We don't know how to reproduce this bug yet

## Expected Result:

The frontend (App) shouldn't hundreds of `GetMapboxAccessToken` requests causing the backend to hit the rate limit.

## Actual Result:

Under some unknown conditions, the frontend (App) can send hundreds of `GetMapboxAccessToken` in a short period of time until the backend start returning errors because we hit the maximum number of request per minute of MapBox.

## Workaround:

N/A

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~014f5cea11408705e8</li>
        <li>Upwork Job ID: 1800674628059073531</li>
        <li>Last Price Increase: 2024-07-09</li>
    </ul>
</details>

**Comment by gawandeabhishek** [comment]
**Proposal**

I have reviewed the issue regarding the sporadic burst of requests to `GetMapboxAccessToken` that cause the rate limit to be exceeded. To address this, I have implemented a throttling mechanism in the `fetchToken` function to prevent it from being called too frequently.

**Summary of Changes**

1. **Throttling Mechanism**:
    - Introduced a `FETCH_INTERVAL` constant to define the minimum interval between fetch attempts.
    - Added `lastFetchTime` to track the last fetch attempt.
    - Modified `fetchToken` to include logic that prevents it from executing if a fetch was attempted within the last minute.

**Code Changes**

Here are the changes I made in the `MapboxToken.ts` file:

```typescript
let lastFetchTime = 0;
const FETCH_INTERVAL = 60000; // 1 minute interval between requests

const fetchToken = () => {
    const currentTime = Date.now();
    if (isCurrentlyFetchingToken || (currentTime - lastFetchTime) < FETCH_INTERVAL) {
        return;
    }
    API.read(READ_COMMANDS.GET_MAPBOX_ACCESS_TOKEN, {}, {})
        .then(response => {
            // Handle successful token fetch
            isCurrentlyFetchingToken = false;
            lastFetchTime = currentTime;
        })
        .catch(error => {
            // Handle errors
            isCurrentlyFetchingToken = false;
        });
    isCurrentlyFetchingToken = true;
};
```

These changes ensure that the `fetchToken` function will not be called more frequently than once per minute, thus preventing the rate limit from being exceeded due to rapid consecutive requests.

**Next Steps**

Please review the changes. If they look good, I can submit a pull request with the modifications. If there are any adjustments or additional requirements, feel free to let me know.

Best regards,  
Abhishek Gawande (@gawandeabhishek)

**Comment by studentofcoding** [comment]
# Proposal

## Please re-state the problem that we are trying to solve in this issue
App sending a burst of GetMapboxAccessToken requests Sporadically 

## What is the root cause of that problem?
**This issue could related to a combination of network status changes and user actions, potentially causing a retry loop.** Here's a breakdown of what might be happening :
- Network Fluctuations and AppState Changes: We might have some users with unreliable network states (e.g., that often offline and online again), thus triggering multiple token refresh attempts.
- Concurrent Access Across Multiple Clients: Continuing the 1st breakdown, if these users use many platforms at once (App, and Web) with each instance attempts to refresh the token independently, this could lead to a surge in requests.
- Also we could potentially have a problem with Token Expiry Handling: The current logic checks if the token has expired and then clears it, which triggers a new fetch. If the token expiry check 1 is too frequent or misaligned with the actual token validity, it could lead to unnecessary fetch attempts.

## What changes do you think we should make in order to solve the problem?
- Network Fluctuations and AppState Changes: We could Modify the `setExpirationTimer` function to ensure that only one timer is active at a time across all clients. This can be done by using a combination of a global flag and checking if the current client is the leader. 
- Implement Exponential Backoff for Token Fetching
We need to Modify the fetchToken function to include an exponential backoff mechanism (or reset on success). This will help in reducing the frequency of requests in case of repeated failures.
- Ensure that the token expiry logic aligns with the actual token lifetime provided by Mapbox and consider adding a buffer to refresh the token before it actually expires. This will allow us to handle scenarios where the app might go into a state (like background mode or network loss) that could prevent a timely refresh at the exact moment of token expiration.

## What alternative solutions did you explore? (Optional)
None

**Comment by aldo-expensify** [comment]
I think we need to find a way to reproduce this before doing any change.

**Comment by vaib-contrib** [comment]
Hi @aldo-expensify,  to narrow down RCA search space, is it possible to know which platform(s) and/or browser(s) were the user(s) on while these bursts happened? 

Until then, just by looking at the impl, here we're calling the API unconditionally without taking `isCurrentlyFetchingToken` into account, which might allow sending multiple requests without waiting for it's response.
 
https://github.com/Expensify/App/blob/60530f643b30f30510914ed28e2a90ed5d37184a/src/libs/actions/MapboxToken.ts#L41-L42


Another potential place would be something causing race-condition that mounts and unmounts `ConfirmedRoute` or `IOURequestStepDistance`, since each mount costs an API request. 

https://github.com/Expensify/App/blob/09ce6375914524757b8047f9ce1b1396cca30c38/src/components/ConfirmedRoute.tsx#L100-L104

**Comment by aldo-expensify** [comment]
No overdue. We still don't know how to reproduce, but added more information about the requests origin.

**Comment by aldo-expensify** [comment]
No updates

**Comment by aldo-expensify** [comment]
No updates

**Comment by abekkala** [comment]
@aldo-expensify should I just apply the retest weekly label? Or do we need to better pinpoint some action steps?

**Comment by aldo-expensify** [comment]
> Or do we need to better pinpoint some action steps?

This ^

Applause won't really have a way to "retest" this until we have reproduction steps.

**Comment by aldo-expensify** [comment]
No updates, going to make this weekly. I'll be OOO next week.

**Comment by abekkala** [comment]
not overdue Aldo is back this week

**Comment by aldo-expensify** [comment]
The error has not happened since `Wed Jun 12 20:18 PDT`, maybe we should close this and reopen if it happens again? It may have been fixed by some changes

**Comment by abekkala** [comment]
got it! thanks Aldo
