### ISSUE TITLE
[$250] Expense - Incorrect Expense Count Shown after removing expense from report then adding it back

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44164]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.0-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4609521
**Email or phone of affected tester (no customers):** dave0123seife+employee10a@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Employee - OldDot
1. Create a Report and Add expense
Employee - NewDot
2. Notice that the report that had the expenses added is shown and No expense number is shown on the Report Preview.
Employee - OldDot
3. Delete the expense created on step 1
4. Add expense on the report created on step 1
Employee - NewDot
2. Notice that the new expense added is shown and 2 expenses is shown on the Report Preview

## Expected Result:
Expense count is not shown in the report preview when there is only 1 expense

## Actual Result:
2 expenses is shown on the Report Preview when there is only one expense

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/4034c6ef-5c41-4e92-a98d-a19c53a3de5b

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e2755d15f45ec65</li>
        <li>Upwork Job ID: 1804294263051320282</li>
        <li>Last Price Increase: 2024-06-28</li>
    </ul>
</details>

**Comment by jp928** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

The expense in report action not reduces even if the transaction is deleted.

### What is the root cause of that problem?

The transaction_ only incremental not removes after deleted.

### What changes do you think we should make in order to solve the problem?

From the `OpenReport` API returns transactions with  "status": "Deleted", or any other flags.

Then in the file https://github.com/jp928/App/blob/main/src/libs/TransactionUtils.ts#L754-L780 modify the filter with status !== 'Deleted'

### What alternative solutions did you explore? (Optional)

Before merge `transaction_` in the Onyx remove all other transactions with same reportID

**Comment by NJ-2020** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Incorrect number of Expenses shown after removing the expense, then adding it back
### What is the root cause of that problem?
When we delete the expense, the GetMissingOnyxMessages isn't being called, and then when we add a new expense, the GetMissingOnyxMessages is called and fetches some data from the Backend.

But the backend doesn't tell the Onyx to delete the transaction_{deleted_expense_id}, so the Onyx keeps the previous expense data which has been deleted.
https://github.com/Expensify/App/blob/4dc1710ea72daaa44875e24ea0f71056b33ed8ef/src/components/ReportActionItem/ReportPreview.tsx#L145
https://github.com/Expensify/App/blob/4dc1710ea72daaa44875e24ea0f71056b33ed8ef/src/components/ReportActionItem/ReportPreview.tsx#L316

I have tried to clear all data in Onyx and then log in again with the same account, and then the Onyx is showing the correct number of Expenses because it only fetches from the Backend with available data.

### What changes do you think we should make in order to solve the problem?
We can use the functionality when we open the Expenses page because it shows the correct length of the expenses
https://github.com/Expensify/App/blob/4dc1710ea72daaa44875e24ea0f71056b33ed8ef/src/pages/home/report/ReportActionsList.tsx#L707

### What alternative solutions did you explore? (Optional)

**Comment by skyweb331** [comment]
I think, this should be solved in BE.

When OD user creates expenses in report, ND user gets updates via `GetMissingOnyxMessages` and this API returns some onyx merge commands to create `transaction_{new}` records.
Problem is when OD user delete expenses in the report, it updates `report_{reportID}` and ND user gets updates via `GetMissingOnyxMessage` and new total money is updated in report, but still `transaction_{deletedID}` exists in Onyx so expenses count shows wrong number.

So simply, BE should send onyx `set` command to clear `transaction_{deletedID}` as `false` or `null`, so that FE could ignore them from active transactions.

**Comment by sakluger** [comment]
@abdulrahuman5196 thanks for unassigning.

@s77rt fyi we have a few proposals already when you have some time to review. Thanks!

**Comment by s77rt** [comment]
🎀 👀 🎀 Internal

After submitting a new expense we get a pusher update updating the relevant reports, report actions and adding the new transaction. However if we delete an expense we don't get any pusher event, specifically we don't get an update that clears the old transaction. Even if we open the report (OpenReport) we still don't get any instruction to clear the old transaction. This leaves us with the "deleted" transaction persisted in storage and counted.

<figure>
  <img
  src="https://github.com/Expensify/App/assets/16493223/dc09947a-e9ce-498f-8e17-d2f57e726978"
  alt="Pusher Onyx update after adding a new expense.">
  <figcaption>Pusher Onyx update after adding a new expense</figcaption>
</figure>

**Comment by sakluger** [comment]
Thanks for the review @s77rt. I've switched to Internal and added Hot Picks so we can get an internal volunteer.

**Comment by sakluger** [comment]
Not overdue.

**Comment by sakluger** [comment]
Switching to weekly for now.

**Comment by trjExpensify** [comment]
>However if we delete an expense we don't get any pusher event, specifically we don't get an update that clears the old transaction. Even if we open the report (OpenReport) we still don't get any instruction to clear the old transaction. This leaves us with the "deleted" transaction persisted in storage and counted.

@mountiny @luacmartins I'm wondering if at some point we stopped the pusher updates from the OldDot delete action due to the fire, otherwise I'm not sure why or when this would have broken. Onyx updates from OldDot should be back on though now, I believe.

**Comment by mountiny** [comment]
> I'm wondering if at some point we stopped the pusher updates from the OldDot delete action due to the fire, otherwise I'm not sure why or when this would have broken. Onyx updates from OldDot should be back on though now, I believe.

Correct, this should be back from as of last week I believe

I am not sure if it was on when @s77rt tested, can you maybe check this out again now in case this was tested just before the updates were re-enabled?

**Comment by s77rt** [comment]
Working! 🎉


https://github.com/Expensify/App/assets/16493223/ccaf6f70-8cab-451f-8d42-25ee061358af

**Comment by trjExpensify** [comment]
Alright, so @sakluger if you want to retest yourself you can but seems like this might be resolved with onyx updates back on. 👍

**Comment by s77rt** [comment]
We can close this @sakluger
