### ISSUE TITLE
[Awaiting Payment Sept 10th] [$250] [Held requests] Hold badge remains on paid expense until refresh the page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#44616]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.3-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4678849&group_by=cases:section_id&group_order=asc&group_id=309128
**Email or phone of affected tester (no customers):** gocemate+a445@gmail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. User A creates expense with User B
2. User B navigates to transaction thread and select Hold from 3-dot menu
3. User B pays the expense elsewhere
4. Take a note of Hold badge on the chat header on both User A and User B

## Expected Result:
Since the expense is payed hold status should not be displayed anymore

## Actual Result:
Hold status remains displayed even expense is payed

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [ ] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

Add any screenshot/video evidence

</details> 

https://github.com/Expensify/App/assets/78819774/44a7d821-2080-46d1-a7f7-078f784eadbf

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~0197333211c4d3993e</li>
        <li>Upwork Job ID: 1821527955232770128</li>
        <li>Last Price Increase: 2024-08-30</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

**Comment by lanitochka17** [comment]
@trjExpensify  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The hold banner doesn't disappear until we refresh the page for a paid expense.

### What is the root cause of that problem?
When we pay the expense, we don't optimistically clear the hold status of the report. The pusher or API response doesn't clear the hold status either until we reload the page (from OpenReport).

### What changes do you think we should make in order to solve the problem?

BE: clears the hold status from the API response and/or pusher.
FE: Optimistically clear the hold status
In `IOU.getPayMoneyRequestParams`, add below optimistic data:
```
...(full ? TransactionUtils.getAllReportTransactions(iouReport.reportID).map((transaction) => ({
    onyxMethod: Onyx.METHOD.MERGE,
    key: `${ONYXKEYS.COLLECTION.TRANSACTION}${transaction.transactionID}`,
    value: {
        comment: {
            hold: null,
        },
    }
})) : []),
```
(and revert it back in failureData)

What the code above does is, get all the expense report transactions and clear the hold status. We only do this if the `full` is true which means we pay all hold and non-hold requests.

**Comment by trjExpensify** [comment]
I have a feeling @robertjchen is working on fixing this already. Maybe he can confirm. 

Bit of a sidebar, but for the whack copy and stuff, you're talking care of that here: https://github.com/Expensify/App/pull/42736

**Comment by robertjchen** [comment]
Yes! This should be addressed with the optimistic changes in: https://github.com/Expensify/App/pull/42573

We can put this on hold until those changes are out and then re-test after to make sure this is fixed 👍

**Comment by trjExpensify** [comment]
Cool, done!

**Comment by trjExpensify** [comment]
Still on hold for https://github.com/Expensify/App/pull/42573

**Comment by trjExpensify** [comment]
Same, melvin. Keep holdin', holdin', holdin'... yeah.

**Comment by trjExpensify** [comment]
Alright, that PR has been deployed to prod: https://github.com/Expensify/App/pull/42573#issuecomment-2256646597

**Comment by trjExpensify** [comment]
Taking this off hold. @lanitochka17 can we get a re-test please? Thanks!

**Comment by lanitochka17** [comment]
Issue is still reproducible 

https://github.com/user-attachments/assets/344382af-d423-4f2a-8c10-906f43b477ca

**Comment by trjExpensify** [comment]
Cool, shipping on.

**Comment by trjExpensify** [comment]
@getusha proposal from @bernhardoj here to review: https://github.com/Expensify/App/issues/44616#issuecomment-2197167370

**Comment by getusha** [comment]
@bernhardoj why not just check if the expense is settled to display the component?

```diff --git a/src/components/MoneyReportHeader.tsx b/src/components/MoneyReportHeader.tsx
index 812baee2d10..2441eb8e9db 100644
--- a/src/components/MoneyReportHeader.tsx
+++ b/src/components/MoneyReportHeader.tsx
@@ -196,7 +196,7 @@ function MoneyReportHeader({policy, report: moneyRequestReport, transactionThrea
     );
 
     const getStatusBarProps: () => MoneyRequestHeaderStatusBarProps | undefined = () => {
-        if (hasOnlyHeldExpenses) {
+        if (hasOnlyHeldExpenses && !ReportUtils.isSettled(transaction?.reportID)) {
             return {title: translate('violations.hold'), description: translate('iou.expensesOnHold'), danger: true};
         }
         if (allHavePendingRTERViolation) {
```

**Comment by bernhardoj** [comment]
That works but that doesn't solve the issue that the transaction data still has the hold status which means if we call `TransactionUtils.isOnHold`, it will return true.

**Comment by trjExpensify** [comment]
What do you think, @getusha?

**Comment by getusha** [comment]
@bernhardoj's [proposal](https://github.com/Expensify/App/issues/44616#issuecomment-2197167370) looks good to me
We could also apply a quick fix since it is a pretty straight-forward issue that exists until we refresh the page.
🎀 👀 🎀 C+ Reviewed!

**Comment by NikkiWines** [comment]
Yep, agreed @bernhardoj's proposal looks good 👍

**Comment by bernhardoj** [comment]
PR is ready

cc: @getusha

**Comment by robertjchen** [comment]
Looks like the backend is not sending Onyx updates when something is being unheld as part of a payment/approval operation. Testing out some solutions locally to see if it'll help here.

**Comment by robertjchen** [comment]
Got a potential BE fix in review

**Comment by robertjchen** [comment]
Fix was merged and should go out on Monday, we can re-test then.

**Comment by robertjchen** [comment]
[Auth deploy was blocked](https://expensify.slack.com/archives/C07J32337/p1724113539981129?thread_ts=1724109473.132529&cid=C07J32337), will re-test after the deploy.

**Comment by robertjchen** [comment]
Backend changes were deployed!

**Comment by robertjchen** [comment]
Tested in prod and confirmed fixed!

https://github.com/user-attachments/assets/11ecaf96-be90-4a32-ab63-7505822ff621

**Comment by bernhardoj** [comment]
@robertjchen can we reopen this issue? We still have a pending PR that clears the hold optimistically.

**Comment by trjExpensify** [comment]
Okay, so @getusha can proceed to review that PR now? https://github.com/Expensify/App/pull/47192

**Comment by robertjchen** [comment]
PR in final review

**Comment by robertjchen** [comment]
FE PR merged 👍

**Comment by trjExpensify** [comment]
Payments are due here today. Payment summary as follows: 

- $250 to @getusha for the C+ review
- $250 to @bernhardoj for the fix 

Both of you can go ahead and request on NewDot, closing!

**Comment by bernhardoj** [comment]
Requested in ND.

**Comment by JmillsExpensify** [comment]
$250 approved for @bernhardoj
