### ISSUE TITLE
[HOLD for payment 2024-07-22] [$250] Invoice - App crashes after receiver deletes all workspaces and sender is unable to send invoice

### ISSUE THREAD

**Issue by izarutskaya** [Expensify/App#44818]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.4-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N
**Found when validating PR :** https://github.com/Expensify/App/pull/43036
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Issue reported by:** Applause-Internal team

## Action Performed:
Precondition:
- User A and User B have their own workspace.

1. Go to staging.new.expensify.com
2. [User A] Send an invoice to User B.
3. [User B] Go to invoice chat.
4. [User B] Click pay button > Pay the invoice as business > Pay elsewhere.
5. [User A] Send another invoice.
6. [User A] Note that User A can send another invoice.
7. [User B] Delete all the workspaces.
8. [User B] Note that app crashes after deleting the workspace.
9. [User A] Send another invoice to User B in the same workspace chat.
10. [User A] Note that user cannot send invoice after User B deletes all the workspaces.
11. [User B] Go to Account settings > Workspaces.
12. [User B] Note that the workspace list shows blank workspace under Free plan.

## Expected Result:
In Step 8, app will not crash after user B deletes all the workspaces.
In Step 10, User A should be able to send another invoice to User B after user B deletes all the workspaces.
In Step 12, there should not be any workspace in the list.

## Actual Result:
In Step 8, app crashes after user B deletes all the workspaces.
In Step 10, User A is unable to send another invoice to User B after user B deletes all the workspaces.
In Step 12, there is a blank workspace under Free plan.

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [x] iOS: Native
- [x] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/115492554/bd7ad84a-c26b-416e-a181-5ef83506431e

[Bug6532944_1720087574902!staging.new.expensify.com-1720087225348.txt](https://github.com/user-attachments/files/16097688/Bug6532944_1720087574902.staging.new.expensify.com-1720087225348.txt)

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~015e8883cec9f5dd20</li>
        <li>Upwork Job ID: 1808990503832944883</li>
        <li>Last Price Increase: 2024-07-04</li>
<li>Automatic offers: </li>
<ul>
<li>c3024 | Contributor | 103001035</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @muttmuure</details>

**Comment by izarutskaya** [comment]
@muttmuure I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors.

**Comment by izarutskaya** [comment]
We think this issue might be related to the #collect project. #vip-bills

**Comment by carlosmiceli** [comment]
Can't reproduce.

**Comment by lanitochka17** [comment]
Issue is still reproducible

https://github.com/Expensify/App/assets/78819774/cab72629-c07d-444a-bb72-6015ace8ba09

**Comment by carlosmiceli** [comment]
@lanitochka17 @izarutskaya To clarify, "User A and User B have their own workspace." means that they both belong to a workspace that was created by User B, right?

**Comment by luacmartins** [comment]
@carlosmiceli I think that means that user A is the owner of workspace A and user B is the owner of workspace B

**Comment by carlosmiceli** [comment]
That explains a lot 😅

**Comment by carlosmiceli** [comment]
This is looking like the offender: https://github.com/Expensify/App/pull/43036

cc @cristipaval @VickyStash can you see if you can find a fix? Adding External for more proposals in the meantime.

**Comment by cristipaval** [comment]
at first glance, the fix should be part of the backend. The invoice room should be archived when the receiver workspace is deleted.

**Comment by mountiny** [comment]
@cristipaval do you want to take this issue as you are working on the project and you have the best context? 

I am demoting this bug, please, let me know if you disagree, but it seems like quite a rare scenario users of NewDot will not run into at the moment. We should still fix with urgency as its causing a crash

**Comment by mountiny** [comment]
I have made a revert of the offending PR though

**Comment by mountiny** [comment]
Actually, since this seems to be the last pending item and we have time to revert, marking this as a blocker and prepared the revert

**Comment by cristipaval** [comment]
> I have made a revert of the offending PR though

Ok, I think this is the best path to go for now as I can't jump into the Invoicing project yet, I have to deal with #newdot-quality and #wave-control things

**Comment by cristipaval** [comment]
I can take it over, it might be related to another [issue](https://github.com/Expensify/App/issues/42412) I already have on my plate

**Comment by mountiny** [comment]
$250 to @c3024 for their review and testing on the PR to confirm this is fixed on all platforms

**Comment by mountiny** [comment]
We will need to pay $250 to @c3024 for their help and review

**Comment by VickyStash** [comment]
I was able to reproduce the issue, though there was no crash or blank workspace for me.

@cristipaval There are something that I've noticed that can be useful:

1. After the receiver workspace is removed, `invoiceReceiver` turns into `null`
![issue3](https://github.com/Expensify/App/assets/23176449/357ec8f7-4cad-4604-a3a3-814d16679fd2)

2. During `OpenReport` a policy with an empty avatar and name is loaded
![issue1](https://github.com/Expensify/App/assets/23176449/339de54d-c782-484e-98af-26f6a2187a3c)

3. Sending invoice doesn't work cause invoiceReceiver is null I guess, it returns this error:
![issue2](https://github.com/Expensify/App/assets/23176449/6f6fb1ce-5bbd-4d1b-a66d-3a6ff0af1c44)
Overall it looks like the room should be archived.

**Comment by cristipaval** [comment]
Thanks a lot! That is valuable information. I'll jump into investigating on the backend side.

**Comment by cristipaval** [comment]
> We will need to pay $250 to [@c3024](https://github.com/c3024) for their help and review

@muttmuure this is the only payment due. The crash is still under investigation.

**Comment by carlosmiceli** [comment]
@c3024 small bump :)

**Comment by c3024** [comment]
* [x]  [@c3024] The PR that introduced the bug has been identified. Link to the PR: This is a revert PR for #43036. The authors are aware that the PR was reverted.
* [x]  [@c3024] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment: NA
* [x]  [@c3024] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion: No, this is not a bug that could be identified earlier with any steps.
* [x]  [@c3024] Determine if we should create a regression test for this bug. This was identified during staging regression tests. So, no regression test is required.
* [x]  [@c3024] If we decide to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps to ensure the same bug will not reach production again. NA

**Comment by muttmuure** [comment]
Paid
