### ISSUE TITLE
Fix workspace defaults for `Manage my team's expenses' intent and manual workspace creation in NewDot

### ISSUE THREAD

**Issue by garrettmknight** [Expensify/App#49127]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** N/A
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Issue reported by:** @garrettmknight 
**Slack conversation:** https://expensify.slack.com/archives/C06ML6X0W9L/p1726136887331749?thread_ts=1725892977.799399&cid=C06ML6X0W9L

## Action Performed:
1. Sign up with a new account
2. Select 'Manage my team's expenses'
3. Enter a first name
4. Enable Workflows in the workspace
5. Navigate to the Workflows tab

Alternatively:
1. Login with any existing account
2. Create a workspace
3. Enable Workflows in the workspace
4. Navigate to the Workflows tab
 
## Expected Result:
Since we're just enabling Workflows for the first time, we'd expect that all settings in Workflows would be disabled. This is actually the configuration we want new workspaces to have by default, but it doesn't present correctly since Payments are enabled even when Workspaces aren't.

So, the default for the `Manage my team's expenses' intent and manual workspace creation should be:
- Workflows are enabled
- Payments are enabled

## Actual Result:
Payments are enabled in the Workflows tab.

## Workaround:
Yep, but it's confusing!

## Platforms:
All

## Screenshots/Videos

Add any screenshot/video evidence

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by mkzie2** [comment]
@garrettmknight Is the summary below expected that we want?

1. When we create a new workspace, the workflow feature and payments should be enabled by default
2. When we disable the workflow feature, all sub-features should be disabled.

**Comment by garrettmknight** [comment]
@mkzie2 has it right [here](https://github.com/Expensify/App/issues/49127#issuecomment-2348026292)

**Comment by garrettmknight** [comment]
Taking this one over to confirm defaults for all intents.

**Comment by MariaHCD** [comment]
Have been out sick, I can take a look at this tomorrow. Please reassign if we this needs more urgency, however.

**Comment by garrettmknight** [comment]
Okay, took a bit, but we're going to keep it simple here and default all manually created workspaces in NewDot to have Workflows and Payments enabled just like they technically are in OldDot.

**Comment by garrettmknight** [comment]
Taking this off hold.

**Comment by garrettmknight** [comment]
@rushatgabhane I'm betting this needs backend changes - let's wait till @MariaHCD is back for her to help.

**Comment by trjExpensify** [comment]
>but we're going to keep it simple here and default all manually created workspaces in NewDot to have Workflows and Payments enabled just like they technically are in OldDot.

Are we? 🤔 If your intent is `track` and you create a workspace after, we wouldn't would we?

**Comment by trjExpensify** [comment]
Alright, so clarifying the expected behaviour here. 

**Enable workflows and payments when a workspace is created**
- when your introSelected value is empty
- your introSelected value is `newDotManageTeam` ("Manage my team's expenses) or `newDotLookingAround` ("Something else").
- If we create a workspace via the Submit > "Pay with business bank account" flow (`convertIOUToExpenseReport` I believe) regardless of the introSelected onboarding intent. 

**Do not enable workflows and payments when a workspace is created when**
- your introSelected value is `newDotTrack` ("Track and budget expenses"), `newDotEmployer` ("Get paid back by my employer") or `newdotSplitChat` ("Chat and split expenses with friends")

**Comment by trjExpensify** [comment]
Okay, so as a next step we're [asking @MariaHCD to confirm](https://github.com/Expensify/App/issues/49127#issuecomment-2349502682) that, yes?

**Comment by MariaHCD** [comment]
Looking through to see what BE changes we will need

**Comment by MariaHCD** [comment]
@trjExpensify could you clarify what we mean by `enabling payments` when a workspace is created? Is that to set the workspace reimbursement to any of [these](https://github.com/Expensify/Auth/blob/7fbb437fb028965769866e3288c8444b067904d3/auth/lib/Policy.h#L325-L332) specific values?

**Comment by trjExpensify** [comment]
Yep, that's right. So in NewDot for the "Enable workflows and payments when a workspace is created" cases above, that means:

- Enable `Workflows` so the Workflows page appears in the LHN of the workflow settings (I believe that's achieved by setting `areWorkflowsEnabled` to `true`).
- On the Workflows page, toggle on `Make or track payments`. In doing so, that should set the `reimbursementChoice` to `reimburseManual` (A.K.A "Indirect"). If they connect a VBBA thereafter, that updates `reimbursementChoice` to `reimburseYes` (A.K.A "Direct"). If they toggle "Make or track payments" off on the Workflows page OR disable "Workflows" in More Features, that should set the `reimbursementChoice` to `reimburseNo` (A.K.A "None").

**Comment by MariaHCD** [comment]
Okay, thanks for clarifying. Will list out the BE changes I think we will need shortly.

**Comment by MariaHCD** [comment]
Here are the changes I think we will need:

1. In CreateWorkspace, get the `introSelected` NVP
2. If it is empty or equal to `newDotManageTeam` or `newDotLookingAround`:
- set the `areWorkflowsEnabled` to true for the policy
- set the `reimbursement` to `manual` for the policy
3. Ensure these two updated values are sent in Onyx so the FE can handle appropriately

cc: @mountiny @luacmartins for a buddy check on the above 🙏🏼

**Comment by luacmartins** [comment]
That sounds good to me. One question, why do we want to enable workflows and reimbursements if `introSelected` is empty?

**Comment by trjExpensify** [comment]
Coz' ~@garrettmknight is passionate about it 😛~ the idea is that if we don't know the intent, we lean on the side of minimally showcasing payment capabilities for now.

**Comment by luacmartins** [comment]
Thanks for clarifying. Plan sounds good to me then.

**Comment by mountiny** [comment]
Sounds good to me as long as that will make Garrett happy

**Comment by mkzie2** [comment]
@parasharrajat I updated [proposal](https://github.com/Expensify/App/issues/49127#issuecomment-2348025049)

**Comment by trjExpensify** [comment]
@parasharrajat, what do you think about that proposal for the frontend? 
@MariaHCD, did you get anywhere with the backend yet to link a draft?

**Comment by MariaHCD** [comment]
Got a draft PR here: https://github.com/Expensify/Auth/pull/12649

Working on tests.

**Comment by trjExpensify** [comment]
>@trjExpensify Do we have to disable delay submit as well?

Yeah, when `Workflows` is disabled it should disabled delayed submission and thus set `scheduledSubmit=instantly`.

**Comment by MariaHCD** [comment]
The BE PR is out for review: https://github.com/Expensify/Auth/pull/12649

To clarify, this PR covers this portion of @mkzie2's proposal:

> When we create a new workspace (CreateWorkspace API), BE should return areWorkflowsEnabled as true and reimbursementChoice as reimburseManual if introSelected is empty or it's equal to newDotManageTeam or newDotLookingAround

**Comment by MariaHCD** [comment]
I wanted to clarify the second point:

> When we disable the workflow feature (EnablePolicyWorkflows API), BE should return additional data which will update autoReportingFrequency to CONST.POLICY.AUTO_REPORTING_FREQUENCIES.INSTANT

@trjExpensify Should auto reporting frequency also be set to instant when the workflows are disabled?

**Comment by trjExpensify** [comment]
Nice yeah, I believe Carlos M fixed that recently.

**Comment by MariaHCD** [comment]
Update on the BE side, hit a bit of a blocker - since we're changing the behavior of policy creation, it looks to be causing quite a few integration tests in the API to fail which will each have to be looked into carefully. Plan here: https://github.com/Expensify/Auth/pull/12649#issuecomment-2388593067

**Comment by trjExpensify** [comment]
Appreciate the update! 👍

**Comment by MariaHCD** [comment]
Resuming on the BE PR this week.

**Comment by MariaHCD** [comment]
Haven't been able to make progress on the BE PR just yet. Still need to look carefully into those failing tests.

**Comment by MariaHCD** [comment]
I'm resuming investigating those integration tests failures so we can push the BE fix.

**Comment by trjExpensify** [comment]
Excellent, thanks! With #wave-collect closed, I'm moving this into the #convert project to ensure workflows & payments are enabled when the "manage my team's expenses" intent is selected and a workspace is created.

**Comment by MariaHCD** [comment]
The BE PR is still on my list. Working on updating those failing tests.

**Comment by MariaHCD** [comment]
Working on fixing the failings tests in https://github.com/Expensify/Web-Expensify/pull/43779 based on the changes in https://github.com/Expensify/Auth/pull/12649

**Comment by MariaHCD** [comment]
From working through those failing tests, I've seen that the behavior of report next steps as well as the `AddWithdrawalAccount` inbox task has changed. Looking into this more next week.

**Comment by trjExpensify** [comment]
Thanks, that would be great. Really keen to get this cleaned up for newbies!

**Comment by MariaHCD** [comment]
This is on my list for this week

**Comment by MariaHCD** [comment]
OOO today will get back to this tomorrow

**Comment by MariaHCD** [comment]
Got a bit swamped with other dailies and chores this week. Going to resume my deep dive into the updated logic for next steps and the `AddWithdrawalAccount` inbox task  tomorrow.

**Comment by MariaHCD** [comment]
Currently working on this!

**Comment by MariaHCD** [comment]
Logic around the report next steps seem to be affected with this change, will look further: https://github.com/Expensify/Auth/pull/12649#issuecomment-2470598436

**Comment by joekaufmanexpensify** [comment]
@trjExpensify @MariaHCD I got assigned [this bug](https://github.com/Expensify/App/issues/52580). I think it might be fixed in this issue, as I suspect part of the issue now is we're prompting US workspaces to pay before enabling payments, even though we aren't yet enabling workflows + payments at the time of workspace creation (which we're doing here). 

Curious if y'all agree?

**Comment by trjExpensify** [comment]
I'm not sure I'm following how they're related, actually. I can take it that issue though!

**Comment by MariaHCD** [comment]
As a summary:
1. The Auth PR that auto-enables workflows and payments is available here: [Auth PR #12649](https://github.com/Expensify/Auth/pull/12649).
2. The failing Web tests in this PR suggest the logic change has side effects on OldDot flows. I've been working on addressing these issues in this Web PR: [Web-Expensify PR #43779](https://github.com/Expensify/Web-Expensify/pull/43779). However, I haven't fully identified all the side effects on OldDot yet.

I'll be OOO next week, but I can pick this back up when I return. If it's urgent, feel free to reassign the task.

**Comment by trjExpensify** [comment]
Maria is back next week, Melv.

**Comment by MariaHCD** [comment]
Back from OOO - resuming this week.

**Comment by MariaHCD** [comment]
Prioritized other dailies last week - relooking here.

**Comment by MariaHCD** [comment]
No updates just yet. Getting back to this today.

**Comment by MariaHCD** [comment]
I believe we might need an App PR to ensure the FE is handling the props correctly: https://github.com/Expensify/App/issues/49127#issuecomment-2374008078

**Comment by trjExpensify** [comment]
How are we getting on here? This topic has come up a few times recently, it would be great to get this over the line.

**Comment by MariaHCD** [comment]
Sorry, haven't been able to resume this since I've been prioritizing stability and retain issues. I'll specifically carve out some time for this tomorrow.

**Comment by trjExpensify** [comment]
I'm putting this back on `Daily`. Hopefully with Maria back from holidays next week, we can get this over the line.

**Comment by MariaHCD** [comment]
Back from OOO - going to prioritize this week

**Comment by MariaHCD** [comment]
Resuming today
- Auth PR updated: https://github.com/Expensify/Auth/pull/12649
- Relooking into the web tests to be updated: https://github.com/Expensify/Web-Expensify/pull/43779

The plan of action will be:
1. Update the Web PR to skip the failing tests as well as update to the new logic: https://github.com/Expensify/Web-Expensify/pull/43779
2. CP the Web PR to prod
3. Merge the Auth PR and wait for it to be deployed to prod
4. Create a new Web PR to un-skip the previously failing tests and verify those tests now pass as expected

**Comment by MariaHCD** [comment]
Still a WIP!

**Comment by trjExpensify** [comment]
Do you think the Auth PR can be ready to be reviewed this week?

**Comment by MariaHCD** [comment]
The Auth PR is basically done, but the [Web PR](https://github.com/Expensify/Web-Expensify/pull/43779) (WIP) needs to go out first. There are about 12 failing tests that need to updated, I've got about 4 done - working on the rest.

**Comment by MariaHCD** [comment]
https://github.com/Expensify/Web-Expensify/pull/43779 is updated and out for review.

Plan of action:
- [x] Update the Web PR to skip the failing tests as well as update to the new logic: https://github.com/Expensify/Web-Expensify/pull/43779
- [ ] CP the Web PR to prod
- [ ] Merge the [Auth PR](https://github.com/Expensify/Auth/pull/12649) and wait for it to be deployed to prod
- [ ] Create a new Web PR to un-skip the previously failing tests and verify those tests now pass as expected

**Comment by MariaHCD** [comment]
CP request: https://expensify.slack.com/archives/C07J32337/p1737361645542359

**Comment by MariaHCD** [comment]
Follow up Web PR: https://github.com/Expensify/Web-Expensify/pull/45186

**Comment by MariaHCD** [comment]
@trjExpensify just clarifying - for users on oldDot, they would not have `introSelected`, correct? That would mean we'd enable workflows and payments on any new policy that they create.

**Comment by trjExpensify** [comment]
>for users on oldDot, they would not have introSelected, correct? That would mean we'd enable workflows and payments on any new policy that they create.

Right, OldDot group workspaces are created with the reimbursement choice manual enabled by default today anyway, which means that should we show their workspace settings in NewDot, Workflows and Payments would be enabled.

**Comment by MariaHCD** [comment]
Auth PR is now unblocked with all Web tests passing: https://github.com/Expensify/Auth/pull/12649

Just awaiting final reviews.

**Comment by MariaHCD** [comment]
@parasharrajat good point. Hopefully, with the next backend deploy, workflows and payments will be auto enabled when a new policy is created. 

I think the FE is already equipped to handle that, correct? So perhaps there aren't any FE changes required. We can double check once the backend deploy goes through.

**Comment by MariaHCD** [comment]
[Auth PR](https://github.com/Expensify/Auth/pull/12649) is merged and should be deployed tomorrow

**Comment by trjExpensify** [comment]
Alrighty, it's deployed! Did we check this? @MariaHCD @parasharrajat 

>I think the FE is already equipped to handle that, correct? So perhaps there aren't any FE changes required. We can double check once the backend deploy goes through.

**Comment by trjExpensify** [comment]
👋 Are we needing a App PR for this? I created a workspace when `newDotPersonalSpend` is set in `introSelected`, but workflows+payments were enabled: 

<img width="1502" alt="Image" src="https://github.com/user-attachments/assets/1c180692-226d-4143-ae04-f345edf71887" />

**Comment by trjExpensify** [comment]
>Currrently, the FE does not behave optimistically as required in this issue

Ah, I think we should do this.

**Comment by MariaHCD** [comment]
Looks like https://github.com/Expensify/App/pull/50391 is still a WIP

**Comment by trjExpensify** [comment]
@MariaHCD does that explain this? https://github.com/Expensify/App/issues/49127#issuecomment-2608102760

**Comment by MariaHCD** [comment]
@trjExpensify Regarding https://github.com/Expensify/App/issues/49127#issuecomment-2608102760, no that wouldn't be a FE issue - that would indicate something is wrong with the backend logic.

Could you let me know the email of the account you were testing with so I can find the logs?

**Comment by trjExpensify** [comment]
Here's a fresh one. 

Email: tom+personalspend34@trj.chat

https://github.com/user-attachments/assets/a7276435-efe6-4bf2-b610-5f697f9c8eb8

**Comment by MariaHCD** [comment]
Logs: https://www.expensify.com/_devportal/tools/logSearch/#query=request_id:(%229088d3189d6448c5-LHR%22)+AND+timestamp:[2025-01-27T11:42:46.709Z+TO+2025-01-27T13:42:46.709Z]&index=logs_expensify-032278

Looks like we did not hit this block for auto-enabling based on intent: https://github.com/Expensify/Auth/blob/f04b5e82eaf0eac6ae9b8151fd17def4a0698c5a/auth/command/CreatePolicy.cpp#L198-L200

In the database, `areWorkflowsEnabled` is set to true but there is no reimbursement key for the policy `64B8AC61242D0F54 ` 🤔 

<details>

<summary>Query</summary>
```sql
sudo readdb.sh -line "select value->>'areWorkflowsEnabled', value->>'reimbursement' from nameValuepairs where name = 'expensify_policy64B8AC61242D0F54'"
value->>'areWorkflowsEnabled' = 1
      value->>'reimbursement' = 
```

</details>

I'll do some testing on my local env

**Comment by trjExpensify** [comment]
🤔 indeed!

**Comment by dangrous** [comment]
I just found [this](https://github.com/Expensify/Auth/pull/12649#issuecomment-2616847925) when working on a related flow - does that help/hurt the bug you're looking at above?

**Comment by MariaHCD** [comment]
Okay, tested locally and looks like workflows are being auto enabled for all new workspaces because of this change: 

PR here: https://github.com/Expensify/Web-Expensify/pull/45335

**Comment by trjExpensify** [comment]
👋 How we looking here?

**Comment by MariaHCD** [comment]
We're just waiting on https://github.com/Expensify/Web-Expensify/pull/45335 to be deployed to prod and then our PR [here](https://github.com/Expensify/Web-Expensify/pull/45335) should be good to go

**Comment by MariaHCD** [comment]
Just merged https://github.com/Expensify/Web-Expensify/pull/45335

Once on staging, we can retest!

**Comment by MariaHCD** [comment]
While https://github.com/Expensify/Web-Expensify/pull/45335 is deployed to staging, we've identified a related issue: https://github.com/Expensify/App/issues/56491 which causes the workspace that is auto created after onboarding to not have workflows auto-enabled.

**Comment by dangrous** [comment]
yep! should solve that

**Comment by trjExpensify** [comment]
Excellenteeee!

**Comment by trjExpensify** [comment]
The Auth PR was merged at the end of last week. We've just kicked off the deploy it looks like, so I suspect it will be deployed within the next hour. 👍

**Comment by trjExpensify** [comment]
Yep, that's still the expected behaviour AFAIK!

**Comment by MariaHCD** [comment]
> [@MariaHCD](https://github.com/MariaHCD) Is the backend change completely? And after a long time, is this [#49127 (comment)](https://github.com/Expensify/App/issues/49127#issuecomment-2374008078) still the expected behavior?

Yes to both 👍🏼 The backend changes are complete and the expected behavior is still the same.

**Comment by trjExpensify** [comment]
Alright cool, we ended up having one front-end PR for this in the end right? Let's get the checklist completed, and then we can pay it out tomorrow.

**Comment by trjExpensify** [comment]
Payment summary as follows: 

- $250 to @parasharrajat for C+
- $250 to @mkzie2 for the PR (offer sent!)

**Comment by JmillsExpensify** [comment]
$250 approved for @parasharrajat

**Comment by trjExpensify** [comment]
@mkzie2, can you accept [the offer](https://www.upwork.com/nx/wm/offer/106512650) please? Thanks!

**Comment by trjExpensify** [comment]
Paid, closing!
