### ISSUE TITLE
[$250] Workflow - Second approver disappears after editing and saving approval workflow

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#50294]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.45-2
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**Email or phone of affected tester (no customers):** applausetester+bm63@applause.expensifail.com
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Go to https://staging.new.expensify.com/
2. Create a new workspace.
3. Add multiple members, including Approver A, Approver B, and an employee.
4. Go to "More Features" and enable workflow.
5. Go to workflow and create an approval workflow:
- The employee submits to Approver A.
- Approver B is set as the second approver.
6. Click on the approval workflow created in step 5.
7. Click on "Expense From" and choose several members along with the employee, then save the changes.
8. Reopen the same approval workflow.
9. In "Expense From," deselect all members except for the employee, then save the configuration.

## Expected Result:
The second approver (Approver B) should remain in the approval workflow after saving the changes.

## Actual Result:
After saving the edited approval workflow, the second approver (Approver B) is removed from the workflow.

## Workaround:
Unknown

## Platforms:

- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4ad435a4-5e23-4765-a7e6-80a4a61e7338

 
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021843144039278346707</li>
        <li>Upwork Job ID: 1843144039278346707</li>
        <li>Last Price Increase: 2024-10-07</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @tgolen</details>

**Comment by IuliiaHerets** [comment]
@Christinadobrzyn  FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by Christinadobrzyn** [comment]
Oh interesting - I can reproduce with the steps in the OP. I think this can be external

**Comment by Christinadobrzyn** [comment]
waiting on proposals

**Comment by VickyStash** [comment]
Hi, I'm Viktoryia from Callstack - expert contributor group - and I would like to work on this issue.

**Comment by VickyStash** [comment]
It looks like it's an **API** issue.

Params the app sends to the `UpdateWorkspaceApproval` API call during expenses members deselect (deselected viktoryia.kliushun+4@callstack.com user):

![image](https://github.com/user-attachments/assets/ee9520a9-4f94-4d77-bb32-75f2c2a8fb0e)

Here is the response I got from the API:

![image](https://github.com/user-attachments/assets/83ba218d-c08a-4ace-b67c-17515c0e27a3)

As you can see API besides updating viktoryia.kliushun+4@callstack.com user updated the viktoryia.kliushun+1@callstack.com (Approver 1) as well. It cleaned up his `forwardsTo` field => due to this Approver 2 got removed.
So the fix would be updating  `UpdateWorkspaceApproval` API call not to clear out `forwardsTo` field of the approver during employee deselect. Maybe Approver 1 (viktoryia.kliushun+1@callstack.com in this example) shouldn't be updated at all. But it's better to confirm with the BE team.

**Comment by VickyStash** [comment]
@abdulrahuman5196 What do you think about my suggestion above?

**Comment by Christinadobrzyn** [comment]
Hi @VickyStash thanks for joining us! I've added you to this GH. @abdulrahuman5196 if you can review the above proposal that would be great! TY!

**Comment by VickyStash** [comment]
@abdulrahuman5196 kind bump 🙂

**Comment by Christinadobrzyn** [comment]
just checking on this review @abdulrahuman5196 - thanks!

**Comment by VickyStash** [comment]
@abdulrahuman5196 any news?

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@Christinadobrzyn I agree, seems to be an API issue as suggested by @VickyStash . Can we involve an internal engineer here?

**Comment by Christinadobrzyn** [comment]
yep! Added the internal label - I'll try to find someone to grab this.

**Comment by Christinadobrzyn** [comment]
Based on the Slack convo - https://expensify.slack.com/archives/C06ML6X0W9L/p1729217268737929

@Beamanator might be able to grab this this week!

**Comment by Beamanator** [comment]
Ok tested and reproduced, but there's also potentially other similar issues when we're removing multiple `Expenses from` people & leaving 1 - I think I was able to "try" to remove multiple `Expenses from` people when the `Approver` is the workspace owner, and nothing happened (the people I removed came back) - I believe because we default to the owner. If so, we should prevent removing people in the FE if the end result is the same

**Comment by Beamanator** [comment]
Anyway, while testing THIS issue, I saw that the API endpoint name is `UpdateWorkspaceApproval`, which I believe was built by @tgolen and his goons :D @tgolen do you want to investigate the weirdness happening in this issue? I should have time a bit later this week to do a deeper investigation ifff you'd prefer 👍

**Comment by Christinadobrzyn** [comment]
I just retested and it's still happening. 

@tgolen would you have the bandwidth to investigate this? Let me know or I can reach out to the team to try and find a volunteer. Thanks!

**Comment by Christinadobrzyn** [comment]
I just retested and it's still happening based on the video and steps in the OP. 

@tgolen would you have the bandwidth to investigate this? Let me know or I can reach out to the team to try and find a volunteer. Thanks!

**Comment by tgolen** [comment]
# Daily Update
- I wrote an [Auth PR](https://github.com/Expensify/Auth/pull/12958) to fix the bug

### Next Steps
- @bondydaa and @Beamanator review and merge the PR
- Wait for it to get deployed
- @Christinadobrzyn verify that the bug is fixed

#### ETA
- Deployed tomorrow, Oct. 29

I think since this is internal, I will unassign @abdulrahuman5196 and @VickyStash. Thanks for pointing out the issue and investigating it!

**Comment by Christinadobrzyn** [comment]
Awesome! thanks @tgolen!

**Comment by Christinadobrzyn** [comment]
monitoring [PR](https://github.com/Expensify/Auth/pull/12958)

**Comment by Christinadobrzyn** [comment]
monitoring https://github.com/Expensify/Auth/pull/12958

**Comment by Christinadobrzyn** [comment]
Tested again and the issue is still happening. I think we're still working on the PR - monitoring

**Comment by Beamanator** [comment]
Yes PR was merged end of last week, should get deployed today 👍

**Comment by Christinadobrzyn** [comment]
Awesome! I tested again, and this is fixed. Thanks @tgolen and @Beamanator! Closing
