### ISSUE TITLE
[Due for payment 2025-03-17] [$500] Desktop - Scan receipts - There is a delay after clicking the submit expense button

### ISSUE THREAD

**Issue by IuliiaHerets** [Expensify/App#52668]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.0.63-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/5231836&group_by=cases:section_id&group_id=294998&group_order=asc
**Issue reported by:** Applause Internal Team

## Action Performed:
1. Navigate to the workspace chat as the employee
2. Select the option to Submit expense &gt; Scan receipt
3. Select the option to upload a receipt
4. Upload a receipt file
5. Click the "Submit expense" button

## Expected Result:
The submitting expense flow using scanning option is smooth

## Actual Result:
There is a delay after clicking the submit expense button

## Workaround:
Unknown

## Platforms:

- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [ ] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/ea18f3ec-ef5d-495d-8000-a7fca7045cae
  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021858847049782861721</li>
        <li>Upwork Job ID: 1858847049782861721</li>
        <li>Last Price Increase: 2025-01-03</li>
<li>Automatic offers: </li>
<ul>
<li>wildan-m | Contributor | 106254364</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @zanyrenney</details>

**Comment by zanyrenney** [comment]
Nice, looks like we also already have a proposal.

**Comment by zanyrenney** [comment]
Moving ahead here.

**Comment by dipanshujindal1992** [comment]
Hi 

I checked that and i find the root cause. Basically we are calling the api and api takes time to write the data especially while we uploaidng the image. In order to prevent multiple clicks, they are using the

```
// Don't let the form be submitted multiple times while the navigator is waiting to take the user to a different page
            if (formHasBeenSubmitted.current) {
                return;
            }

            formHasBeenSubmitted.current = true;
```

**### The Solution is** 

We can display the ActivityIndicator until api success or fails on Press of SubmitExpenses.


Contributor details
Your Expensify account email: <dipanshujindal1993@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/dipanshuj>

**Comment by dipanshujindal1992** [comment]
Hi @c3024 
Did you get the chance to review my proposals ?

**Comment by c3024** [comment]
Thanks for the tags.

@daledah , I will update soon.

@dipanshujindal1992 , Please check out the [contributing guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md). Only proposals in the format given there will be reviewed.

**Comment by dipanshujindal1992** [comment]
Hi @c3024 

I uploaded the content as your format. May i know what is missing in my format?

Contributor details
Your Expensify account email: <dipanshujindal1993@gmail.com>
Upwork Profile Link: <https://www.upwork.com/freelancers/dipanshuj>

**Comment by c3024** [comment]
@daledah , `getLocationPermission` returns value as `GRANTED` but still fetching the coordiantes gets timed out on desktop build. This is working well with Chrome. Config value for `GCP_GEOLOCATION_API_KEY` is empty even for Chrome. If we use this check you suggested 
```js
CONFIG.GCP_GEOLOCATION_API_KEY;

const getCurrentPosition: GetCurrentPosition = (success, error, options) => {
    if (navigator === undefined || !('geolocation' in navigator) || !CONFIG.GCP_GEOLOCATION_API_KEY) {
...
return;
}
```
on desktop, we will skip fetching coordinates everytime. I think it needs to be found if the check 
```js
navigator.permissions.query({name: 'geolocation'})
```
in `getLocationPermission` is correctly returning the result.

**Comment by c3024** [comment]
There may be an issue with the `GCP_GEOLOCATION_API_KEY` in the `secrets`, as the request consistently times out. Could the internal engineer please verify and confirm?

🎀 👀 🎀

**Comment by zanyrenney** [comment]
how are we doing here everyone? @c3024 what is the next step?

**Comment by c3024** [comment]
@luacmartins 

Can you please check [this comment](https://github.com/Expensify/App/issues/52668#issuecomment-2497155274)? Location never gets fetched and always gets timed out in desktop on any environment. It looks like there is some issue with `GCP_GEOLOCATION_API_KEY`.

**Comment by luacmartins** [comment]
I created an [internal ticket](https://github.com/Expensify/Expensify/issues/449336) to verify the API secrets are correct. Assuming they are, what's the next step here?

**Comment by luacmartins** [comment]
@c3024 we updated the credentials for staging/production. We don't know if they were out of sync because we can't see the values once they are set, but they should be in sync now. Can we test it again after the next deploy?

**Comment by c3024** [comment]
Tested just now on staging version 9.0.72-0. The bug still exists.

 

https://github.com/user-attachments/assets/d7d9fb6a-7066-40a7-ab78-e2d14ca7f845


I guess the updated credentials must be available on staging now. So, this needs a front-end fix and new proposals.

**Comment by c3024** [comment]
Waiting for proposals!

**Comment by c3024** [comment]
No proposals yet!

**Comment by luacmartins** [comment]
Still looking for proposals

**Comment by c3024** [comment]
Not overdue!

**Comment by c3024** [comment]
Awaiting proposals!

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by c3024** [comment]
I can still reproduce this on production!

**Comment by luacmartins** [comment]
This is still reproducible. We updated the [credentials](https://github.com/Expensify/App/issues/52668#issuecomment-2515037971) a while ago so they should be correct now, @c3024 @daledah any ideas here?

**Comment by c3024** [comment]
I have not found anything yet. [Posted](https://expensify.slack.com/archives/C01GTK53T8Q/p1735897335887849) on Slack for proposals.

**Comment by luacmartins** [comment]
Doubled the price since this is a core flow and platform.

**Comment by brunovjk** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
There is a delay when clicking the "Submit Expense" button in the desktop app. If the geolocation API key is missing, the geolocation functionality is not handled gracefully, causing the flow to break or timeout.

### What is the root cause of that problem?
The desktop app currently relies on `navigator.geolocation.getCurrentPosition` without a fallback for when the `GOOGLE_GEOLOCATION_API_KEY` is missing. Additionally, the `.desktop` implementation of `getCurrentPosition` [was removed](https://github.com/Expensify/App/pull/26546#discussion_r1313691610), leading to inconsistent behavior compared to web.

### What changes do you think we should make in order to solve the problem?
Reintroduce a desktop-specific `getCurrentPosition` implementation that:
1. Uses the Google Geolocation API when the key is available.
2. Handles missing API keys gracefully by skipping geolocation and providing a clear fallback response.
3. Aligns error handling with the web implementation for consistency.

Like we had [here](https://github.com/Expensify/App/blob/fab2259a8d78f6532f5cafd532a78fb02bd15660/src/libs/getCurrentPosition/index.desktop.ts). 

<details>
<summary>POC:</summary>



https://github.com/user-attachments/assets/977c2f75-dd30-43dd-9e19-35ae25889f8f


</details>



### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
1. Test the desktop geolocation flow with:
   - A valid `GOOGLE_GEOLOCATION_API_KEY`.
   - A missing `GOOGLE_GEOLOCATION_API_KEY`.
2. Verify fallback behavior when geolocation is unavailable.
3. Simulate timeout scenarios and confirm proper handling.

### What alternative solutions did you explore? (Optional)

**Comment by c3024** [comment]
@brunovjk 

Can you please share a branch with the changes required for enabling/using location for Desktop app and sending the location details in the payload for money request? It seems that the POC in your proposal shows only skipping of location fetching.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

At the desktop interface, there is a delay in processing receipts after clicking the submit expense button.

### What is the root cause of that problem?

Location service is not enabled for the electron app

### What changes do you think we should make in order to solve the problem?

If delay occurred, there is a chance that user setting not enable location service, in that case we can provide the user two options:
1. Enable the setting
2. Continue the transaction without location

in electron main.ts, we can add new handle that will prompt for location access. The location access setting will be effective after we re-launch app, so we also need inner dialog for re-launching the app:

```tsx

               ipcMain.handle(ELECTRON_EVENTS.PROMPT_LOCATION_PERMISSION, () => 
                    dialog.showMessageBox({
                        type: 'warning',
                        title: 'Location Access Error',
                        message: 'Unable to access your location',
                        detail: 'This could be due to disabled location services.',
                        buttons: ['Continue Without Location', 'Open Location Settings'],
                        defaultId: 1,
                        cancelId: 0
                    }).then((result) => {
                        if (result.response === 1) {
                            exec('open x-apple.systempreferences:com.apple.preference.security?Privacy_Location');

                            dialog.showMessageBox({
                                type: 'info',
                                buttons: ['Relaunch Now', 'Later'],
                                defaultId: 0,
                                message: 'System Preferences Opened',
                                detail: 'Please enable location access in the System Preferences, then relaunch the app for changes to take effect.\n\nTo enable: Check the box next to the app name in the Location Services list.'
                            }).then((result) => {
                                if (result.response === 0) {
                                    app.relaunch();
                                    app.exit(0);
                                }
                            });
                            return 'SETTINGS_OPENED';
                        }
                        return 'CONTINUE_WITHOUT_LOCATION';
                    })
                );

```

That handle will only being used for desktop through `promptLocationPermission` function, we'll mock the function for other platform

src/libs/actions/promptLocationPermission/index.desktop.ts
```tsx

import ELECTRON_EVENTS from '@desktop/ELECTRON_EVENTS';
import type PromptLocationPermission from './types';

const promptLocationPermission: PromptLocationPermission = () => window.electron.invoke(ELECTRON_EVENTS.PROMPT_LOCATION_PERMISSION) as Promise<string>;

export default promptLocationPermission;

```

In IOURequestStepConfirmation, when the user confirming the request, if there is timeout error, ask user to check the location setting. Do the same thing for track expense or any calls to getCurrentPosition

```tsx

                // If the transaction amount is zero, then the money is being requested through the "Scan" flow and the GPS coordinates need to be included.
                if (transaction.amount === 0 && !isSharingTrackExpense && !isCategorizingTrackExpense && locationPermissionGranted) {

                    getCurrentPosition(
                        (successData) => {

                            requestMoney(selectedParticipants, trimmedComment, receiptFile, {
                                lat: successData.coords.latitude,
                                long: successData.coords.longitude,
                            });
                        },
                        (errorData) => {

                            Log.info('[IOURequestStepConfirmation] getCurrentPosition failed', false, {
                                code: errorData?.code,
                                message: errorData?.message,
                                error: {
                                    PERMISSION_DENIED: errorData?.code === GeolocationPositionError.PERMISSION_DENIED,
                                    POSITION_UNAVAILABLE: errorData?.code === GeolocationPositionError.POSITION_UNAVAILABLE,
                                    TIMEOUT: errorData?.code === GeolocationPositionError.TIMEOUT
                                }
                            });

                            if (errorData?.code === GeolocationPositionError.TIMEOUT) {
                                setIsConfirming(false);
                                promptLocationPermission().then((message) => {
                                    if (message === 'SETTINGS_OPENED') {
                                        setIsConfirmed(false);
                                        formHasBeenSubmitted.current = false;
                                        return;
                                    }
                                    // When there is an error, the money can still be requested, it just won't include the GPS coordinates
                                    requestMoney(selectedParticipants, trimmedComment, receiptFile);
                                })
                                return;
                            }
                            // When there is an error, the money can still be requested, it just won't include the GPS coordinates
                            requestMoney(selectedParticipants, trimmedComment, receiptFile);
                        },
                        {
                            maximumAge: CONST.GPS.MAX_AGE,
                            timeout: CONST.GPS.TIMEOUT,
                        },
                    );
                    return;
                }

                // Otherwise, the money is being requested through the "Manual" flow with an attached image and the GPS coordinates are not needed.
                requestMoney(selectedParticipants, trimmedComment, receiptFile);
                return;
            }

            requestMoney(selectedParticipants, trimmedComment);
        },
      
```

Add `isConfirming` state to indicate loading of button.
[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/52668-delay-submit-expense?expand=1#diff-e140a4e301565a464356efb0001afe4f8d8155cb3442473fed02f54fb5dd8065R315)

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

### What alternative solutions did you explore? (Optional)
We can also do the similar thing on app initialization, but getcurrentposition timeout can also have other reason other than location service being disabled

**Comment by brunovjk** [comment]
Thank you for the review @c3024! I will work on the branch. Before proceeding, I’d like to clarify a few points about the expected behavior:

On web and native platforms, geolocation handling is more intuitive. For instance:
- **Web**: If the user grants location permission initially, the flow works seamlessly for subsequent actions. If permission is denied, the app shows a UI explaining the issue and redirects users (e.g., to support). Users can then enable location in their browser settings (e.g., Chrome’s location icon) or dismiss the modal to proceed without delay. 
- **Desktop**: I think we assume the `GOOGLE_API_KEY` is set (even in dev mode, where it's absent). This assumption leads to discrepancies:
    - `getLocationPermission` returns `GRANTED` on Desktop even if location isn't enabled.
    - Consequently, `navigator.geolocation.getCurrentPosition` is called, causing a fallback delay when the key is missing.

The current [proposal](https://github.com/Expensify/App/issues/52668#issuecomment-2569740238) addresses handling `getCurrentPosition` gracefully on Desktop, but I’d like to confirm the expected UI behavior for this case. Unlike web, enabling location in Electron isn’t as straightforward for users. Should we:

1. Use the UI similar to web for explaining location issues and guiding how to enable (I don’t think this is possible?)?
2. Allow users to proceed seamlessly without location (like the POC in my proposal)?

Thanks in advance.

**Comment by c3024** [comment]
Thanks for the updates. I will check and update!

**Comment by c3024** [comment]
Thank you for your proposals.

The primary issue we need to fix here is to fetch the current location when we click on "Use current location" in waypoint select page for distance requests and to fetch and send "gpsCoordinates" with the "RequestMoney" request for scan expenses.

It seemed the API keys sent from backend are correct and this was something to be fixed on the frontend. However, I created a new API key created and used it. This fetched the current location correctly and updated the current location correctly in waypoint selector page and also in the `gpsCoordinates` sent with the `RequestMoney` request.

https://github.com/user-attachments/assets/e2650b45-d755-4f6c-81ef-31e414be66f5

So, I think this is an issue with the API key `CONFIG.GCP_GEOLOCATION_API_KEY` sent from the backend and needs a fix from there. @luacmartins

**Comment by wildan-m** [comment]
@c3024 try to hardcode the api key with valid billing enabled key in main.ts, then disable location service in system preferences.

close the desktop app and start. In my test the timeout still occurred even when we insert valid api key.

**Comment by c3024** [comment]
@wildan-m , yes, we can add your suggestion of prompting and directing the user to System Preferences if location is disabled for the app. We can address this part on the frontend.

cc: @luacmartins

**Comment by luacmartins** [comment]
Adding a prompt to system preferences sounds good to me. Is this the latest proposal addressing that? https://github.com/Expensify/App/issues/52668#issuecomment-2570031498

**Comment by luacmartins** [comment]
@c3024 I'm not sure what else we can do on the backend. We already re-generated the keys and updated them, but it seems like the same error still occurs 🤔

**Comment by c3024** [comment]
Could there be some issue with API settings on Google maps dashboard because of which it is not allowing the requests?

I generated a key with no restrictions and hard-coded it in the code. Location was fetched correctly.

I'm not sure why it does not work on production and staging desktop apps too if the existing key is configured correctly.

**Comment by luacmartins** [comment]
@c3024 what error are you seeing when we make the request to Google's API? That might help us troubleshoot this in the backend.

**Comment by luacmartins** [comment]
Hmm I didn't see any errors in any of my environments. I'll bring this up to Slack in case others have an idea of what might be the issue.

**Comment by luacmartins** [comment]
Before I do that actually, it seems like the requests are timing out, not straight out failing. I'd expect the request to just fail if the API key was incorrect. Maybe there's something else in App preventing the request from going through.

**Comment by wildan-m** [comment]
> This is the error I get on Dev app.
> 
> <img alt="Screenshot 2025-01-08 at 9 43 38 PM" width="1438" src="https://private-user-images.githubusercontent.com/102477862/401220943-68926bea-d47f-46b5-b7b8-db32dfbf8fe3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MDI0MTgsIm5iZiI6MTczNjQwMjExOCwicGF0aCI6Ii8xMDI0Nzc4NjIvNDAxMjIwOTQzLTY4OTI2YmVhLWQ0N2YtNDZiNS1iN2I4LWRiMzJkZmJmOGZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQwNTU1MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOTFjODI0MDlhMzViNDQwZThmMWRkNTU1Y2YwMzQ4MDczNzFiNzFjNjk0ZWU2YWFhYWEzZWQ2NzlkNGQyOTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.f-wGBrRCrCQtRM7pJrMxdL6eOtUq-KkrDebuLdh_chw">
> I am not seeing any other errors on Production desktop app.

@c3024 I think that's expected. It means production build have valid api key, but the api key is empty by default for dev.

**Comment by c3024** [comment]
@wildan-m 

Do you see location getting fetched on production or staging?

**Comment by luacmartins** [comment]
>@luacmartins Does the staging build include the valid location API key?

Yes, it should.

**Comment by wildan-m** [comment]
@c3024 you're right the coordinate is not retrieved in staging and prod. The delay is gone after enabling the location service, but the location failed to retrieve.


@luacmartins The valid api key might not properly inserted to the build pipeline.

To test, you can execute this in electron console tab.
```tsx

if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(
                position => {
                    console.log('[wildebug] position', position.coords);
                },
                error => {
                    console.log("[wildebug] Error: ", error)
                },{ timeout: 50000 });
}

```

I've tried to build my own production build and it's working properly:
<img width="701" alt="Screenshot 2025-01-10 at 13 47 30" src="https://github.com/user-attachments/assets/dc3735a7-0338-43f4-afe8-2579035b25cb" />

**Comment by luacmartins** [comment]
>@luacmartins The valid api key might not properly inserted to the build pipeline.

Did you use the same script we have in App to insert the key? Because we should have the proper keys set up in our environment to insert it into the build.

**Comment by wildan-m** [comment]
@luacmartins did some restriction applied to the api key?

If yes, can you temporarily choose the restriction to none?

![image](https://github.com/user-attachments/assets/763606f9-8abf-4bb5-b5da-6c4fc2c633bf)

**Comment by zanyrenney** [comment]
Hey @luacmartins can you get back to the contributor about the question above, please? Thanks!

**Comment by luacmartins** [comment]
Oh I totally missed that one. Thanks for the ping. Asking someone with access to verify

**Comment by luacmartins** [comment]
Asked [here](https://github.com/Expensify/Expensify/issues/449336#issuecomment-2593790415)

**Comment by luacmartins** [comment]
@wildan-m our team confirmed that there are not Application restrictions on the API key. We only have a restriction on the API that can be called, which is set to `Geolocation API`

![Image](https://github.com/user-attachments/assets/554815d2-8dfb-4b80-baec-c13f271c5c9e)

**Comment by wildan-m** [comment]
@luacmartins Thanks for the confirmation.

Could you please execute this to console log with YOUR_API_KEY replaced to production key. What is the response?

```tsx

fetch('https://www.googleapis.com/geolocation/v1/geolocate?key=YOUR_API_KEY', {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    }
})
.then(response => response.json())
.then(data => {
    console.log('API Key Status:', data);
})
.catch(error => {
    console.error('Error:', error);
});

```

**Comment by luacmartins** [comment]
I [asked our team member](https://github.com/Expensify/Expensify/issues/449336#issuecomment-2598405629) to run the snippet above. I'll report back once I get a response.

>Also could we temporarily use a different API key for the CI/CD process? For example, can I provide you with my private API key to manually trigger the build pipeline for staging using my key? This way, we can confirm that any issues are not stemming from the CI/CD build pipeline itself.

Maybe we can explore this once we get a response to the request above.

**Comment by zanyrenney** [comment]
Thanks for following up and the progress to try move ahead here @luacmartins @wildan-m

**Comment by luacmartins** [comment]
@wildan-m no errors while using both the production or staging keys:

![Image](https://github.com/user-attachments/assets/53e20346-10f5-4ea9-a034-e3418b8cae7a)

**Comment by luacmartins** [comment]
>Also could we temporarily use a different API key for the CI/CD process? For example, can I provide you with my private API key to manually trigger the build pipeline for staging using my key? This way, we can confirm that any issues are not stemming from the CI/CD build pipeline itself.

Maybe the issue is coming from how we're inserting the key into the App 🤔

**Comment by wildan-m** [comment]
@luacmartins I've slack DM the api key to you, that API key works with local production build. If it will also not working through CI/CD pipeline, then there might be issue with the variable configuration.

Possible issues:

- The vars value empty
- The vars value has extra text, maybe quotes/double quotes

**Comment by luacmartins** [comment]
>@luacmartins I've slack DM the api key to you, that API key works with local production build. If it will also not working through CI/CD pipeline, then there might be issue with the variable configuration.

Unless I'm missing something, I think testing this would require changing the API keys in our CI/CD pipeline, which would affect all App builds during that time and we can't do that. Let me know if you were thinking of testing this some other way.

**Comment by wildan-m** [comment]
As far as I know, some CI/CD platforms offer a manual trigger feature, allowing administrators to temporarily change it quickly, perform a manual build, and then revert back to the original settings. Is this possible? @luacmartins

**Comment by luacmartins** [comment]
The issue is that any PRs could be merged in that timeframe, which would trigger builds with the incorrect key. So we'd also have to freeze all merges, which I don't think we want to do. I'll ask the team for ideas on this one.

**Comment by c3024** [comment]
Not overdue Melvin. Discussion started on Slack!

**Comment by luacmartins** [comment]
No updates on the Slack thread yet

**Comment by zanyrenney** [comment]
hey @luacmartins any chance you can bump the thread? Feel free to tag specific people who you think might be able to help, so we can keep up the momentum here. Thanks!

**Comment by luacmartins** [comment]
Done!

**Comment by luacmartins** [comment]
We're still working on it. Latest here - https://github.com/Expensify/Expensify/issues/465441

**Comment by luacmartins** [comment]
We merged one PR that should fix the API key issues - [Remove $ to fix Google Geolocation API #55903](https://github.com/Expensify/App/pull/55903)

**Comment by c3024** [comment]
>If the user hasn't been located before, we'll experience a delay

I think this is expected because we fetch the location synchronously since we pass GPS coordinates with the request. The first fetch takes a while. Even when we directly use “Use my location” first in distance requests, it takes some time to fetch the location.

**Comment by luacmartins** [comment]
Yea, I wonder if we could implement an async solution for that so that we don't experience such a delay.

**Comment by wildan-m** [comment]
The issue persist if we disable location service, I think [prompt for location service](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498) is required.


Ensure to close the app after toggling the location service

https://github.com/user-attachments/assets/578709ba-269d-4181-8d7d-ef499fe484e3

**Comment by luacmartins** [comment]
Yea, I think there are a few things left to do here:

1. If the user has never been prompted to enable location services, add a prompt.
2. If the user has dismissed the location prompt in the past AND location services is disabled, bypass the location feature in App.
3. If the user has approved access to location services, fetch the user known location when they first open the Request money flow to avoid the delay in fetching the user location

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498)

- Address 1st and 2nd point of [this comment](https://github.com/Expensify/App/issues/52668#issuecomment-2649026127)
- Add result video
- Change the electron't modal prompt to existing location modal



> If the user has approved access to location services, fetch the user known location when they first open the Request money flow to avoid the delay in fetching the user location

@luacmartins I think that's existing behavior, but the desktop require restart the app, so it will be fetched after the new request money after restart

**Comment by luacmartins** [comment]
@c3024 leet's review the proposal above

**Comment by c3024** [comment]
@wildan-m 's [proposal](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498) looks good to me.

>>If the user has approved access to location services, fetch the user known location when they first open the Request money flow to avoid the delay in fetching the user location

>@luacmartins I think that's existing behavior, but the desktop require restart the app, so it will be fetched after the new request money after restart

Presently, the location is fetched at the final confirmation step when the user makes a scan request for the first time. I think @luacmartins meant to see if we can start fetching the location when a user begins the request or scan flow, rather than waiting until they reach the confirmation page.

**Comment by wildan-m** [comment]
@c3024 In that scenario, I believe we should simply activate the `getLocationPermission` when a user initiates a new request. This way, the subsequent location request will be quicker, eliminating the need to save it in a variable.

There is a possibility that a user may start a money request in Location A but complete the confirmation process in Location B. Therefore, it remains crucial to re-fetch the location during the confirmation process.

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498)
- Pre-fetch location when do scan request

**Comment by wildan-m** [comment]
@luacmartins currently the pre-fetch only fill the user location on initial request when the call to `navigator.geolocation.getCurrentPosition` success, and do nothing if the request failed.

If we show the location modal at the start, in desktop it will create unexpected result.

The duration of the timeout period can vary. When we invoke `navigator.geolocation.getCurrentPosition`, it may complete quickly or take up to tens seconds, I think that is why we have set our `GPS.TIMEOUT` to 15 seconds. If we were to shorten the timeout to, let's say, 5 seconds, this would increase the likelihood of receiving false positive results. In such cases, the modal will continue to prompt the user to enable location services even if they are already activated.

If we stick to the current 15-second timeout, the modal might appear while the user is in the process of attaching the document, it might annoy the user or it may not appear at all if the user has already confirmed the request.

If we agree with this unpredictable behavior then we can store the location in this `LocationPermissionModal`'s useEffect:

```tsx

    useEffect(() => {
        if (!startPermissionFlow) {
            return;
        }

        getLocationPermission().then((status) => {
            onInitialGetLocationCompleted?.(status);
            if (status === RESULTS.GRANTED || status === RESULTS.LIMITED) {
                clearUserLocation();
                getCurrentPosition((params) => {                    
                    const currentCoords = { longitude: params.coords.longitude, latitude: params.coords.latitude };
                    setUserLocation(currentCoords);
                }, () => { });
                return onGrant();
            }

            setShowModal(true);
            setHasError(status === RESULTS.BLOCKED);
        });
        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps -- We only want to run this effect when startPermissionFlow changes
    }, [startPermissionFlow]);

```

**Comment by luacmartins** [comment]
The behavior I'm proposing is:

1. When the user opens `Create Expense > Scan` check if location services is enabled. If it is, pre-fetch the user current location. If not, do nothing.
2. When the user attaches a receipt and taps `Create expense` check if location services is enabled. If it is disabled, prompt the user to enable it. If it's enabled, just submit the expense (we should have pre-fetched the current location in this case, so the submission would be fast without delays)

Does that make sense?

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498)
- Add alternative solution based on 2nd requirement of [this comment](https://github.com/Expensify/App/issues/52668#issuecomment-2657270976)

**Comment by wildan-m** [comment]
> The behavior I'm proposing is:
> 
> 1. When the user opens `Create Expense > Scan` check if location services is enabled. If it is, pre-fetch the user current location. If not, do nothing.
> 2. When the user attaches a receipt and taps `Create expense` check if location services is enabled. If it is disabled, prompt the user to enable it. If it's enabled, just submit the expense (we should have pre-fetched the current location in this case, so the submission would be fast without delays)
> 
> Does that make sense?

@luacmartins the 1st behavior is done in both solutions

the 2nd behavior done in my [alternative proposal](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498) 

The delay is unavoidable in both scenarios; the main distinction lies in when we choose to implement the delay when the location service is disabled. The main solution involves delaying the confirmation, while the alternative involves shifting the delay to the uploading step.

**Comment by wildan-m** [comment]
[Proposal Updated](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498)

- Add result video for alternative proposal
- add comment `timeout: CONST.GPS.TIMEOUT, // depending on requirement we can use 0 for no caching`

**Comment by luacmartins** [comment]
>while the alternative involves shifting the delay to the uploading step.

Why is that the case? I think we should start fetching the current location on component mount (on background), not when the user uploads the receipt. That way, when the user submits the receipt the current location is already known and there's no delay.

**Comment by luacmartins** [comment]
@c3024 would something like this work? https://stackoverflow.com/questions/63471851/how-can-i-enable-location-permission-in-electron

**Comment by wildan-m** [comment]
> [@c3024](https://github.com/c3024) would something like this work? https://stackoverflow.com/questions/63471851/how-can-i-enable-location-permission-in-electron

@luacmartins using `navigator.permissions.query` is a method that we have already utilized. However, it provided us with a false positive result. You can find more details in [the RCA](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498).

**Comment by luacmartins** [comment]
I feel like [both proposed solutions](https://github.com/Expensify/App/issues/52668#issuecomment-2570031498) are still not ideal. We have a delay either way and the user looses their progress requesting money. I think we should continue to explore additional solutions to this problem so we can get to a better overall UX.

**Comment by zanyrenney** [comment]
Okay good challenge @luacmartins - do we want to amend the proposals or search for new ones?

**Comment by zanyrenney** [comment]
This is obviously not due for payment then.

**Comment by luacmartins** [comment]
>do we want to amend the proposals or search for new ones?

I'd be ok with @wildan-m amending their proposal if they come up with a new solution. But as it stands, I don't think we should go with the existing proposal.

**Comment by dannymcclain** [comment]
I honestly don't mind that, but definitely want to hear what the rest of the design team thinks before moving forward.

Do we use location for anything other than timezone and currency? If so it'd be nice to update that modal copy to let users know exactly why it's important for us to have it.

**Comment by dubielzyk-expensify** [comment]
Sorry if I'm a bit slow here, but does that mean moving the permission dialog on first run experience for users?

**Comment by shawnborton** [comment]
Agree with Jon, I feel like it's better if there is context behind asking for permission. Can't we just use some kind of loading state to manage this one? Like a spinner on the button, etc.

**Comment by dannymcclain** [comment]
>The thing I like about where it is now is that there's context to when the permission gets asks. If an app just asked you about the permission without any context, I've seen big numbers in declines which is hard to change once the users have said no.

Actually now that you mention this I remember us talking about this in SF. 🤦‍♂ 

>Can't we just use some kind of loading state to manage this one? Like a spinner on the button, etc.

Definitely down for an approach like this.

**Comment by luacmartins** [comment]
Keeping the prompt where it is and using a loading spinner sounds good to me.

**Comment by wildan-m** [comment]
> Keeping the prompt where it is and using a loading spinner sounds good to me.

@luacmartins in that case, would you re-consider my main proposal? I think we can use the button for loading purpose?

**Comment by wildan-m** [comment]
@dannymcclain @dubielzyk-expensify @shawnborton  
Can I get the text confirmation for the second pop up. Is the text ok? this will only show for desktop
<img width="740" alt="Image" src="https://github.com/user-attachments/assets/ab6dbdab-65da-4e80-9f76-71b7179f69a5" />

Complete flow

https://github.com/user-attachments/assets/3255ab8b-a6ed-48ae-9116-43575a165ab9

**Comment by dubielzyk-expensify** [comment]
Why is the loading spinner so long? Is this expected or are we testing this on slower networks?

As for the screen where location permission already has been denied, we should use this copy:

![Image](https://github.com/user-attachments/assets/424c55ce-ff8a-4253-8f2e-992dc56be61c)

After they tap Settings, I think we should actually stay on that dialog until we've detected that they've turned on Location permission. Do we really need to relaunch the app to make use of the new permission? On macOS I've noticed that location permission seems to not do that for other apps, but for things like screen recording permission you have to trigger a relaunch.

The reason why I'm hesitant with a relaunch is that we'll break their flow and discard their work so far, right? So I'd rather not lose the image and things they've done unless it's crucial for us to have that information before proceeding?

**Comment by dannymcclain** [comment]
Sounds good—I agree with all of Jon's comments.

**Comment by shawnborton** [comment]
Yup, agree as well - glad we don't need to force the user to relaunch the app, that felt weird!

**Comment by wildan-m** [comment]
> After they tap Settings, I think we should actually stay on that dialog until we've detected that they've turned on Location permission.

@dubielzyk-expensify when the setting enabled, there is no OS event that directly tells the app that some settings has been modified. Our options are:

1. Pooling, check location for every x second when the modal shown
2. Check only when we re-focus the app
3. Provide / change `Settings` button to `Check Location`, that will manually check the permission.

@luacmartins @c3024 any suggestion which way to choose?

**Comment by dubielzyk-expensify** [comment]
I can't speak to technicalities, but I prefer 1 or 2 over a relaunch at least. If 2 is reliable, then that feels pretty reaasonable to me. 

I feel like option 3 is a foreign concept to a user, but maybe with the right copy like "Retry" or something. Still prefer 1 and 2, but I'll let the technical part for others.

**Comment by c3024** [comment]
Yea, both (1) and (2) LGTM.

I think we can use a combination of them.

1. For most cases, the polling will find that the location has been enabled before the user returns to the app.
2. If, for some reason, the polling until that time could not establish this, we can check for it immediately when the user refocuses the app.

**Comment by luacmartins** [comment]
I'd prefer 2 to avoid constant polling.

**Comment by wildan-m** [comment]
@luacmartins when we call requestMoney, we save the GPS coordinates of the receipt. However, I noticed that there was no location information in the response for the transaction. Could you clarify what that location is used for and where it is stored?

**Comment by c3024** [comment]
It is used to guess the currency and timezone of the user submitting the receipt to improve the accuracy of currency detection. The backend uses it for this purpose but does not return it in the response.

**Comment by wildan-m** [comment]
> It is used to guess the currency and timezone of the user submitting the receipt to improve the accuracy of currency detection. The backend uses it for this purpose but does not return it in the response.

@c3024 Thanks for clarification, I guess only dev can fully verify the result then. The PR is ready https://github.com/Expensify/App/pull/57660. Thanks!

**Comment by luacmartins** [comment]
What @c3024 said is correct. Thanks for opening the PR for review @wildan-m. @c3024 let's get this one reviewed once you're online.

**Comment by zanyrenney** [comment]
@c3024 please can you complete the checklist ahead of the 17th of March. The payouts are due on that day but without the check was complete we will not be able to pay that. Thank you!

**Comment by zanyrenney** [comment]
Readding the `bug` label since I will be OOO on this day! Only thing remaining:
- check the checklist is posted
- complete the payouts (1x auto offer, 1 x ND requests offer) Thanks!

**Comment by zanyrenney** [comment]
dammit!

**Comment by zanyrenney** [comment]
TYSM @greg-schroeder

**Comment by zanyrenney** [comment]
adding myself back too.

**Comment by c3024** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by greg-schroeder** [comment]
Payment summary:

Contributor: @wildan-m - $500 - Paid via Upwork
C+: @c3024 - $500 - Please make a manual request via ND

**Comment by greg-schroeder** [comment]
Regression test filed, closing

**Comment by JmillsExpensify** [comment]
$500 approved for @c3024
