### ISSUE TITLE
[HOLD for payment 2025-05-06] [$250] No option to report physical card damaged or stolen before it's activated

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#55189]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:** 
**Reproducible in production?:** 
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @twisterdotcom 
**Slack conversation** (hyperlinked to channel name): [expensify-bugs](https://expensify.slack.com/archives/C049HHMV9SM/p1736522736431619)

## Action Performed:
1. Join a workspace with the Expensify Card enabled
2. Be assigned a physical Expensify Card
3. Wait for it to arrive (but not really)
4. See there is no option to mark as damaged or lost

## Expected Result:
See the option to "Report physical card loss/damage" regardless of whether it's arrived or not.
This directs to the url: `https://new.expensify.com/settings/wallet/card/${cardID}/report-card-lost-or-damaged`
## Actual Result:
The option only appears AFTER a card has been activated (unlike oldDot where it exists constantly)
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

![Image](https://github.com/user-attachments/assets/b6a772e2-86fb-4004-aa4f-620a0fca8d3c)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021880049924929110511</li>
        <li>Upwork Job ID: 1880049924929110511</li>
        <li>Last Price Increase: 2025-01-17</li>
<li>Automatic offers: </li>
<ul>
<li>paultsimura | Reviewer | 105738733</li>
<li>neonbhai | Contributor | 105738734</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @jliexpensify</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
No option to report physical card damaged or stolen before it's activated
### What is the root cause of that problem?
We are only showing that link if `card.state === CONST.EXPENSIFY_CARD.STATE.OPEN`:
https://github.com/Expensify/App/blob/58343c73eed297c501df699c9169b923c1327f4d/src/pages/settings/Wallet/ExpensifyCardPage.tsx#L255
### What changes do you think we should make in order to solve the problem?

we can update it as:
```typescript
{physicalCards.map((card) => {
    if (card.state === CONST.EXPENSIFY_CARD.STATE.OPEN) {
        return (
            <>
                <MenuItemWithTopDescription
                    description={translate('cardPage.physicalCardNumber')}
                    title={CardUtils.maskCard(card?.lastFourPAN)}
                    interactive={false}
                    titleStyle={styles.walletCardNumber}
                />
                <MenuItem
                    title={translate('reportCardLostOrDamaged.report')}
                    icon={Expensicons.Flag}
                    shouldShowRightIcon
                    onPress={() => Navigation.navigate(ROUTES.SETTINGS_WALLET_REPORT_CARD_LOST_OR_DAMAGED.getRoute(String(card.cardID)))}
                />
            </>
        );
    }
    
    if (card.state === CONST.EXPENSIFY_CARD.STATE.NOT_ACTIVATED || card.state === CONST.EXPENSIFY_CARD.STATE.STATE_DEACTIVATED) {
        return (
            <MenuItem
                title={translate('reportCardLostOrDamaged.report')}
                icon={Expensicons.Flag}
                shouldShowRightIcon
                onPress={() => Navigation.navigate(ROUTES.SETTINGS_WALLET_REPORT_CARD_LOST_OR_DAMAGED.getRoute(String(card.cardID)))}
            />
        );
    }

    // Return null if card is in any other state
    return null;
})}
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


### What alternative solutions did you explore? (Optional)

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

No option to report physical card damaged or stolen before it's activated

### What is the root cause of that problem?

We only display the physical card number and the option to report a card as lost or damaged when the card state is OPEN.

https://github.com/Expensify/App/blob/d4ae0cd00876fa61187ef29f99cb1929ceb910cf/src/pages/settings/Wallet/ExpensifyCardPage.tsx#L255

### What changes do you think we should make in order to solve the problem?

To resolve the issue, the Report physical card loss/damage option needs to be available regardless of the card’s activation state. We’ll update the code logic to check for any physical card state other than STATE_NOT_ISSUED and display the menu option accordingly.


```diff
{physicalCards.map((card) => {
    // Check if the card is in a valid state to show the option
    const validStatesForReporting = [
        CONST.EXPENSIFY_CARD.STATE.OPEN,
        CONST.EXPENSIFY_CARD.STATE.NOT_ACTIVATED,
        CONST.EXPENSIFY_CARD.STATE.DEACTIVATED,
        CONST.EXPENSIFY_CARD.STATE.SUSPENDED,
        CONST.EXPENSIFY_CARD.STATE.CLOSED,
    ];

    if (!validStatesForReporting.includes(card.state)) {
        return null;
    }

    return (
        <>
            <MenuItemWithTopDescription
                description={translate('cardPage.physicalCardNumber')}
                title={CardUtils.maskCard(card?.lastFourPAN)}
                interactive={false}
                titleStyle={styles.walletCardNumber}
            />
            <MenuItem
                title={translate('reportCardLostOrDamaged.report')}
                icon={Expensicons.Flag}
                shouldShowRightIcon
                onPress={() => Navigation.navigate(ROUTES.SETTINGS_WALLET_REPORT_CARD_LOST_OR_DAMAGED.getRoute(String(card.cardID)))}
            />
        </>
    );
})}
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


Add unit tests to verify the menu rendering for each state.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by Shahidullah-Muffakir** [comment]
@paultsimura  Shouldn't we return `null` instead of returning `cardPage.physicalCardNumber? `
when `card.state !== CONST.EXPENSIFY_CARD.STATE.OPEN` ?

**Comment by MitchExpensify** [comment]
@neonbhai bump

**Comment by MitchExpensify** [comment]
Done, lets keep this moving!

**Comment by Shahidullah-Muffakir** [comment]
@MitchExpensify @paultsimura
Could you please help me with assigning a physical card? I’m currently unable to assign one.

I tried using the following code, but it didn’t work:

```

Onyx.merge('cardList', {
    'physical': {
        cardID: 234523452345,
        state: 4,
        bank: '1000',
        availableSpend: 10000,
        domainName: 'Expensify',
        maskedPan: '•••• •••• •••• 2345',
        isVirtual: false,
    },
})

**Comment by cristipaval** [comment]
I might have some capacity to tackle this one tomorrow.

**Comment by cristipaval** [comment]
@paultsimura @Shahidullah-Muffakir, I investigated this one today. What I found is that the App somehow hits the API twice. It succeeds the first time, but it fails the second time.

So, here's what I did:
1. I reverted the revert PR locally
2. I tested NewDot and OldDot

@Shahidullah-Muffakir could you please do the same and confirm?

<img width="1126" alt="Image" src="https://github.com/user-attachments/assets/91441676-f2ef-4a64-b393-d2a823eb7fd2" />

**Comment by Shahidullah-Muffakir** [comment]
@cristipaval I’m trying to replicate the issue, but when using the following card details for testing, the `RequestReplacementExpensifyCard` endpoint returns an auth error

Are there any test Expensify card details I can use to test this properly?
```typescript
Onyx.merge('cardList', {
    '21534538': {
        accountID: 18974130,
        bank: 'Expensify Card',
        cardID: 21534538,
        domainName: 'expensify-policy1.exfy',
        nameValuePairs: {cardTitle: '  NOT_ACTIVATED:', isVirutal: false, issuedBy: 18974130},
        isVirtual: false,
        lastFourPAN: '',
        state: 4,
    },
})

**Comment by cristipaval** [comment]
Could you give me the email address that you're using for testing?

**Comment by Shahidullah-Muffakir** [comment]
> Could you give me the email address that you're using for testing?

shahidmuffakir@gmail.com

**Comment by Shahidullah-Muffakir** [comment]
@paultsimura Unfortunately, no. I'm still facing the same issue(https://github.com/Expensify/App/issues/55189#issuecomment-2640104683)

**Comment by cristipaval** [comment]
@Shahidullah-Muffakir can you please access [this section](https://docs.google.com/document/d/1BvohU05MTaHnjOD_vwJv_aqDAirv-ChkyRnKCAvOVyQ/edit?tab=t.0#bookmark=id.8gcd0q45oqwz) in the Google Doc? Could you please try setting up Expensify Cards using those steps?

**Comment by mountiny** [comment]
@Shahidullah-Muffakir is not C+ so they wont have access to the doc

**Comment by cristipaval** [comment]
Thanks @mountiny! Then @paultsimura could follow those steps, add @Shahidullah-Muffakir's test account to a workspace, and issue an Expensify Card for them.

**Comment by Shahidullah-Muffakir** [comment]
Thanks, I will test it now.

**Comment by Shahidullah-Muffakir** [comment]
It seems there is another bug in the app. When I click on **Get physical card,** the magic code is not being sent. I waited for 30 seconds and clicked **'Didn't receive a new magic code,'** but the API does not seem to be called at all. I think this issue needs to be fixed.

https://github.com/user-attachments/assets/1af1eb0b-5078-4f6c-9e9b-337d5eeaf78f

**Comment by mountiny** [comment]
@DylanDylann @allgandalf @dukenv0307 I feel like this was handled somewhere recently?

**Comment by DylanDylann** [comment]
Hmmm, I am not sure but I haven't seen it before

**Comment by mountiny** [comment]
@Shahidullah-Muffakir I have tested this in staging and the code was sent just fine, can you try to find more specific reproduction steps?

**Comment by DylanDylann** [comment]
@Shahidullah-Muffakir Please reset cache and try again

**Comment by DylanDylann** [comment]
@Shahidullah-Muffakir More information, the validateCodeSent flag on the FE sometimes is wrong if we try to send the code many times. If that, resetting the cache will solve this problem.

**Comment by Shahidullah-Muffakir** [comment]
@mountiny @DylanDylann Thanks for your help! Clearing the cache after each magic code sent resolves the issue of sending another magic code.

However, as shown in the video, the `SetPersonalDetailsAndShipExpensifyCards` API returns an error.

@paultsimura , do you get the same error?

https://github.com/user-attachments/assets/1f2a24a0-1a30-4b18-b176-916faf22520c

**Comment by mountiny** [comment]
@Shahidullah-Muffakir I can see that you are getting - `402 Missing modifiedFields` error - This is because you already have all the details filled in. I will look into fixing it

**Comment by mountiny** [comment]
@DylanDylann The change to allow this was merged and it also included change to return the card data with shipped status

**Comment by mountiny** [comment]
Not deployed yet

**Comment by cristipaval** [comment]
your fix has been deployed, @mountiny, correct?

@Shahidullah-Muffakir could you please test?

**Comment by mountiny** [comment]
Yes! although noting that using the testing Plaid account you actually cannot successfully ship the cards, the command will not fail, but the cards are not shipped so a bit hard to test cc @DylanDylann who is testing something similar

**Comment by DylanDylann** [comment]
>  the command will not fail

yes, I confirmed that

**Comment by DylanDylann** [comment]
@Shahidullah-Muffakir Do you have any problem here?

**Comment by Shahidullah-Muffakir** [comment]
That's strange, now the **Get Physical Card** button isn't working at all for me. I tested it in staging and prod, cleared the cache, and even tried different browsers, but I’m still facing the issue. Not sure what I might be missing. Any ideas?

https://github.com/user-attachments/assets/5085c808-2cb8-4625-a020-bf716f50e9e4

**Comment by Shahidullah-Muffakir** [comment]
However, in the dev environment, when I click **Get Physical Card** I receive the magic code. After entering it, I no longer get the [error](https://github.com/Expensify/App/issues/55189#issuecomment-2665914933) from the API, but nothing changes, the state remains the same, and the 'Get Physical Card' button is still visible. Also, I don't see the 'Report Physical Card Loss/Damage' option.

Shouldn't the `SetPersonalDetailsAndShipExpensifyCards` endpoint return the updated card status, changing it from `Open` to `Not_Activated`? Currently, the `onyxData` in the response is empty. Or should we get the updated card status through Pusher?

https://github.com/user-attachments/assets/7404aed4-e423-4d30-b46d-023d2950a4e2

**Comment by DylanDylann** [comment]
> when I click Get Physical Card I receive the magic code. After entering it, I no longer get the https://github.com/Expensify/App/issues/55189#issuecomment-2665914933 from the API, but nothing changes, the state remains the same, and the 'Get Physical Card' button is still visible

It is expected

**Comment by DylanDylann** [comment]
@Shahidullah-Muffakir Because the original PR was reverted, please post a new proposal

**Comment by DylanDylann** [comment]
@mountiny I believa that we need a callstack agency to help solve this problem, external contributors will can't reproduce this

**Comment by mountiny** [comment]
Not even the agency workers can really reproduce this. Might have to be internal

**Comment by MitchExpensify** [comment]
@mountiny shall we make this internal? Your call!

**Comment by mountiny** [comment]
I think so, but I would make it weekly, not sure if @cristipaval wants to tackle it

**Comment by cristipaval** [comment]
if you already have context on this, feel free to take it over, @mountiny. You would do me a favor. Otherwise, I might be able to work on it late next week

**Comment by MitchExpensify** [comment]
@mountiny when do you think you'll get a chance to check this out?

**Comment by mountiny** [comment]
I'm focusing on the `stability` issue now, so it's not likely soon; I think this is the lower priority, though; correct me if I am wrong. The card is not activated yet so it cannot be used for fraud

**Comment by MitchExpensify** [comment]
I don't think that's the main consideration, it is really for the employee to be able to request a new card e.g. Lost in the post @mountiny

**Comment by jliexpensify** [comment]
@cristipaval do you have capacity to pick this up? Or should we just keep it as a `Weekly` for now?

**Comment by cristipaval** [comment]
I don't have the capacity, unfortunately. I am currently assigned to external commit and stability issues.
I'll watch it and pick it up when I clear my plate a bit.

**Comment by jliexpensify** [comment]
No worries! @cristipaval would you like me to assign you to this? What would you say the urgency would be here? Do we need to make this a `hot pick` for #migrate? cc @mountiny

**Comment by mountiny** [comment]
I will try to get to this one today or tomorrow to at least debug it more and maybe if I cannot resolve it, I could make this a first pick

**Comment by mountiny** [comment]
Got a bit sick so working reduced hours

**Comment by mountiny** [comment]
On my list to tackle soon

**Comment by jliexpensify** [comment]
Just a heads up, I am OOO until the 30th - I can sort out any payments when I get back.

**Comment by mountiny** [comment]
Catching up mostly today, will test tomorrow

**Comment by mountiny** [comment]
Card in NOT_ACTIVATED state showing both the activate and get physical card buttons which I think we should not show 

<img width="1628" alt="Image" src="https://github.com/user-attachments/assets/4e592a3e-7d36-4251-995b-d732809ddfd1" />

**Comment by mountiny** [comment]
PR from @nkdengineer merged

**Comment by mountiny** [comment]
I believe this issue is now completed! We just need to pay $250 to @DylanDylann 

@DylanDylann could you please write a regression test to add with multiple physical cards ?

**Comment by jliexpensify** [comment]
Payment Summary

- C+: @DylanDylann $250 (to be paid via New Expensify payments)

**Comment by DylanDylann** [comment]
### Regression Test Proposal

Condition: the account does not have all the private personal details to ship a card set

1. Issue a physical card to user B
2. Login to account B
3. Go to Card detail in Wallet
4. Make sure you can see the Get Physical Card button there and not the Activate card button nor the option to Report physical card loss / damageGo through the Get physical card flow
5. Once shipped, make sure the button showing is Activate card
6. Now you should also see the Report physical card loss / damage button on this card
7. Activate this card
8. Make sure there is no button to activate the card or to get physical one
9. Make sure you can still see the Report physical card loss / damage button

**Comment by Shahidullah-Muffakir** [comment]
@mountiny @jliexpensify Just wanted to mention that our PR was reverted due to reasons that I believe were outside the original scope of the PR. considering that, along with the back-and-forth and the tricky testing involved, I was hoping I could also be considered eligible for the payment

**Comment by jliexpensify** [comment]
Ah ok - I'l let @mountiny make the call here.

Vit - do we pay @Shahidullah-Muffakir $250 for his efforts?

**Comment by mountiny** [comment]
Looking back at it, I appreciate you have put in a lot of work and it was hard for you to test, however, in the end the PR caused 2 issues and revert resolved it so more work had to be done by others to investigate and fix it. We had to resolve this internally. 

Since this was not really a change in product UX / decision by product team that led to revert, I think we dont issue any payment here. Sorry for the outcome, we appreciate your contributions. I hope you can land jobs in other proposals

**Comment by DylanDylann** [comment]
> Reviewer: @DylanDylann owed $250 via NewDot

@jliexpensify I was assigned to the issue prior to being eligible for NewDot payment, so I should be paid via Upwork

**Comment by DylanDylann** [comment]
@jliexpensify Accepted it, ty!

**Comment by jliexpensify** [comment]
This new Upworks UI is SO BAD. Finally found it, paid, job closed.
