### ISSUE TITLE
[$250][HIGH] Bank account - After turning on the Make or track payments,the BA flow opens on the page where it was left

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#55453]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.87-0
**Reproducible in staging?:** Y
**Reproducible in production?:** Y
**If this was caught on HybridApp, is this reproducible on New Expensify Standalone?:**  N/A
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Navigate to https://staging.new.expensify.com/
2. Create the workspace
3. Allow Workflows
4. Navigate to workflows
5. Start the "Connect bank account flow"
6. Quit the flow in the middle
7. Click on the "Connect bank account", verify there are two options : Continue setup and Start over.
8. Dismiss the Connect bank account window
9. Turn off the "Make or track payments" toggle
10. Turn on the "Make or track payments" toggle
11. Click on the Connect bank account button

Use Regions Bank
Username: user_good | Password: pass_good
Account type: Plaid Saving (2nd option)
CompanyName: Alberta Bobbeth Charleson
CompanyTaxID: 123456789
First Name: Alberta
Last Name: Charleson

## Expected Result:
After turning on the "Make or track payments" toggle, the two options should appear to Continue setup or Start over

## Actual Result:
After turning on the "Make or track payments" toggle, the bank account flow opens on the page where it was left. The user can see all information they put earlier

## Workaround:
Unknown

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Standalone
- [ ] Android: HybridApp
- [ ] Android: mWeb Chrome
- [ ] iOS: Standalone
- [ ] iOS: HybridApp
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

  
</details> 

https://github.com/user-attachments/assets/a54f2c38-b786-424e-a9d1-b8a075bd0652

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021881877923986389660</li>
        <li>Upwork Job ID: 1881877923986389660</li>
        <li>Last Price Increase: 2025-03-12</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @abdulrahuman5196</details>

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user starts the bank account connection flow and quits in the middle, then toggles off and on the "Make or track payments" setting, the app should show two options: "Continue setup" or "Start over". Instead, it's directly opening the bank account flow where it was left off.
### What is the root cause of that problem?
The root cause is premature state initialization. When the "Make or track payments" toggle is turned on, the reimbursementAccount data goes through three states:

1. undefined
2. empty object {}
3. populated with actual data

The component is making decisions about whether to show the continue/start over options too early in this process, when reimbursementAccount is either undefined or empty. 
1. this cause this to return false
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L183C14-L183C31
2.then this returns false
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L191
3. hence the initial state is set as false here:
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L207
### What changes do you think we should make in order to solve the problem?

1. Remove the initial state calculation from shouldShowContinueSetupButton useState hook - start with false as a placeholder
`    const [shouldShowContinueSetupButton, setShouldShowContinueSetupButton] = useState(false);
`
2.Add a useEffect that waits for reimbursementAccount to be fully loaded before deciding whether to show the continue/start over options
```javascript
    useEffect(() => {
        // Only set the state once we have the actual data
        if (reimbursementAccount !== undefined && !reimbursementAccount.isLoading) {
            setShouldShowContinueSetupButton(getShouldShowContinueSetupButtonInitialValue());
        }
    }, [reimbursementAccount, route]);
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

NA
### What alternative solutions did you explore? (Optional)
NA

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user starts the bank account connection flow and quits in the middle, then toggles off and on the "Make or track payments" setting, the app should show two options: "Continue setup" or "Start over". Instead, it's directly opening the bank account flow where it was left off.
### What is the root cause of that problem?
The root cause is premature state initialisation. When the "Make or track payments" toggle is turned on, the reimbursementAccount data goes through three states:

1. undefined
2. empty object {}
3. populated with actual data

The component is making decisions about whether to show the continue/start over options too early in this process, when reimbursementAccount is either undefined or empty. 
1. this cause this to return false
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L183-L185

2.then this returns false
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L183-L184
3. hence the initial state is set as false here:
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L207
### What changes do you think we should make in order to solve the problem?

1. Remove the initial state calculation from shouldShowContinueSetupButton useState hook - start with false as a placeholder
`    const [shouldShowContinueSetupButton, setShouldShowContinueSetupButton] = useState(false);
`
2.Add a useEffect that waits for reimbursementAccount to be fully loaded before deciding whether to show the continue/start over options
```javascript
    useEffect(() => {
        // Only set the state once we have the actual data
        if (reimbursementAccount !== undefined && !reimbursementAccount.isLoading) {
        setShouldShowContinueSetupButton(getShouldShowContinueSetupButtonInitialValue());
        }
        }, [reimbursementAccount, route]);
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

NA
### What alternative solutions did you explore? (Optional)
NA

https://github.com/user-attachments/assets/32fc32a6-df7e-4ad0-9cea-5c8430847606

**Comment by Shahidullah-Muffakir** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
When a user starts the bank account connection flow and quits in the middle, then toggles off and on the "Make or track payments" setting, the app should show two options: "Continue setup" or "Start over". Instead, it's directly opening the bank account flow where it was left off.
### What is the root cause of that problem?
The root cause is premature state initialisation. When the "Make or track payments" toggle is turned on, the reimbursementAccount data goes through three states:

1. undefined
2. empty object {}
3. populated with actual data

The component is making decisions about whether to show the continue/start over options too early in this process, when reimbursementAccount is either undefined or empty. 
1. This cause this to return false
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L183-L185

2.Then this returns false
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L183-L184
3. hence the initial state is set as false here:
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L207
### What changes do you think we should make in order to solve the problem?

1. Remove the initial state calculation from shouldShowContinueSetupButton useState hook - start with false as a placeholder
`    const [shouldShowContinueSetupButton, setShouldShowContinueSetupButton] = useState(false);
`
2.Add a useEffect that waits for reimbursementAccount to be fully loaded before deciding whether to show the continue/start over options
```javascript
    useEffect(() => {
        // Only set the state once we have the actual data
        if (reimbursementAccount !== undefined && !reimbursementAccount.isLoading) {
        setShouldShowContinueSetupButton(getShouldShowContinueSetupButtonInitialValue());
        }
        }, [reimbursementAccount, route]);
```
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

NA
### What alternative solutions did you explore? (Optional)
We can update the condition for showing `FullScreenLoadingIndicator`, if the `reimbursementAccount` is not fully available yet then show the loading screen
https://github.com/Expensify/App/blob/86b9c79672ffbd9e5eee8eb41472d41d9d2660fc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L424-L426



https://github.com/user-attachments/assets/32fc32a6-df7e-4ad0-9cea-5c8430847606

**Comment by huult** [comment]
🚨 Edited by **proposal-police**: This proposal was **edited** at 2025-01-20 04:58:52 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.

After turning on the Make or track payments,the BA flow opens on the page where it was left

### What is the root cause of that problem?

When we disable `Make or track payments`, the `REIMBURSEMENT_ACCOUNT` data will become `undefined` due to the `SetWorkspaceReimbursement` call, which returns a `null` reimbursementAccount value.

So, when we open the `Connect bank account` modal, the `REIMBURSEMENT_ACCOUNT` data will be refetched, but the `shouldShowContinueSetupButton` is set before the `REIMBURSEMENT_ACCOUNT` data is loaded. This causes the issue.

Called refetch `REIMBURSEMENT_ACCOUNT` data

https://github.com/Expensify/App/blob/478a3fd4a96b2fee8f2326a6087fb5cc16d03884/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L290


`shouldShowContinueSetupButton` is set before `REIMBURSEMENT_ACCOUNT` is loaded.

https://github.com/Expensify/App/blob/478a3fd4a96b2fee8f2326a6087fb5cc16d03884/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L207


### What changes do you think we should make in order to solve the problem?

To resolve this issue, we must fully load `REIMBURSEMENT_ACCOUNT` before opening the `Connect bank accoun`t modal to avoid `shouldShowContinueSetupButton` being set while the `REIMBURSEMENT_ACCOUNT` data is still loading. To implement this, we can do something like the following:

1. We check if `Make or track payments` is `enabled` but `reimbursementAccount` is `undefined`, then we should call `openReimbursementAccountPage`

https://github.com/Expensify/App/blob/5d6438912d271c71c283718ae962dbde1fd54ecc/src/pages/workspace/workflows/WorkspaceWorkflowsPage.tsx#L217

add this:

```diff
    if (!!isEnabled && !reimbursementAccount) {
        BankAccounts.openReimbursementAccountPage('', '', '', route.params.policyID);
    }
```

<details>
<summary>POC</summary>

https://github.com/user-attachments/assets/3e27ea29-8894-491f-8627-2a9c7d363cef

</details>

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?


I think this issue is a UI bug and does not require testing.

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by VictoriaExpensify** [comment]
Agree we should fix this. i think #quality is the best fit for the issue.

**Comment by VictoriaExpensify** [comment]
Hey @abdulrahuman5196 - there's a couple of good looking proposals there, can you please take a look?

**Comment by abdulrahuman5196** [comment]
Hi, @VictoriaExpensify  I would be unavailable for couple of days. Could you kindly add the appropriate labels for another random C+ to take over? Unassigning myself to avoid delays.

**Comment by abdulrahuman5196** [comment]
Oh this was still not re-assigned 🤕 . I am back myself, I will take a look today.

**Comment by wildan-m** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

Bank account - Upon enabling the "Make or track payments" option, the user will be directed to the BA flow page where they last left off.

### What is the root cause of that problem?

In this useEffect 

https://github.com/Expensify/App/blob/5d6438912d271c71c283718ae962dbde1fd54ecc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L308-L314

We only evaluate `shouldShowContinueSetupButton` when the prevReimbursementAccount is not null, but in the above reproduction step,  initial reimbursementAccount is undefined, so it doesn't re-evaluate the `shouldShowContinueSetupButton`.

### What changes do you think we should make in order to solve the problem?
We can add a new state `isCheckingShowContinueSetupButton` that will perform `shouldShowContinueSetupButton` evaluation if the initial `reimbursementAccount` is undefined. Add:

src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx
```tsx

    const [isCheckingShowContinueSetupButton, setIsCheckingShowContinueSetupButton] = useState(!reimbursementAccount);

```

Modify the useEffect logic to

```tsx

            if (
                (prevReimbursementAccount &&
                prevReimbursementAccount.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE &&
                reimbursementAccount?.pendingAction !== prevReimbursementAccount.pendingAction) || isCheckingShowContinueSetupButton
            ) {
                setShouldShowContinueSetupButton(hasInProgressVBBA());
            }

```

And hold the loading until the evaluation completed.

Change

https://github.com/Expensify/App/blob/5d6438912d271c71c283718ae962dbde1fd54ecc/src/pages/ReimbursementAccount/ReimbursementAccountPage.tsx#L433

To 
```tsx

        (!hasACHDataBeenLoaded || isLoading || isCheckingShowContinueSetupButton) &&

```



[Branch for this solution](https://github.com/Expensify/App/compare/main...wildan-m:wildan/fix/55453-continue-bank-account?expand=1)

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
UI bug, don't need automated test
### What alternative solutions did you explore? (Optional)

**Comment by abdulrahuman5196** [comment]
Checking now

**Comment by abdulrahuman5196** [comment]
@VictoriaExpensify I don't see this issue anymore. Are you able to repro this issue?


https://github.com/user-attachments/assets/02412874-819c-4255-aaef-0a18bd02f877

**Comment by mallenexpensify** [comment]
👀 plz @VictoriaExpensify, also through retest-weekly on here. 
Made HIGH for now so we can either move this along or get it closed cuz we can't repro.  Thx

**Comment by mallenexpensify** [comment]
[Posted in #qa to get a retest](https://expensify.slack.com/archives/C9YU7BX5M/p1741904480884429)

**Comment by izarutskaya** [comment]
Issue is not reproducible
 
https://github.com/user-attachments/assets/a6d7fa0b-123d-4de4-90e2-46d0cc1e05ef
https://github.com/user-attachments/assets/ea139b21-5a3e-4fe5-abfc-144c43cfe433

**Comment by mvtglobally** [comment]
Issue not reproducible during KI retests. (First week)

**Comment by VictoriaExpensify** [comment]
Closing this issue as it's no longer reproducible. Thanks everyone.
