### ISSUE TITLE
Investigate HybridApp crash "Error receiving broadcast Intent"

### ISSUE THREAD

**Issue by mateuuszzzzz** [Expensify/App#58453]
[Crashlytics](https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg/issues/6da9acfd719b64ecec55fbb173c2a2b9?time=last-seven-days&versions=9.1.9.8%20(509010908)&types=crash&deviceCategories=Mobile:samsung%EF%BF%BFSM-A135F%E2%87%92Galaxy%20A13;Mobile:samsung%EF%BF%BFSM-A136B%E2%87%92Galaxy%20A13%205G;Mobile:samsung%EF%BF%BFSM-S136DL%E2%87%92Galaxy%20A13%205G;Mobile:samsung%EF%BF%BFSM-A135U%E2%87%92Galaxy%20A13&os=13&sessionEventKey=67D1DD9302DB00017E4FF7397747F82D_2059449707327903522)

```
Fatal Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=com.expensify.reactnativebackgroundtask.TASK_ACTION flg=0x10 (has extras) } in com.expensify.reactnativebackgroundtask.ReactNativeBackgroundTaskModule$taskReceiver$1@f19da12
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1928)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by mateuuszzzzz** [comment]
So far, I haven't had any luck reproducing it

**Comment by sakluger** [comment]
@mountiny what do you need me to do for this bug? Do I need to add external or internal?

**Comment by mountiny** [comment]
@mateuuszzzzz will handle it, should be all good

**Comment by mateuuszzzzz** [comment]
I wasn't able to reproduce it, but I found similar issue https://github.com/facebook/react-native/issues/48756 and probably I will be able to apply similar reproduction steps as those suggested in comments (via Samsung Remote Test Lab)

**Comment by mateuuszzzzz** [comment]
Still not reproducible, but I have an idea. Galaxy A13 is rather low end device. The linked crash suggests that things are not fully initialized when we attempt to use them.

Initialisation of background tasks happens early in `App.tsx` ([source](https://github.com/Expensify/App/blob/f16475d4bc249be9db8493a9d9a43c50b5c7fa47/src/App.tsx#L43)).

Perhaps we could delay this initialisation a bit on JS side. Alternatively we could try to use `needsEagerInit` for this Turbo Module. cc: @szymonrybczak as you are the author of those changes

**Comment by gedu** [comment]
I will give a hand to @szymonrybczak given that he isn't working on Expensify.

**Comment by mateuuszzzzz** [comment]
@gedu do you have any thoughts on that [proposal](https://github.com/Expensify/App/issues/58453#issuecomment-2733342019)?

**Comment by gedu** [comment]
Hey @mateuuszzzzz I tried to reproduce it but no luck, I would try first just the `needsEagerInit`, create an ad-hoc build and let the user test it and check how it goes, before trying to delay something on JS, what do you think?

**Comment by mateuuszzzzz** [comment]
> Hey [@mateuuszzzzz](https://github.com/mateuuszzzzz) I tried to reproduce it but no luck, I would try first just the `needsEagerInit`, create an ad-hoc build and let the user test it and check how it goes, before trying to delay something on JS, what do you think?

100% agree, I'll prepare PRs and @NJ-2020 should be able to test it as he experiences this issue

**Comment by mateuuszzzzz** [comment]
@NJ-2020 can you try this build? https://ad-hoc-expensify-cash.s3.amazonaws.com/android/58990-hybrid/index.html

**Comment by mateuuszzzzz** [comment]
😕 I talked with @WoLewicki about this issue, we have a few ideas what could possibly fix this so I'll be checking this later today / tomorrow

**Comment by mateuuszzzzz** [comment]
@mountiny, how feasible is it to execute this background task immediately on app startup? Would it be problematic if we next 15 minutes to run it?

I can add simple `null` check in the implementation to prevent this crash, but it will wait next 15 minutes to execute this task.
Our next option here is to restart the task if the event cannot be emitted yet.

Task name for reference: `FLUSH-SEQUENTIAL-QUEUE-BACKGROUND-FETCH`

**Comment by mateuuszzzzz** [comment]
@NJ-2020 I prepared new fix, could you re-test it once adhoc builds are ready? https://github.com/Expensify/App/pull/59232

**Comment by Julesssss** [comment]
> Initialisation of background tasks happens early in App.tsx ([source](https://github.com/Expensify/App/blob/f16475d4bc249be9db8493a9d9a43c50b5c7fa47/src/App.tsx#L43)). Perhaps we could delay this initialisation a bit on JS side

A brief delay sounds reasonable but I agree with 15 minutes being too long. 

> could you re-test it once adhoc builds are ready? https://github.com/Expensify/App/pull/59232

Nice idea, I just triggered an Android build.

**Comment by mountiny** [comment]
@NJ-2020 Thanks! What Device and android version do you use? I wonder what is so special about your setup

**Comment by mountiny** [comment]
@mateuuszzzzz Could you please test using that configuration? 

@NJ-2020 Is that on physical device only? What steps exactly do you take? Is it logging in to existing account eor even any new account?

**Comment by mateuuszzzzz** [comment]
> [@mateuuszzzzz](https://github.com/mateuuszzzzz) Could you please test using that configuration?
> 
> [@NJ-2020](https://github.com/NJ-2020) Is that on physical device only? What steps exactly do you take? Is it logging in to existing account eor even any new account?

@mountiny I was testing it using mentioned configuration, but I wasn't able to reproduce

**Comment by mateuuszzzzz** [comment]
@NJ-2020  I was trying to find this crash in Crashlytics, but there's no record of it on the Galaxy A13 in the HybridApp Adhoc build. Do you think you could connect your phone to Logcat and check the logs during the crash?

**Comment by mateuuszzzzz** [comment]
I only found one from March 31

https://console.firebase.google.com/u/0/project/expensify-mobile-app/crashlytics/app/android:org.me.mobiexpensifyg.adhoc/issues/efa47ac9c42ab1fb686a258a8b0136a6?time=last-seven-days&versions=9.1.20.0%20(509012000)&sessionEventKey=67eabb8700da00015139dee53c48baab_2066449168324895620

**Comment by mateuuszzzzz** [comment]
Thanks @NJ-2020 ! I think now's the crash looks even worse 😆 But I have one more idea to try. We must ensure that everything on JS thread is initialised when we use `BackgroundTasks` I will re-adjust my PR and ask someone to create another adhoc build

**Comment by mateuuszzzzz** [comment]
@NJ-2020 new build is ready: https://ad-hoc-expensify-cash.s3.amazonaws.com/android/59232-hybrid/index.html

**Comment by mateuuszzzzz** [comment]
Hmmmm originally, our issue was that we wanted to use the event emitter for our Turbo Module before it was set. Now, we are trying to set the event emitter callback when the reference to the Turbo Module is `null`. It's pretty nasty race condition, but we can try to re-enable eager init for this TurboModule and still delay registration of background tasks. I adjusted PR one more time. Let's see if it works this time

**Comment by mountiny** [comment]
Yeah lets do that thanks

**Comment by mateuuszzzzz** [comment]
@mountiny can we run adhoc build [here](https://github.com/Expensify/App/pull/60114)? I noticed that it was crashing on my local machine when build was triggered via RNEF, but maybe it's local issue. `./gradlew installDebug` worked fine tho.

**Comment by mountiny** [comment]
Done

**Comment by mateuuszzzzz** [comment]
@NJ-2020 can you try to reproduce on this build? https://ad-hoc-expensify-cash.s3.amazonaws.com/android/60114-hybrid/index.html

**Comment by mateuuszzzzz** [comment]
Could you share the logs from your device?

**Comment by gedu** [comment]
@mateuuszzzzz given that it is the recommended one, what would be the replacement for `EventEmitter`  if we need to send multiple time value from `native` to `JS`.
Couldn't be a bug from the RN core?

**Comment by mateuuszzzzz** [comment]
> [@mateuuszzzzz](https://github.com/mateuuszzzzz) given that it is the recommended one, what would be the replacement for `EventEmitter` if we need to send multiple time value from `native` to `JS`. Couldn't be a bug from the RN core?

@gedu it is a bug in React Native core. There have been attempts to fix it directly in the core, but it still crashes on some architectures. I was thinking of using `NativeEventEmitter` or `DeviceEventEmitter` instead of the new codegen type that we're currently using. I'll prepare a PR and ping you to review it.

**Comment by gedu** [comment]
Do we know if this crash happens to more users or/and more devices?

**Comment by Julesssss** [comment]
Still non-stock Android: 

<img width="444" alt="Image" src="https://github.com/user-attachments/assets/e2ffbd36-7470-4a17-afc1-9d1e4de99b87" />

I will say that the occurrences are less frequent now though. 

[org.me.mobiexpensifyg_issue_6da9acfd719b64ecec55fbb173c2a2b9_crash_session_6807F9B403280001793EF84F7AF3D01D_DNE_0_v2.log](https://github.com/user-attachments/files/19871209/org.me.mobiexpensifyg_issue_6da9acfd719b64ecec55fbb173c2a2b9_crash_session_6807F9B403280001793EF84F7AF3D01D_DNE_0_v2.log)
[org.me.mobiexpensifyg_issue_6da9acfd719b64ecec55fbb173c2a2b9_crash_session_6807F9B403280001793EF84F7AF3D01D_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/19871208/org.me.mobiexpensifyg_issue_6da9acfd719b64ecec55fbb173c2a2b9_crash_session_6807F9B403280001793EF84F7AF3D01D_DNE_0_v2_stacktrace.txt)

**Comment by Julesssss** [comment]
No update, next step is to trial [this](https://github.com/Expensify/App/issues/58453#issuecomment-2820735896) EventEmitter fix.

**Comment by sakluger** [comment]
Hey @mateuuszzzzz, any update on the EventEmitter fix?

**Comment by mateuuszzzzz** [comment]
> Hey [@mateuuszzzzz](https://github.com/mateuuszzzzz), any update on the EventEmitter fix?

Hi! I was OOO from May 1st to May 4th.  I've started preparing the `EventEmitter` PR.

**Comment by mateuuszzzzz** [comment]
Great to here! I think that second crash might have a different origin 🤔 I will investigate that in Crashlytics

**Comment by mateuuszzzzz** [comment]
Not an overdue, we're waiting for confirmation that second crash is not related to background tasks

**Comment by sakluger** [comment]
Hey @NJ-2020, any luck getting logs from your device related to the notification crash?

**Comment by mateuuszzzzz** [comment]
I can give it one more try and see if I’m able to reproduce it.

At the moment, we have a fix in place that prevents the Expensify app from crashing. However, there's still one issue that @NJ-2020 experienced after accepting a notification, so we cannot merge the current fix without confirming that it's unrelated.

**Comment by mateuuszzzzz** [comment]
Hi! Good info, this crash is related to `libjsc.so` which is our OldDot JS runtime so it's not related to ReactNativeBackgroundTasks.

**Comment by mateuuszzzzz** [comment]
Marked https://github.com/Expensify/App/pull/61479 as ready for a review

**Comment by sakluger** [comment]
@mateuuszzzzz mind completing the BZ checklist for this one?

Also, it looks like @ahmedGaber93 reviewed the linked PR - do you require payment here?

**Comment by ahmedGaber93** [comment]
@sakluger yes please, I reviewed the PR as C+

**Comment by ahmedGaber93** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [x] 1z. Other: Firebase Crashlytics reports

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [x] 3z. Other: SWM expert

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: https://github.com/Expensify/App/pull/54616/files#r2127629815
    No offending PR, the root cause comes from React Native itself, but I left a comment on the PR that implement this part to be aware of this issue.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A.

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

No regression test required, the issue has been reported from Firebase Crashlytics, and it is hard to reproduce.

**Comment by ahmedGaber93** [comment]
@sakluger checklist is completed.

**Comment by sakluger** [comment]
Summarizing payment on this issue:

Contributor+: @ahmedGaber93 $250, please request on Newdot
