### ISSUE TITLE
[Due for payment 2025-07-15] [$250] Tooltip-Tooltip on the "expense reports" filter is not displayed

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#61099]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.33-8
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/58721
**Email or phone of affected tester (no customers):** agexptest+pr2904.4@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Windows 10/ Chrome, Samsung S23FE/ Android 14
**App Component:** Other

## Action Performed:
1. Create an account on staging.expensify.com (OldDot), choosing the 10+ employees option on signup, so that you are directed to Expensify Classic
2. In the browser console, run the following code snippet:
NVP.set('tryNewDot', {
    "classicRedirect": {
        "dismissed": "false",
        "timestamp": "2024-10-28 20:04:24.610"
    },
    "nudgeMigration": {
        "timestamp": "2024-10-28 20:04:24.610"
    }
})
3. Sign out and back in
4. Click on the "Try New Expensify" button in the right panel
5. You will get redirected to NewDot and see the modal
6. Dismiss the modal
7. Verify that the tooltip on the "expense reports" filter is displayed

## Expected Result:
Tooltip on the "expense reports" filter is displayed.

## Actual Result:
Tooltip on the "expense reports" filter is not displayed.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/f15201fa-857b-4331-811e-8af5f42dff38

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021922333040188144414</li>
        <li>Upwork Job ID: 1922333040188144414</li>
        <li>Last Price Increase: 2025-06-03</li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @CortneyOfstad</details>

**Comment by jponikarchuk** [comment]
@CortneyOfstad QA team still can reproduce this issue on build v9.1.43-7

https://github.com/user-attachments/assets/1bd9eb5c-5656-44f3-9ac8-df1a5426fdc2

**Comment by CortneyOfstad** [comment]
Thanks @jponikarchuk!

**Comment by cch5ng** [comment]
hi, I was trying to look for patterns around tooltips in the code. one search led to this file:

https://github.com/Expensify/App/blob/main/.github/ISSUE_TEMPLATE/TooltipsTemplate.md

is there already an internal process for requesting additional tooltips? is that the case here? it seems like this would require a little back and forth between the person enabling it in code and perhaps a tech writer who provides content (I used to work as a tech writer before getting into dev).

otherwise, if the tooltip was implemented in the past and is simply broken currently, these were my other questions...

hi, is the tooltip working correctly on the classic expensify expense reports filter? I'm trying to understand what is broken/missing but then I need a working control to compare to. after I create a new account in classic expensify and try to go to Reports (LHN) and hover over the Expense Filter icon, I don't see anything pop up (no text or popup or modal). is there some example of a working tooltip to reference?

**Comment by lizardwalk5** [comment]
hi, I was trying to look for patterns around tooltips in the code. one search led to this file:

https://github.com/Expensify/App/blob/main/.github/ISSUE_TEMPLATE/TooltipsTemplate.md

is there already an internal process for requesting a new tooltip? is that the case here? it seems like this would require a little back and forth between the person enabling it in code and perhaps a tech writer who provides content (I used to work as a tech writer before getting into dev). if I can work on it (external contributor), can I get access to the content here (?): https://stackoverflowteams.com/c/expensify/questions/20762

otherwise, if the tooltip was implemented in the past and is simply broken currently, these were my other questions...

hi, is the tooltip working correctly on the classic expensify expense reports filter? I'm trying to understand what is broken/missing but then I need a working control to compare to. after I create a new account in classic expensify and try to go to Reports (LHN) and hover over the Expense Filter icon, I don't see anything pop up (no text or popup or modal). is there some example of a working tooltip to reference?

**Comment by jponikarchuk** [comment]
@CortneyOfstad The tooltip should see as marked in the red square.
Step 7 When navigated to NewDot open Reports tub in LHN bottom and verify that the tooltip on the "expense reports" filter is not displayed, but it should be present.


![Image](https://github.com/user-attachments/assets/3beeeeda-a141-4e1b-943d-f7f20c1f1150)

**Comment by lizardwalk5** [comment]
@jponikarchuk thanks. I am looking at the Expense Reports (LHN) > search filter and it looks like it has a tooltip (automatically displays) in staging v9.1.49-1 (screenshot attached)... macOS/Chrome. is this the same tooltip that you were looking for?

<img width="650" alt="Image" src="https://github.com/user-attachments/assets/40f29d86-bd6a-4b3a-8f4e-9b7ce550878c" />

**Comment by jponikarchuk** [comment]
@lizardwalk5 According to PR video it's not expected tooltip.

**Comment by lizardwalk5** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

In newDot, there is a missing tooltip. To reproduce, use large device and from the LHN, select Reports. In the next column, select Reports. A tooltip should display below the menu item (but it was not rendering).

### What is the root cause of that problem?

In SearchTypeMenu (component), there was a variable, 'shouldShowTooltip' which would always evaluate to false because it was dependent on another variable, 'shouldShowExpenseReportsTypeTooltip' which appeared to be undefined. I could not find a definition for it within the file and also could not find it getting passed in as a param from elsewhere (I could not find it referenced in the repo under /src). I updated the code like this so that if the user selects 'Expense Reports', the tooltip should display:

`const shouldShowTooltip = item.translationPath === 'common.reports' && focused;`

https://github.com/Expensify/App/blob/2db88255fb6ae2029c566e4eeedf7f1213278685/src/pages/Search/SearchTypeMenu.tsx#L204

Note: In the latest dev code/build, I'm not seeing tooltips appear for other elements. I'm not clear why.

------

There is a section that might be cleaned up but I did not do a lot of testing there. Some variables looked redundant and also unused.

https://github.com/Expensify/App/blob/2db88255fb6ae2029c566e4eeedf7f1213278685/src/pages/Search/SearchTypeMenu.tsx#L51-L60

**Comment by CortneyOfstad** [comment]
@jponikarchuk can you provide an update on @parasharrajat's comment [here](https://github.com/Expensify/App/issues/61099#issuecomment-2902622586)?

**Comment by lizardwalk5** [comment]
@CortneyOfstad fyi that I put a first proposal up on the issue, although I edited it later last night so it shows up second. it's up to you who gets the job assignment but just fyi. I did spend a lot of time to track why the tooltip would not render...

**Comment by jponikarchuk** [comment]
@parasharrajat The behavior for the "Control expenses for a larger organization" option has changed. So, steps 1 and 2 can't be reproduced anymore. In any case, tester finished the onboarding process, but the tooltip still doesn't appear.

https://github.com/user-attachments/assets/8ae78df4-8531-464f-a7da-77727d3fce2d

**Comment by CortneyOfstad** [comment]
@getusha can you please provide follow-up on the proposals above by EOD?

**Comment by getusha** [comment]
Doesn't seem to be reproducible on staging anymore, will test `main`

**Comment by CortneyOfstad** [comment]
Thanks @getusha and please keep us posted on what you find 👍

**Comment by CortneyOfstad** [comment]
Hey @getusha! Just a heads up that I am heading OoO this afternoon (6/3) to Monday (6/9). If any action is needed from a BZ perspective, please reapply the label or reach out in Slack. Otherwise, I will address it right away when I am back. Thanks!

**Comment by CortneyOfstad** [comment]
Having QA retest — will follow up as soon as I hear back 👍

**Comment by IuliiaHerets** [comment]
@CortneyOfstad Tester can reproduced the issue, build - v9.1.58-0

https://github.com/user-attachments/assets/3a910ac7-295f-4c57-b55a-ff7409d01f18

**Comment by getusha** [comment]
>In addition, to test this on the dev environment, I disabled these 3 lines to simulate where the user dismissed the welcome modal

I don't think it's how it works, you can copy the redirection link from oldDot and test. the reason your solution appears to work could be because you're commenting that section.

**Comment by getusha** [comment]
Posted on slack for more proposals, https://expensify.slack.com/archives/C01GTK53T8Q/p1749189567157589

**Comment by CortneyOfstad** [comment]
Thank you @getusha!!

**Comment by dmkt9** [comment]
🚨 Edited by **proposal-police**: This proposal was **edited** at 2025-06-09 03:15:39 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Tooltip on the "expense reports" filter is not displayed.

### What is the root cause of that problem?
1. The `translationPath` has been changed and no longer includes `common.expenseReports`, so the tooltip will never be displayed.  
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/pages/Search/SearchTypeMenu.tsx#L224
Function to create the menu item list:
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/libs/SearchUIUtils.ts#L1049-L1082
2. The `shouldShow` function of `EXPENSE_REPORTS_FILTER` depends on `hasBeenAddedToNudgeMigration`; however, the backend does not send `tryNewDot?.nudgeMigration?.timestamp`, which causes the `shouldShow` function to always return `false`.
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/components/ProductTrainingContext/index.tsx#L54
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/components/ProductTrainingContext/TOOLTIPS.ts#L129-L130

### What changes do you think we should make in order to solve the problem?
1. Correct the `translationPath` to the proper value. In the future, the `translationPath` used in the menu should be stored as a CONST variable to avoid repeated mistakes.  
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/pages/Search/SearchTypeMenu.tsx#L224
```js
const shouldShowTooltip = item.translationPath === 'common.reports' && !focused && shouldShowExpenseReportsTypeTooltip;
```
2. Correct data for `tryNewDot?.nudgeMigration`:
- Update the backend to send the correct data for `tryNewDot?.nudgeMigration`.
- Alternatively, we can fix it on the frontend by:
    - Since the transition from OD to ND definitely goes through the route `TRANSITION_BETWEEN_APPS`  
    https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/ROUTES.ts#L26
    - Therefore, we could manually add the onyx data similar to prompt to open in desktop app `promptToOpenInDesktopApp`
    https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/components/DeeplinkWrapper/index.website.tsx#L23-L42
- Alternatively, remove `hasBeenAddedToNudgeMigration`. I think this tooltip is still appropriate even if it's not specifically about migrating from OD.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
N/A

### What alternative solutions did you explore? (Optional)
N/A

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Test:**

https://github.com/user-attachments/assets/da906886-6515-484d-b41d-26027ffc4efa

**Comment by getusha** [comment]
>Update the backend to send the correct data for tryNewDot?.nudgeMigration.

Thanks for the proposal @dmkt9 
Since this was reproducible before we changed the translation path, i am pulling internal engineer to look the BE side.

>Conditions: role = Admin (in at least 1 workspace), the user is on the Reports tab and the nudgeMigration.timestamp is not null.

These are the conditions to show the tooltip. from https://github.com/Expensify/App/issues/57045

🎀 👀 🎀

**Comment by mjasikowski** [comment]
Looking at it today

**Comment by mjasikowski** [comment]
Looking at the backend, currently `nudgeMigration.timestamp` is only set when policies are migrated to NewDot via the `MigratePolicies` command.

@CortneyOfstad do you know under what circumstances this tooltip should be showing? Should it be also showing when the user transitions via the "try new expensify" button? Seeing that the content of the tooltip is "Welcome! Find all of your company's reports here", I think it makes sense. Putting that into every transition from OldDot to NewDot would be a bit of an overkill in my taste.

It also doesn't make much sense to enable this for new accounts coming from NewDot invitiations, because they may have not used OldDot before.

**Comment by CortneyOfstad** [comment]
> Seeing that the content of the tooltip is "Welcome! Find all of your company's reports here", I think it makes sense.Putting that into every transition from OldDot to NewDot would be a bit of an overkill in my taste.

> It also doesn't make much sense to enable this for new accounts coming from NewDot invitiations, because they may have not used OldDot before.

I agree with this 100% @mjasikowski 

Does that work with your proposal, or will you need to adjust?

**Comment by dmkt9** [comment]
> Does that work with your proposal, or will you need to adjust?

@CortneyOfstad @c3024 From what I understand, there’s nothing wrong with the backend. So we only need to fix the frontend, right?

**Comment by mjasikowski** [comment]
@dmkt9 that's correct. @getusha are we good to go with @dmkt9's proposal?

**Comment by CortneyOfstad** [comment]
@getusha — are we good with @dmkt9's proposal? Thanks!

**Comment by CortneyOfstad** [comment]
Bump @getusha on the comment [here](https://github.com/Expensify/App/issues/61099#issuecomment-2969543106)

**Comment by getusha** [comment]
@dmkt9 only modifying the translation path condition won't fix it, I am assuming that leaves us with "do nothing"

**Comment by dmkt9** [comment]
@getusha Yes, but if we don't fix it, the tooltip will never appear in every case.

**Comment by getusha** [comment]
@mjasikowski what do you say? Do nothing for this case?

**Comment by mjasikowski** [comment]
@getusha @dmkt9 the translation path needs to be fixed so it appears correctly even if the conditions for its appearance are special/rare, even just in case it will be used elsewhere in the future.

**Comment by getusha** [comment]
Lets fix the translation path. we can assign @dmkt9 https://github.com/Expensify/App/issues/61099#issuecomment-2949618593. however we need to remove this case from testrail.
🎀 👀 🎀 C+ Reviewed

**Comment by CortneyOfstad** [comment]
Thank you @mjasikowski!

**Comment by CortneyOfstad** [comment]
Not overdue!

**Comment by dmkt9** [comment]
@getusha PR is ready

**Comment by getusha** [comment]
# BugZero Checklist:

- [x] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [x] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [x] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [x] 3d. QA
  - [ ] 3z. Other:

</details>

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: N/A We decided on a different expected result and fixed an issue that would have affected every scenario due to the implementation of the Suggested Search feature.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/a

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

I don't think we need one, and we should probably remove the steps in the OP from the test cases we have.

**Comment by garrettmknight** [comment]
$250 approved for @getusha
