### ISSUE TITLE
mWeb- Composer loses focus after emoji is added during message edit

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#62703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.1.51-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/62071
**Email or phone of affected tester (no customers):** htad26+fgjfkh@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Tecno Spark 8/Chrome
**App Component:** Chat Report View

## Action Performed:
1. Open the app on mobile web
2. Navigate to any chat > Send any message
3. Long press on the message and choose Edit
4. Tap the emoji picker and select any emoji to insert into the message.
5. Observe the edit composer after adding the emoji

## Expected Result:
The emoji is inserted, and the message composer remains focused so the user can continue typing.

## Actual Result:
After inserting the emoji, the composer loses focus, requiring the user to tap the composer again to continue editing.

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/706dfa77-2e53-4a14-b256-337e6c35a8d7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by zanyrenney** [comment]
Hey @eVoloshchak I just retested this and I cannot reproduce. Are you able to?

**Comment by eVoloshchak** [comment]
I can reproduce this one with the test steps provided (mWeb Chrome)

https://github.com/user-attachments/assets/5604adc2-f858-4423-909e-ae31e844fb09

Also tried reproducing this on native (HybridApp), but it works as expected there, so this definately a bug

**Comment by marcaaron** [comment]
Pinged in Slack. With a reproduction hopefully we will get some proposals.

**Comment by Eskalifer1** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
mWeb- Composer loses focus after emoji is added during message edit
### What is the root cause of that problem?
The main reason for this behavior is a problem with the focus check. The bug was also reproduced in IOS on mweb. I was also able to reproduce this bug not only when editing, but also when creating a comment

In my opinion, the reason for this bug is that focusing works a little differently on mobile devices than on PCs, because there is no mouse cursor, so focusing works a little differently. The problem occurs in the onModalHide function:
https://github.com/Expensify/App/blob/4f5bde6ee00f8381f1c949b37e14b65ed84e146b/src/pages/home/report/ReportActionItemMessageEdit.tsx#L526-L532

I haven't really been able to pinpoint the problem, but I think it might have something to do with the fact that the emoji functions work with ref:
https://github.com/Expensify/App/blob/4f5bde6ee00f8381f1c949b37e14b65ed84e146b/src/libs/actions/EmojiPickerAction.ts#L52

Therefore, at the moment when the onModalHide function is called, we still have the button element in focus, so we get into an if and the focus does not occur
### What changes do you think we should make in order to solve the problem?

Since getting the active element when the function is thrown causes this bug, I suggest moving the getting of an active element from this function to the component that renders the EmojiPicker, so we can guarantee that we always get the correct element in focus

Move this line to the component:
```ts
const activeElementId = DomUtils.getActiveElement()?.id;
``` 
(Do the same for the creation component)

For reasons unknown to me, an error occurs on android(on IOS i coudn't reproduce that) in the edit component when trying to focus, which comes from this line:
https://github.com/Expensify/App/blob/4db7a1f48f128ad55385f59bcfd7b431e805b380/src/pages/home/report/ReportActionItemMessageEdit.tsx#L178
In this function:
https://github.com/Expensify/App/blob/4db7a1f48f128ad55385f59bcfd7b431e805b380/src/libs/focusComposerWithDelay/setTextInputSelection.ts#L1-L15
Error: textInput.setSelectionRange is not a function
I suspect that at some point somewhere the wrong textInput is passed, which is why there is no such function

Therefore, we ca replace the line with(Add "?"):
```ts
(textInput as HTMLTextAreaElement).setSelectionRange?.(forcedSelectionRange.start, forcedSelectionRange.end);
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

None
### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by eVoloshchak** [comment]
@Eskalifer1, thank you for the [proposal](https://github.com/Expensify/App/issues/62703#issuecomment-2946671346)!

> I haven't really been able to pinpoint the problem, but I think it might have something to do with the fact that the emoji functions work with ref:

I do think that it's important we get to the actual root cause of this, as workarounds can create even more bugs. 

> For reasons unknown to me, an error occurs on android(on IOS i coudn't reproduce that) in the edit component when trying to focus

The error might be the key for this, it would be helpful to know **what** is causing it.
It's also worth noting that the bug is not reproducible with the suggestions modal, how does it differ from the emoji picker modal?

https://github.com/user-attachments/assets/fcdcb4f3-882e-4ea1-be2b-45d0abf0285e

**Comment by Eskalifer1** [comment]
@eVoloshchak 
I took a look at the problem you wrote about, and this is what I was able to research:
1. An error with setSelection and setSelectionRange: This function is only called if there is a parameter: forcedSelectionRange:
https://github.com/Expensify/App/blob/a30a5e49222f195a3e1eddefa5337eb147582d75/src/libs/focusComposerWithDelay/index.ts#L11-L43
This parameter is passed in this part of the code:
https://github.com/Expensify/App/blob/a30a5e49222f195a3e1eddefa5337eb147582d75/src/pages/home/report/ReportActionItemMessageEdit.tsx#L171-L182
But the emojiPickerSelectionRef is only there if it is an Android chrome browser, it is passed in this part:
https://github.com/Expensify/App/blob/a30a5e49222f195a3e1eddefa5337eb147582d75/src/pages/home/report/ReportActionItemMessageEdit.tsx#L291-L306

In general, the problem is that the textInput that is called here does not have setSelection and setSelectionRange in it, neither on the phone nor on the PC:
https://github.com/Expensify/App/blob/a30a5e49222f195a3e1eddefa5337eb147582d75/src/libs/focusComposerWithDelay/setTextInputSelection.ts#L7-L14

This part of the code:
https://github.com/Expensify/App/blob/a30a5e49222f195a3e1eddefa5337eb147582d75/src/libs/focusComposerWithDelay/index.ts#L26-L28
is called only in the browser on the phone (and probably on Android), so this function works infrequently, and because of the problem with focusing (we get into an if and focus is not performed), which I described above, it has not occurred before. Now, if you move the focus state, this bug occurs
A possible solution is the following:
Add these 2 functions to the useImperativeHandler:
https://github.com/Expensify/App/blob/a30a5e49222f195a3e1eddefa5337eb147582d75/src/components/Composer/implementation/index.tsx#L292-L309
```ts
 setSelectionRange: (start: number, end?: number) => {
 setSelection({start, end});
 },
 setSelection: (start: number, end?: number) => {
 setSelection({start, end});
 }
```

Regarding the active element, I noticed that the active element on PC and phone is different, it changes at 800px, but I didn't find out what the cause of the problem is, because the function to determine the active element is not used in many places.

You also asked what is the difference between suggestion and composer, and for me the difference is that when working with suggestion we always have the composer element active, and when working with emojiButton we make a click, where the focus is lost on the composer and at some point this focus goes to this emoji button

**Comment by zanyrenney** [comment]
hey @eVoloshchak please could you look at the proposal above and let me know if we can assign that contributor to work on this issue. Thank you!

**Comment by eVoloshchak** [comment]
@Eskalifer1, correct me if I'm wrong, you [propose](https://github.com/Expensify/App/issues/62703#issuecomment-2955372121) to call `setSelection` if `setSelectionRange` is not available. That would be equivalent to setting `setSelectionRange` to `false` in `src/libs/shouldSetSelectionRange/index.website.ts`, but this logic was specifically added in https://github.com/Expensify/App/pull/37666. Wouldn't your fix introduce https://github.com/Expensify/App/issues/28563 back?

**Comment by Eskalifer1** [comment]
I think we need to clarify some of the things we are talking about:
1. Focusing on an element after selecting an emoji does not work

The problem here is that when closing the modal window (Emoji), the active element on phones is still the button, so in onModalHide we get into an if, which is why the focus does not work

I've done some research, but I haven't been able to find the reason for this behavior, maybe it's a built-in behavior of browsers. I noticed that this check(for active lement) was added as a result of this bug:
https://github.com/Expensify/App/issues/27612
But currently this bug is not reproducible as the search field is focused when opening the mobile window with Emoji(Maybe im missing something, but...), here is a video recording with the check removed:

https://github.com/user-attachments/assets/0d6cd60d-beeb-4935-adf8-d9d1974d3543

(Sorry for the lags, I'm building an android project in parallel :))

So in theory, this part can be removed, but I'm not sure if it will create new bugs.

You can do it differently, since the emoji button becomes active when you select an emoji, you can clear the active element when you select an emoji:
You need to add this part of the code:
```ts
const active = DomUtils.getActiveElement();
 if (active instanceof HTMLElement) {
 active?.blur?.();
 }
```

In this function, which is executed when selecting an emoji:
https://github.com/Expensify/App/blob/38b53fc3144a4145aabd76149cecc86dc3cc03b9/src/pages/home/report/ReportActionItemMessageEdit.tsx#L291-L306

In this case, we leave the check, but when selecting an emoji, we blur the active element, which fixes the bug. But in this case, the focus will not happen after you open the emoji window and simply close it:

https://github.com/user-attachments/assets/db203079-7810-46b0-89e6-a6812d3ce2bf

2. The problem with selection, currently input does not have such functions as setSelection, setSelectionRange, that's all that composer has, these functions are very rarely used, I described it in a previous post, because they were essentially used only on android and android chrome:

<img width="819" alt="Image" src="https://github.com/user-attachments/assets/e39791c9-c8fa-48da-98ca-1d3c44ec5114" />

That is, this bug has existed for some time, but because there was no focus after selecting an emoji, the bug was not noticeable, but now that the problem with focus has been solved, this bug appears, and in the previous post I also described the reason why and when this function is called. 

In fact, at the moment I don't see this bug for which this logic was added, perhaps something else has affected it:

https://github.com/user-attachments/assets/b883a50f-b79a-4e7f-a0e8-02c0dccb8627
So, to keep this logic, because maybe this bug is still just hard to reproduce, I suggested in the previous post a solution to add these values through useImperativeHandle, but you can't do it like with focus and blur, that is, it won't work like this:
```ts
useImperativeHandle(ref, () => {
 const textInputRef = textInput.current;
 console.log(textInputRef, "textInputRef")
 if (!textInputRef) {
 throw new Error('textInputRef is not available. This should never happen and indicates a developer error.');
 }

        return {
... textInputRef,
 // Overwrite clear with our custom implementation, which mimics how the native TextInput's clear method works
 clear,
 // We have to redefine these methods as they are inherited by prototype chain and are not available directly
 blur: () => textInputRef. blur(),
 focus: () => textInputRef.focus(),
 setSelectionRange: (start, end, direction) => textInputRef.setSelectionRange(start, end, direction),
 get scrollTop() {
 return textInputRef.scrollTop;
 },
 };
 }, [clear]);
```

Because the textInputRef itself does not have setSelectionRange in it, so we will still get an error. This may have something to do with the input component itself, which we import from here:
import {MarkdownTextInput} from '@expensify/react-native-live-markdown';

<img width="819" alt="Image" src="https://github.com/user-attachments/assets/3b87a1eb-f454-4a99-97f8-dd542856bba3" />

**Comment by marcaaron** [comment]
Still in discussion.

**Comment by eVoloshchak** [comment]
> The problem with selection, currently input does not have such functions as setSelection, setSelectionRange,

@Eskalifer1, I get why the input doesn't have a `setSelectionRange` function (as it is supported by HTMLTextAreaElement only), but why doesn't it have `setSelection`? Is it simply not exposed to the ref, or does it not exist on the component at all?

> Because the textInputRef itself does not have setSelectionRange in it, so we will still get an error. This may have something to do with the input component itself, which we import from here:
import {MarkdownTextInput} from '@expensify/react-native-live-markdown';

If that is the case, we should fix this in '@expensify/react-native-live-markdown'

I think it's important we get to the bottom of this, finding a real root cause is essential. Otherwise, we'll apply a workaround that works around another workaround, which will inevitably produce more bugs (kind of what happened here)

**Comment by Eskalifer1** [comment]
@eVoloshchak Yes, I mentioned at the end that it's probably just that the component itself doesn't return such a function, I attached a screenshot where I made a console.log ref of the element itself and it doesn't have setSelection or SetSelectionRange, so it would be good if someone from the developers of this component could take a look at it

What do you think about the first point (About the focus, what do we need to stick to)?

**Comment by Eskalifer1** [comment]
@eVoloshchak 

After hours of debugging, I think I found the real reason for the focus problem:
1. We have a wrapper higher up the tree that uses a FocusTrap component to store focus. In turn, the EmojiPicker renders a PopoverWithMeasuredContent:
https://github.com/Expensify/App/blob/4c48b2c19c5ebdae211be230f009fded80cd7049/src/components/EmojiPicker/EmojiPicker.tsx#L194

This component renders a Popover inside itself, and the Popover has logic that is tied to the width of the screen:
This component will render on devices smaller than 800px:
https://github.com/Expensify/App/blob/4c48b2c19c5ebdae211be230f009fded80cd7049/src/components/Popover/index.tsx#L97-L112

And if we are on devices smaller than 800px, then we pass a different type of modal window:
```ts
type={isSmallScreenWidth ? CONST.MODAL.MODAL_TYPE.BOTTOM_DOCKED : CONST.MODAL.MODAL_TYPE.POPOVER}
```

Here is a part of the code where, depending on the type of modal window, another component is rendered:
https://github.com/Expensify/App/blob/fbae9af7200a4132c741d45b850d5e581e468f87/src/components/Modal/BaseModal.tsx#L36-L43

The main difference between these two components is that ReactNativeModal uses the `react-native-modal `library, and BottomDockedModal uses the Modal from “`react-native”`. And react-native, in turn, supports the wcag 2.1 recommendations (https://www.w3.org/TR/WCAG21/#focus-order), as a result of which, when the window is closed, the focus returns to the last active element, which in our case is the Emoji button that was clicked before(https://www.w3.org/TR/WCAG21/#focus-visible means that when you click a button, the focus moves to it and this focus should be visible. Restoring focus to the button after a modifier helps to meet this requirement).

In turn, react-native-modal does not support this recommendation, so its active element does not revert back when the modal window is closed.

To check if this is true, I rewrote the BottomDockedModal component to use the modal window from react-native-modal, and indeed there is no active element when the modal window is closed, here is a video:

https://github.com/user-attachments/assets/85ee98af-8007-4a79-b273-9206d08a6a2f


Therefore, to solve the problem with focus, we can find a solution that is related to overriding this default logic, since this logic is not used on the PC, but is used only in this type of modal window. But since I don't think it's a good idea to rewrite the logic in the `BottomDockedModal` component, since it is already used in many places and it can lead to new bugs, I suggest adding the following part of the code:
```ts
if (shouldUseNarrowLayout) {
 const active = DomUtils.getActiveElement();
 if (active && active instanceof HTMLElement) {
 active.blur();
 }
        }
```

To the hideEmojiPicker function:
https://github.com/Expensify/App/blob/b9b346227ad8ddbe067e10682f5f28e1057e80b5/src/components/EmojiPicker/EmojiPicker.tsx#L115-L125

That is, it will look like this:
```ts
const hideEmojiPicker = (isNavigating?: boolean) => {
 if (shouldUseNarrowLayout) {
 const active = DomUtils.getActiveElement();
 if (active && active instanceof HTMLElement) {
 active.blur();
 }
        }
 const currOnModalHide = onModalHide.current;
 onModalHide.current = () => {
 if (currOnModalHide) {
 currOnModalHide(!!isNavigating);
 }

            emojiPopoverAnchorRef.current = null;
 };
 setIsEmojiPickerVisible(false);
 };
```
This way we do not affect the logic on wider screens, and fix the bug

Here is the video:

https://github.com/user-attachments/assets/a28c3b46-16dc-4591-b8cf-fd1b8de3d112

**Comment by eVoloshchak** [comment]
@Eskalifer's [proposal](https://github.com/Expensify/App/issues/62703#issuecomment-2990412987) looks good to me!

I think we can make use of an already existing [blurActiveElement](https://github.com/Expensify/App/blob/main/src/libs/Accessibility/blurActiveElement/index.ts)

🎀👀🎀 C+ reviewed!

**Comment by Eskalifer1** [comment]
@eVoloshchak Hi, I've started working on the PR, but what are we going to do with setSelection and setSelectionRange?

I can add ?. before the call to avoid this error, but the problem still needs to be solved. To me, this error is not related to the main task.

It seems that it is from the component that we do not get this function, if it should be here

https://github.com/user-attachments/assets/9584264f-f0bf-4ba9-86d3-f5ad5b2de3c7

**Comment by Eskalifer1** [comment]
@eVoloshchak Here is the PR:https://github.com/Expensify/App/pull/64807

If we plan some other approach to setSelection and setSelectionRange, I will add it to the PR with the following commit

**Comment by zanyrenney** [comment]
Hey @Eskalifer1 did you not apply for the upwork job? I

**Comment by Eskalifer1** [comment]
Yes, indeed, my mistake, I apologize.

Already accepted

**Comment by Eskalifer1** [comment]
I have accepted, thank you

**Comment by zanyrenney** [comment]
**Payment Summary**

Reviewer: @eVoloshchak owed $250 via NewDot - please request.
ROLE: @Eskalifer1 paid $(AMOUNT) via Upwork (LINK) - paid via upwork.
