### ISSUE TITLE
[Due for payment 2025-06-16] [Due for payment 2025-06-16] [Due for payment 2025-06-13] [Due for payment 2025-06-12] Android - category-Download as csv is partially hidden in categories settings page

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#63468]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.59-0
**Reproducible in staging?:** Y
**Reproducible in production?:** N 
**If this was caught during regression testing, add the test name, ID and link from TestRail:** N/A
**Email or phone of affected tester (no customers):** applausetester+8@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
1. Launch app
2. Go to workspace settings - category - more

## Expected Result:
Download as csv is partially must not be hidden in categories settings page

## Actual Result:
Tapping more, in bottom modal "Download as csv" is partially hidden in categories settings page
Note: In tags and taxes pages also, bottom modal options are hidden

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/8bf421f3-fb17-46b8-b967-841dc2f91313

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @eh2077</details>

**Comment by BlameGPT** [comment]
### Possible culprit PRs for this issue
- #63304: This PR fixes the issue of bottom modal options being partially hidden when tapping more, matching the issue's reproduction steps and UI flow.
- #63237: This PR involves workspace settings and category-related UI flows, somewhat related to categories settings page mentioned in the issue.

**Comment by samranahm** [comment]
PR https://github.com/Expensify/App/pull/63304 recently deployed to staging, it should resolve this issue, requesting retest @lanitochka17

**Comment by mountiny** [comment]
@nkdengineer @eh2077 this should be fixed with https://github.com/Expensify/App/pull/63304, could you check what is wrong in this case?

**Comment by eh2077** [comment]
I can't reproduce this issue on the main branch. @nkdengineer Can you reproduce it?

<img width="337" alt="Image" src="https://github.com/user-attachments/assets/c964a88f-ff65-4ec8-9c72-1b92a016bcd2" />

**Comment by IuliiaHerets** [comment]
QA team rechecked production for this issue and still can't reproduce it here. We check on the prod build from Play Marked (build V9.1.56-1) and using the apk file (build - v9.1.58-4)

https://github.com/user-attachments/assets/46408507-10d5-49f1-afbd-c7a61bbc35ef
https://github.com/user-attachments/assets/997885ee-794b-4544-9bc2-dd1506347670

**Comment by IuliiaHerets** [comment]
We additionally recheck stg, issue still reproducible (build - v9.1.59-0)

![Image](https://github.com/user-attachments/assets/0a6102b4-759b-4f05-a023-e4822a6c1f02)

**Comment by nkdengineer** [comment]
I'll raise a PR in a few hours

**Comment by eh2077** [comment]
@IuliiaHerets Thanks for the testing!

@nkdengineer I think this line causes the difference

https://github.com/Expensify/App/blob/46949adc9a7f11b6c8b17a34550bc713ce80c2ab/src/components/ButtonWithDropdownMenu/index.tsx#L235

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/0bc43c98-29f6-45d8-8382-504d9dbcef00" /> <img width="300" alt="Image" src="https://github.com/user-attachments/assets/71b283a8-2e33-46a0-86ab-3381fd2c4ae9" />

**Comment by nkdengineer** [comment]
@eh2077 @mountiny We have a follow up PR [here](https://github.com/Expensify/App/pull/63536)

**Comment by mountiny** [comment]
Thanks

**Comment by mountiny** [comment]
CPed to staging, waiting for QA to confirm

**Comment by eh2077** [comment]
This is a regression from https://github.com/Expensify/App/issues/62573 and payment will be handled in the linked issue.
