### ISSUE TITLE
[Awaiting Checklist] [Due for payment 2025-07-15] [$250] Report - Report loads after sending a message in the empty report

### ISSUE THREAD

**Issue by lanitochka17** [Expensify/App#63662]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.1.60-1
**Reproducible in staging?:** Y
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** applausetester+060610kh@applause.expensifail.com
**Issue reported by:** Applause - Internal Team

## Action Performed:
Precondition:
- User has a workspace.

1. Go to staging.new.expensify.com
2. Click + > Create report
3. Send a message in the empty report

## Expected Result:
Report will not load after sending a message in the empty report

## Actual Result:
Report loads after sending a message in the empty report

## Workaround:
Unknown

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

<details>
  <summary>Add any screenshot/video evidence</summary>

</details> 

https://github.com/user-attachments/assets/9099eedc-2b7b-4c9c-ad3c-56ff2638e37c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021931039622180073550</li>
        <li>Upwork Job ID: 1931039622180073550</li>
        <li>Last Price Increase: 2025-06-13</li>
<li>Automatic offers: </li>
<ul>
<li>truph01 | Contributor | 107713474</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @garrettmknight</details>

**Comment by FitseTLT** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
Report - Report loads after sending a message in the empty report
### What is the root cause of that problem?
When creating the first report acton internal bug in FlatList is causing onStartReached callback to wrongly be called which will set loading old report actions to true 
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L613
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/libs/actions/Report.ts#L1455
so initial loader will be shown
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/components/MoneyRequestReportView/MoneyRequestReportView.tsx#L185-L188
### What changes do you think we should make in order to solve the problem?

This is a known flat list issue where it wrongly calls callback like onStartReached or onEndReached on its initial render and one of the suggested solutions is to create a ref that we only set on `onMomentumScrollBegin` and early return if the ref is not set in the callbacks to avoid all invokation of the callbacks not triggered by scrolling.
```
    const onStartReachedCalledDuringMomentum = useRef(true);

    const onStartReached = useCallback(() => {
        if (onStartReachedCalledDuringMomentum.current) {
            return;
        }
        onStartReachedCalledDuringMomentum.current = true; // We can avoid this.
       
```
https://github.com/Expensify/App/blob/aeffce7e48153b4ba33a7eabe04e4c81b698c026/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L613

```
onMomentumScrollBegin={() => {
                            onStartReachedCalledDuringMomentum.current = false;
                        }}
```
We can implement this for onEndReached too.
### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

N/ A
### What alternative solutions did you explore? (Optional)

**Comment by truph01** [comment]
🚨 Edited by **proposal-police**: This proposal was **edited** at 2025-06-12 07:09:20 UTC.

## Proposal

### Please re-state the problem that we are trying to solve in this issue.
- When sending a message in an otherwise empty report, the report appears to "load" unnecessarily.

### What is the root cause of that problem?
- When a new message is sent in an empty report, the UI transitions from the empty state:
  https://github.com/Expensify/App/blob/e1766ef329607a44d08fe805e22e11d26fab6f25/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L595

  to the regular list state:
  https://github.com/Expensify/App/blob/e1766ef329607a44d08fe805e22e11d26fab6f25/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L603

- At that point, the FlatList's content fits within the screen bounds. This causes `onStartReachedThreshold` to be immediately satisfied, which triggers the `onStartReached` callback.

- The `onStartReached` callback invokes `loadOlderChat`:
  https://github.com/Expensify/App/blob/e1766ef329607a44d08fe805e22e11d26fab6f25/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L211

- This, in turn, meets the condition inside:
  https://github.com/Expensify/App/blob/e1766ef329607a44d08fe805e22e11d26fab6f25/src/components/MoneyRequestReportView/MoneyRequestReportView.tsx#L185

  resulting in the loading skeleton being shown unnecessarily.

#### But why the `GetOlderActions` API is still called? I will explain below.

In the following middleware logic:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/libs/Middleware/Pagination.ts#L111-L113

we append `-2` to the end of the `reportActionPage_` Onyx key when `OpenReport` returns `hasOlderActions: false`. This marks the report as fully loaded (i.e., no more pages to fetch), which is later interpreted as `hasNextPage: false` in:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/libs/PaginationUtils.ts#L220

As a result, in the `useLoadReportActions` hook:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/hooks/useLoadReportActions.ts#L98

we exit early and skip the API call to load report actions.

This behavior is expected when `hasOlderActions` is `false`. However, in the case of a newly created report, the `OpenReport` API response returns `hasOlderActions: null`, not `false`.

### What changes do you think we should make in order to solve the problem?
- We should ensure that `onStartReached` only triggers if the list was previously scrollable.
- To accomplish this, introduce a new `useRef` to track whether the list has ever been scrollable:

<pre><code>
const listUsedToBeScrolledRef = useRef(false);
</code></pre>

- At the point where we detect the list is scrollable:
  https://github.com/Expensify/App/blob/e1766ef329607a44d08fe805e22e11d26fab6f25/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L359

  add:

<pre><code>
listUsedToBeScrolledRef.current = true;
</code></pre>

- Then, within `onStartReached`:
  https://github.com/Expensify/App/blob/e1766ef329607a44d08fe805e22e11d26fab6f25/src/components/MoneyRequestReportView/MoneyRequestReportActionsList.tsx#L205

  guard the callback with:

<pre><code>
if (!listUsedToBeScrolledRef.current) {
    return;
}
</code></pre>

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
- None

### What alternative solutions did you explore? (Optional)

- We should consider the case `hasOlderActions === null` pagination middleware:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/libs/Middleware/Pagination.ts#L111-L113

```
        if (response.hasOlderActions === false || response.hasOlderActions === null) {
            newPage.push(CONST.PAGINATION_END_ID);
        }
```

**Comment by DylanDylann** [comment]
@FitseTLT @truph01 I can't reproduce this bug anymore. Agree that loadOlderChats and loadNewerChats are executed but both of them are early returned

**Comment by truph01** [comment]
@DylanDylann I agree with you that the current bug is no longer reproducible, since the condition to show the loading skeleton was updated in [this PR](https://github.com/Expensify/App/pull/63555/).

However, we're still observing that the `GetOlderActions` API is being called redundantly, even when there are no additional older actions to fetch. This unnecessary call is the root cause of the original issue, even if the visual bug is no longer present.

Because of that, I believe it's still important to address and fix the underlying logic to prevent these redundant API calls.


https://github.com/user-attachments/assets/e11c6ffd-4c29-4303-a892-0b454b91e05e

**Comment by DylanDylann** [comment]
Yeah, agree. It maybe a good improvement

**Comment by DylanDylann** [comment]
@truph01 Could you explain why GetOlderActions is called? I think `loadOlderChats` function should be returned early. It seems hasOlderActions has the wrong value in this case and I prefer to fix this RCA

**Comment by truph01** [comment]
@DylanDylann 

#### RCA:
In the following middleware logic:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/libs/Middleware/Pagination.ts#L111-L113

we append `-2` to the end of the `reportActionPage_` Onyx key when `OpenReport` returns `hasOlderActions: false`. This marks the report as fully loaded (i.e., no more pages to fetch), which is later interpreted as `hasNextPage: false` in:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/libs/PaginationUtils.ts#L220

As a result, in the `useLoadReportActions` hook:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/hooks/useLoadReportActions.ts#L98

we exit early and skip the API call to load report actions.

This behavior is expected when `hasOlderActions` is `false`. However, in the case of a newly created report, the `OpenReport` API response returns `hasOlderActions: null`, not `false`.

#### Solution:
We should consider the case `hasOlderActions === null` pagination middleware:

https://github.com/Expensify/App/blob/f223c8ff72dd6baee12de9e74330d23010afcd06/src/libs/Middleware/Pagination.ts#L111-L113

```
        if (response.hasOlderActions === false || response.hasOlderActions === null) {
            newPage.push(CONST.PAGINATION_END_ID);
        }
```

**Comment by FitseTLT** [comment]
I see hasOlderActions return as false in OpenReport and unnecessary call of GetOlderActions API is not happening from report screen it is only happening from the search page and I think the BE should be fixed to return hasOlderActions:false.

**Comment by DylanDylann** [comment]
@truph01 Thanks for investigation, could you please give your new update to the original proposal?

**Comment by truph01** [comment]
### [Proposal updated](https://github.com/Expensify/App/issues/63662#issuecomment-2951529220)

- I updated the RCA section and added an alternative solution

**Comment by DylanDylann** [comment]
The current bug is no longer reproducible, as the condition for displaying the loading skeleton was updated in another PR. However, we’re still seeing redundant calls to the GetOlderActions API, even when there are no more older actions to retrieve. While the visual issue has been resolved, these unnecessary API calls are the underlying cause and should still be addressed. Because of that, I would prefer to go with @truph01's [proposal](https://github.com/Expensify/App/issues/63662#issuecomment-2951529220)  to fix the underlying problem and improve the App perf. 

🎀👀🎀 C+ reviewed

**Comment by neil-marcellini** [comment]
I'm partially OOO. 25% today and 50% the next two days until 6/19 when I will be back fully. I will try to move things along as much as I can in order of priority.

**Comment by neil-marcellini** [comment]
Haven't had time to review yet

**Comment by neil-marcellini** [comment]
> The current bug is no longer reproducible, as the condition for displaying the loading skeleton was updated in another PR. However, we’re still seeing redundant calls to the GetOlderActions API, even when there are no more older actions to retrieve. While the visual issue has been resolved, these unnecessary API calls are the underlying cause and should still be addressed. Because of that, I would prefer to go with [@truph01](https://github.com/truph01)'s [proposal](https://github.com/Expensify/App/issues/63662#issuecomment-2951529220) to fix the underlying problem and improve the App perf.
> 
> 🎀👀🎀 C+ reviewed

Ok, sounds good to me too. Let's also implement the alternate solution as an extra valuable check for the future, and remember to include unit tests.

**Comment by truph01** [comment]
@DylanDylann [PR](https://github.com/Expensify/App/pull/64412) is ready

**Comment by DylanDylann** [comment]
# BugZero Checklist:

- [ ] **[Contributor]** Classify the bug:

<details>
<summary>Bug classification</summary>


Source of bug:
  - [ ] 1a. Result of the original design (eg. a case wasn't considered)
  - [ ] 1b. Mistake during implementation
  - [ ] 1c. Backend bug
  - [ ] 1z. Other:

Where bug was reported:
  - [ ] 2a. Reported on production (eg. bug slipped through the normal regression and PR testing process on staging)
  - [ ] 2b. Reported on staging (eg. found during regression or PR testing)
  - [ ] 2d. Reported on a PR
  - [ ] 2z. Other:

Who reported the bug:
  - [ ] 3a. Expensify user
  - [ ] 3b. Expensify employee
  - [ ] 3c. Contributor
  - [ ] 3d. QA
  - [ ] 3z. Other:

</details>

- [ ] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment:

- [ ] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [ ] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

<details>
<summary>Regression Test Proposal Template</summary>


- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal
### Precondition:


-

### Test:


1.

Do we agree 👍 or 👎


</details>

**Comment by quinthar** [comment]
Approved $250 to @DylanDylann
