### ISSUE TITLE
[$250] [Due for payment 2026-01-20] LHN - Thread remains pinned in LHN after deleting all thread message

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#69415]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.0-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://test-management.browserstack.com/projects/2219752/test-runs/TR-513/41237487/864760351?q=lhn&issue_type=jira
**Email or phone of affected tester (no customers):** sdsjidosjdnoids@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Mac 15.5 / Chrome
**App Component:** Left Hand Navigation (LHN)

## Action Performed:
1. Go to staging.new.expensify.com
2. Go to any chat.
3. Send a message.
4. Right click on the message > Reply in thread.
5. Click on the thread header > Pin.
6. Close the RHP.
7. Delete the parent message.
8. Navigate away from the thread.

## Expected Result:
The deleted thread should auto unpin from LHN.

## Actual Result:
The deleted thread remains pinned in LHN. It is displayed as Hidden in LHN with skeleton loader in the thread header.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [x] Windows: Chrome
- [x] MacOS: Chrome / Safari
- [x] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/8428e33f-be8d-4f27-9cc4-6711fc98e740

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~022013491338367470784</li>
        <li>Upwork Job ID: 2013491338367470784</li>
        <li>Last Price Increase: 2026-01-20</li>
    </ul>
</details>

**Comment by bernhardoj** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The deleted pinned thread remains on LHN.

### What is the root cause of that problem?
We don't have any logic to unpin the deleted thread.

### What changes do you think we should make in order to solve the problem?

I think it's better to just delete the thread (if no reply) since visiting it shows a broken report which kinda make sense since the message is already deleted.

```
if (reportAction.childReportID && reportAction.childVisibleActionCount === 0) {
    optimisticData.push(
        {
            onyxMethod: Onyx.METHOD.MERGE,
            key: `${ONYXKEYS.COLLECTION.REPORT}${reportAction.childReportID}`,
            value: null,
        }
    );
}
```
(and revert when fails)

But this requires BE changes too because if we use Clear cache & restart, the BE will return the deleted thread back.

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

We can test the deleteReportComment and verify the thread (child) report is also deleted.

**Comment by QichenZhu** [comment]
@nyomanjyotisa, your solution also unpins non-empty threads, and after clearing the cache, empty threads will come back. BTW, some backtick and dollar signs are missing in your code, but no worries, I can still understand it.

**Comment by QichenZhu** [comment]
@mkzie2, your solution unpins threads with a draft.

**Comment by QichenZhu** [comment]
I'm wondering if we actually need backend changes, since https://github.com/Expensify/App/issues/22950 was the same issue and fixed in frontend alone. Later https://github.com/Expensify/App/pull/30154/commits/e9777a763c7abd072f45c96fdf8905f6ecfa0277 reverted the fix. Not sure if it was on purpose or a mistake.

**Comment by bernhardoj** [comment]
What is the expected result here? I think it's a bit different than https://github.com/Expensify/App/issues/22950.

In https://github.com/Expensify/App/issues/22950, the thread has a reply, so when deleting the thread, the report still exists. It was reverted most likely because it makes a pinned empty thread not visible on the LHN.

In this issue, we delete an empty thread, and if we visit the report, it shows a broken view.

**Comment by QichenZhu** [comment]
Thanks to all for your input!

**Comment by QichenZhu** [comment]
Still waiting for proposals.

**Comment by huult** [comment]
https://github.com/Expensify/App/issues/69415#issuecomment-3336758468 I don’t think my proposal is a duplicate. @QichenZhu, what do you think?

**Comment by QichenZhu** [comment]
@huult, I think your proposal is similar to [@mkzie2's](https://github.com/Expensify/App/issues/69415#issuecomment-3232453405) and also [unpins threads that have a draft](https://github.com/Expensify/App/issues/69415#issuecomment-3249203621).

BTW, you might want to check our [discussion](https://github.com/Expensify/App/issues/69415#issuecomment-3291338285) about the expected behavior.

**Comment by dubielzyk-expensify** [comment]
Shawn is out at the moment, but I don't think it makes any sense to pin a fully deleted thread, but maybe there's some scenarios where if there's multiple comments made, then you'd wanna save those. I lean towards unpinning deleted things, but curious for @Expensify/product-pr and @Expensify/design take as well

**Comment by huult** [comment]
- Empty & deleted threads → hidden.
- Pinned threads (even without replies) → shown.
- Threads with replies → shown.

@QichenZhu @dubielzyk-expensify Does this match the intended behavior?

**Comment by dubielzyk-expensify** [comment]
~~I think we should pin empty threads. Basically my thinking is respect the user when they've pinned anything. Unless it's deleted, cause then it doesn't exist so there's nothing to pin.~~

When writing it out, I guess a empty thread is a comment which you can't pin, so yeah the summary makes sense to me

**Comment by huult** [comment]
> * Empty & deleted threads → hidden.
> * Pinned threads (even without replies) → shown.
> * Threads with replies → shown.
> 
> [@QichenZhu](https://github.com/QichenZhu) [@dubielzyk-expensify](https://github.com/dubielzyk-expensify) Does this match the intended behavior?

Another case:

- Pinned threads (even without replies) & deleted threads → hidden
- Pinned threads (even with a draft) & deleted threads → shown
- Threads with replies & deleted threads → shown

cc @dubielzyk-expensify @dannymcclain

**Comment by dubielzyk-expensify** [comment]
1. 👍
2. Hmm. I guess yes, but can you send a draft to a deleted thread? 
3. 👍

**Comment by kadiealexander** [comment]
@dubielzyk-expensify bump on this! I agree it should stay pinned and shown.

**Comment by dubielzyk-expensify** [comment]
Yeah I think the behavior in that video is very weird. But I don't see the video sending the message. I'm curious if you can send it after it's deleted. I see the draft in the composer, but not it being sent.

**Comment by QichenZhu** [comment]
> Yeah I think the behavior in that video is very weird. But I don't see the video sending the message. I'm curious if you can send it after it's deleted. I see the draft in the composer, but not it being sent.

Yes, it can be sent.

https://github.com/user-attachments/assets/67e12444-2463-4194-82ee-05b6c7884ac7

**Comment by huult** [comment]
@dubielzyk-expensify https://github.com/Expensify/App/issues/69415#issuecomment-3467465003 what do you think?

**Comment by dannymcclain** [comment]
Yeah I kinda think it's weird too, but I'm fine with where you're landing. Feels like an odd edge case to begin with honestly haha.

**Comment by huult** [comment]
Hi team, has a final decision been made on this?

**Comment by huult** [comment]
@QichenZhu When we delete a message in a workspace chat, the report ID of the thread message is not updated because we currently only update the workspace reports. Therefore, we also need to fix the getUpdatedReports function to fully resolve this issue. I’ll need more time to make this update

**Comment by marufsharifi** [comment]
@kadiealexander, offer accepted. thanks
