### ISSUE TITLE
[Due for payment 2025-10-15] [$250] IOU - IOU created offline, only shows "Owes XX$" without receiver´s name, when online again.

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#70079]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.2-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://test-management.browserstack.com/projects/2219752/test-runs/TR-704/folder/13177049/41237813/881815853
**Email or phone of affected tester (no customers):** ibellicotest+1727@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Motorola MotoG60 / Android 12 / Chrome ( mWeb / Hybrid app)
**App Component:** Money Requests

## Action Performed:
1. Open the Expensify app.
2. Turn off internet connection.
3. Tap on FAB and select "Create Expense"
4. Create a manual expense and submit it to an individual with no existing conversation and that is not part of "Recents" or "Contacts" list.
5. Once navigated to chat, note that expense preview shows receiver´s Email, before "Owes XX$" on expense preview.
6. Turn on internet connection.
7. Note that receiver´s Email disappears from expense preview, and now only "Owes XX$" is visible.
8. Open the expense.
9. Note that receiver´s name, appears before "Owes XX$" on report header.
10. Return to chat.
11. Note that now, receiver´s name, also appears on expense preview.

## Expected Result:
When creating an IOU while offline, and recovering internet connection, receiver´s name should be visible on expense preview, before "Owes XX$"

## Actual Result:
When creating an IOU while offline, receiver´s Email can be seen before "Owes XX$" on expense preview, but when internet connection is recovered, Email disappears and only "Owes XX$" can be seen. 
After opening expense report, receiver´s name appears.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/d413fc77-fcfc-47f6-9720-3bd009aab350

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021968073725250120693</li>
        <li>Upwork Job ID: 1968073725250120693</li>
        <li>Last Price Increase: 2025-09-16</li>
<li>Automatic offers: </li>
<ul>
<li>mkzie2 | Contributor | 108811340</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @mallenexpensify</details>

**Comment by mallenexpensify** [comment]
@c3024 Please review @dmkt9 and @mkzie2 's proposals above. Thx
If there are other known instances of this bug in other places, that are fixed easily, please tackle those in the PR.  If the additional work is not insignificant we can discuss potential increase in payment.  Thx

**Comment by c3024** [comment]
We should prefer derived values over other choices because they update centrally whenever their dependencies change. In this particular case, subscribing to `personalDetails` and drilling them down to the last function does not seem performance intensive and might be fine. However, in `getReportName`, there are cases other than `getMoneyRequestReportName` where this bug can still happen, and `personalDetails` might also need to be passed to those functions. It is better to subscribe to `reportAttributes` and pass it to the function, since it directly returns the derived value in `getReportName` before checking for other conditions.

@mkzie2 's [solution](https://github.com/Expensify/App/issues/70079#issuecomment-3269361612) LGTM!

🎀 👀 🎀

**Comment by mountiny** [comment]
I am curious what @TMisiukiewicz thinks of that proposal. The reportAttributes are always tricky when it comes to performance

**Comment by mallenexpensify** [comment]
Test case created, thx @c3024 
- https://github.com/Expensify/Expensify/issues/563241
