### ISSUE TITLE
[Due for payment 2026-04-30] `pending BZ checklist` [Due for payment 2026-02-17] [Due for payment 2025-10-21] [$250] If an expense report is not eligible to have reports moved to it, don't show it in the list

### ISSUE THREAD

**Issue by clarajones-expensify** [Expensify/App#70423]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:**
**Reproducible in staging?:**
**Reproducible in production?:**
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:**
**Slack conversation** (hyperlinked to channel name): [quality](https://expensify.slack.com/archives/C05LX9D6E07/p1757535644671009)

## Action Performed:

**Account pre-reqs:** instant submit is turned on, there are no approvers in the workflow, and the report that you are going to move expenses to contains only non-reimbursable expenses.

1. Select expenses on an open report
2. Click More > move expenses
3. Select the report that meets the **account pre-reqs** from above
4. You will see that the expenses do not move to the new report, and there is no error message or warning to indicate to the customer why

## Expected Result:
What should happen is that the report that is ineligible to have expenses moved to it should not even appear in the list of reports as an option to select.

## Notes from engineering:

Make sure that only reports that we can move the expenses to are listed as an option (i.e. Draft and processing)

## Platforms:
Select the officially supported platforms where the issue was reproduced:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

<details>
  <summary>Platforms Tested:</summary>
On which of our officially supported platforms was this issue tested:

- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

</details>

## Screenshots/Videos

https://github.com/user-attachments/assets/0c259c1e-7e58-4be3-93c8-2cbe5482b78e

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021966230998916008704</li>
        <li>Upwork Job ID: 1966230998916008704</li>
        <li>Last Price Increase: 2025-09-11</li>
<li>Automatic offers: </li>
<ul>
<li>abzokhattab | Contributor | 108878612</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @huult</details>

**Comment by allroundexperts** [comment]
@ganzz4 `canAddTransaction` has other checks which might not be relevant in this case.

**Comment by allroundexperts** [comment]
# BugZero Checklist:

- [x] **[Contributor]** The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to comment: I wasn't able to find the frontend PR that caused this. It seemed like the backend validation changed which led to this behaviour on the frontend.

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion: N/A

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

- [ ] **[BugZero Assignee]** Create a GH issue for creating/updating the regression test once above steps have been agreed upon.

    Link to issue:

## Regression Test Proposal

### Precondition:

N/A

### Test:


1. Create a workspace
2. Disable delayed submit, approvals, and payments
3. Create a reimbursable expense
4. Retract the report to reopen it as a draft report
5. Create a non-reimbursable expense
6. Retract the report to reopen it as a draft report
9. Go to Report -> submit
10. Select the reimbursable
11. Click More > move expenses
Ensure that the non-reimbursable expense (created in step 5) doesn't show up in the list.

Do we agree 👍 or 👎

**Comment by m-natarajan** [comment]
@clarajones-expensify @grgia Able to reproduce the original issue, Should I open the closewd issue or create a new issue for this?

https://github.com/user-attachments/assets/5648f64e-f772-46a9-96cd-a277978d9f53

**Comment by m-natarajan** [comment]
@allroundexperts Able to reproduce the original issue, Should I open the closewd issue or create a new issue for this?

**Comment by clarajones-expensify** [comment]
@grgia @allroundexperts what do you think is better in this case?

**Comment by allroundexperts** [comment]
Hm... @abzokhattab Can you check the issue here?

**Comment by abzokhattab** [comment]
@grgia Yes its a regression from the other PR https://github.com/Expensify/App/pull/73341 .. we should make a fix that makes sure both issues are fixed and dont have regressions.

**Comment by clarajones-expensify** [comment]
@grgia @abzokhattab @allroundexperts - how should we proceed here?

**Comment by clarajones-expensify** [comment]
@allroundexperts @abzokhattab are we all set here? anything else needs to be done before closing? thanks so much!

**Comment by abzokhattab** [comment]
i will raise a pr tackling that

**Comment by clarajones-expensify** [comment]
PR is in progress, @abzokhattab do you have an eta on this? TY!

**Comment by mallenexpensify** [comment]
@mananjadhav 👀 [plz](https://github.com/Expensify/App/pull/84832#issuecomment-4240017108)

**Comment by grgia** [comment]
Assigning @huult as C+

**Comment by mitarachim** [comment]
Deploy Blocker https://github.com/Expensify/App/issues/88425 was identified to be related to the PR https://github.com/Expensify/App/pull/84832 that attempted to fix this issue.

**Comment by lanitochka17** [comment]
Deploy Blocker #https://github.com/Expensify/App/issues/88424 was identified to be related to the PR #https://github.com/Expensify/App/pull/84832 that attempted to fix this issue.

**Comment by huult** [comment]
@abzokhattab Please open a new PR and double-check the deploy blocker issue. Thanks.

**Comment by abzokhattab** [comment]
This is a bit confusing. I am not quite sure what the correct fix should be now,, do u you have any suggestions @huult

**Comment by huult** [comment]
@abzokhattab Could you share what you're confused about? We can clarify it together and resolve each ticket one by one.

**Comment by abzokhattab** [comment]
@huult not sure what is the correct way to handle it given the regression... do u have any suggestions to consider?

**Comment by huult** [comment]
@abzokhattab Could you please list what you are confused about and kindly comment here to confirm the expected behavior?

**Comment by abzokhattab** [comment]
tried to cover mentioned regressions https://github.com/Expensify/App/pull/89079 ..   let me know what you think about this approach @huult

**Comment by huult** [comment]
@abzokhattab I think we should clarify the points you still don't understand, and then confirm them to avoid another regression test.

**Comment by abzokhattab** [comment]
Lets move the discussion to the pr the regressions are already mentioned there

**Comment by huult** [comment]
No payment is needed because the PR was reverted

**Comment by mallenexpensify** [comment]
@abzokhattab @huult if there's a parent issue where the amount should be reduced because of reverts and/or regressions, please link this one there.  Thx

Also.. can this be closed?

**Comment by huult** [comment]
@mallenexpensify Sure. We have a new PR open to fix this issue, so this ticket is not closed for now. @abzokhattab is working on it.

**Comment by huult** [comment]
We are working on [this PR](https://github.com/Expensify/App/pull/89079)

**Comment by huult** [comment]
@clarajones-expensify Per [this comment](https://github.com/Expensify/App/pull/89079#issuecomment-4659496969), could you help us retest this ticket?

**Comment by huult** [comment]
> [@clarajones-expensify](https://github.com/clarajones-expensify) Per [this comment](https://github.com/Expensify/App/pull/89079#issuecomment-4659496969), could you help us retest this ticket?

bump @clarajones-expensify

**Comment by clarajones-expensify** [comment]
hi!! sorry for the delay. looks like this is working, as i can move expenses between Draft and Outstanding reports, but once the report is Approved, the Approved report no longer appears in the list of available reports to be moved to

https://github.com/user-attachments/assets/7427ee80-5db5-4bc8-91cc-c37b42e55f30

**Comment by huult** [comment]
@clarajones-expensify I think this is expected behavior. Once a report reaches the Approved state, it has already gone through the approval process and entered the next stage of the workflow, so it would make sense that expenses can no longer be moved into it. That said, let's wait for @trjExpensify's thoughts as well. cc @abzokhattab

> but once the report is Approved, the Approved report no longer appears in the list of available reports to be moved to

Hi @trjExpensify  Since you reviewed the product change in PR https://github.com/Expensify/App/pull/89079, I'd also love to hear your thoughts on this. Could you share your perspective? thank you!

**Comment by trjExpensify** [comment]
That is indeed expected. Else, you could do something like this: 

- Submit a coupla' expenses to your manager
- Your manager approves it 
- You slip a cheeky of bottle of champagne onto the approved report
- Finance pay it thinking the manager was cool with it.

**Comment by huult** [comment]
Thanks for confirming! ❤️ 

Yeah, I think everything looks good now, so we can close this ticket since it's working as expected.

**Comment by huult** [comment]
> [@abzokhattab](https://github.com/abzokhattab) [@huult](https://github.com/huult) if there's a parent issue where the amount should be reduced because of reverts and/or regressions, please link this one there. Thx
> 
> Also.. can this be closed?


Hi @mallenexpensify,

Based on this comment: https://github.com/Expensify/App/issues/70423#issuecomment-4772900226, and since @clarajones-expensify's concern was addressed in:

* https://github.com/Expensify/App/issues/70423#issuecomment-4774836996
* https://github.com/Expensify/App/issues/70423#issuecomment-4774856872

I believe we're good to close this issue and proceed with payment.

The original PR, https://github.com/Expensify/App/pull/84832, was reverted due to some unexpected issues. Later, @abzokhattab opened a replacement PR, https://github.com/Expensify/App/pull/89079, but that PR has since been closed as well.

I'm not entirely sure how we should handle payment in this situation given the revert and replacement PR flow. @mallenexpensify, could you please help clarify how we should proceed?

**Comment by abzokhattab** [comment]
i am not sure as well how the payment should be handled here ... we first made the first PR then another issue made a regression not ours (shown here https://github.com/Expensify/App/issues/70423#issuecomment-3593818647) --> [old payment summary](https://github.com/Expensify/App/issues/70423#issuecomment-3928636855) then i volunteered to work on the fix and then it got merged and that was reverted later ... now after working on it the issue was fixed on the backend ... so how should we handle this?

**Comment by mallenexpensify** [comment]
@huult and @abzokhattab are you both fine with $125? Partially cuz it's quick/easy. 

More details would be... if a PR (or more) were raised and reviewed, then closed, you could be due up to the full amount.  If that's the case, which PR/s are directly related to this issue?

**Comment by abzokhattab** [comment]
Hi @mallenexpensify — quick clarification on scope. The original fix for this issue was completed and deployed, which covers the initial $250 
After its regression period, the issue surfaced again — but **this was not caused by our PR**. A separate PR (#73341) had since changed the same area of code and reintroduced the bug. I verified this directly: reverting #73341 fixed the issue ([ref](https://github.com/Expensify/App/issues/70423#issuecomment-3593818647)) https://github.com/Expensify/App/issues/70423#issuecomment-3655727893. grgia asked whether #73341 was the cause ([ref](https://github.com/Expensify/App/issues/70423#issuecomment-3655698690)), and I confirmed it was a regression from that PR ([ref](https://github.com/Expensify/App/issues/70423#issuecomment-3655727893)) 

[old payment summary](https://github.com/Expensify/App/issues/70423#issuecomment-3928636855) and [contributor + payment confirmation](https://github.com/Expensify/App/issues/70423#issuecomment-3710079673) 


I then volunteered to rework the fix despite the regression originating elsewhere ([ref](https://github.com/Expensify/App/issues/70423#issuecomment-3704283765)). Since that rework did go through some regressions of its own before landing, I'm fine treating it as a reduced  $125  for that second round.

So I'd ask we settle this at  $250 (original fix) + $125 (rework) = $375  Happy to clarify anything further — thanks!

**Comment by mallenexpensify** [comment]
### Payment Summary
Contributor+: @abzokhattab  due $125 via NewDot

Thanks for the thorough breakdown @abzokhattab , it's helpful.  

This appears to be a pretty extreme edge case.  I'm thinking the above makes the most sense cuz the PR was created and tested by @abzokhattab , @huult hadn't posted the reviewers checklist yet, so no payment.   Will leave open for other 👀 /thoughts.

**Comment by huult** [comment]
@mallenexpensify I completed the PR checklist and reviewed https://github.com/Expensify/App/pull/84832. However, that PR was removed, and its replacement is https://github.com/Expensify/App/pull/89079.

I didn't post the checklist on the new PR because I first reviewed it with the Product team and QA to discuss the implementation and make sure we could close the ticket. Given that I completed the required review work, I believe I should still be eligible for payment.

**Comment by mallenexpensify** [comment]
oh.. hmm.. I think I thought that the first PR was merged/paid and there was only the one after that wasn't merged.  

So, @huult are you proposing $250 to you and @abzokhattab for https://github.com/Expensify/App/pull/84832? If so, does it also make sense to add $125 for @abzokhattab for https://github.com/Expensify/App/pull/89079 ?  (that's the way I'm reading it now, but I already messed this up once)

**Comment by huult** [comment]
### Payment Recommendation

Given the full history of this issue:

**Contributor (@abzokhattab): $125**
- Original fix (PR #71439) was already paid [$250](https://github.com/Expensify/App/issues/70423#issuecomment-3928636855) ✅
- The regression was caused by PR #73341, not the original fix
- Subsequent rework (PRs #78766, #84832, #89079) involved significant effort but none shipped successfully — the issue was ultimately resolved by a backend fix
- $125 partial payment fairly acknowledges the rework effort without double-paying for the same issue

**Contributor+ (@huult): $125**
- Completed review work on PR #84832 and extensive coordination on PR #89079 (ad-hoc build, product review with @trjExpensify, QA retest)
- No PR merged successfully under a completed reviewer checklist in this cycle
- Partial payment acknowledges the C+ review/coordination work

**Total new payment this cycle: $250** ($125 + $125)

This issue can be closed and QA confirmed expected behavior on Jun 22.

**Comment by abzokhattab** [comment]
> oh.. hmm.. I think I thought that the first PR was merged/paid

i think i got the confusing part ... the [the old summary](https://github.com/Expensify/App/issues/70423#issuecomment-3427271691) mistakenly mentions I was paid, but i still have the [Upwork contract](https://www.upwork.com/nx/wm/offer/108878612) running and not yet handled ... lets cancel this one and handel both payments together via newdot : )

**Comment by huult** [comment]
cc @mallenexpensify

**Comment by mallenexpensify** [comment]
@grgia 👀 above plz to confirm you're 👍 with paying @huult and @abzokhattab $125 each . 

@abzokhattab you've already been paid on the Upwork contract so payment will be on this issue.

**Comment by abzokhattab** [comment]
my bad just checked upwork again.. yes the contract was paid https://www.upwork.com/nx/wm/offer/108878612 ..  agree on the latest summary.

**Comment by huult** [comment]
https://github.com/Expensify/App/issues/70423#issuecomment-4906088750 @grgia Could you check this comment when you have time?

**Comment by grgia** [comment]
@mallenexpensify confirmed
