### ISSUE TITLE
[$250] WEB - Book Travel - RHP does not auto scroll when an error message appears off-screen

### ISSUE THREAD

**Issue by nlemma** [Expensify/App#70601]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** v9.2.13-1
**Reproducible in staging?:** Yes
**Reproducible in production?:** Yes
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://test-management.browserstack.com/projects/2219752/folder/13177079/test-cases/41237922
**Email or phone of affected tester (no customers):** N/A
**Issue reported by:** Applause Internal Team
**Device used:** Windows 11 / Chrome
**App Component:** Other

## Action Performed:
Precondition:
- Sign in to a Expensifail account in OD
- Create one or 2 group workspaces if there is no existing workspaces
- Set the Individual workspace as default

1. Login to ND
2. Click the FAB > Book Travel
3. Click the Book travel

## Expected Result:
RHP should auto scroll when an error message appears off-screen

## Actual Result:
RHP does not auto scroll when an error message appears off-screen
Note:
- Only reproducible on Web

## Workaround:
Unknown

## Platforms:
- [ ] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [x] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/b04273ff-2f6b-412a-961b-272bc057291c

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021968701196072938668</li>
        <li>Upwork Job ID: 1968701196072938668</li>
        <li>Last Price Increase: 2025-09-18</li>
<li>Automatic offers: </li>
<ul>
<li>huult | Contributor | 109030520</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @NagaraniKaleeswaran</details>

**Comment by NagaraniKaleeswaran** [comment]
@MelvinBot 
**Proposal**

**Problem:** On Web, when an error message appears in the RHP (Right-Hand Panel) but is off-screen, the panel does not auto-scroll, so the user may not notice the error.  

**Root cause:** The error message is being rendered but there’s no trigger to scroll the RHP into view when new validation errors appear.  

**Fix approach:**  
- Add a small utility to detect when a new error message is inserted into the DOM.  
- On detection, call `scrollIntoView({ behavior: "smooth", block: "nearest" })` for the error element.  
- Scope this only to RHP forms (e.g. Book Travel) to avoid unintended global scrolling.  

**Validation:**  
- Reproduce the bug on staging by triggering form validation errors that are off-screen.  
- Confirm RHP auto-scrolls to bring the error into view.  
- Test on Chrome (Windows + Mac), Safari, and cross-browser to ensure consistent behavior.  
- Regression check: ensure no extra scrolling happens for already-visible errors.  

This ensures errors are always visible without breaking the user’s scroll position unnecessarily.

**Comment by ikevin127** [comment]
Thanks everyone for the proposals!

##

Personally I'm not able to reproduce the issue on MacOS: Chrome, it always scrolls even if I delay the appearance of the error:

https://github.com/Expensify/App/blob/2b499bf77e0a13e322edbce68058beb603131ce6/src/components/BookTravelButton.tsx#L109-L112

I have set a 2 seconds timeout delay on the error being set, and it still scrolls (see below), which basically invalidates both proposals RCAs:

> It scrolls while not ensure the error message is fully rendered

> The scroll action is triggered immediately when the error message state changes, but before the DOM has completed rendering the error message component

None of the RCAs are valid / correct because as mentioned above, I set a delay on purpose on the error being set in state and as soon as it's set, the scroll function is called here:

https://github.com/Expensify/App/blob/2b499bf77e0a13e322edbce68058beb603131ce6/src/components/BookTravelButton.tsx#L77-L82

This confirms that the root cause is not at all related to the error not being rendered and scroll being called earlier, because scroll is only called (`setShouldScrollToBottom(true)`) when the error is set in state, which triggers:

https://github.com/Expensify/App/blob/ec8478b247f0cbe07264eb2088ee10d3f19e83bc/src/pages/Travel/ManageTrips.tsx#L41-L53

Here's the demo with the error set in state being 2 seconds delayed and scroll still works:

https://github.com/user-attachments/assets/7d0dde86-f1b4-428a-bb73-27552e1b6ef0

☝️ This confirms that none of the proposals have a correct RCA, without which there's no point in moving forward with any solution before understanding why the issue is happening.

---

🔄 I understand that things like `requestAnimationFrame` or `setTimeout` can fix this issue because they have better timing management, but we should first understand what's happening and why on Windows: Chrome it seems like the scrolling is being delayed excessively or indefinitely.

##

@NagaraniKaleeswaran In order for your proposal to be considered, please format it to follow the [proposal template](https://github.com/Expensify/App/blob/main/contributingGuides/PROPOSAL_TEMPLATE.md) as per our contributor guidelines [docs](https://github.com/Expensify/App/blob/ec8478b247f0cbe07264eb2088ee10d3f19e83bc/src/pages/Travel/ManageTrips.tsx#L41-L53).

**Comment by NagaraniKaleeswaran** [comment]
@ikevin127 
Proposal

Problem
On Windows Chrome, when an error message appears, the page does not always scroll to the bottom as expected. On macOS Chrome it works fine.

Root cause
The scroll action is triggered right after the error state is set, but on Windows Chrome the layout is not yet complete when the scroll runs. This causes the scroll position to be incorrect or delayed.

Proposed change
Trigger the scroll only after the error message has finished rendering. The simplest way is to add a small delay using requestAnimationFrame (or two RAFs) inside scrollToBottom, so the scroll runs after the layout is ready.

Example:

```
const scrollToBottom = () => {
  InteractionManager.runAfterInteractions(() => {
    requestAnimationFrame(() => {
      scrollViewRef.current?.scrollToEnd({ animated: true });
    });
  });
};
```


Tests to add

Error message appears → scrolls to bottom immediately on both macOS and Windows Chrome.

Delayed error (e.g. 2s timeout) still scrolls correctly.

Multiple consecutive errors trigger one scroll each.

Alternatives explored

setTimeout → works but less reliable.

Using onLayout callback → more precise, but adds complexity.

**Comment by ikevin127** [comment]
@NagaraniKaleeswaran Unless you follow and use the proposal template, your proposal will not be reviewed. Proposal template looks like this (markdown to copy & paste, then fill up with your proposal details):

```md
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

### What is the root cause of that problem?

### What changes do you think we should make in order to solve the problem?
<!-- DO NOT POST CODE DIFFS -->

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?
<!-- Clearly describe the different test cases you recommend adding or updating. Explain how they will ensure the problem is fully covered and that any future changes do not cause a regression. Consider edge cases, input variations, and typical user interactions that could trigger this issue. To get guidance on how to write tests, refer to the [README.md](https://github.com/Expensify/App/blob/main/tests/README.md) in the tests folder. -->

### What alternative solutions did you explore? (Optional)

<!-- **Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job. -->

```

> The scroll action is triggered right after the error state is set, but on Windows Chrome the layout is not yet complete when the scroll runs. This causes the scroll position to be incorrect or delayed.

We need to understand the **WHY** here, why is the layout not yet complete on Windows: Chrome right after the error state is set ? What causes that and why only on Windows: Chrome but not on MacOS: Chrome ?

**Comment by NagaraniKaleeswaran** [comment]
@ikevin127 @MelvinBot 
I have updated my proposal above. Can you now check this

**Comment by NagaraniKaleeswaran** [comment]
@ikevin127 @MelvinBot 
Now I have added clearly Why its occurring.Please once check and let me know

**Comment by huult** [comment]
https://github.com/user-attachments/assets/a403b536-7bce-4c5f-ae59-5b7f1f8fea7c

@ikevin127 is this issue still reproducible? I tried but couldn’t.

**Comment by ikevin127** [comment]
Turns out it's reproducible only on **Windows: Chrome**, I'll have to get a windows VM running to confirm.

Will review existing proposals soon, and will debug to check whether the mentioned root cause is verifiable.

**Comment by NagaraniKaleeswaran** [comment]
@ikevin127 
When debugging on a Windows VM, please log scrollHeight before and after scrollToEnd, and inside one/two requestAnimationFrame ticks — this will confirm whether layout is being delayed compared to macOS Chrome.

**Comment by NagaraniKaleeswaran** [comment]
@PiyushChandra17 You’re right — the issue doesn’t reproduce on macOS Chrome. Still, running the same `scrollHeight` + `requestAnimationFrame` logs there could be useful as a baseline. That way, when we compare with Windows Chrome, it should highlight whether the layout timing behaves differently across platforms.

**Comment by NagaraniKaleeswaran** [comment]
@PiyushChandra17 True, that could work short-term, but platform-specific code can be fragile. A layout-timing fix should solve it for Windows without needing browser checks.

**Comment by ikevin127** [comment]
Thanks everyone for the proposals / interest in addressing this issue!

##

♻️ I was able to test on **Windows: Chrome** using the **Sauce Labs** platform, and honestly I'm not able to reproduce the issue  as its being shown in the OP, the most I was able to reproduce was that the scroll trigger was slightly delayed on Windows: Chrome after the error appeared (but it always scrolled), compared to MacOS: Chrome where scrolling happened as soon as the error appeared.

I've been able to confirm the [first detailed RCA](https://github.com/Expensify/App/issues/70601#issuecomment-3311097629) - here's a breakdown of what happens on Windows vs MacOS:

1. Used the `onContentSizeChange` prop of `ScrollView` to track the content height (since React Native doesn’t expose scrollHeight directly).
2. Added logging around your `scrollToBottom` call.
3. Chain `requestAnimationFrame` calls to check if layout updates later.

I added logs as per the comment described:

<details>
<summary>Logs code</summary>

```ts
const scrollViewRef = useRef<RNScrollView>(null);
const [contentHeight, setContentHeight] = useState(0);

const scrollToBottom = () => {
    InteractionManager.runAfterInteractions(() => {
        console.log('Before scroll, contentHeight:', contentHeight);

        scrollViewRef.current?.scrollToEnd({animated: true});

        console.log('After scroll (immediate), contentHeight:', contentHeight);

        requestAnimationFrame(() => {
            console.log('rAF 1, contentHeight:', contentHeight);

            requestAnimationFrame(() => {
                console.log('rAF 2, contentHeight:', contentHeight);
            });
        });
    });
};

// ...below in component ScrollView

<ScrollView
    contentContainerStyle={styles.pt3}
    ref={scrollViewRef}
    onContentSizeChange={(w, h) => {
        console.log('onContentSizeChange ->', h);
        setContentHeight(h);
    }}
>
    {/* ... your content */}
</ScrollView>
```

</details>

I got the following log results:

```log
// MacOS: Chrome
index.ts:71 onContentSizeChange -> 680
index.ts:71 Before scroll, contentHeight: 680
index.ts:71 After scroll (immediate), contentHeight: 680
index.ts:71 onContentSizeChange -> 774
index.ts:71 rAF 1, contentHeight: 680
index.ts:71 rAF 2, contentHeight: 680

// Windows: Chrome
index.ts:71 onContentSizeChange -> 680
index.ts:71 Before scroll, contentHeight: 680
index.ts:71 After scroll (immediate), contentHeight: 680
index.ts:71 rAF 1, contentHeight: 680
index.ts:71 rAF 2, contentHeight: 680
index.ts:71 onContentSizeChange -> 771
```

This confirms the suspected RCA - here’s the analysis:

**MacOS Chrome**
- `onContentSizeChange` -> 680 → initial content height
- `Before scroll` / `After scroll` → 680 (no change yet)
- `onContentSizeChange` -> 774 → content size updated after scroll
- `rAF 1/2` → still 680

**Interpretation:**
- MacOS calculates the new layout synchronously with the next render
- The `scrollToEnd` call is effectively scrolling to the right height, because the layout will catch up almost immediately

**Windows: Chrome**
- `onContentSizeChange` -> 680 → initial content height
- `Before scroll` / `After scroll` → 680
- `rAF 1/2` → 680 (still no change)
- `onContentSizeChange` -> 771 → content height only updates after `scrollToEnd` and rAF log

**Interpretation:**
- Windows is delaying the layout calculation, so `scrollToEnd` runs before the height has increased
- That’s why our scroll is ending up short: the container thinks it’s still 680 tall when we scroll

### Conclusion
- On Windows, we need to wait for layout to finish before scrolling
- Using `requestAnimationFrame` alone (or within `InteractionManager.runAfterInteractions`) won’t always be enough, because the height update happens after rAF
- Using a platform specific solution as suggested [here](https://github.com/Expensify/App/issues/70601#issuecomment-3313261828) is not viable and would go against our clean-code guidelines

### ↪️ Moving forward

For a holistic solution to this issue that's platform-agnostic and reliable, we need to leverage ScrollView's `onContentSizeChange` and remove the existing `useEffect` / `scrollToBottom` functions. ↪️ The first updated proposal to detail this RCA and implement this solution to an acceptable level, will be assigned to work on the issue.

**Comment by NagaraniKaleeswaran** [comment]
@ikevin127 
**Proposal**
**Please re-state the problem that we are trying to solve in this issue.**

On Windows Chrome, when an error message is displayed, the ScrollView does not always scroll to the bottom correctly. On macOS Chrome, scrolling works immediately, but on Windows the scroll happens before the layout finishes updating, which leaves the error message out of view.

**What is the root cause of that problem?**

As confirmed by logs:

- On macOS Chrome, `onContentSizeChange `fires almost immediately after render, so `scrollToEnd `works correctly.
- On Windows Chrome, the content height updates only after `scrollToEnd `and after `requestAnimationFrame `ticks, so the scroll is triggered with stale height (too short).
- In short, `scrollToEnd `runs before layout finishes updating on Windows.

**What changes do you think we should make in order to solve the problem?**

- Replace the current `useEffect + scrollToBottom` logic with a scroll triggered by `onContentSizeChange`.
- When `errorMessage `is set:
  1. Wait for `onContentSizeChange `to fire with the updated height.
  2. Then call `scrollToEnd`({ animated: true }).
- This ensures scrolling happens only after layout is complete, and works consistently across platforms.

**What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?**

- Error message appears on Windows Chrome → always scrolls fully to bottom.
- Error message appears on macOS Chrome → scrolls immediately as before.
- Error message with delayed render (e.g. 2s timeout) → still scrolls correctly.
- Multiple consecutive errors → each triggers a proper scroll.
- Cross-platform: verify identical behavior on Android, iOS, macOS, Windows.

**What alternative solutions did you explore? (Optional)**

- Using `requestAnimationFrame` or `setTimeout `→ helped sometimes, but not reliable on Windows since layout finished after rAF.
- Platform-specific hacks (Windows-only) → rejected as fragile and against clean-code guidelines.

This solution is minimal, platform-agnostic, and guaranteed to scroll only after layout is ready. I’d be happy to implement it once confirmed.

**Comment by huult** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

RHP does not auto scroll when an error message appears off-screen

### What is the root cause of that problem?

On `Windows: Chrome`, layout calculation for `ScrollView` is delayed.

- This causes `scrollToEnd()` to execute before the new content height is applied.

- On macOS: Chrome, the layout updates synchronously, so the issue is not visible.

https://github.com/Expensify/App/blob/ec8478b247f0cbe07264eb2088ee10d3f19e83bc/src/pages/Travel/ManageTrips.tsx#L41

### What changes do you think we should make in order to solve the problem?

Replace the current `useEffect / scrollToBottom` approach with an implementation that leverages ScrollView’s `onContentSizeChange` callback.

https://github.com/Expensify/App/blob/ec8478b247f0cbe07264eb2088ee10d3f19e83bc/src/pages/Travel/ManageTrips.tsx#L51

This ensures the scroll only happens after the layout has updated and the final content height is known, making it reliable across platforms.

https://github.com/Expensify/App/blob/ec8478b247f0cbe07264eb2088ee10d3f19e83bc/src/pages/Travel/ManageTrips.tsx#L58

```diff
    onContentSizeChange={() => {
        if (!shouldScrollToBottom) {
            return;
        }

        requestAnimationFrame(() => {
            scrollViewRef.current?.scrollToEnd({animated: true});
        });
    }}
```

### What specific scenarios should we cover in automated tests to prevent reintroducing this issue in the future?

none

### What alternative solutions did you explore? (Optional)

**Reminder:** Please use plain English, be brief and avoid jargon. Feel free to use images, charts or pseudo-code if necessary. Do not post large multi-line diffs or write walls of text. Do not create PRs unless you have been hired for this job.

**Comment by ikevin127** [comment]
@NagaraniKaleeswaran You don't have to tag everybody, especially not MelvinBot since it's a bot 😅

> Hi team, I’m setting up my local environment.

Seems strange that you don't have your local env setup since in order to work on a proposal you should be able to reproduce the issue (locally) first.

Please make sure to thoroughly read the [contributor guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md) as 99% of your questions are answered there including:
- what you need for testing / local development
- how to contribute / what to do once your proposal was accepted
- how you're getting paid for contributing

You're supposed to be familiar with the guidelines before you start posting proposals / contributing.

> Could you please share the test credentials I should use for logging into the app?

You use your own email address and increment with +1, 2, 3 and so on for testing. Eg: test+1@gmail.com. Refer to the guidelines for details.

> Also, just to confirm — will the Upwork Contributor contract be sent out before I proceed with opening the PR?

I explained already the next steps [here](https://github.com/Expensify/App/issues/70601#issuecomment-3321889614), don't worry about payment for now - make sure you open the PR as soon as possible or at least give us a timeline. You will always get your payment after the regression period of the PR is over.

**Comment by NagaraniKaleeswaran** [comment]
@ikevin127 
Thanks for clarifying! I was under the impression new test credentials would be shared, but now I understand I should create test accounts myself using my own email with +1, +2, etc. suffixes as per the contributor guidelines.

I’ve got my local environment set up and I’m working on the fix. I expect to open the PR by Sep 26.

**Comment by huult** [comment]
If we reassign the ticket, then my proposal is valid because it comes after the selected proposal.

**Comment by strepanier03** [comment]
We are going to reassign and flipped a coin between @huult and @lorretheboy since there were two folks volunteering to push the change forward. 

@huult is the lucky winner.

**Comment by ikevin127** [comment]
@huult Please keep the solution exactly as https://github.com/Expensify/App/pull/71426, since that was the assigned solution and we're happy with the result (tested already), we will make sure to run an adhoc build anyway to have QA try and reproduce to ensure the issue is fixed.

**Comment by huult** [comment]
I'm working on the PR.

**Comment by ikevin127** [comment]
### ⚠️ Payment automation failed here
- should be on **[HOLD for Payment 2025-10-20]** according to PRs [production deploy](https://github.com/Expensify/App/pull/72061#issuecomment-3399059016) from **5 days ago**

cc @strepanier03

**Comment by strepanier03** [comment]
@ikevin127 - We need the checklist here too. Can you take care of that while I do the payment summary?

**Comment by huult** [comment]
@strepanier03 It looks like you missed the payment for me. I still haven’t received it.

**Comment by strepanier03** [comment]
I updated the payment summary and sent the offer. I'll keep an eye out for this.
