### ISSUE TITLE
[$250] Android 16 only - "Add" is displayed instead of "Add approver" on Change approver page

### ISSUE THREAD

**Issue by jponikarchuk** [Expensify/App#77357]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.75-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** N/A - new feature, doesn't exist in prod
**If this was caught during regression testing, add the test name, ID and link from BrowserStack:** https://github.com/Expensify/App/pull/75729
**Email or phone of affected tester (no customers):** isjdsoijsojnsiojisndj@gmail.com
**Issue reported by:** Applause Internal Team
**Bug source:** Pull Request QA execution
**Device used:** Samsung Galaxy S25 FE / Android 16
**App Component:** Money Requests

## Action Performed:
Precondition:
- Android 16 only.
- Device font size is minimum.

1. Launch Expensify app.
2. Go to workspace chat.
3. Create an expense.
4. Tap Submit.
5. Go to Reports > Menu > Reports.
6. Select the report by long tapping > Select.
7. Tap dropdown button > Change approver.

## Expected Result:
"Add approver" will be displayed.

## Actual Result:
"Add" is displayed instead of "Add approver" on Change approver page.

This issue only happens when "Change approver" page is opened from Reports.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [ ] Android: mWeb Chrome
- [ ] iOS: App
- [ ] iOS: mWeb Safari
- [ ] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/3e922090-db92-47d2-947a-43e3cce3c19e

<img width="419" height="868" alt="Image" src="https://github.com/user-attachments/assets/ccd2253f-a0ad-4749-b582-c4434a175058" />

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)
<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021999132738674419346</li>
        <li>Upwork Job ID: 1999132738674419346</li>
        <li>Last Price Increase: 2025-12-11</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 109820139</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @kadiealexander</details>

**Comment by Nodebrute** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
"Add" is displayed instead of "Add approver" on Change approver page
### What is the root cause of that problem?
We have two pages that show `Add Approver` 
 `SearchChangeApproverPage` 
`ReportChangeApproverPage`

on one page it's working fine but on other we have this problem the issue is we use `SelectionListWithSections` on SearchChangeApprover Page. Previously we had these kind of issues on other pages too they got fixed by migrating to new selection list 
### What changes do you think we should make in order to solve the problem?

We should migrate `SearchChangeApproverPage` to use new selection list instead of using `SelectionListWithSections`. This fixed the issue. we can do the same for category page
### What alternative solutions did you explore? (Optional)
We can pass `  listItemTitleStyles={styles.mnw100}` in `categorypicker` selection list and in `SearchChangeApproverPage` selection list 
https://github.com/Expensify/App/blob/da1a9a8467eb0012ec7bfb2a691f42128d023369/src/components/CategoryPicker.tsx#L78

We should also fix this issue on tags page too

**Comment by situchan** [comment]
The [proposal](https://github.com/Expensify/App/issues/77357#issuecomment-3644470792) of migrating to new `SelectionList` looks good.

The original issue (`SearchChangeApproverPage`) is not reproducible as [offending PR](https://github.com/Expensify/App/pull/75729) was reverted. (@QichenZhu please use `SelectionList` instead of deprecated `SelectionListWithSections` in rework PR)
But issue still happens on `CategoryPicker` (`approver` is cut on some devices, multiline on some other devices) so let's fix that!

<img width="357" height="792" alt="Image" src="https://github.com/user-attachments/assets/835469d8-eb6b-4f64-a44c-0e80b99fa364" />

🎀 👀 🎀 C+ reviewed

**Comment by Nodebrute** [comment]
Pr will be ready in few hours 🚀

**Comment by JS00001** [comment]
Nice, thanks!

**Comment by Nodebrute** [comment]
pr is ready for review https://github.com/Expensify/App/pull/78607

**Comment by JS00001** [comment]
Waiting on @kadiealexander , will make them the issue owner
