### ISSUE TITLE
[$500] Long workspace name breaks the alignment of side arrow - @Tushu17

### ISSUE THREAD

**Issue by mvtglobally** [Expensify/App#8461]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
 1. Create a workspace
 2. Go to General Settings
 3. Use a long name for workspace
 4. Now go to settings and see the arrow at the right side of workspace.
 
## Expected Result:
 It shouldn't break the alignment of the side arrows.

## Actual Result:
Long workspace name disturb the alignment of the side arrow of workspace.

## Workaround:
unknown 

## Platform:

Where is this issue occurring?

- Web

**Version Number:** 1.1.46-1
**Reproducible in staging?:** Y 
**Reproducible in production?:** Y 
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** Any additional supporting documentation 
![image - 2022-04-04T001410 986](https://user-images.githubusercontent.com/43995119/161472861-203db0a6-b8ca-472a-ba86-f0394db486e5.png)

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @Tushu17
**Slack conversation:** 
https://expensify.slack.com/archives/C01GTK53T8Q/p1648247302114379

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by arielgreen** [comment]
https://www.upwork.com/jobs/~017410ee10e9594e18

**Comment by nadir** [comment]
I was able to fix this by setting flex-shrink to 1 on the container view
![image](https://user-images.githubusercontent.com/79141224/162446370-6b8b6a7f-751b-4b87-9140-81132da520ae.png)

**Comment by roryabraham** [comment]
Nice! LGTM 👍

**Comment by Santhosh-Sellavel** [comment]
@roryabraham Were you able to reproduce this issue?

I am unable to reproduce this one,
<img width="1440" alt="Screenshot 2022-04-09 at 12 51 55 AM" src="https://user-images.githubusercontent.com/85645967/162510378-efd16b43-d14b-4a6f-a7c9-7bf62d5e5efc.png">

**Comment by nadir** [comment]
You can reproduce it by adding more workspaces

**Comment by Santhosh-Sellavel** [comment]
Still no luck @nadir,

<img width="1437" alt="Screenshot 2022-04-09 at 1 08 25 AM" src="https://user-images.githubusercontent.com/85645967/162514929-6384fdb1-952b-4d8b-856e-224cc39208b9.png">

**Comment by nadir** [comment]
5 workspaces seem to trigger it 
![image](https://user-images.githubusercontent.com/79141224/162515649-0eba9b13-2928-4457-8a46-0c49185f0d02.png)

**Comment by Santhosh-Sellavel** [comment]
@nadir 
I am not unable to reproduce this yet. 

<img width="1430" alt="Screenshot 2022-04-09 at 1 17 42 AM" src="https://user-images.githubusercontent.com/85645967/162516401-8b5970cf-f165-4001-8814-5bae334a009a.png">

**Comment by Santhosh-Sellavel** [comment]
@mvtglobally Can you check whether this is still reproducible? 
I am unable to reproduce this.

**Comment by roryabraham** [comment]
@Santhosh-Sellavel thanks for checking, I did not verify this (since it was reported by Applause)

**Comment by mvtglobally** [comment]
You need to have 5 Workspaces to be able to reproduce it. Issue reproduced  for build 1.1.54.0![image](https://user-images.githubusercontent.com/43995119/162556274-1eb76c3d-c379-4930-9498-63cd81e90aab.jpeg)

**Comment by roryabraham** [comment]
surely it has to do with the length of the workspace name and not the number of workspaces?

**Comment by roryabraham** [comment]
Unless I'm mistaken, it has been 12 days since we've heard from @nadir. According to our contributing guidelines:

> Daily updates on weekdays are highly recommended. If you know you won’t be able to provide updates for > 1 week, please comment on the PR or issue how long you plan to be out so that we may plan accordingly. We understand everyone needs a little vacation here and there. Any issue that doesn't receive an update for 1 full week may be considered abandoned and the original contract terminated.

Since it's been 12 days and they were pinged for an update in their PR, I'm going to unassign them.

@arielgreen Can you please cancel the upwork contract and open it back to applications?

**Comment by arielgreen** [comment]
done

**Comment by arielgreen** [comment]
[Price increased.](https://expensify.slack.com/archives/C01GTK53T8Q/p1651621220786659)

**Comment by Santhosh-Sellavel** [comment]
> I’m not able to reproduce this even once, were you able to reproduce @roryabraham?
> 
> @mvtglobally & @Tushu17 Is this occurring consistently for you all. If then Please share the following info: Platform: In Mac or Windows Browser: Display Size in inches: Thanks!

Is this still reproducible?

**Comment by Tushu17** [comment]
> Is this reproducible?

Yes @Santhosh-Sellavel It's still reproducible in Window on chrome.

**Comment by Santhosh-Sellavel** [comment]
Windows OS?

**Comment by Tushu17** [comment]
> Windows OS?

@Santhosh-Sellavel Yes

**Comment by jayeshmangwani** [comment]
https://github.com/Expensify/App/blob/569289ba2cb2c99971f6164cd869e67efedc4a48/src/components/MenuItem.js#L62
adding `flex: 1` at the parent of the title is fixing this issue

Before this change
![Screenshot 2022-05-05 at 1 47 14 AM](https://user-images.githubusercontent.com/35371050/166819347-30c0c698-ebec-4eb3-bf5b-badd94f2e07b.png)

After this change
![Screenshot 2022-05-05 at 1 48 11 AM](https://user-images.githubusercontent.com/35371050/166819396-7ec042e7-0e48-4bef-a47c-f30fc25857d7.png)

**Comment by Santhosh-Sellavel** [comment]
Thanks, @Tushu17, I was able to reproduce this one, on chrome (Windows).
The issue exists on staging but is no longer reproducible in the main branch. Check out the video in the slack [thread](https://expensify.slack.com/archives/C01GTK53T8Q/p1651857959769129?thread_ts=1648247302.114379&cid=C01GTK53T8Q)!

cc: @roryabraham

**Comment by roryabraham** [comment]
@Santhosh-Sellavel can you please retest on staging today? There was a staging deploy yesterday, so the main branch was deployed to staging environment.

**Comment by Santhosh-Sellavel** [comment]
Issue unable to reproduce for me on staging. @Tushu17 can you confirm the same?

**Comment by jayeshmangwani** [comment]
@Santhosh-Sellavel @roryabraham 
I think this commit is fixing this issue https://github.com/Expensify/App/commit/388cfe3793be3fb3f0f570c31049a8f57b051853

this change I already commented but I think this change was already done before my comment

https://github.com/Expensify/App/issues/8461#issuecomment-1117862841

**Comment by Tushu17** [comment]
> Issue unable to reproduce for me on staging. @Tushu17 can you confirm the same?

@Santhosh-Sellavel yup, It's no more reproducible.

**Comment by roryabraham** [comment]
Actually, I'll leave this open for you and just unassign myself

**Comment by roryabraham** [comment]
My mistake, @Santhosh-Sellavel is also eligible for C+ compensation for reviewing https://github.com/Expensify/App/pull/8576, even though it wasn't merged.

**Comment by arielgreen** [comment]
@Tushu17 and @Santhosh-Sellavel just sent over offers to both of you via Upwork, once you accept I will pay out the job and close the issue.

**Comment by Tushu17** [comment]
@arielgreen Thank you, Offer accepted.

**Comment by Santhosh-Sellavel** [comment]
@arielgreen 
Accepted the offer, thanks!

**Comment by arielgreen** [comment]
Paid.
